### ISSUE TITLE
Add a real time character counter 

### ISSUE THREAD

**Issue by Uma-95** [pranjay-poddar/Dev-Geeks#1000]
**Describe the project you want to add with tech stack**
In this project when a paragraph or some text is entered, it shows the number of characters added and the number of characters that can be added so as not to exceed the maximum character limit.
Techstack:HTML,CSS,JS
(As a part of GSSOC'23)

**Comment by bparul7** [comment]
Hey

I am interested in working on this project. 

Why?
I have already made some projects using HTML, CSS, JS, Nodejs like weather app, calculator, group chatting app. I can use my previous knowledge to build this

How?
- Create a basic HTML page
- Add logic using JS
- Will use CSS for beautifying view

Next Steps?
Please let me know could i work on this and guide me how can i start on this?

Thanks

**Comment by Uma-95** [comment]
@pranjay-poddar I'm a GSSOC'23 contributor,could you please assign this to me as a part of GSSOC'23

**Comment by bparul7** [comment]
@Uma-95 , sorry I didn't realise you were contributor to project. Sorry, the project is yours:)

**Comment by theanushka-v18** [comment]
I would like to add this project, I have participated in open source program for the first time.
Please assign this task to me.

**Comment by Uma-95** [comment]
@pranjay-poddar  I'm a GSSOC'23 contributor, could you please assign this to me as a part of GSSOC'23
