### ISSUE TITLE
Add a Discord clone[GSSoC'23]

### ISSUE THREAD

**Issue by surbhi400** [pranjay-poddar/Dev-Geeks#1001]
**Describe the project you want to add with tech stack**
I want to make a Discord clone. please assign it to me under GSSoC'23

**Expected behavior**
It will be a view only clone.

**Screenshots (optional)**
![Screenshot 2023-05-20 110905](https://github.com/pranjay-poddar/Dev-Geeks/assets/77582783/d1dceebb-7744-42a1-a1c3-b86f69c66b77)

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23. Can u please assign this to me?

**Comment by Gun2902** [comment]
can u assign this issue
