### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by Niladri2003** [pranjay-poddar/Dev-Geeks#1003]
A fully functional weather app

**Expected behavior**
Shows weather for your current location as well as you can search any place

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/93518661/20ccf7c5-c296-4dad-9ea5-e012adfce623)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/93518661/29870396-0191-4b04-98d1-12aebc7c1abd)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/93518661/d546e504-9d34-4de4-b788-c8eaa822d759)

**Additional context (optional )**

**Comment by bparul7** [comment]
Hey

I am interested in working on building backend and logic for the website. 
I can help with:
- Creating basic HTML page for user interaction
- Fetching data using JS and rendering it on screen
- Adding basic CSS

Please guide me through next steps:)

Thanks

**Comment by Niladri2003** [comment]
Which website you are talking about ?

**Comment by pranjay-poddar** [comment]
Project already present
