### ISSUE TITLE
Archery game - website

### ISSUE THREAD

**Issue by Pavishnaam** [pranjay-poddar/Dev-Geeks#1004]
**Describe the project you want to add with tech stack**
Creating a game using html,css,js

Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.@pranjay-poddar

**Comment by ARGHYADIPROY** [comment]
I would like to contribute to this issue under the GSSoC'23
Describe the project you want to add to the tech stack
Creating a game using HTML,CSS, Js

Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.@pranjay-poddar.
Please assign me this project.
