### ISSUE TITLE
BMI calculator 

### ISSUE THREAD

**Issue by Pavishnaam** [pranjay-poddar/Dev-Geeks#1005]
**Describe the project you want to add with tech stack**
  Bmi calculator with functionality to gain health body

Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.@pranjay-poddar

**Comment by 20a31a0538** [comment]
I want to work on this project using JavaScript as a part of Gssoc '23.
So, could you please assign it to me.
If yes, Please message me to this mail: princepavan025@gmail.com

Thank you
Pavan

**Comment by imrish4** [comment]
Please assign me this issue under GSSOC 23

**Comment by SamridhiNancy** [comment]
I want to  contribute on this issue , under Gssoc'23'. i want to make changes please assign it to me.

**Comment by ishita80** [comment]
Hi @Pavishnaam , I feel I would be able to accomplish this project. So, can you please assign this to me.

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by pranjay-poddar** [comment]
Project already present
