### ISSUE TITLE
Virtual Piano

### ISSUE THREAD

**Issue by Rishita7281** [pranjay-poddar/Dev-Geeks#1006]
**Describe the project you want to add with tech stack**
I want implement virtual piano as a new project by using html css and javascript.

**Expected behavior**
i want create some fun and enjoyable instrument :- Piano 

**Screenshots (optional)**

**Additional context (optional )**
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.@pranjay-poddar

**Comment by pjyoti121** [comment]
please assign me this issue under gssoc23

**Comment by Avdhesh-Varshney** [comment]
@pranjay-poddar @Saurabh-kumar09 @MohitGupta121 Sirs, please assign this task to me to create a pull request and contribute in this repository under GSSoC'23 program
