### ISSUE TITLE
Responsive online blogging website

### ISSUE THREAD

**Issue by Pavishnaam** [pranjay-poddar/Dev-Geeks#1008]
**Describe the project you want to add with tech stack**
Responsive blogging site using php/mysql. The layout will be similar to WordPress.
 Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
I will convert the whole website into responsive. 
Kindly provide me the opportunity to work on the issue.@pranjay-poddar

**Comment by Gun2902** [comment]
can u assign me this isssue
