### ISSUE TITLE
Add Number guessing game 

### ISSUE THREAD

**Issue by Chayandev** [pranjay-poddar/Dev-Geeks#1009]
**Describe the project you want to add with tech stack**
Everytime starting the game , one random number will be generated by computer and player have to guess the number within 10 chances, each time wrong guess reduce the chance by one and score , and one hint will be displayed (range of the exact number).

Html,CSS and JavaScript is used for awesome ui and game logic with music.

**Expected behavior**
Each time empty input will give warning , after end of the game score will be displayed and two options will be there one is to restart the game and other is to leave the game .

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Chayandev** [comment]
@pranjay-poddar please provide me the opportunity to add this project...

**Comment by anjali7235** [comment]
please give me the opportunity...

**Comment by ishita80** [comment]
Hi @Chayandev , I feel I would be able to accomplish this project. So please assign this to me.

**Comment by Chayandev** [comment]
@ishita80 I already asked the project admin to assign. Me this issue which I created....

**Comment by ishita80** [comment]
Ok
