### ISSUE TITLE
Improve UI to Birthday Website

### ISSUE THREAD

**Issue by devasyarajguru** [pranjay-poddar/Dev-Geeks#1013]
**Describe the Feature you want to end**
This issue is a request to enhance the user interface (UI) of the website

**Expected behavior**
The current UI could benefit from improvements to enhance the overall user experience and make the website more visually appealing.

**Screenshots (optional)**
<img width="957" alt="birthday" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/35f294b2-edcb-40be-b67e-1578894c6c22">

**Additional context (optional )**

**Comment by vikram-8290** [comment]
i want to work on this issue Under Gssoc 2023 . Please Assign me this

**Comment by manuzz29** [comment]
This looks interesting ,please assign me onto this. I want to work on this issue under GSSoC2023 @pranjay-poddar

**Comment by PrajwalGraj** [comment]
I can enhance the UI and wish to work on it, So can u assign this to me.

**Comment by Srideepthi2384** [comment]
Plz assign me this under gssoc.. As can I make this website using various static, responsive and html

**Comment by imrish4** [comment]
Please assign me this issue under GSSOC 23

**Comment by SONUKUMARRAM145** [comment]
Hey I would like to work on this project so that i can make this website more visually appealing by adding good UI features . pls assign it to me under GSSOC23

**Comment by ishita80** [comment]
Hi @devasyarajguru. I would love to add some UI features to this project. So, please assign this to me.

**Comment by ishita80** [comment]
Hey I want to add some features to this website and also enhance the UI for this project. Can you please assign this to me. @pranjay-poddar

**Comment by defected-rbc** [comment]
Hello I am GSSoC'23 contributor.
The feature I want to add:
1. I can make the website more beautiful by adding a good color combination and design background to make it more appealing to the approaching customers.
2. I also want to add a slide show more ideas about birthday gifts.
3.  I can also make the text error-free and new catchy lines can be added by me.
4.  I can add Readme section in this website to help future contributor.

Expected behaviour
It will look more professional and concise and the user will have a good experience while surfing on it.

**Comment by devasyarajguru** [comment]
@pranjay-poddar Will you assigned me this issue? It will be kind to know that are you  active and can see my issue so that I can work on it?

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by ishikagoyal02** [comment]
Please assign me this issue under GSSOC23
@pranjay-poddar 
features I will add-
1.A selection of pre-designed birthday cards.
2.introducing an interactive card customization feature
3. users would have the freedom to personalize their cards with colors, fonts, images, and even short animations.
4.  This customization option would make each card truly unique and add a touch of personalization to the birthday greetings.
