### ISSUE TITLE
Changing the ui of password validator

### ISSUE THREAD

**Issue by Yashika-Agrawal** [pranjay-poddar/Dev-Geeks#1014]
**Describe the Feature you want to end**
I want to add glassmorphism effect with catchy colours in password validator project

**Additional context (optional )**

**Comment by manuzz29** [comment]
This looks interesting.Please assign this to me @pranjay-poddar

**Comment by SamridhiNancy** [comment]
I want to  contribute on this issue , under Gssoc'23'. i want to make changes please assign it to me.

**Comment by ishita80** [comment]
Hi @Yashika-Agrawal , I feel I can add the glass morphism feature to it. Can you please assign this to me.
