### ISSUE TITLE
Loan Calculator 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#1016]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

I would like to create a loan calculator where we can predict the loan total amount with rate of interest and time period.
I will use HTML,CSS and JavaScript for this project.
Please assign it to me.

**Comment by imrish4** [comment]
Please assign me this issue under GSSOC 23

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this! "

**Comment by Saurabhmaurya111** [comment]
Please assign me this issue under GSSOC 23

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me

**Comment by Tusharjoshi1703** [comment]
Thanks for merging it 🤝
