### ISSUE TITLE
English Dictionary 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#1017]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

I will create a English Dictionary which consists of various words with their respective meanings.
I will use Html Css Javascript for this project.
Please assign it to me.

**Comment by Srideepthi2384** [comment]
I will create a english dictionary website using html, css static and responsive website as I am good in this

**Comment by KamelMoohamed** [comment]
Please assign this project to me for GSSOC'23.

I will use HTML, CSS, and JavaScript for this project. Also, I will use google translate APIs to get the right translation.

**Comment by Developer-Swati** [comment]
Hello, I can make an English Dictionary which will search any word and will give its meaning. I will use HTML, CSS ,JS and an API also. 
Thanks

**Comment by jiya10208** [comment]
can you assign the project to me under gssoc'23.

**Comment by Tusharjoshi1703** [comment]
Thanks for assigning the task to me.
