### ISSUE TITLE
Word App Tkinter GUI

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [pranjay-poddar/Dev-Geeks#1019]
**Describe the project you want to add with tech stack**
I want add a word count app , it will include featues like word count, character count, remove extra spaces, etc...
The project will be made using:
Python
Tkinter GUI

**Expected behavior**
A person will be able to add there text and will be able to edit and use different features like word, character count etc.

**Comment by Swapnil-Singh-99** [comment]
Please assign me this issue under GSSOC 23

**Comment by atikachandel** [comment]
I would like to contribute to this issue under GSSoC'23 as I have the required tech stack skills to resolve the same.
