### ISSUE TITLE
To add a Search bar with auto complete search suggestion project

### ISSUE THREAD

**Issue by Yashika-Agrawal** [pranjay-poddar/Dev-Geeks#1021]
**Describe the project you want to add with tech stack**
The proposed project involves creating an Auto Complete Search Bar using JavaScript, which will enable users to search for specific items or information within our application with ease. As users type in the search bar, the system will provide suggestions in real-time, dynamically updating the suggestions based on the input provided.

**Expected behavior**
Implement the logic to generate and display real-time search suggestions as users type in the search bar. This will involve handling user input, querying the data source, and dynamically updating the suggestions

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97408966/53399ee6-f9c2-4968-aba7-ee08e7e9cf9d)

**Comment by Yashika-Agrawal** [comment]
Hello , I am a GSsoc'23 contributor, please assign this issue to me as it comes under my skills.

**Comment by creator79** [comment]
@pranjay-poddar I would like to work on this issue under GSSOC'23. Can u please assign this issue to me

**Comment by atikachandel** [comment]
@pranjay-poddar I would like to work on this issue under GSSoC'23. Can you please assign this issue to me so that I could use my skills to resolve it ASAP.

**Comment by Suchitra-Sahoo** [comment]
Hello @pranjay-poddar I would like to resolve the issue of creating a search bar with autocomplete search suggestion of your project under GSoc'23. I have experience working with search functionality and front end technologies such as HTML, JavaScript , CSS and bootstrap. Looking forward to your response.
Best Regards,
Suchitra Sahoo

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
