### ISSUE TITLE
Proposal to add color picker chrome extension using Js

### ISSUE THREAD

**Issue by Yashika-Agrawal** [pranjay-poddar/Dev-Geeks#1022]
**Describe the project you want to add with tech stack**
Color picker extension will extract any color from the web page which user can use later. Tech stack: html,css,js

**Expected behavior**
The proposed project involves creating a Chrome extension that enables users to pick colors directly from web pages. This extension will offer a user-friendly interface, allowing users to select any color on a web page and obtain its corresponding hexadecimal or RGB value.

**Additional context (optional )**
This enhancement aligns with the needs of web designers, developers, and graphic designers who seek a quick and efficient way to pick colors from web pages.

**Comment by Yashika-Agrawal** [comment]
Hey i m GSsoc'23 contributor , please assign this issue to me.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by manan1979** [comment]
hi can you please assign this project to me so i'll work on it under GSSOC-23
