### ISSUE TITLE
Add personal portfolio project built on React.js.

### ISSUE THREAD

**Issue by JatinBisht2308** [pranjay-poddar/Dev-Geeks#1023]
It is a personal portfolio web app built on react.js for fresher developers to showcase there developers' skills to the recruiter.

I expect that this project get added and my pr get accepted , one more thing please add the gssoc23 label in this issue please.

**Comment by JatinBisht2308** [comment]
@pranjay-poddar please assign this issue as I am an gssoc23 contributor then I can start working on it.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by JatinBisht2308** [comment]
@adityavpawar instead of sliding into others created issue try to make your own issue okeh.
