### ISSUE TITLE
FilteruserApp

### ISSUE THREAD

**Issue by Lovegupta112** [pranjay-poddar/Dev-Geeks#1032]
**Describe the project you want to add with tech stack**
I want to add FilterUser App using html,CSS ,JavaScript

**Expected behavior**
In this we can filter user using filter options and also add user

**Comment by Lovegupta112** [comment]
sir please assign me this  under Gssoc'23 
![239694927-72ae839e-b925-4e18-9237-e0e0ac227e7e](https://github.com/pranjay-poddar/Dev-Geeks/assets/90507983/9f751be2-b4bb-4879-8516-f06377bdcc40)

**Comment by MohitGupta121** [comment]
@Lovegupta112 please go ahead

**Comment by Lovegupta112** [comment]
@MohitGupta121  thankyou , could you assign me under gssoc'23 please
