### ISSUE TITLE
Wishing-App

### ISSUE THREAD

**Issue by ishita80** [pranjay-poddar/Dev-Geeks#1033]
Describe the project you want to add with tech stack
Hi! I want to make a wishing app using html, css, javascript and reacjst.  I want to contribute to this project for GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue.@pranjay-poddar

Expected behavior
 for various occasions like birthdays, anniversaries, Mother's Day, teacher's Day, or any festive occasion. Also, it would have various options for a particular occasion to choose from.

**Comment by sonustar** [comment]
can i also work on this issue since i had many forms build
