### ISSUE TITLE
Improve the UI of Calculator

### ISSUE THREAD

**Issue by Naincy04** [pranjay-poddar/Dev-Geeks#1034]
I will improve the UI of the Calculator.

**Comment by Naincy04** [comment]
Assign this issue to me. I want to contribute to this repo under GSSoc'23.

**Comment by Abhishek-465** [comment]
I want to contribute to this project. I can improve the UI of the calculator with the help of Vanilla CSS .

**Comment by shreyaamukherjee** [comment]
Please assign this issue to me. I have already developed a calculator website as a part of my project. So I feel I will be able to justify your demand, since I have prior experience in it. I am experienced at HTML, CSS and JavaScript. 

Thankyou

**Comment by Naincy04** [comment]
Thank you for assigning me this issue. I have started working on it.
