### ISSUE TITLE
Restaurant website

### ISSUE THREAD

**Issue by ishita80** [pranjay-poddar/Dev-Geeks#1035]
Describe the project you want to add with tech stack
Hi! I want to make a Restaurant website using html, css, javascript and reacjs.  I want to contribute to this project for GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue.@pranjay-poddar

Expected behavior
It would show all the items in a restaurant according to different categories. Also, you can add items of your choice and at the end it would generate a bill for it.

**Comment by Abhishek-465** [comment]
Hello !! I will be very happy to make this Restaurant website using HTML, CSS, JAVASCRIPT and REACTJS. I want to contribute to this project for GSSoC'23. I think i am capable of doing this project. I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue.@pranjay-poddar

Features:
Firstly there will be a attractive homepage.It will highlight some bestseller dishes. Then in another page it would show all the items in a restaurant according to different categories. After ordering it would also generate a bill for it.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by bhoomigupta1406** [comment]
Hey @pranjay-poddar , Using HTML, CSS , and JAVASCRIPT . I want to make this restaurant site look more beautiful and attractive. Responsive in laptop, phone and tablet also. With navbar, logo, hover effect on menu and animated icon.
with different sections.
In 2nd section we'll have a beautiful "SLIDE BAR FOR ORDERING FOOD" and it will have button for ordering food with hover effect and can also scroll down with buttons. Custom slide bar also.
In 3rd section I made a "WELCOME MENU" it has hover effect on image and on button.
In the 4th section, we'll have a "TEAM MENU" it has very attractive hover effect on it also. 
In the 5th section, we'll have a bouquet table "RESERVATION SECTION". You can fill the form and I can connect with PHP and its's only front-end website and single page website.
And in the next section we'll have "LATEST NEWS " section and animated images.
in the last section "FOOTER SECTION" and have a top bottom on by click. This way we can go to top section and it's clickable and you can jump to any section by the menu icon.
This makes the "RESTAURANT SITE" looks attractive and more beautiful.
I would like to contribute in it under GSSoC.

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by bhoomigupta1406** [comment]
Hey @pranjay-poddar , using HTML CSS and JS i want to contribute to this issue. I have made different sections for menu display, for booking , for billing. with a beautiful homepage.
![Uploading Screenshot (45).png…]()

**Comment by bhoomigupta1406** [comment]
Hey @pranjay-poddar , using HTML CSS and JS i want to contribute to this issue. I have made different sections for menu display, for booking , for billing. with a beautiful homepage.

**Comment by RitikaRathore05** [comment]
Hey @pranjay-poddar  I want to work on this issue, please assign me .I will html, css & javascript
