### ISSUE TITLE
Adding different Animations to the Animation section 

### ISSUE THREAD

**Issue by Teddy1404** [pranjay-poddar/Dev-Geeks#1036]
**Describe the project you want to add with tech stack**

I can add more CSS animation to this project .
**Expected behavior**

The animations can be used in any project that I will add so it will save time for other project developer , they can just import that animation into their projects .
**Screenshots (optional)**

**Additional context (optional )**

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by Teddy1404** [comment]
bro here u have to make issue on your own then you can pull request, Just go through the readme file once.
