### ISSUE TITLE
[GSSOC'23 Contribution]: URL Shortener

### ISSUE THREAD

**Issue by singh-anushka** [pranjay-poddar/Dev-Geeks#1037]
**Describe the project you want to add with tech stack**

A URL shortener is a web tool that converts long and complex URLs into shorter and more manageable ones. This web app is built on MERN Stack.

**Expected behavior**

As soon as we give a URL to the website. It shrinks the same immediately and the URL and its shortened version are saved in the database. Also, the number of times the saved URL is visited since then.

Can you please assign me this issue?
@Saurabh-kumar09

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by ayushg1411** [comment]
I would like to contribute to this issue as a part of @GSSOC'23. I have worked upon it earlier during my personal projects with MERN stack.
Please assign it to me. Thank you. I am very excited for this.

**Comment by singh-anushka** [comment]
@Saurabh-kumar09 I already made my project, all I need is to create a PR. Please assign me this issue, so that I can create the PR asap.
