### ISSUE TITLE
A website to display quotes 

### ISSUE THREAD

**Issue by Anikinee** [pranjay-poddar/Dev-Geeks#1041]
**Describe the project you want to add with tech stack**
A website to display quotes based on users interest under various categories using HTML, CSS, JAVASCRIPT.
For example:
If the user want to view quotes related to friendship then just by selecting the friendship option, the related quotes will be displayed.
Apart from this, there will be also options to add your own quote in the category you want.

Please assign me to build this project under GSSOC'23

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by ayushg1411** [comment]
I have created this project earlier using javascript css and html. it can be done easily using API.
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.
I am very excited for this .

**Comment by Khudaija** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by pranjay-poddar** [comment]
Project already present
