### ISSUE TITLE
Currency converter

### ISSUE THREAD

**Issue by Naincy04** [pranjay-poddar/Dev-Geeks#1042]
**Describe the project you want to add with tech stack**
 A website that converts the currency of one country to the currency of another currency.

**Expected behavior**
It will convert the currency of a country to the currency of another country.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by prousium** [comment]
I am interested to contribute to this issue. Kindly allow me to contribute to your project.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by shreyaamukherjee** [comment]
Respected sir, 
I have prior experience in development of webpage and has made a calculator web page in my 2nd year. I want to contribute in it.Please assign it to me.

**Comment by pranjay-poddar** [comment]
Project already present
