### ISSUE TITLE
Web Paint Website

### ISSUE THREAD

**Issue by aman-kumar29** [pranjay-poddar/Dev-Geeks#1045]
**Describe the project you want to add with tech stack**
**Web Paint Website - JavaScript/HTML/CSS Project**

Introduction:
 A simple web-based paint application using JavaScript, CSS, and HTML. It will allow users to draw and paint on a virtual canvas directly in their web browser.

Overview:
The web paint website will provide a user-friendly interface where users can choose from a variety of drawing tools, including a pencil, brush, eraser, and shapes. They can select different colors, adjust the brush size, and undo/redo their actions. The application also will support saving and loading drawings, enabling users to continue their work at a later time.

Codebase:
The project will primarily be built using JavaScript, CSS, and HTML. The JavaScript code handles the drawing functionality and user interactions, while CSS is responsible for styling the interface elements. The HTML file serves as the main entry point for the application.

**Expected behavior**
To use the web paint website, simply open the HTML file in a modern web browser or a deployed link. No additional installation is required. Users can start drawing by selecting a tool and interacting with the canvas using their mouse or touch input. Clear instructions on how to use the various tools are provided within the interface. 

**Screenshots (optional)**

**Additional context (optional )**
I want to do this as part of GSSoC '23. Can you please add this as one of the projects!!

**Comment by aman-kumar29** [comment]
I would like to work on this project. Please assign it to me! I have already worked on similar projects like this I just need to add more functionalities into it and it will be complete. @prateekj7777

**Comment by aman-kumar29** [comment]
I would like to work on this project. Please assign it to me! I have already worked on similar projects like this I just need to add more functionalities into it and it will be complete.

**Comment by prousium** [comment]
I can make a Web Paint Website using HTML and CSS.
Kindly assign me this issue

**Comment by aman-kumar29** [comment]
@pranjay-poddar can you please assign this issue to me

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
