### ISSUE TITLE
Adding features like animated texts and colour changing background

### ISSUE THREAD

**Issue by Student9876** [pranjay-poddar/Dev-Geeks#1046]
##The features I want to add
1. I can add some animated texts under the buttons in the index.html file to show what going to happen after the process. 
2. I can also add animated colour changing background behind every page this project has.

After this changes, this webpage is going to look more beautiful than before.

#Problems
I've seen repeating codes in this project. To maintain the **DRY** rule I'll remove the extra codes and make it simple.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by prousium** [comment]
I can do contribute to your project with my HTML AND CSS skills. Kindly assign me this issue

**Comment by Student9876** [comment]
Well I've already created and implemented the features I've mentioned. But the thing is this is not my project and some other issue is holding back all our pull requests. If you guys see the last pull requests, you can find out every pull requests are stuck for that one reason, **Netflix clone** project. As all these projects are in one repo so during merge, Github is trying to deploy the **netflix-clone** project and failing. Somebody please contact the mentor and tell this issue.
