### ISSUE TITLE
Spotify Clone for GSSOC '23

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1049]
**Describe the project you want to add with tech stack**
I want to make a Spotify clone using HTML, CSS and vanilla Javascript

**Expected behavior**
The website will have the UI similar to Spotify, it would be able to play songs, change  to next or previous songs, able to search for artists or songs

**Comment by ayushg1411** [comment]
I would like to contribute to this issue as a part of @GSSOC'23.
I have created this project in my 2 year. I would modify it little more according to given behaviour. I have 1+ year of experienced with MERN stack.
Please assign it to me. Thank you.

**Comment by abcxyz31** [comment]
i can contribute to this task i am familiar with the mern stack
