### ISSUE TITLE
Fitness-App using React js

### ISSUE THREAD

**Issue by Teddy1404** [pranjay-poddar/Dev-Geeks#1052]
**Describe the project you want to add with tech stack**

I am contributing in this by making a Fitness app using React js .
**Expected behavior**

The data comes from the api for all the gym exercise . This website will be helpful for the gym content . This is a fully functional dynamic website.
**Screenshots (optional)**

**Additional context (optional )**

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
