### ISSUE TITLE
Add BMI Calculator

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Dev-Geeks#1054]
**Describe the project you want to add with tech stack**
Hey @pranjay-poddar I want to add BMI Calculator created using react in this repo. Pkease assign me this issue. Thank you!

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by shubha987** [comment]
please assign me the task to resolve the issue..

**Comment by sumitkr2000** [comment]
@shubha987 I am working on this issue. Please raise another issue if you want to contribute. Thank you!

**Comment by sumitkr2000** [comment]
@pranjay-poddar Please assign me this issue.
