### ISSUE TITLE
Taxi Booking website Using React JS

### ISSUE THREAD

**Issue by Harikaraja** [pranjay-poddar/Dev-Geeks#1061]
**Describe the project you want to add with tech stack**
  A Taxi Booking website where users can book a taxi by selecting the start and the drop location on a specified date and time.

  Tech stack : HTML,CSS,REACT, boot strap

**Expected behavior**
  The user need to enter the start and the drop location on a specified date and time and click on Book button then he will get a success message saying taxi has been booked sucessfully . else an error message
**Screenshots (optional)**

**Additional context (optional )**

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Harikaraja** [comment]
I have raised the issue first
