### ISSUE TITLE
Random password Generator using JS

### ISSUE THREAD

**Issue by Harikaraja** [pranjay-poddar/Dev-Geeks#1062]
**Describe the project you want to add with tech stack**
Here Random passwords are generated from if the user clicks on Generate password button , the user can even copy the generated password by clicking copy password button .

Tech stack : HTML,CSS,BOOTSTRAP,JAVA SCRIPT

**Expected behavior**

The user interface contains 2 buttons one is for generating a password and the other is to copy the generated password , when the user clicks on generate password then a password is generated and displayed to the user the user can then click on copy password button to copy the password to clipboard

**Screenshots (optional)**

**Additional context (optional )**

**Comment by ShivamAgarwal00** [comment]
i would like to contribute for ths issue under gssoc'23...please assign this  task to me.

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Harikaraja** [comment]
I have raised the issue first

**Comment by Suparnojit** [comment]
!assign

**Comment by shubha987** [comment]
i would like to contribute for this issue under gssoc'23...please assign this task to me.

**Comment by Harikaraja** [comment]
I have raised this issue first

**Comment by pranjay-poddar** [comment]
Project already present
