### ISSUE TITLE
Improving the buttons in Apple Ecommerce website

### ISSUE THREAD

**Issue by DEVANSHUKEJRIWAL** [pranjay-poddar/Dev-Geeks#1064]
**Describe the Feature you want to end**

The button in the watch section is not properly Visible.
The button in the home section is overlapping with website.

**Expected behavior**
Fixing the buttons in the website and solving the redirecting issues in the website

**Screenshots (optional)**

**Additional context (optional )**

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by pranjay-poddar** [comment]
Project already present
