### ISSUE TITLE
Add : Signup page for Apple E-commerce website [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1069]
I would like to add or create a sign up page with js validation for the Apple E-commerce website. 

Expected behavior
The primary purpose of a sign-up page is to capture user details and create a unique account for them within the system.

**Comment by Chhavi-Adlakkha** [comment]
can i please work on this sign-up feature

**Comment by Pragati-3003** [comment]
Thanku for assigning this to me.

**Comment by Gun2902** [comment]
can u assign me this isssue
