### ISSUE TITLE
Add : Signin page in Apple E-commerce website (GSSOC'23) 

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1070]
I would like to add a sign in or login page to the Apple E-commerce website. 
It increases the user interaction with the website. 
So, please approve the issue and assign this issue to me.

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by itzanway** [comment]
Please assign me to this task has done this work previously

**Comment by pjyoti121** [comment]
please assign me this isuue

**Comment by Pragati-3003** [comment]
> please assign me this isuue

Thanks for assigning me.
