### ISSUE TITLE
Enhance ui/ux of Apple E-commerce website. 

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1071]
I would like to change the ui/ux of the website as it is not looking attractive.

I would like to enhance the watch section of the website as it lacks visual appeal. My plan is to create a slider that showcases all the available watches, allowing users to click "Buy Now" to make a purchase. 
Also , I would like to change the overall ui/ux of the website. 
So , please assign this issue to me.

**Comment by Kapileswar-Moharana** [comment]
I would like to change the overall UI/UX of the website.
So , please assign this issue to me.
