### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by sanyayaa** [pranjay-poddar/Dev-Geeks#1074]
A QR Code Generator which allows user to enter any text or URL and it generated the QR Code.
This project is build using HTML CSS JAVASCRIPT.

**Comment by ayushnighoskar** [comment]
I would like to work on this issue.Please assign this to me.

**Comment by PARTH-1712** [comment]
Hello Sanyayaa, this issue supports my tech stack so I want to contribute. So, please assign this issue to me.

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by pranjay-poddar** [comment]
Project already present
