### ISSUE TITLE
Add JS Project

### ISSUE THREAD

**Issue by TusharMinche** [pranjay-poddar/Dev-Geeks#1077]
Dear @prateekj7777 ,
I hope this message finds you well. I would like to request the addition of my JavaScript project to your repository. The project is designed to help children learn the alphabet in an interactive and engaging way.

**The project features a user interface that displays all the alphabets from A to Z, accompanied by corresponding images. When a child clicks on a specific alphabet or types a single alphabet, a corresponding sound is played. For example, if the child clicks on the letter 'A', a sound saying "A for apple" will be played.**

The purpose of this project is to provide a fun and educational tool for children to learn and familiarize themselves with the alphabet. By associating each letter with a visual representation and an auditory cue, it aims to enhance their understanding and retention of the alphabet.

**Comment by TusharMinche** [comment]
Assign this to me.

**Comment by Manish12-verma** [comment]
please assign this task to me
