### ISSUE TITLE
add centimeters to feet option to height converter project 

### ISSUE THREAD

**Issue by ShinaKumari** [pranjay-poddar/Dev-Geeks#1078]
add centimeters to feet option to height converter project 
This option should in another html file
Please assign this to me I am working this feature

**Comment by Pranav-Rayaprolu** [comment]
hey i have good know ledge in html please assign this project to me. You can trust me . I will definetely complete it.

**Comment by Pranav-Rayaprolu** [comment]
please assign me under GSSOC-23
