### ISSUE TITLE
Add :Navbar or header in Btech Chai Wala website [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1084]
I would like to add a navbar and header to the website. 
This will increase the visibility of the website and also increase the user interaction. 
So, please assign this issue to me under GSSOC'23.

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by VC6378** [comment]
Please assign me this task

**Comment by itzanway** [comment]
please assign me to this task

**Comment by xyz031** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by SimranKumari93** [comment]
i would like to resolve the issue in this website .please assign me this job in gssoc'23.
