### ISSUE TITLE
A Simple spotify clone project using javascript

### ISSUE THREAD

**Issue by Tanishashrivas** [pranjay-poddar/Dev-Geeks#1085]
Hey there, i have been selected as a gssoc contributor and i wanted to add a javascript project to this. Hope i will get the opportunity.

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.I will try to make it as better as possible.Please assign this issue to me.It would be grateful for me to work on it.

**Comment by anandpiyush1521** [comment]
I would like to work on this project.

**Comment by pranjay-poddar** [comment]
Project already present
