### ISSUE TITLE
Enhance : Feedback form [GSSOC'23].

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1086]
I would like to improve the feedback form of the Btech Chai wala website. 
I will change the Ui/ux of the feedback form which increase the visibility of the website and website will become more attractive. 
So, please assign this issue to me.

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.Please assign this issue to me under GSSOC'23..It would be grateful for me to contribute.

**Comment by itzanway** [comment]
please assign me to this task

**Comment by SimranKumari93** [comment]
i would like to resolve the issue in this website .please assign me this job in gssoc'23
