### ISSUE TITLE
Project: Text Animation [GSSoC'23]

### ISSUE THREAD

**Issue by Sriparno08** [pranjay-poddar/Dev-Geeks#1088]
**Describe the project you want to add with tech stack**

I want to add a text animation project, created using HTML & CSS.

**Additional context (optional )**

I am contributing this project as part of GSSoC'23.

**Comment by Sriparno08** [comment]
I would like to work on this.

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.Please assign this issue to me under GSSOC'23..It would be grateful for me to contribute.

**Comment by prousium** [comment]
I want to contribute to this project.
Kindly assign me this issue.
