### ISSUE TITLE
Improve the slider in Disney Hotstar Clone [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1090]
I would like to enhance the quality of slider as it is not slide smoothly.
 I will add smoothness to the slider. 
So, please assign this issue to me.

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.Please assign this issue to me under GSSOC'23..It would be grateful for me to contribute.

**Comment by pranjay-poddar** [comment]
Not a required change
