### ISSUE TITLE
add restaurant management and bill handeling project

### ISSUE THREAD

**Issue by AMAN-BAGADIYA** [pranjay-poddar/Dev-Geeks#1091]
adding a restaurant management and food odering , seat booking, project which we will be customer centric and includes many ither functionalities 
I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.

**Comment by SnigdhaP2022** [comment]
I would like to change the Home and About Us page, it's UI isn't quite comforting from the users Point of view. I would also like to add both register and login in the home section for better user experience. I'm experienced in web development and love to contribute for this project. I'll make this worth.
Please assign this to me.
<img width="1440" alt="Screenshot 2023-05-20 at 10 46 56 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/6c37190b-c947-4f73-acd1-2c2751672ee1">
I mentioned this page
