### ISSUE TITLE
Add : login and signup form in Disney Hotstar clone [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [pranjay-poddar/Dev-Geeks#1092]
I  would like to add or create a login or sign up form to the Disney hotstar clone . 
So, please assign this issue to me under GSSOC'23.

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.Please assign this issue to me under GSSOC'23..It would be grateful for me to contribute.

**Comment by abcxyz31** [comment]
I am experienced with this tech stack i would be happy contributing to this task

**Comment by itzanway** [comment]
I would like to work on this project. 
Want to contribute in this work.
