### ISSUE TITLE
Add snake game

### ISSUE THREAD

**Issue by stuti-09** [pranjay-poddar/Dev-Geeks#1094]
I want to add a snake game.Snake game is a javascript game.

Snake is a sub-genre of action video games where the player maneuvers the end of a growing line, often themed as a snake. The player must keep the snake from colliding with both other obstacles and itself, which gets harder as the snake lengthens. 

It would look like this-

![Screenshot (167)](https://github.com/pranjay-poddar/Dev-Geeks/assets/93007935/b004701e-e8f9-4512-a7e3-918aa03c002c)

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.Please assign this issue to me.It would be grateful for me to contribute.

**Comment by PayalPadmalyaPrusty** [comment]
@stuti-09 I want to contribute.Please assign me

**Comment by samarthhapse** [comment]
I want to add a snake game it's just simplest task for me. I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward for collaborating with you all on this.

Thanks !

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by pranjay-poddar** [comment]
Project already present
