### ISSUE TITLE
Project: Movie Recommender System [GSSOC'23]

### ISSUE THREAD

**Issue by sanketsaurav2411** [pranjay-poddar/Dev-Geeks#1095]
Hi,
I would like to contribute a Movie Recommender Project.
Please assign me this under GSSOC'23.

Stack: 
    Programming Language: Python
    Libraries/Frameworks: Streamlit Pandas, NumPy, Scikit-learn, Pickle, PorterStemmer
    Web Framework: Streamlit
    Machine Learning: Collaborative Filtering, Content-Based Filtering
    Data Analysis: Pandas, NumPy
    Model Evaluation: Scikit-learn
    Development Environment: Jupyter Notebook

The project is a recommender system that utilizes a specific algorithm for generating personalized recommendations. It is designed to analyze user preferences and make relevant suggestions based on their previous interactions and behavior. The system aims to improve user experience by providing accurate and tailored recommendations, thereby enhancing their engagement with the platform. The project's implementation involves leveraging a tech stack consisting of Python and associated libraries for data processing and machine learning tasks. The recommender system employs sophisticated algorithms and techniques to offer users valuable and personalized recommendations.

Screenshot:
![Screenshot 2023-05-20 203831](https://github.com/pranjay-poddar/Dev-Geeks/assets/75113050/1c64704e-342b-4b3c-ac34-405307a4ed1a)

**Comment by sanketsaurav2411** [comment]
Hi @pranjay-poddar,
I have added my Movie Recommender Project under this issue.
I have created a Pull Request PR #1362.
Thank You :)

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
