### ISSUE TITLE
Improving the readme file of BMI CALCULATOR

### ISSUE THREAD

**Issue by harshsingh32** [pranjay-poddar/Dev-Geeks#1096]
I would like to improve the readme file of ML Projects/ BMI CALCULATOR making it engaging for the users and make it more expressive. I would like to add features of the project and increase the engagement of this project.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by harshsingh32** [comment]
Please assign this issue to me under GSSoC'2, I would like to work on this issue.

**Comment by pranjay-poddar** [comment]
Not a required change
