### ISSUE TITLE
Adding Theme switcher to simple to-do list

### ISSUE THREAD

**Issue by MaitriBhandari** [pranjay-poddar/Dev-Geeks#1098]
I would like to add a button which changes the theme of the Frontend-Projects / simple to-do list to make it more appealing to the users. I have the required tech stack. Request to assign this issue to me so that I can contribute under GSSoC'23.

**Comment by Kapileswar-Moharana** [comment]
I would like to add a button that changes the theme. I have the required tech stack. Request you to assign this issue to me so that I can contribute under GSSoC'23.

**Comment by pranjay-poddar** [comment]
Project already present
