### ISSUE TITLE
Improving the readme file Gym website

### ISSUE THREAD

**Issue by harshsingh32** [pranjay-poddar/Dev-Geeks#1099]
I would like to work on improving the readme file of Frontend-Projects/Gym website of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Paramhans-Singh** [comment]
As a contributor to GSSOC 23, I would like to work on improving the readme file of the Frontend-Projects/Gym website of this project making it more elaborate about the projects for the users and make it more engaging and expressive.

I would like to work on this issue, please assign this issue to me under GSSoC'23. I would like to get this opportunity to make the readme file more engaging.

**Comment by harshsingh32** [comment]
Sir, I have relevant experience and skillset to resolve the issue. I have relevant experience in frontend and experience in improving the readme file of projects previously. I would like to add more features in the readme and make it more engaging for the users. I would like add catchy phrases and colourful symbols so that it increases the engagement of the users to project and they contribute to the project.

**Comment by Snehaaa18** [comment]
⭐

**Comment by Sahilyadav123** [comment]
It would be great if I could work on improving the readme file for this project so that it is engaging for the users and more expressive for them as well.

**Comment by samarthhapse** [comment]
I am damn sure that I can make your Readme file most attractive and engaging for users .  I have relevant experience and skillset to resolve the issue. Assign this issue to me under GSSoC'23.

**Comment by defected-rbc** [comment]
Hello I am a GSSoC'23 contributor I can change the Readme section according to your need and easily understandable for other people. Please assign this issue to me.
