### ISSUE TITLE
Tip Calculator

### ISSUE THREAD

**Issue by ArgyPorgy** [pranjay-poddar/Dev-Geeks#1101]
I wanna build a Tip calculator using HTML,CSS and JS. It will take the bill amount and the desired tip percentage as inputs, and calculate the total amount including the tip. It will come under JS projects file. Please assign this project to me under gssoc label. Thank you!

**Comment by PayalPadmalyaPrusty** [comment]
@ArgyPorgy  I want to contribute.Please assign me

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by ArgyPorgy** [comment]
Hey there @pranjay-poddar, could you please look into this issue and assign me? Tagging you cuz it's been 2 days. Thank you!

**Comment by samsorrahman** [comment]
@ArgyPorgy  would you like to assign to me

**Comment by ArgyPorgy** [comment]
@PayalPadmalyaPrusty @Saksham0205 @samsorrahman i cant assign this to you as im the one who created it and im a contributor just like you. Only mentors and project admin can assign
