### ISSUE TITLE
[GSSoC'23] Random Quote Generator

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1103]
**Describe the project you want to add with tech stack**
 The Random Quote Generator (A React Advice App) is a web app that displays random quotes each time the user clicks a button. It provides a collection of quotes from various sources, such as famous quotes, inspirational messages, or any other category you prefer. The app allows users to get random quotes for inspiration, motivation, or entertainment purposes.
I'm going to use React on the front end and make get requests to Advice Slip JSON API.

**Expected behavior**
 The app consists of a simple user interface with a button. When the user clicks the button, a new quote is generated and displayed on the screen. The quotes can be styled to make them visually appealing and easy to read. Users can continue clicking the button to generate more random quotes. 

**Screenshots (optional)**

**Additional context (optional )**
Assign me this issue under GSSoC'23 , I'll make this web app a success.

**Comment by Pranav-Rayaprolu** [comment]
I would like to work on the project. Please assign this project to me. I will defenitely do it

**Comment by pranjay-poddar** [comment]
Project already present
