### ISSUE TITLE
Clicking link to project not opening and giving 404 GitHub error

### ISSUE THREAD

**Issue by sabhisharma-ise** [pranjay-poddar/Dev-Geeks#1104]
**Describe the bug**

Actual Behavior: The project does not open and a 404 GitHub error is displayed.

**Expected behavior**

Expected Behavior: When clicking the link to the Dice Game project, the project should open in a new tab or window.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100849696/40bc2a0c-3e40-4513-9074-aef1d00dc79c)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100849696/8918225d-3c4f-497b-9b58-530e782f9ac1)

**Additional context (optional )**

I can solve this issue by adding the project "The Dice Game" to this repository

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
