### ISSUE TITLE
Add Quiz Game to repository

### ISSUE THREAD

**Issue by sabhisharma-ise** [pranjay-poddar/Dev-Geeks#1106]
**Describe the project you want to add with tech stack**

Issue: We would like to add a new project called Quiz Game to the repo.
Project Description: Quiz Game is a simple quiz game that allows users to test their knowledge on a variety of questions.
Tech Stack: HTML, CSS, JS

**Expected behavior**

Benefits: Quiz Game will be a fun and educational tool for users of all ages. It will also be a valuable addition to the repo, as it will provide users with a new way to learn and have fun.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100849696/0fbb8769-cdd2-4d06-9378-86666944c7fa)

**Additional context (optional )**

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Sehaj-kahlon** [comment]
I want to work on the issue.
I created a quiz app using html , css and js 
https://github.com/Sehaj-kahlon/Quizz-App
https://sehaj-kahlon.github.io/Quizz-App/

**Comment by prousium** [comment]
I want to contribute to this issue because I can create a well structured website. 
Kindly assign me this issue.
