### ISSUE TITLE
Redefining the Contact Form in Food-Website (44)

### ISSUE THREAD

**Issue by souraOP** [pranjay-poddar/Dev-Geeks#1107]
**Describe the Feature you want to end**

Changing the Contact Us form in the Food Website

**Expected behavior**
Will be adding a much more visually appealing contact us form using html and css

Name - Sourasish Mondal | GSSoC 23' Contributor

**Comment by Purnima3** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by souraOP** [comment]
> I would like to work on this issue, please assign this issue to me under GSSoC'23.

I'm currently working under and has made the PR too

**Comment by prousium** [comment]
I can contribute to this issue with my HTML and CSS skills.
Kindly assign this issue.
