### ISSUE TITLE
[GSSoC'23] Sudoku Game using Java

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1108]
**Describe the project you want to add with tech stack**
The Sudoku game is a popular logic-based puzzle where players need to fill a 9x9 grid with digits from 1 to 9. The objective is to ensure that each column, each row, and each of the nine 3x3 subgrids contains all of the digits from 1 to 9 without any repetition. 
I'll use JAVA to make the application.

**Expected behavior**
The Sudoku game as a Java desktop application allows users to play Sudoku puzzles on their computers. The application provides a graphical user interface (GUI) where users can interact with the game by selecting cells and inputting numbers.

**Screenshots (optional)**

**Additional context (optional )**
PLz assign me this issue, under GSSoC'23, I'll make a good Java desktop game.

**Comment by prousium** [comment]
I want to contribute to your project by working on this issue

**Comment by Unnati2310** [comment]
I would like to contribute to this project. i have worked on the same project in C++, would like to try with Java too.
