### ISSUE TITLE
Responsive  Footer Design

### ISSUE THREAD

**Issue by ojKunal** [pranjay-poddar/Dev-Geeks#1109]
A Fully Responsive  Footer Design using HTML,  CSS and JAVA SCRIPT . Will be very suitable for different types of personal websites or business websites. 
It is made fully responsive so that it can be easily used on any device. CSS's Flexbox has been used to make it responsive. With the help of Flexbox, no separate CSS code had to be added to make it responsive.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114463169/4e3fe1fb-9ecd-4e41-a897-838c673ee8cb)

**Comment by ojKunal** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by green-veggies** [comment]
I am interested in contributing in this issue please assign this to me

**Comment by defected-rbc** [comment]
Hello I am GSSoC'23 contributor.
The feature I want to add:
1.I can add footer in this web site 
2. I can also improve Readme that can help future contributors.

Expected behaviour
It will look more professional and concise and the user will have a good experience while surfing on it.

**Comment by anoopgangwar4** [comment]
I would like to work on this issue, please assign this issue to me.

**Comment by divyank25** [comment]
I would like to work on this issue, please assign this issue to me.

**Comment by Kapileswar-Moharana** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Kapileswar-Moharana** [comment]
Hello, @pranjay-poddar sir mistakenly i unassigned myself, actually, I already complete the task and come here to raise the pull request, but mistakenly I unassigned can you please reassign me its already done by me?

**Comment by utkarshgupta04092003** [comment]
Hey mentor,
I resolved this issue, as i create many projects and all the project have responsive footer like this,
so please assigned this issue to me, I'll do it in an efficient way.
