### ISSUE TITLE
[GSSoC'23]Car Game in C++

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1110]
**Describe the project you want to add with tech stack**
The car game implemented in C++ is a simple console-based game where the player controls a car on a road. 

**Expected behavior**
The objective of the game is to avoid obstacles and navigate the car as far as possible without crashing.

**Screenshots (optional)**

**Additional context (optional )**
Assign me this issue under GSSoC'23 so that I can make a car game using C++

**Comment by sand0903** [comment]
Assign me this issue because I have worked on this type of project before

**Comment by prousium** [comment]
Assign me this issue because I have worked on this type of project before

**Comment by samarthhapse** [comment]
The car game in C++ is a simple  game where the player controls a car on a road. Assign me this issue under GSSoC'23 so that I can make a car game using C++.

Thank you !

**Comment by Unnati2310** [comment]
I have worked on a similar project. C++ is a strong suit. I would love to work on this project
