### ISSUE TITLE
STUDENT ACADEMIC DATABASE

### ISSUE THREAD

**Issue by shubha987** [pranjay-poddar/Dev-Geeks#1111]
**Describe the project you want to add with tech stack**
coding language C, sorting and searching algo

**Expected behavior**
it will take the input of the student's details and a database will be created which has both searching ,sorting insertion and deletion capability.
**Screenshots (optional)**

please assign me this task for GsSoc'23
**Additional context (optional )**

**Comment by prousium** [comment]
assign me this issue i can contribute to your project
