### ISSUE TITLE
LIGHT AND DARK MODE

### ISSUE THREAD

**Issue by HeyfromNandini** [pranjay-poddar/Dev-Geeks#1120]
Hello , I am a GSSOC contributor 
I would like to work on the light and dark theme of the project . 
looking forward to useful contributions ...
Thankyou.

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Michelle031** [comment]
Please can I be assigned this issue

**Comment by EmberTSeal** [comment]
Hello, there has been no update on this. Can I work on this issue as part of GSSOC '23?
