### ISSUE TITLE
Number Guessing Game Project in Java

### ISSUE THREAD

**Issue by 5h0ov** [pranjay-poddar/Dev-Geeks#1121]
I would like to contribute a Java Project on Number Guessing Game.

I would love to contribute in this open source project for GSSoC '23. Thank you!

**Comment by dk172923** [comment]
I would like to contribute to your project by working on this issue for you.  I have knowledge of JAVA. Assign it to me under GSSOC'23 label

**Comment by 5h0ov** [comment]
closing this as i noticed a similar project already exists in the repo! sorry
