### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by HeyfromNandini** [pranjay-poddar/Dev-Geeks#1123]
Hello , I am a GSSOC contributor 
I would like to work on the login page of the frontend projects . 
I have some creative ideas for the UI and also the functionalities.
looking forward to useful contributions ...
Thankyou.

**Comment by anoopgangwar4** [comment]
I would like to work on this issue, I have some creative ideas design to login page. please assign this issue to me.

**Comment by ShreyaDhiman24** [comment]
Hello, I'm hoping to contribute to the front end of the login page as a GSSoC participant.

**Comment by Cadit21** [comment]
I would like to work on this issue, I have some good and innovative  ideas for designing login page and would like to make it more interactive .
