### ISSUE TITLE
Disney hotstar clone 

### ISSUE THREAD

**Issue by HeyfromNandini** [pranjay-poddar/Dev-Geeks#1124]
Hello , I am a GSSOC contributor 
I would like to work to make the UI and functionalites up to mark  .
I have worked on similar projects such as netflix clone in the past so it would provide as a good base for this project. 
looking forward to useful contributions ...
Thankyou.

**Comment by koushik395** [comment]
please assign the issue to me. I am a web developer with good knowledge.
