### ISSUE TITLE
Youtube clone

### ISSUE THREAD

**Issue by HeyfromNandini** [pranjay-poddar/Dev-Geeks#1125]
Hello , I am a GSSOC contributor
I would like to work to make the UI and functionalites up to mark .
I have worked on similar projects such as netflix clone in the past so it would provide as a good base for this project.
looking forward to useful contributions ...
Thankyou.

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by palakag29** [comment]
@MohitGupta121 @pranjay-poddar Please re-assign me this issue. This issue has been opened for more than a month and there is no progress

**Comment by palakag29** [comment]
@MohitGupta121 Youtube clone is already therefore closing the issue.
