### ISSUE TITLE
to add more information in readme.md

### ISSUE THREAD

**Issue by ankitrajrj** [pranjay-poddar/Dev-Geeks#1128]
**Describe the Feature you want to end**

i want to add screenshots in how to contribute section in readme.me file which will help contributors 

**Expected behavior**

after adding acreenshoot . contributors will see were to click and what to do for contibute

**Additional context (optional )**

make a section in end of readme file to go on top of readme file

**Comment by ankitrajrj** [comment]
@pranjay-poddar assign it to me

**Comment by pranjay-poddar** [comment]
Not required
