### ISSUE TITLE
BMI calculator

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#1132]
**Describe the Feature you want to end**

I wpuld like to add the feature involves "inches" in the input box which helps in better way to get results

**Expected behavior**

I believe this way we can handle the BMI calculator both ways and increases usage.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
I'm experienced in web development and would like to complete this task. Please assign this to me.

**Comment by Varshatay** [comment]
I would like to contribute

**Comment by srushtikage** [comment]
Hi I'm GSSoC'23 Contributor pls assign this issue to me.

**Comment by pranjay-poddar** [comment]
Project already available
