### ISSUE TITLE
Restaurant Site

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#1133]
**Describe the Feature you want to end**

I would like to add some features into this site :
1) Login Feature in the Home page
2) Make the About Us page more appealing to user using HTML,CSS
3) Would like to increase the UI in Menu section

**Expected behavior**

This way it makes the whole site more interactive for the users. As a UI/UX developer I can make this work.

**Screenshots (optional)**

**Additional context (optional )**

I would like to contribute for this site.  @pranjay-poddar  Please assign this to me.
Name : Snigdha Patibandla | GSSOC'23 Contributor

**Comment by manshasinghal** [comment]
I would like to contribute for this site. Please assign this to me.

**Comment by bhoomigupta1406** [comment]
Hey @SnigdhaP2022 I would like to work on this project :
 By adding login Feature in the Home page
 and  the About Us page more appealing to user using HTML,CSS
Would like to increase the UI in Menu section


I would like to contribute for this site.  Please assign this to me.
Name : Bhoomi Gupta | GSSOC'23 Contributor

**Comment by SnigdhaP2022** [comment]
@bhoomigupta1406 Don't copy past my descriptions and ideas to feature the page. Try to review the site and create your own ideas. You doing this can result in breaking the code of conduct. Hope you don't repeat this again. Thank you.

**Comment by Cadit21** [comment]
I would like to contribute to this issue, I have some innovative ideas for designing  the website and would like to make it more interactive .
I'm proficient in html,css and js .
