### ISSUE TITLE
ML- House price prediction using Regression model (Gssoc'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [pranjay-poddar/Dev-Geeks#1134]
**Describe the project you want to add with tech stack**
I would like to add "House price prediction using Regression model". It contains pandas, numpy, sklearn, tkinter, and pickle.
**Expected behavior**
User can give input and the expected price will be output.

**Comment by Jyotsna1304** [comment]
Hello, I am a GSSOC'23 contributor. Can you please assign me this issue.

**Comment by koushik395** [comment]
Hello , I am a GSSOC'23 contributor. Also i am a ML enthusiastic. Please assign me this issue.

**Comment by Parijatkumar** [comment]
Hi @Bharatpathak08  I am a GSSOC'23 contributor. Can you please assign me this issue.

**Comment by Bharatpathak08** [comment]
@pranjay-poddar plz label it it under Gssoc'23 and also the level.
