### ISSUE TITLE
fruit_website

### ISSUE THREAD

**Issue by Anshikay2104** [pranjay-poddar/Dev-Geeks#1136]
The feature I want to add:
1. I can make the website more beautiful by adding a good colour combination and design background to make it more appealing to the approaching customers.
2. I also want to add a slide show wherein all the latest trends and new comings will be shortlisted.
3.  I can also make the text error-free and new catchy lines can be added by me.
4. I can also make a readme file wherein I can give the description of the project which will help future contributors who want to contribute to this project.
Expected behaviour
It will look more professional and concise and the user will have a good experience while surfing on it.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by Anshikay2104** [comment]
sir the work has been done..how to submit it?
