### ISSUE TITLE
pizza corner

### ISSUE THREAD

**Issue by defected-rbc** [pranjay-poddar/Dev-Geeks#1139]
The feature I want to add:
1. I can make the website more beautiful by adding a good colour combination and design background to make it more appealing to the approaching customers.
2. I want to add a slide show wherein all the dishes will be shortlisted.
3.  I can make the text error-free and catchy lines.
4. I can also add header and footer on the page.
5. I can also improve Readme section to help future contributor to understand more about the project.

Expected behaviour
It will look more professional and concise and the user will have a good experience while surfing on it.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.
