### ISSUE TITLE
Algo_Viewer

### ISSUE THREAD

**Issue by LokeshSangrame** [pranjay-poddar/Dev-Geeks#1142]
Introducing Algo Viewer, a captivating project by me. Visit https://lokeshsangrame.github.io/Algo_Viewer/ to explore interactive visualizations of various algorithms. Gain a deeper understanding of their inner workings and embark on an algorithmic journey today!

**Comment by Anjali2312-Thombare** [comment]
hey @LokeshSangrame  I would like to work on this issue . Can you Please assign me this issue?

**Comment by aarushiagarwal131** [comment]
Sir, I am a Gssoc participant and took interest in your issue. I have a good knowledge of various algorithms.I would be greatful if you will assign me this project.
