### ISSUE TITLE
Frontend Project - Birthday Website (GSSOC'23)

### ISSUE THREAD

**Issue by shruti8302** [pranjay-poddar/Dev-Geeks#1147]
Hey @pranjay-poddar, as a part of GSSOC'23 I would like to add more features in birthday website. I would like to change the background, fonts, header, footer, etc. I would also like to add many more features like hover effect, transitions, etc. Kindly assign me this issue.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by Cadit21** [comment]
I would like to work on this issue, I have some creative ideas for designing this birthday website and would like to make it more interactive and would like add some features.

**Comment by gkm0001** [comment]
I hope this message finds you well. I am writing to express my interest and enthusiasm in contributing to an open-source web development project. As a beginner in web development, I am eager to leverage my skills and collaborate with a dynamic team to create meaningful and impactful solutions.

**Comment by SHIVA769** [comment]
I Would like to  work this issue .please  assign me

**Comment by laibaahsan27** [comment]
I can make your website looking from this to a much more appealing and colourful version of it.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/740a06a3-006e-44a9-a48f-0bc0f1e805f7)
i can customize it like this with a picture of your friend which will bring a smile on their face.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/cb0554f7-c899-4550-b771-1e043e97733a)
or i could make it look like an instagram story for the trendy social people.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/f69ebc74-3a5d-4182-9630-c3c612d9da2e)
i can add aesthetic images which will make it stand out from the rest.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/509e8241-78c6-4e0d-8b0b-4a433078075c)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/f7f1490d-7e8c-4eb2-b9c9-39ee59e6d334)

these are just few of the many ideas i would like to implement on your website as per your requirements and wishes but only if you allow me. so i request you to assign me this project under the label of GGSOC 2023
