### ISSUE TITLE
Project : Responsive Travel website

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#1150]
**Describe the Feature you want to end**

I believe the site is in its initial stage, it needs lot more upgrade to launch
1)I would like to design the Home page
2)add required info in the about, news and other sections
3) would also like to make some touches in the styling of the Home page

**Expected behaviour**

As UI/UX developer, I will bring out the best in my work. It increases user interaction and makes use of it in future.
**Screenshots (optional)**

**Additional context (optional )**

I would like to contribute to this site. @pranjay-poddar  Please assign this to me.
Name : Snigdha Patibandla | GSSOC'23 Contributor

**Comment by manan1979** [comment]
hey @pranjay-poddar can you please assign this project as i love to contribute in it, i already made some great UI designs. can you assign this project to me.
