### ISSUE TITLE
Project : Chat App

### ISSUE THREAD

**Issue by vishal8113** [pranjay-poddar/Dev-Geeks#1152]
**Describe the project you want to add with tech stack**
I want to add one simple chat application project where users can send messages, upload statuses, and much more...

 Tech stack:-
Android Studio
Firebase
Java

**Comment by vishal8113** [comment]
hey! @pranjay-poddar, can you please assign me this issue under GSSoc '23.

**Comment by manan1979** [comment]
hi @pranjay-poddar can you assign me this issue

**Comment by KomalS2002** [comment]
hey ! @pranjay-poddar I want to add a simple chat application project made using ReactJS, Firebase so can you please assign me this issue as GSSoC'2023 contributor.

**Comment by pranjay-poddar** [comment]
Project already present
