### ISSUE TITLE
Project: tik-tak-toe game

### ISSUE THREAD

**Issue by DurgaSanthosh** [pranjay-poddar/Dev-Geeks#1154]
**Describe the project you want to add with tech stack**
I was hoping to add a tik-tak-toe game created with React js as a part of GSSOC 23'. ( I'm a contributor of gssoc 23')

**Expected behavior**
The game will be a two-player (in single PC) board game where the first to get all x or o in a row wins. Thre will be feature to go back to each step or to start again if required.

**Screenshots (optional)**

![Screenshot 2023-05-21 164617](https://github.com/pranjay-poddar/Dev-Geeks/assets/75644571/389d789b-cbf0-4d2d-b153-597888fd6c2d)

**Additional context (optional )**

**Comment by DurgaSanthosh** [comment]
hey! @pranjay-poddar, can you please assign me this issue under GSSoc '23.

**Comment by SinghSachin2000** [comment]
hey! @pranjay-poddar , can you please assign me this issue under GSSOC'23. I know how to make a tik-tak-toe game.

**Comment by Sandeeppratap2021** [comment]
I can work on this issue under GSSOC '23, as I had made tic-tac-toe game using html, css and javascript.

**Comment by pranjay-poddar** [comment]
Project already present
