### ISSUE TITLE
project name: Frontend Projects/Gym Website: 

### ISSUE THREAD

**Issue by aditipatni3** [pranjay-poddar/Dev-Geeks#1156]
I want to enhance the UI  and update the readme file for better understanding of the project. 
Can you please assign me the issue.
<img width="1270" alt="Screenshot 2023-05-21 170124" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/91011940/6b08f274-6e50-4a45-b5fe-cafdd113d2ac">

**Comment by SinghSachin2000** [comment]
Hey @pranjay-poddar! I am super excited and eager to take on this incredible project for GSSOC'23. With my passion, dedication, and skills, I am ready to dive headfirst into this opportunity and make it a resounding success.

**Comment by manan1979** [comment]
hi @pranjay-poddar can i work on this , I can enhance this UI to attractive one and also update the Readme as best possible way to get the understanding of this project. can u assign this project to me

**Comment by 000626574705** [comment]
i eagerly want to work on this website issue

**Comment by jyotsanashyama** [comment]
@pranjay-poddar I would like to redesign the whole website from scratch. Can you please assign me this issue under GSSoC'23?
