### ISSUE TITLE
Snake and Ladder

### ISSUE THREAD

**Issue by pavitrachavda97** [pranjay-poddar/Dev-Geeks#1160]
**Describe the project you want to add with tech stack**

I want to add project of Snake and Ladder game which is created using Java.

**Expected behavior**

This game can be played by two player and one player with computer.

**Screenshots (optional)**

This game will something look like this:
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/91004608/b4bf6294-b821-4594-91b0-abe8f6d90b9c)

**Comment by Pranav-Rayaprolu** [comment]
Hey i have good experience in java .Can u please assign me this project under Gssoc-23. I will. defenitely complete it.
