### ISSUE TITLE
E commerce website

### ISSUE THREAD

**Issue by BTANISHA11** [pranjay-poddar/Dev-Geeks#1161]
I want to add a project of e commerce website contatining the tech stack react js .
It will contain shopping cart and and product addition subtraction in the cart.
It will also include Products along with sample price .
It can be used by anyone for personal purpose also.
Can you pls assign this issue to me.

**Comment by manan1979** [comment]
can u assign me this project?

**Comment by BTANISHA11** [comment]
No i can't since i ma working on this.

**Comment by BTANISHA11** [comment]
no i cant since i am working on this.
