### ISSUE TITLE
46. footer_new: spacing issue.

### ISSUE THREAD

**Issue by laibaahsan27** [pranjay-poddar/Dev-Geeks#1162]
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/5bdd9c96-8e61-46e7-b0cb-34e32ca2485d)

As you can see the spacing of the rows is little off which i can fix with just few smple steps. The right side space (next to follow us column) is appearing to be more than the left side space (next to branches section). 
please asssign it to me @pranjay-poddar under the label GSSOC 2023

**Comment by mohitcs46** [comment]
Please assign me this issue under GSSoC'23, @laibaahsan27 , thank you.

**Comment by mohitcs46** [comment]
I will keep the website's footer in good condition.
 Please assign me this issue under GSSoC'23, thank you.

**Comment by laibaahsan27** [comment]
please asssign it to me @pranjay-poddar under the label GSSOC 2023
