### ISSUE TITLE
Updating Readme.md (GSSoC 2023)

### ISSUE THREAD

**Issue by Shreyaprasad02** [pranjay-poddar/Dev-Geeks#1171]
**Updating the Available Projects section in Readme.md file**
The Available Projects section in Readme.md has extra column after S.No 156 which makes it look unordered.

**Expected behavior**
Each row must have 4 columns 

**Screenshot**
![Screenshot 2023-05-21 193740](https://github.com/pranjay-poddar/Dev-Geeks/assets/87193512/7196c4c9-d8c1-4e83-9504-df373e42e32d)

**Comment by Shreyaprasad02** [comment]
Please assign me this issue under GSSoC 2023 label.

**Comment by amanupadhyay33822** [comment]
Please assign this issue to me and I can fix this issue

**Comment by jyoti145** [comment]
I would like to work on this issue.Please assign me this issue
