### ISSUE TITLE
Add new project-password generator using python

### ISSUE THREAD

**Issue by harshinirhsv** [pranjay-poddar/Dev-Geeks#1172]
**Describe the project you want to add with tech stack**
I want to create a simple application that can randomly generate strong passwords using the Python.

**Expected behavior**
This application can generate a random password, with the combination of letters, numerics, and special characters. One can mention the length of the password based on requirement and can also select the strength of the password.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Varshatay** [comment]
i have good knowledge in this and i want to modify this issue. so, please assign me this issue under gssoc'23

**Comment by aarushiagarwal131** [comment]
Sir, I am a Gssoc participant and took interest in your issue .I have created many games in python and this project excites me a lot.If i get assigned to this issue i will work on the issue
