### ISSUE TITLE
Add more styling to Frontend-Projects/BeautifulTweets

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1179]
I can make the page look better and also make it look like the original twitter. Plus, add a dark and light mode toggle button and change the bg color of dark theme to match that of twitter.

**Comment by iamFaizanArif** [comment]
Assign me!

**Comment by siwangigahlot** [comment]
i will be delighted to take this issue. i will try my best to make it better than before.
