### ISSUE TITLE
Tetris Game

### ISSUE THREAD

**Issue by Harshal0902** [pranjay-poddar/Dev-Geeks#118]
**Describe the project you want to add with tech stack**
Making a Tetris game using HTML, CSS, Js

**Expected behavior**
Making a simple Tetris game

**Comment by Subha-5** [comment]
i want to work on this @Harshal0902

**Comment by Subha-5** [comment]
@pranjay-poddar i have already contributed to this issue here
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Js-Games/Tetris%20Game%20JS,
 you may close this issue or you can tell me if any improvements to be made so i can improve this project
