### ISSUE TITLE
Updating UI or Food ordering website

### ISSUE THREAD

**Issue by uuc110** [pranjay-poddar/Dev-Geeks#1180]
**Describe the bug**
I want to update this website UI and make it more neat and clean

**Expected behavior**
A Improved layout and better accesiblity

**Screenshots (optional)**

**Additional context (optional )**
Assign this to me for the work

**Comment by Rakteem007** [comment]
Sir, I am a Gssoc participant and took interest in your issue . If i get assigned to this issue i will  work on the issue.

**Comment by manan1979** [comment]
hell, can i work on this issue under GSSOC 23, as i like this project and want to contribute in it. could you assign this to me

**Comment by aarushiagarwal131** [comment]
I would like to contribute in this project. Please assign this to me.
