### ISSUE TITLE
Update UI of Btech Tea shop website

### ISSUE THREAD

**Issue by yaswika0311** [pranjay-poddar/Dev-Geeks#1181]
The landing page is way too broken, alignments are not up to mark, there is no animation and images are not added. I want to update the css and make it look way more attractive and I also want to make the website interactive and user friendly.
Please assign me this issue under GSSOC'23.

**Comment by Anjali2312-Thombare** [comment]
hey @yaswika0311  I would like to work on this issue.Please assign me this issue

**Comment by Sandeeppratap2021** [comment]
I also want to work on this issue under GSSOC' 23

**Comment by 000626574705** [comment]
I also want to work on this issue under GSSOC' 23

**Comment by Kapileswar-Moharana** [comment]
i want to work on this , Assign this to me
