### ISSUE TITLE
[GSSoC'23] Flappy Bird Game Clone

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1182]
**Describe the project you want to add with tech stack**
A simple JS clone of the flappy bird. The Flappy Bird game is a popular side-scrolling mobile game where players control a bird and navigate it through a series of pipes. The objective of the game is to fly the bird as far as possible without hitting the pipes or the ground.

**Expected behavior**
In the Flappy Bird game, points are typically scored based on successfully passing through the gaps between the pipes. If you hit the pipe or ground, the game is over and the total score will be shown.

**Screenshots (optional)**

**Additional context (optional )**
Assign me this issue kindly under GSSoC'23, so that I can build the project.

**Comment by Anjali2312-Thombare** [comment]
hey @Arka2708  I would like to work upon this issue .Please assign me this issue

**Comment by Arka2708** [comment]
> hey @Arka2708 I would like to work upon this issue .Please assign me this issue


I'm a GSSoC'23 contributor myself and want to add this project already written above:). I can't assign you

**Comment by Anjali2312-Thombare** [comment]
Thank you for informing me
