### ISSUE TITLE
Rock Paper Scissor

### ISSUE THREAD

**Issue by Kuldeep2001** [pranjay-poddar/Dev-Geeks#1186]
**Describe the project you want to add with tech stack**
I want to add a project in Python that shows the UI for the famous game Rock, Paper, and Scissors.

**Expected behavior**
It will use random outputs for the bot and the user will choose his/her choice. And then the result will be printed based on some rules:

The winning Rules are as follows:
1. Rock vs paper-> paper wins
2. Rock vs scissor -> Rock wins
3. paper vs scissor -> scissor wins.

**Comment by laibaahsan27** [comment]
i can add the score to display on the webpage itself as shown below in the picture. this will make your website better and appealing. 
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123810454/40c1356d-81bf-411d-888a-fe1a723e3085)
please assign me this task under the label GSSOC 2023

**Comment by Kuldeep2001** [comment]
@pranjay-poddar when can I start work on this issue.
When will it be assigned to me

**Comment by OWAIS221B** [comment]
I would like to work on it. Can you please assign it to me @pranjay-poddar?
