### ISSUE TITLE
Want To Add New Project With Reference to Gssoc 23

### ISSUE THREAD

**Issue by AbhishekCS3459** [pranjay-poddar/Dev-Geeks#1187]
<h1>Weather Prediction Web App using React and Open Weather API</h1>
<h2> Tech Stacks </h2>
<ul>
<li> React 18 </li>
<li>Open Weather API </li>
<li>React Animated Weather </li>
<li>React Geolocation using the Browser</li>
<li>React Live Clock</li>
<li>React Skyccons</li>
</ul>

<p> It can detect the current weather condition of your location weather and Show icons corresponding to it</p>

<h1> Preview of the Weather App </h1>

![image](https://user-images.githubusercontent.com/94506000/225564402-4be6ee0c-86ef-4cef-b5af-fea786d73e93.png)

<h2> Further Improvement </h2>
<ul>
<li> Image Change with Location</li>
<li>Login Logout Functionality</li>
<li>Weather news for 7 days forecast</li>
</ul>

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by AbhishekCS3459** [comment]
@pranjay-poddar , I have submitted the pull request regarding the aforementioned issue. Kindly review and merge it under gssoc23.
