### ISSUE TITLE
Avatar Generator React App

### ISSUE THREAD

**Issue by VC6378** [pranjay-poddar/Dev-Geeks#1189]
Hey,
I would like to add Avatar Generator React App, where one gets their very own avatar, modify it as per their need and also download them in their local system. Please assign me this issue as Contributor in GGSoC'23.
Thanks and Regards,
Vibhuti Chandrakar.
![WhatsApp Image 2023-05-21 at 23 21 24](https://github.com/pranjay-poddar/Dev-Geeks/assets/111688295/8695e893-361e-49cc-9148-fdfc8b6896f3)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
