### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by Harshal0902** [pranjay-poddar/Dev-Geeks#119]
**Describe the project you want to add with tech stack**
Making a QR Code Generator using HTML, CSS and Js

**Expected behavior**
A QR Code Generator using with help of Js

**Comment by Nirvik07** [comment]
I want to work on this project.

**Comment by Nirvik07** [comment]
@[Harshal0902](https://github.com/Harshal0902) in which folder should I upload my project?

**Comment by Harshal0902** [comment]
> @[Harshal0902](https://github.com/Harshal0902) in which folder should I upload my project?

@Nirvik07 I am not the owner of the repo, so @pranjay-poddar could answer it.

**Comment by Nirvik07** [comment]
@pranjay-poddar  in which folder should I upload my project?

**Comment by pranjay-poddar** [comment]
@Nirvik07 under js_projects folder make another folder as qr code generator.
