### ISSUE TITLE
An Image Search App using ReactJs and Unsplash API

### ISSUE THREAD

**Issue by NehaKariya0309** [pranjay-poddar/Dev-Geeks#1192]
Project: Image Search App 

Use: It lets the users search images as per the given keyword.
Tech Stack : HTML, CSS, ReactJs and Unsplash API.

Screenshot:

![Screenshot (49)](https://github.com/pranjay-poddar/Dev-Geeks/assets/100693529/5328d480-e7c5-44e2-a6e1-0be4202545f0)

Hey, 
I am a GSSoC'23 Contributor. I am interested to share my project. The valuable feedback and suggestions that I would receive from others would help me make further improvements in this project.
Thanks and regards,
Neha Kariya

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
