### ISSUE TITLE
Guess-my-number

### ISSUE THREAD

**Issue by ayan878** [pranjay-poddar/Dev-Geeks#1196]
**Describe the Feature you want to end**

**Expected behavior**
I want to Integrate celebration features to enhance user experience and bring joy upon winning games.

**Screenshots (optional)**
![Screenshot (744)](https://github.com/pranjay-poddar/Dev-Geeks/assets/91191292/720efdfb-652c-4208-acb7-36e19dc2059f)

**Comment by stutishah177** [comment]
I would like to upgrade the UI of this game

**Comment by trisharaj06** [comment]
I would like to work on this issue, please assign this to me
