### ISSUE TITLE
Update Readme.md 

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#12]
update readme with the missing information and add some attractive components and badges in it.

**Comment by Nymphalys** [comment]
Can you assign this issue to me,I can fix this

**Comment by Gautam-10137** [comment]
@pranjay-poddar  Can you assign it to me?

**Comment by IT-0824** [comment]
I would like to contribute to the particular issue, kindly assign me the concerned issue.
