### ISSUE TITLE
Real-time Weather Information Provider

### ISSUE THREAD

**Issue by swati-sharma14** [pranjay-poddar/Dev-Geeks#1200]
Description:
The Real-time Weather App is a web application that provides users with live weather updates for their desired location. The app will display the current weather conditions, temperature, humidity, wind speed, and other relevant information. It will also include vibrant icons and animations representing different weather conditions, such as sun, clouds, rain, and snow. The app will be developed using HTML, CSS, and JavaScript, and it will make use of a weather API to fetch real-time weather data.

Expected behavior:
When the user opens the Real-time Weather App, they will be prompted to enter their location or grant permission to use their current location. The app will then fetch the weather data for that location from the weather API and display it on the screen. The weather information will be presented in a visually appealing and interactive manner, with vibrant icons and animations corresponding to the current weather conditions. The app will update the weather information periodically to ensure it stays up to date.

**Comment by jyoti145** [comment]
hey @swati07sharma I would like to work on this issue.Please assign me this issue
