### ISSUE TITLE
[GSSoC'23] Pac-man Game

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1204]
**Describe the project you want to add with tech stack**
 I would like to create a Pac-Man game using vanilla JavaScript, HTML, and CSS. The game will be a simplified version of the classic arcade game.

**Expected behavior**
1. The game will have a maze with walls, pellets, and ghosts.
2. The player will control Pac-Man using arrow keys to move in four directions (up, down, left, right).
3. Pac-Man will be able to eat pellets as it moves through the maze, increasing the player's score.
4. Ghosts will move around the maze, attempting to catch Pac-Man.
5. If Pac-Man collides with a ghost, the game will end.
6. The game will display the player's score and provide an option to restart the game.

**Screenshots (optional)**

**Additional context (optional )**
Kindly assign this project to me under GSSoC'23

**Comment by Mridulians** [comment]
Kindly assign this project to me under GSSoC'23

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Sampath-Vatsavaya** [comment]
Please assign this issue to me
