### ISSUE TITLE
[GSSoC'23] Wordle Clone

### ISSUE THREAD

**Issue by Arka2708** [pranjay-poddar/Dev-Geeks#1206]
**Describe the project you want to add with tech stack**
 Wordle is a popular word-guessing game where players try to guess a five-letter word by making guesses and receiving feedback on the correctness of their guesses. I'm gonna build it with HTML, CSS, JS, Rapid API, and Dictionary API.

**Expected behavior**
Players will be presented with a blank word and an input field where they can enter their guesses. After submitting a guess, the game will provide feedback on the correctness of the guess. The feedback may include information on correct letters in the correct positions and correct letters in the wrong positions. The player continues making guesses until they successfully guess the five-letter word or run out of attempts.

**Screenshots (optional)**

**Additional context (optional )**
Assign me this project under GSSoC'23.

**Comment by Gun2902** [comment]
can u assign me this isssue
