### ISSUE TITLE
Want to add background to the notes

### ISSUE THREAD

**Issue by PrachiChauhan23** [pranjay-poddar/Dev-Geeks#1207]
i want to add background image in the notes. That will make it attractive. please assign me this isuue @pranjay-poddar under GSSOC'23

**Comment by ankitsunil530** [comment]
I am want  to work on it.Please assign it to me.

**Comment by ankitsunil530** [comment]
i want to add background image in the notes. That will make it attractive. please assign me this isuue @pranjay-poddar under GSSOC'23

**Comment by kadamvarsha112** [comment]
I want to work on this issue under GSSOC23. Please assign it to me.

**Comment by PrachiChauhan23** [comment]
Sir, what's the deadline for this. @pranjay-poddar

**Comment by pranjay-poddar** [comment]
> Sir, what's the deadline for this. @pranjay-poddar 

There is no deadline

**Comment by Gun2902** [comment]
can u assign me this isssue
