### ISSUE TITLE
Lip Read using DL || GSSoC'23

### ISSUE THREAD

**Issue by Mochoye** [pranjay-poddar/Dev-Geeks#1212]
Hey!
Myself Archisman, GSSoC'23

**Describe the project you want to add with tech stack**
It will be a convolutional neural network that is trained on a large dataset of videos of people speaking. The model can be used to recognize words and phrases from lip movements.

**Expected behavior**
 A powerful tool for lipreading and has been used in a variety of applications, including:

Automatic speech recognition
Sign language recognition
Virtual assistants
Video surveillance

**Comment by Mochoye** [comment]
I want to do this

**Comment by Gun2902** [comment]
can u assign me this isssue
