### ISSUE TITLE
Educational Course website

### ISSUE THREAD

**Issue by Ks103** [pranjay-poddar/Dev-Geeks#1214]
**Describe the project you want to add with tech stack**
An Educational Course website where students gets access to all the free courses

**Expected behavior**
Through this website student can get knowledge and able to skilledup their skills.

**Screenshots (optional)**
![Screenshot 2023-05-22 134540](https://github.com/pranjay-poddar/Dev-Geeks/assets/86292101/6d3bb4ac-5c6c-4cd5-afc2-84ad05918468)

**Additional context (optional )**
Please assign me this issue so that i can start working on the project

**Comment by aarushiagarwal131** [comment]
I would like to contribute in this project. Please assign this to me.

**Comment by Ks103** [comment]
Please assign it to me as I was the first to raise the pr
