### ISSUE TITLE
[GSSoC'23] Adding a translator.

### ISSUE THREAD

**Issue by ShivangRawat30** [pranjay-poddar/Dev-Geeks#1215]
**Describe the project you want to add with tech stack**
We can add a translator which can translate full sentences from one language to another using HTML, CSS and JS. 

**Expected behaviour**
A person can translate the sentence from their native language to another language using this project, we can also provide text to speech option also.

**Screenshots (optional)**

**Additional context (optional )**
Can you assign this to me ?

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Gun2902** [comment]
can u assign me this isssue
