### ISSUE TITLE
[GSSoC'23] Adding a Todo app.

### ISSUE THREAD

**Issue by ShivangRawat30** [pranjay-poddar/Dev-Geeks#1216]
**Describe the project you want to add with tech stack**
We can add a Todo app in which we can add the important work we have to do.

**Expected behavior**
This app will provide you to add everything that you have to do and can delete the task after completion.

**Screenshots (optional)**

**Additional context (optional )**
Please Assign this to me

**Comment by aarushiagarwal131** [comment]
I would like to contribute in this project. Please assign this to me.

**Comment by Humaira-Sadia** [comment]
Hello @pranjay-poddar I would be very happy to contribute to this project😃

Functionality of the project :- 
1. User can ADD a list of tasks they need to complete or things that they want to do.
2. User can DELETE the accomplished tasks.
3. User can EDIT the list of tasks.
4. With a beautiful UI and user interacting Interface and also with many more features.

Please assign this issue to me :)

**Comment by Sanikagoyal28** [comment]
Hello sir, I would like to make my contribution to this project.
Functionality that can be added to the project :
1. user can add a task
2. user can delete a task
3. user can edit a task
4. user can view their tasks
5.  provide an interactive UI
6. data will retain on the page even after refreshing the page

**Comment by pranjay-poddar** [comment]
Todo app is already present
