### ISSUE TITLE
[GSSoC'23] Styling & Improving Js-Projects - Digital Clock

### ISSUE THREAD

**Issue by Ekam-Bitt** [pranjay-poddar/Dev-Geeks#1218]
**Describe the Feature you want to add**

Improve the overall styling (CSS) of the digital clock project and make it responsive
<br>
**Expected behavior**

The clock will be more visually appealing and be responsive for all screens
<br>
**Screenshots (optional)**
<br>
**Additional context**

I would like to work on this issue, please assign this to me

**Comment by AdityaGoel0320** [comment]
hi , i am ready to solve this issue 
I will update its UI and make it responsive , kindly assign this to me under GSSOC'23
