### ISSUE TITLE
Rock Paper Scissors Enhance UI

### ISSUE THREAD

**Issue by ayan878** [pranjay-poddar/Dev-Geeks#1219]
**Describe the Feature you want to end**

**Expected behavior**
I want to enhance the UI of Rock Paper Scissors Game

**Screenshots (optional)**
![Screenshot (750)](https://github.com/pranjay-poddar/Dev-Geeks/assets/91191292/7bf9fda8-e1fc-4eca-af93-36f8c7812900)

**Comment by AdityaGoel0320** [comment]
hi i am ready to solve this issue please assign me this .

**Comment by MahibaJeyaraj** [comment]
is this issue open ?
