### ISSUE TITLE
adding dark mode button on top in mobile screen

### ISSUE THREAD

**Issue by RJ025** [pranjay-poddar/Dev-Geeks#1224]
hello @pranjay-poddar 
currently dark mode button is in burger menu in top right while in mobile screen size.
CHANGES : it would look better side of the website logo it would look more aesthetic.
please assign me this issue under the tag of GSSOC'23
I am GSSOC'23 contributor

**Comment by rajputsingh808** [comment]
hello sir 
i want to work on this project under GSSOC'23 which helps to read the screen easily. Please assign me.
