### ISSUE TITLE
devloping apple-ecommerce project

### ISSUE THREAD

**Issue by Chhavi-Adlakkha** [pranjay-poddar/Dev-Geeks#1225]
I  would like to build this website with react.js
I will enhance some ui part like the navbar ,header footer and diffrent pages
I will add products , wishlist and a bag to the navbar and the navbar will be responsive with hamburger menu.
I will add signin and signup for this website
I will like to list diffrent apple products like mac book , iphone ,ipad  with the help of strapi api.
I will change the tiltle of the website

By changing all of this the apple eccommerce project will become more elegant and userfriendly.

**Comment by Kapileswar-Moharana** [comment]
I would like to work on this project and make more attractive and user friendly, assign this to me
