### ISSUE TITLE
Calculator in java projects 

### ISSUE THREAD

**Issue by SALONI-AGGARWAL0304** [pranjay-poddar/Dev-Geeks#1227]
**Describe the project you want to add with tech stack**

I want to add JAVA project that is calculator , to perform basic operations like addition , subtraction , division and multiplication . 

**Expected behavior**

A calculator where you can perform basic operations . 

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SALONI-AGGARWAL0304** [comment]
I have learnt java language on intermediate level , and I can easily make calculator using java . Please assign this to me under GSsoc'23

**Comment by Vanshika2103** [comment]
I want to know some something. So do you require GUI based code using swing java. If yes then please assign this task to me.

**Comment by Sushilverma002** [comment]
can u please assign me this project.  I will do this
