### ISSUE TITLE
[GSSoC'23] Adding RandomForestRegression model and mean absolute error - ML Projects- Bitcoin Price Prediction

### ISSUE THREAD

**Issue by AkhilN7** [pranjay-poddar/Dev-Geeks#1228]
Describe the Feature you want to end
We can a RandomForestRegression model and also to add mean absolute error.

Expected behavior
To have a better model.

**Screenshots (optional)**

**Additional context (optional )**
Please assign it to me

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
