### ISSUE TITLE
Drum kit in frontend projects 

### ISSUE THREAD

**Issue by SALONI-AGGARWAL0304** [pranjay-poddar/Dev-Geeks#1229]
**Describe the project you want to add with tech stack**

I want to add new project or a game in frontend projects . 

**Expected behavior**

It is a drum kit game where while pressing the required keys sounds will be generated . 

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/112769048/1dec5257-c723-443e-9a57-af3aa22af763)

**Additional context (optional )**

**Comment by SALONI-AGGARWAL0304** [comment]
Please assign the above issue to me under GSsoc'23

**Comment by pranjay-poddar** [comment]
Project already present
