### ISSUE TITLE
modify the arrays file

### ISSUE THREAD

**Issue by Kavya-chitipotu-05** [pranjay-poddar/Dev-Geeks#1231]
**Describe the Feature you want to end**

I want to contribute to the project, by adding 3 new problem statements (easy - med - hard) with detailed approaches and time complexity 

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Kavya-chitipotu-05** [comment]
please assign this issue to me under GSSOC'23

**Comment by pranjay-poddar** [comment]
> **Describe the Feature you want to end**
> 
> I want to contribute to the project, by adding 3 new problem statements (easy - med - hard) with detailed approaches and time complexity 
> 
> **Expected behavior**
> 
> 
> **Screenshots (optional)**
> 
> 
> **Additional context (optional )**
> 
> DSA problem are not accepted
