### ISSUE TITLE
[GSSOC'23] Image finder 

### ISSUE THREAD

**Issue by sumitbaroniya** [pranjay-poddar/Dev-Geeks#1232]
I want to add image finder project. Please assign me this issue under GSSOC'23.

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by sumitbaroniya** [comment]
@Aditi323 i am working on it so please look another issue.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
