### ISSUE TITLE
[GSSOC'23] Codepen clone

### ISSUE THREAD

**Issue by sumitbaroniya** [pranjay-poddar/Dev-Geeks#1233]
Please assign me this issue under GSSOC'23.

**Comment by iam-ravi-12** [comment]
I'm interested in working on this project. I'm going to use React.js to integrate Codepen into this website. hence, give me this assignment to work on during GSSOC'23.

**Comment by sumitbaroniya** [comment]
@iam-ravi-12 i am working on it so please look another issue
