### ISSUE TITLE
Add a Tic Tac Toe project using javascript

### ISSUE THREAD

**Issue by AyishikD** [pranjay-poddar/Dev-Geeks#1236]
I want to add a Tic Tac Toe game using html css and javascript as a project. It will also help other fellow contributors to contribute in the new project.

**Comment by AyishikD** [comment]
This project is a tic tac toe game. It is made using html css javascript. In this project two user can play tic tac toe. Using javascript the logic is done. If a player wins it shows either player one or player two has won. also for draw it shows match drawn. Of suggested I can add another feature to play with computer on various difficulties.. Also can add background image. Currently I dont have screenshot as it is under development

**Comment by AyishikD** [comment]
Also to mention it is under gssoc

**Comment by pjyoti121** [comment]
I am GSSOC contributor. can you please assign this issue to me ?

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by AyishikD** [comment]
Please review the work done
