### ISSUE TITLE
I want to change the title of the page

### ISSUE THREAD

**Issue by shivani2190** [pranjay-poddar/Dev-Geeks#1242]
**Describe the Feature you want to end**
want to add a catchy heading to the website

**Expected behavior**
attractive heading for people to approach and visit the website

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by khushi767** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by gkm0001** [comment]
Please assign me this issue ,I want to work on this issue .

**Comment by Shiwani2002** [comment]
I want to work on it please assign this issue to me @pranjay-poddar
