### ISSUE TITLE
Random Quote Generator 

### ISSUE THREAD

**Issue by Vidhi-44** [pranjay-poddar/Dev-Geeks#1243]
I would like to make website which generates Random Quotes . I will be using HTML, CSS and JavaScript as my  programming language. 
The UI would be simple and attractive > 
DO assign this issue to me under GSSoC-23 . Really excited to work on this issue .

**Comment by Vanshika2103** [comment]
can you please assign this task to me ? i want to work on your code.

**Comment by Vanshika2103** [comment]
I can create a beautiful Random qoutes generator website by just using HTML, CSS, JS.
