### ISSUE TITLE
I would like to give an attractive title

### ISSUE THREAD

**Issue by Silentshooter** [pranjay-poddar/Dev-Geeks#1248]
**Describe the Feature you want to end**
an attractive title for Btech Tea shop

**Expected behavior**
your site will gain popularity 
**Screenshots (optional)**

**Additional context (optional )**

**Comment by rawalgeetika** [comment]
I am Geetika Rawal. Could you please assign this task to me. I am GSSOC ' 23 contributor.

**Comment by pjyoti121** [comment]
Can you please assign this task to me ?

**Comment by Gun2902** [comment]
can u assign me this isssue
