### ISSUE TITLE
Sales Prediction 

### ISSUE THREAD

**Issue by Shreyg-27** [pranjay-poddar/Dev-Geeks#1249]
**Describe the project you want to add with tech stack**
With the help of an appropriate Machine Learning model, I would like to create a Sales Prediction Model for a retail Supermart, or any shop.

**Expected behavior**
So for a specific dataset, the first step would be finding out the best model (that gives the best accuracy) followed by training and testing the model on that selected model and then predicting the values.

**Comment by Gun2902** [comment]
can u assign me this isssue
