### ISSUE TITLE
Space Invaders Game

### ISSUE THREAD

**Issue by Ayushkumargit7** [pranjay-poddar/Dev-Geeks#1251]
**Describe the project you want to add with tech stack**
I want to Add a Space Invaders Game, made using HTML , CSS  and JavaScript.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114018461/8fab86b9-addd-4c13-b1a2-6a287ec9e86f)

**Comment by Harshajny** [comment]
Hi 
I would like to work on this. Can you please assign it to me.
