### ISSUE TITLE
Want to add new title to Ecommerce Sneaker Website under GSSOC'23

### ISSUE THREAD

**Issue by Zedoman** [pranjay-poddar/Dev-Geeks#1255]
**Describe the Feature you want to end**
A attractive title to the website

**Expected behavior**
will make the website more attractive and also gain popularity.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Akashsingh1118** [comment]
I would like to add a new attractive title to the website.

**Comment by Zedoman** [comment]
completed
