### ISSUE TITLE
Expanding image Carousel Project Addition 

### ISSUE THREAD

**Issue by buildwithaman** [pranjay-poddar/Dev-Geeks#1257]
**Describe the project you want to add with tech stack**
This is a simple JavaScript project where the viewer can choose their own images from their local . when clicked on a particular image it will expand with  an animation effect.

Tech Stacks Used --  HTML , CSS , JavaScript . 

**Expected behavior**
When clicked on a particular image it will expand with an animation effect

**Screenshots (optional)**
This is an example where I have chosen my favourite images. But others can choose their own

 
![1st Cover image](https://github.com/pranjay-poddar/Dev-Geeks/assets/112074298/b125a980-79b7-422d-aa87-c9a88797f04e)

**Comment by buildwithaman** [comment]
hello 
I am a GSSOC ' 23 contributor 
please assign me this issue

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
