### ISSUE TITLE
[New Project]Want to add a maze solver in cpp-projects

### ISSUE THREAD

**Issue by vishal8113** [pranjay-poddar/Dev-Geeks#1260]
**Describe the project you want to add with tech stack**
I will create a CPP program using dfs(Depth First Search) algorithm which will find the shortest path from a start point to an exit point

**Expected behavior**
It will solve a maze by finding the shortest path

**Screenshots (optional)**

**Additional context (optional )**

**Comment by pranjay-poddar** [comment]
Cpp codes are not accepted under GSsoc23
