### ISSUE TITLE
Weather Application

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1261]
**Describe the project you want to add with tech stack**
A Weather application using HTMl, JavaScript and CSS, and OpenWeather API

**Expected behavior**
On entering the location, the application will show you the temperature of that place, with enhanced symbols depicting the weather at that place

**Comment by pranjay-poddar** [comment]
Project already present

**Comment by PoulavBhowmick03** [comment]
Okay.
