### ISSUE TITLE
Addition of Fruit Ninja Game in Games

### ISSUE THREAD

**Issue by Mukesh751** [pranjay-poddar/Dev-Geeks#1265]
**Describe the project you want to add with tech stack**
A classic a fruit ninja game made HTML, CSS and JS.

**Expected behavior**
 A game where user slice all the fruit thrown at the screen, every fruit he/she cuts will be counted for high score, if the user misses three times, game over.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by Mukesh751** [comment]
Sir I have already completed this issue, #1574 . I am closing this issue. 

THANK YOU SO MUCH SIR
