### ISSUE TITLE
[GSSoC'23] ML project to detect Spam Email's

### ISSUE THREAD

**Issue by ManasaKaza** [pranjay-poddar/Dev-Geeks#1269]
**Describe the project you want to add with tech stack**
The project aims to develop a machine learning-based system for detecting spam emails. The goal is to build a robust model that can accurately classify incoming emails as either spam or non-spam (ham) based on their content and characteristics.
Tech Stack: Python,Scikit-learn, NLTK, Pandas

**Expected behavior**
This is a reliable spam email detection ML project that can accurately classify all the incoming e-mails as a spam or non-spam mails and gives them seperately.

**Comment by IishuJainn** [comment]
Please assign me this issue.

**Comment by pooranjoyb** [comment]
Hey @ManasaKaza , is it possible that we work this out together, I was planning for a simple Streamlit GUI for the same.
Refer to Issue #1275
Reply if feasible.

**Comment by ManasaKaza** [comment]
Sure @pooranjoyb let's do it.

**Comment by pooranjoyb** [comment]
Let's get assigned then we can start. @ManasaKaza @pranjay-poddar 😄
