### ISSUE TITLE
Portfolio Website Using Python Django

### ISSUE THREAD

**Issue by samsorrahman** [pranjay-poddar/Dev-Geeks#1277]
**Describe the project you want to add with tech stack**

I want to add a portfolio project using Python Django
I have worked on frontend now I want to add on the backend using Python Django

**Expected behavior**

We would like to use postgres Database along with Django where a person can upload his/her newly updated information, skills, services, and a contact form

**Screenshots (optional)**

![Capture2](https://github.com/pranjay-poddar/Dev-Geeks/assets/112087807/d718f492-1c48-434d-8925-0eb19b6ae04f)

**Additional context (optional )**

**Comment by siddhiagarkar** [comment]
I am willing to work on this website as I am well-versed in the Django framework. In my previous projects, I have worked with the SQLite3 database. I am excited to learn to work with Postgres. Could you assign the work to me?

**Comment by samsorrahman** [comment]
https://github.com/samsorrahman/myPortfolio 
@siddhiagarkar the above is the reposioty
First we have to create model delete the existence model and create new one

**Comment by siddhiagarkar** [comment]
> https://github.com/samsorrahman/myPortfolio @siddhiagarkar The above is the repository First we have to create a model delete the existing model and create a new one

Do I need to create login logout functionality?

**Comment by samsorrahman** [comment]
@siddhiagarkar No you don't need to create login functionality
for visualizing purpose you can visit [portfolio](https://salmon-sand-067339700.2.azurestaticapps.net/)
