### ISSUE TITLE
Add Logo Finder in fronted projects

### ISSUE THREAD

**Issue by devWonderkind** [pranjay-poddar/Dev-Geeks#1280]
**Describe the project you want to add with tech stack**
I want to add logo finder website. 
Tech stack:  HTML, Tailwind CSS, JS.

**Expected behavior**
Here you can enter the URL of website and find logo of the website as well as download the logo.

**Screenshots (optional)**
![project2](https://github.com/pranjay-poddar/Dev-Geeks/assets/110322061/7873d6bf-d73d-4c1d-821f-8131536c5023)
![project1](https://github.com/pranjay-poddar/Dev-Geeks/assets/110322061/d48529ce-3bcb-4302-bfc7-68017b3f1db3)

hey @pranjay-poddar Please assign this issue to me under GSSoC'23.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
