### ISSUE TITLE
want to add a stock price prediction under python projects

### ISSUE THREAD

**Issue by Zedoman** [pranjay-poddar/Dev-Geeks#1281]
**Describe the project you want to add with tech stack**
want to add a stock market price prediction code in python projects section under GSSOC'23.

**Expected behavior**
Predict the Stock market values for ups and downs.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
