### ISSUE TITLE
Prediction of Hand Written digits 

### ISSUE THREAD

**Issue by Raghucharan16** [pranjay-poddar/Dev-Geeks#1282]
**Describe the project you want to add with tech stack**
 ****This Deep Learning project was simple hand written digit recognition integrated with web including MNIST dataset and tensorflowjs .****

**Expected behavior**
****The project is expected to predict the handwritten digits, so that users can draw any numbers and the model predicts the number and displays the confidence of graph****
**Screenshots (optional)**

![Screenshot (1)](https://github.com/pranjay-poddar/Dev-Geeks/assets/104614903/804218eb-9037-4543-a3e2-c1ab3035fc09)

***kindly assign this issue to me under GSSoC label.***

**Comment by Saurabh-kumar09** [comment]
@Raghucharan16 You can start working on this issue.

**Comment by Raghucharan16** [comment]
_**hey @Saurabh-kumar09 I prepared the files and wanting to show how this one works. I already hosted it online and same was on my github and you can see the page at [Hand written digit prediction](https://raghucharan16.github.io/Hand-Written-Digit-Recognition/). if you like the project I want to make series of deep learning projects and I request you to create a deep learning folder under your main Dev-Geeks repo. or it would be fine to place this under python projects.
thank you.**_

**Comment by Raghucharan16** [comment]
Hey @Saurabh-kumar09 I made a pull request #1568 regarding my idea. Hope it suits the domain (ML projects) please review it and label the difficulty Label 1,2,3 (as it suits). 
### Looking forward to work and contribute more to [Dev-Geeks](https://github.com/pranjay-poddar/Dev-Geeks)  

## Thank you.

**Comment by Raghucharan16** [comment]
Hey @Saurabh-kumar09, Thanks for merging this PR. But this level3 score (45 points) doesn't reflect in total score. can i know why is that? Is there any mistake done from my side so that i can rectify it and improve my score. As i can see you labelled my PR as level3 but score was not added to me. please help me with this.
