### ISSUE TITLE
[GSsoc'23] React Project (pomodoro timer)

### ISSUE THREAD

**Issue by AhmedBedeir** [pranjay-poddar/Dev-Geeks#1286]
Pomodoro timer by Reactjs

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/66643588/b7ae2bee-edbb-4b76-ba2c-0ef90604bdf6)

**Comment by AhmedBedeir** [comment]
@pranjay-poddar 
Please assign me this issue under GSSOC'23.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
