### ISSUE TITLE
[GSSOC'23] React project (YouTube clone)

### ISSUE THREAD

**Issue by AhmedBedeir** [pranjay-poddar/Dev-Geeks#1288]
**Describe the project you want to add with tech stack**
This project includes the major features of Youtube such as

- home feed
- searching for videos
- watching videos
- displaying video details and channel details

Tech stack:
- React / Vite
- react-router
- Axios
- Material-UI

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/66643588/de5728de-d8ac-4b99-a818-52092bae8ac2)

**Additional context (optional )**
@pranjay-poddar, please assign me this under GSsoc'23

**Comment by AhmedBedeir** [comment]
@rising-star2712 Nope, it just adds the project to react project lists.
and if you have any kind of project you can add it to the category that it belongs.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
