### ISSUE TITLE
Digital clock 

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#129]
**Describe the project you want to add with tech stack**
A digital clock in vanilla javascript

**Expected behavior**
It would display time.

**Screenshots (optional)**
Haven't made yet

**Additional context (optional )**

**Comment by sumitbaroniya** [comment]
@pranjay-poddar please assign me this issue

**Comment by srinjoy-26** [comment]
> @pranjay-poddar please assign me this issue

Already made a PR and it got merged too
