### ISSUE TITLE
QRCODE-Generator 

### ISSUE THREAD

**Issue by vidhimakani74** [pranjay-poddar/Dev-Geeks#1297]
**Describe the project you want to add with tech stack**
this is simple QR code generator in which you generate qr code with only give the String or link/url using html,css and javascript.
 

**Expected behavior**
in this generator you can enter any url/link or any string and just click on Generate button & QR Code is genearted. 

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100896986/28921b4b-e857-4eda-9bc4-401df8ce6567)

**Additional context (optional )**

**Comment by akhilmishra365** [comment]
please assign me this issue i have already created the html and css part.

**Comment by akhilmishra365** [comment]
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/88160249/afeeb42e-a453-44e8-84bd-3d666b5d9667)
Code Pen  LINK ----:   [](https://codepen.io/AKHIL-MISHRA/pen/gOBqRrb)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
