### ISSUE TITLE
Improve Responsive Sidebar

### ISSUE THREAD

**Issue by Ayush9951** [pranjay-poddar/Dev-Geeks#1298]
Hi @pranjay-poddar, I am a contributor in GSSOC'23.
I want to work on Improving the Responsive sidebar project under navbars repository.
Please assign me this task under label gssoc23

problem - 
1. letter-spacing in sidebar is not proper.
2. sidebar icons and title are stacked on top of each other in each card

solution -
I will make icons and title stacked horizontally and Improve the letter-spacing 

![Screenshot 2023-05-23 183421](https://github.com/pranjay-poddar/Dev-Geeks/assets/60573378/78e1dce8-3bd3-489f-81ca-a22986821976)

**Comment by ismilesardar** [comment]
I want work on Improving the Responsive side bar project. Please assign me.

**Comment by Hemangi-soni** [comment]
Hello @pranjay-poddar 
I am a contributor in GSSOC'23. I would like to solve this issue. Please assign me this task under label gssoc23.

Problem identified :-
    1.	Menu item names and icons are not aligned properly
    2.	The sidebar title is not descent
    3.	Letter-spacing is not appropriate
    4.	The CSS doesn’t look eye-catching

Solution :-
I will make the icons and menu-item names aligned properly and change the menu-title name “sidebar” and Improve the letter-spacing. Moreover , I will make it more descent and eye-catching . I will also work on improving the hamburger-menu icon.

**Comment by dheeraj1129** [comment]
I am a contributor in GSSOC'23. I would like to solve this issue. Please assign me this task under label GSSOC'23.

Problem Solution:

1.Utilize CSS media queries
2.Prioritize important content
3.Implement a toggle button
4.Optimize touch interaction
5.Test across multiple devices

**Comment by sahilduhan** [comment]
Hello @pranjay-poddar 
I am a contributor in GSSOC'23. I would like to solve this issue. Please assign me this task under label gssoc23.

Possible Solutions for the problems

1. Using Media queries in order to improve the responsiveness of the navbar
2. Improving the design and the layout keeping user-friendliness at high priority
3. Testing the code over multiple screen sizes in for better responsiveness

**Comment by mahimak13** [comment]
I would like to do this task .
Please assign me the task

**Comment by Ayush9951** [comment]
Hi @Saurabh-kumar09, I've successfully the Improved the layout issue and sent the pull request but still It's not been assigned.
Kindly please assign this issue and merge the pull request.
