### ISSUE TITLE
Want to add new title to Ecommerce Bike Website under GSSOC'23

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1299]
**Describe the Feature you want to end**
A attractive title to the website

**Expected behavior**
will make the website more attractive and also gain popularity.

**Additional context (optional )**
I would like to add a new attractive title to the website.

**Comment by AYUSHSURYAVANSHI** [comment]
I would like to add a new attractive title to the website.
