### ISSUE TITLE
Website For DevGeeks

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#130]
A website for dev geeks listing all the projects with a search option.

**Comment by iamsandeepshekhawat** [comment]
@pranjay-poddar can you assign this issue to me.

**Comment by anjaliSilawat** [comment]
I would like to work on this task, @pranjay-poddar please assign it to me

**Comment by Harshita1010** [comment]
I would like to work on this issue under GSSOC'23 , Please assign this issue to me @pranjay-poddar

**Comment by Haricharan0310** [comment]
Hey @pranjay-poddar ! I have experience in building websites, I'd like to work on this issue under GSSOC'23.

**Comment by bleep123** [comment]
I would like to work on this issue. Can you please assign this issue to me. @pranjay-poddar

**Comment by kriti-002** [comment]
I would like to work on this issue. Can you please assign this issue to me? @pranjay-poddar

**Comment by Suchitra-Sahoo** [comment]
I would like to work on this issue under GSoC'23. I have experience in web development particulary HTML, CSS, JavaScript. Can you please assign this to me @pranjay-poddar

**Comment by PriyankaTamhankar01** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by Saloni581** [comment]
Could you please assign me this issue? I believe that I will learn a lot from it.

**Comment by ivanMehvish** [comment]
Can you please assign me this issue for GSSoC'23?
I believe i can research and help you out with it.

**Comment by PoulasthaMukherjee** [comment]
@pranjay-poddar Could you please assign me this? I have experiences relevant to this.

**Comment by ishita-saraswat** [comment]
I am interested in taking this issue up. I have experience in these technologies and am looking forward to contributing to this issue. @pranjay-poddar

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by rv1830** [comment]
can you please assign this to me

**Comment by SinghSachin2000** [comment]
Hey @pranjay-poddar  I am super excited and eager to take on this incredible project for GSSOC'23. With my passion, dedication, and skills, I am ready to dive headfirst into this opportunity and make it a resounding success

**Comment by gkm0001** [comment]
Hey @pranjay-poddar  I am interested to work in this issue . I would be happy to work on this issue.

**Comment by AVUKU-PRAGATHESWARI** [comment]
Hey @pranjay-poddar ..Please assign me this issue under GSSoC'23, thank you.

**Comment by OWAIS221B** [comment]
I would like to work on this project. I am familiar with these technologies. Please assign me this project. THANKS

**Comment by Meghaa702** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by guptafactory** [comment]
I am interested in taking this issue up. I have experience in these technologies and am looking forward to contributing to this issue @pranjay-poddar

**Comment by akshat-gupta60** [comment]
Can you assign this issue to me. I have decent knowledge of HTML,CSS and Javascript

**Comment by ujjwal-11103** [comment]
I would like to work and contribute to this issue, please assign this issue to me @pranjay-poddar

**Comment by ombhojane** [comment]
Hey @pranjay-poddar , Please tell what to do exactly.
I would happy to contribute.
GSSOC'23 :)

**Comment by Parijatkumar** [comment]
Hi I would like to work on this issue plz Assign it to me   @pranjay-poddar

**Comment by Himanshurajputrr** [comment]
Hi I wants to work on this issue plse Assign me @himanshurajputrr

**Comment by Nandita099** [comment]
Hey I want to work on this issue @pranjay-poddar.
please assign me this issue
I am a GSSOC'23 contributor.

**Comment by 007AnupamSharma** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by Shiwani2002** [comment]
Hi I would like to work on this issue plz Assign it to me @pranjay-poddar

**Comment by soumya-maheshwari** [comment]
I want to work on it.
please assign it to me 
@pranjay-poddar

**Comment by soubhik-111** [comment]
@MohitGupta121 Can you assign me this task under GSSOC'23
