### ISSUE TITLE
Flow CV Login Page Clone

### ISSUE THREAD

**Issue by Ayush9951** [pranjay-poddar/Dev-Geeks#1300]
Hi @pranjay-poddar , I am a contributor in GSSOC'23
I want to add a new project in frontend-projects repository.

project details - I will create a simple login page clone of Flow CV website.
About Flow CV -  It is a resume making website.

Please assign me this task under label gssoc23.

**Comment by Sujal942** [comment]
I would like to work in this project. Please assign it to me.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
