### ISSUE TITLE
[GSSoC23] react project new website.

### ISSUE THREAD

**Issue by Saurabhrajput1234** [pranjay-poddar/Dev-Geeks#1301]
Project Description:
I have created an news website called "News-sa" using React and  CSS. The app serves as a platform for users to find news . where we fetch a news API .

Tech Stack:

React: I chose React as the main framework for building the app due to its component-based architecture, virtual DOM, and extensive ecosystem of libraries and tools. It allows for efficient and scalable development of user interfaces.
 CSS: I used  CSS as the styling framework for the app. It provides a utility-first approach, enabling rapid development and customization of the user interface. With its extensive set of pre-defined classes, I was able to create a visually appealing and responsive design.
Expected behavior
The app should provide a seamless   experience for users. They should be able to navigate through different news  categories, view news in details.

please assign me this issue to  solve
as under the GSSoC'23
thanks you

**Comment by Saurabhrajput1234** [comment]
ok
please assign me this issue

**Comment by Saurabh-kumar09** [comment]
@Saurabhrajput1234 You can start working on this issue.
