### ISSUE TITLE
Want to add new title to Hotel Website under GSSOC'23

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1302]
**Describe the Feature you want to end**
A attractive title to the website

**Expected behavior**
will make the website more attractive and also gain popularity.

**Additional context**
I would like to add a new attractive title to the website.

**Comment by siwangigahlot** [comment]
I will be delighted to take up this issue

**Comment by gkm0001** [comment]
I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. With my [mention relevant skills/experience], I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.
