### ISSUE TITLE
TO-DO-LIST ui changed

### ISSUE THREAD

**Issue by harshita-2003** [pranjay-poddar/Dev-Geeks#1305]
**Describe the Feature you want to end**

In frontened project to do list is there but with poor frontened though it works fine I have improved the look of it
NOTHING IS CHANGED IN THE WORKING OF IT IT WORKS PERFECTLY FINE.

**Screenshots (optional)**
(EARLIER):
![Screenshot 2023-05-23 184032](https://github.com/pranjay-poddar/Dev-Geeks/assets/119532943/6490f89e-2a0a-41c9-aab1-09f790cf63c3)

(NOW):
![Screenshot 2023-05-23 193404](https://github.com/pranjay-poddar/Dev-Geeks/assets/119532943/a6e00d7a-30fb-4bd4-9def-c151f4e1c804)

**Comment by harshita-2003** [comment]
assign this to me

**Comment by SadiqITrmlau** [comment]
I think we can make the ui far more subtle and aesthetic. So pls assign me

**Comment by pragya1976** [comment]
I would like to work on this

**Comment by Kapileswar-Moharana** [comment]
I Would like to work on this project under GSSoC , Assign this issue to me

**Comment by harshita-2003** [comment]
DONE IN #1306 
you can close this now
