### ISSUE TITLE
[GSSOC'23] Item Lister

### ISSUE THREAD

**Issue by sahil-1729** [pranjay-poddar/Dev-Geeks#1320]
**Describe the project you want to add with tech stack**
The projects aims to create, search and delete items.
The tech stack being used is HTML, CSS, Javascript

**Expected behavior**
The user can create task, also search the task which has been created, and lastly once the task is completed, the user can delete the task

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97158384/d4d6ffdf-6f89-4801-816c-a9c6a87175b4)

**Additional context (optional )**
I am a GSSOC'23 contributer, so kindly assign me this issue

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
