### ISSUE TITLE
Crypto Currency

### ISSUE THREAD

**Issue by code-gen21** [pranjay-poddar/Dev-Geeks#1321]
**Describe the project you want to add with tech stack**
The React app on cryptocurrency tracker is a powerful and user-friendly application built using the React JavaScript library. It is designed to provide real-time information and analysis of various cryptocurrencies, enabling users to track their favorite digital assets efficiently. Users can view detailed information about each cryptocurrency, such as current price, market capitalization, trading volume, and price charts over different timeframes.

**Expected behavior**
The app leverages APIs from reputable cryptocurrency exchanges and data providers to fetch real-time market data. This ensures that users receive accurate and up-to-date information on cryptocurrency prices and market trends. The app's integration with these APIs enables users to make informed decisions about buying, selling, or holding their cryptocurrencies.

**Screenshots (optional)**
![Home Page](https://i.imgur.com/C3hBI4f.png)
![News Page](https://i.imgur.com/xTFfvHU.png)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
