### ISSUE TITLE
Add new frontend project named FunSite

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1323]
As I said, I can create a new frontend project called the the FunSite using HTML, CSS andJavascript which can generate memes, jokes, riddles and quotes and the site will be responsive too. Please assign me this!

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/d326aff3-0b38-4bd1-95fc-e2730d63f861)

**Comment by SoarinSkySagar** [comment]
please check the issue @pranjay-poddar and assign it to me

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
