### ISSUE TITLE
Laptop Price Predictor 

### ISSUE THREAD

**Issue by Shreyg-27** [pranjay-poddar/Dev-Geeks#1327]
**Describe the project you want to add with tech stack**
A machine learning model that would help in predicting the price of a laptop. 

**Expected behavior**
Various models will be used and their Mean Absolute Error will be calculated so that we can Identify the model that has the maximum accuracy.

**Comment by iLakshya** [comment]
Please assign me this issue

**Comment by Shreyg-27** [comment]
Hi! @pranjay-poddar! I am a GSSoC'23 contributor and I have raised this issue. Kindly assign this to me under the GSSoC'23 contribution.
Thank you!

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Shreyg-27** [comment]
Hi @pranjay-poddar! I have linked a pull request which has both the sales prediction #1249 and #1327 (Laptop Price Predictor). 
Kindly review it once. Thank you!
