### ISSUE TITLE
Turtle on the Go 

### ISSUE THREAD

**Issue by Royal-Emine** [pranjay-poddar/Dev-Geeks#1329]
**Describe the project you want to add with tech stack**

- ### Game Objective : 

The objective of the game is to control a turtle using keyboard inputs and earn points by avoiding obstacles. The player aims to achieve the highest score possible.

- ### Game Description:

The Turtle Game is a simple interactive game where the player controls a turtle on the screen.
The objective of the game is to navigate the turtle through the screen, avoiding obstacles and collecting points.
The player can move the turtle forward, backward, and turn left or right using arrow keys.
The game includes a time limit within which the player must complete the game.

- ### Game Elements :

## Player Turtle: 
The player controls a turtle represented by a turtle-shaped object on the screen. The turtle can move forward, backward, turn left, and turn right based on the player's keyboard inputs.
## Obstacles: 
Randomly positioned circular obstacles are scattered throughout the game window. The player must avoid colliding with these obstacles.
## Score: 
The player's score is displayed on the screen, indicating the number of points earned. The score increases continuously and decreases by 10 whenever the player collides with an obstacle.

**Expected behavior**

- ### Game Flow:

1. The turtle game screen is created with a black background and dimensions of 800x600 pixels.
2. The player turtle is created with a white color and placed at the center of the screen.
3. The score is initialized to zero, and a score pen is created to display the score on the screen.
4. Keyboard bindings are set up to control the player's movements using arrow keys.
5. Random obstacles in the form of red circles are created and positioned at random locations on the screen.
6. The time count bar is created as a green square shape at the bottom-left corner of the screen.
7. The main game loop starts, where the player's movements are processed, and the screen is updated.
8. Within the game loop, collisions between the player and obstacles are checked, and the score is updated accordingly.
9. The score is increased by 1 point for every frame of the game loop.
10. The current score is displayed on the screen using the score pen.
11. The time count bar is updated based on the remaining time.
12. Concurrently, a timer thread runs in the background, counting down the time limit.
13. If the time limit of 2 minutes is reached, the timeout function is called.
14. The timeout function displays the final score and terminates the program

**Screenshots (optional)**

![tg3](https://github.com/pranjay-poddar/Dev-Geeks/assets/112507451/a38e008a-922a-45f1-8e55-a33e59e2ebff)
![tg2](https://github.com/pranjay-poddar/Dev-Geeks/assets/112507451/53210175-2170-4584-bb5f-d2230af45ba7)
![tg1](https://github.com/pranjay-poddar/Dev-Geeks/assets/112507451/b4b9ffa6-7e3f-4f15-afa0-122420a25992)
![tg](https://github.com/pranjay-poddar/Dev-Geeks/assets/112507451/8df2c9b0-4ca4-464e-9ecb-1662f17ae267)

**Additional context (optional )**

- ## Features:

1. The game utilizes the turtle module in Python for graphics and turtle movements.
2. The turtle screen is set up with a black background and dimensions of 800x600 pixels.
3. The turtle player is represented by a white turtle shape.
4. The score is displayed on the screen using a white turtle object and a score pen.
5. Random obstacles in the form of red circles are created on the screen for the player to avoid.
6. The player's score increases by 1 point for every frame of the game loop.
7. If the player collides with an obstacle, the score decreases by 10 points, and the obstacle is repositioned randomly.
8. The player's current score is displayed on the screen.
9. A time count bar is added to visually represent the remaining time.
10. The time count bar is a green square shape that shrinks as time elapses.
11. The time limit is set to 2 minutes (120 seconds).
12. The game ends when the time limit is reached, displaying the final score.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
