### ISSUE TITLE
Text Analyzer

### ISSUE THREAD

**Issue by prrockzed** [pranjay-poddar/Dev-Geeks#1330]
**Describe the project you want to add with tech stack**
Text Analyzer - Made using React

**Expected behavior**
The Text Analyzer analyses the text written in the box and gives you a summary of the number of texts and the characters written in the box as well as the amount of time one will take to read it. Not only that, the text analyzer will convert the text to any form that you like, be it the normal UPPERCASE, lowercase, Sentence case, Capitalized Case, aLtErNaTe cAsE, iNVERSE cASE, camelCase, PascalCase, nocase, skewer-case, snake_case(sm), SNAKE_CASE(UP) and period.case. Not only this the project also lets you remove extra spaces, copy the text to clipboard, clear text and download text. This project is a one stop solution to people looking for text analyzer.

**Screenshots (optional)**
<img width="1429" alt="prrockzed 2023-05-24 at 1 37 46 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/97661506/2bbb2fba-f3ad-4062-ad5a-e069f2b915de">
<img width="1429" alt="prrockzed 2023-05-24 at 1 38 58 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/97661506/ad0a2388-a495-47c6-a742-dbdc45d2c61e">

**Additional context (optional )**
@pranjay-poddar Please assign this to me under gssoc23.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
