### ISSUE TITLE
[GSSoC'23] 3D_Shape volume calculator

### ISSUE THREAD

**Issue by ash1418** [pranjay-poddar/Dev-Geeks#1331]
Improvements can help make the code more organized, readable, and less prone to potential bugs. Additionally using block-scoped variables and constants improves code reliability and reduces the risk of unintended variable modifications. Please assign this task to me as Gssoc contributor.

**Comment by gkm0001** [comment]
I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this  project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. With my [mention relevant skills/experience], I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.
