### ISSUE TITLE
Update the User Interface 

### ISSUE THREAD

**Issue by surajsharma14** [pranjay-poddar/Dev-Geeks#1334]
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by surajsharma14** [comment]
Update Required

**Comment by gkm0001** [comment]
I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by pranjay-poddar** [comment]
@surajsharma14 can you please explain more, and also mention the modification and the project
