### ISSUE TITLE
[GSSoC '23] Animated Clock 

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1335]
**Describe the project you want to add with tech stack**
A clock made using HTML and CSS that keeps working all the time the website is open

**Expected behavior**
The seconds, minutes and hour hand of the clock works like a normal real world clock, at the centre of the page

**Comment by AVUKU-PRAGATHESWARI** [comment]
Hey @pranjay-poddar,
I would like to on this issue as a contributor of [GSSoC '23].
Thank you.

**Comment by AVUKU-PRAGATHESWARI** [comment]
Hey @pranjay-poddar,
I would like to work on this issue as a contributor of [GSSoC '23].
Thank you.

**Comment by gkm0001** [comment]
Hey @pranjay-poddar I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. With my [mention relevant skills/experience], I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.
