### ISSUE TITLE
blackjack game/js project 

### ISSUE THREAD

**Issue by mohitparmar1** [pranjay-poddar/Dev-Geeks#1336]
blackjack is a game.
**tech stack:**
 HTML , CSS, and Javascript
**rules**
$ IF YOU GET SUM OF 2 CARDS IS 21 THEN YOU WON THE GAME  
$ IF YOU GET SUM OF 2 CARDS <21 YOU CAN DRAW A NEW CARD.
$ AND IF SUM OF TWO CARDS >21 , YOU ARE OUT OF THE GAME.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
