### ISSUE TITLE
NotePad application 

### ISSUE THREAD

**Issue by TejPrakash18** [pranjay-poddar/Dev-Geeks#1340]
**Describe the project you want to add with tech stack**

1. Add save functionlity to ctrl+s, each time to save file goto save section
2. UI design enhance 
3. convert into application file in Readme.md file 
**Expected behavior**

look like as professional look
Batter experience for user 

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by TejPrakash18** [comment]
Okay i will respond as soon as possible
