### ISSUE TITLE
I want to add an Elixir based project

### ISSUE THREAD

**Issue by shubhisingh184** [pranjay-poddar/Dev-Geeks#1342]
An Elixir based web application with live working link.
Tech stack : Elixir and Phoenix liveview

Elixir is a functional, concurrent, general-purpose programming language that runs on the BEAM virtual machine used to implement the Erlang programming language. Elixir builds on top of Erlang and shares the same abstractions for building distributed, fault-tolerant applications. Elixir also provides productive tooling and an extensible design.
I've worked on Elixir and want to add a basic project on it, as it works with Phoenix Liveview and has high fault tolerance feature, which is well suited for web applications.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
