### ISSUE TITLE
Chat bot

### ISSUE THREAD

**Issue by Prakhar-Shankar** [pranjay-poddar/Dev-Geeks#1347]
**Describe the project you want to add with tech stack**
Chat bot with floating button option, which will help the user to add this chat bot in any already existing website.
Tech Stacks used are - HTML, CSS, Vanilla JS, API

**Expected behavior**
Can answer any question as it fetches info from openAI APP

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/6a5b7197-8356-441f-9eb6-f530d56f29c7)

**Comment by dchugh312** [comment]
please assign this issue to me

**Comment by Sujal942** [comment]
I would like to work in this project. Can you Please assign me in this project this is my first open source contribution and would like to work in this.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
