### ISSUE TITLE
Drum Kit Website

### ISSUE THREAD

**Issue by Prakhar-Shankar** [pranjay-poddar/Dev-Geeks#1349]
**Describe the project you want to add with tech stack**

A website with simple and user friendly UI, which plays drum -
1. By clicking the images 
2. By pressing the key mentioned on every drum kit
Tech stack - HTML, CSS, JavaScript

**Expected behavior**

Plays drum with both mouse click as well from keyboard's input.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/3f966a22-5dea-460d-885e-a1b65b6c7b9e)

**Comment by pjyoti121** [comment]
I can solve this issue

**Comment by pranjay-poddar** [comment]
Project Already added
