### ISSUE TITLE
Update the "Buy Now" Button of Apple Ecommerce Website

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1350]
**Describe the bug**
The Design of the "Buy Now" Button for the Watch in Apple Ecommerce Project
**Expected behavior**
Redesigning the "Buy Now" Button to Enhance its Visual Appeal in Apple Ecommerce Project

**Screenshots (optional)**
![Screenshot (155)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/3f8675dc-432f-498c-be2d-9bb4342ff693)

**Additional context (optional )**
I want to work on this issue please assign me this issue

**Comment by manoranjanonline** [comment]
I want to work on this issue please assign me this issue
