### ISSUE TITLE
Add card components

### ISSUE THREAD

**Issue by MohdSaquib114** [pranjay-poddar/Dev-Geeks#1355]
**Describe the Feature you want to end**'
I like to add some responsive card components made by using html and css

**Comment by MohdSaquib114** [comment]
Thanks for letting me make changes to the project

**Comment by manoranjanonline** [comment]
I like to add some responsive card components made by using html and css

**Comment by MohdSaquib114** [comment]
> I like to add some responsive card components made by using html a
