### ISSUE TITLE
3D Car Racing Game

### ISSUE THREAD

**Issue by Teddy1404** [pranjay-poddar/Dev-Geeks#1356]
**Describe the project you want to add with tech stack**

The project is a 3D car racing game , it is for single player . It is made using html , CSS and JavaScript .

**Expected behavior**

The player can play the game using up , down , left , right arrow keys and c is used to start the game .
**Screenshots (optional)**

**Additional context (optional )**

**Comment by dchugh312** [comment]
please assign this issue to me

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
