### ISSUE TITLE
Improving Styling of E-commerce bike website

### ISSUE THREAD

**Issue by Sahil21dev** [pranjay-poddar/Dev-Geeks#1361]
**Describe the Feature you want to end**
I would like to improve the styling of the website as :
1 : Improving the navbar with proper spacing , alignment and colour .
2 : Bicycle image is not in fit to the website's frame , will try to fix that.
**Expected behavior **
The site would look more appealing and user friendly.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
