### ISSUE TITLE
Add more pages to the site 

### ISSUE THREAD

**Issue by Sahil21dev** [pranjay-poddar/Dev-Geeks#1363]
**Describe the Feature you want to end**
I want to add more pages to the site like about , contact , services and feedback so that the site becomes more informative and responsive .
I also want to improve the readme file of the project.

**Expected behavior**
The site would become more informative , responsive and user friendly .
**Screenshots (optional)**

**Additional context (optional )**

**Comment by Hephzibah7** [comment]
I  am a GSSoc'23 contributer. Could you please assign me with this issue

**Comment by Sahil21dev** [comment]
Hey @pranjay-poddar  could you please assign this issue .

**Comment by pranjay-poddar** [comment]
Hey @Sahil21dev,

We want to keep the page basic and simple, there is no need of any other pages.
