### ISSUE TITLE
New feature in restaurant site 

### ISSUE THREAD

**Issue by kanishka-parmar** [pranjay-poddar/Dev-Geeks#1365]
**Describe the Feature you want to end**
I want to add the feature of table booking by giving more details about the price of the table and if any decoration they want for the same.

i need to change the UI for the site which make it more interactive .

**Expected behavior**
it will make site more interactive.
This will help the user if he is planning for any party, some meeting, dates etc. This will give him the comfort to pre decide the theme and various other arrangements.

**Additional context (optional )**
I would be happy if I got chance to contribute on this project @pranjay-poddar and show my efficient skills of HTML CSS and JAVASCRIPT. please assign me this ...I have worked on such project you can check on my GitHub so i think i will definitely make this issue.

**Comment by kanishka-parmar** [comment]
> **Describe the Feature you want to end** I want to add the feature of table booking by giving more details about the price of the table and if any decoration they want for the same.
> 
> i need to change the UI for the site which make it more interactive .
> 
> **Expected behavior** it will make site more interactive. This will help the user if he is planning for any party, some meeting, dates etc. This will give him the comfort to pre decide the theme and various other arrangements.
> 
> **Additional context (optional )** I would be happy if I got chance to contribute on this project @pranjay-poddar and show my efficient skills of HTML CSS and JAVASCRIPT. please assign me this ...I have worked on such project you can check on my GitHub so i think i will definitely make this issue.

please assign me  this for gssoc 23 !!!

**Comment by bhoomigupta1406** [comment]
Hey @pranjay-poddar , using HTML CSS and JS i want to contribute to this issue. I have made different sections for menu display, for booking , for billing. with a beautiful homepage.

**Comment by kanishka-parmar** [comment]
@MohitGupta121  Hey why this issue has been closed???
