### ISSUE TITLE
Responsive Sidebar

### ISSUE THREAD

**Issue by UdaySutradhar** [pranjay-poddar/Dev-Geeks#1368]
**Describe the Feature you want to end**
I want to make the side bars of the webpage responsive will the help of js and css. will give the detailed responsiveness possible. And will add a bit of css detailing to make the webpage as sound as possible

**Expected behavior**
The Sidebar of the webpage will be responsive

**Comment by manoranjanonline** [comment]
i want to wark plz assign me

**Comment by manoranjanonline** [comment]
i want to work on it plz assign me

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
