### ISSUE TITLE
add a new weather forecasting website

### ISSUE THREAD

**Issue by gulshanjakhon** [pranjay-poddar/Dev-Geeks#1372]
Hi @pranjay-poddar ,
i would like to contribute web-based project on weather forecasting, please assign me.
**Describe the project you want to add with tech stack**
A weather app that Fetch data from the OpenWeatherMap API to allow users to search for and view the forecast in cities worldwide
tech stack used Html, CSS, Js, Api(OpenWeatherMap Api )

**Expected behaviour**

- 

**Screenshots (optional)**

![Screenshot (154)](https://github.com/pranjay-poddar/Dev-Geeks/assets/72978519/7c643482-86e1-43d7-8862-efed8914eefc)
![Screenshot (155)](https://github.com/pranjay-poddar/Dev-Geeks/assets/72978519/042eb93b-74fa-4567-b1ac-82fde537687c)

**Additional context (optional )**

also please add gssoc tag, as I am contributing under the Girlscript summer of code Gssoc23.
Thank you!

**Comment by Ritikkumar03** [comment]
I want to make it, I'm a gssoc '23 contributor.
kindly assign it to me.

**Comment by tina-goel** [comment]
i want to contribute in this kindly do assign me

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by IT-0824** [comment]
looking forward to work on this issue.
