### ISSUE TITLE
Add a new landing page for a fitness website

### ISSUE THREAD

**Issue by Sreenija03** [pranjay-poddar/Dev-Geeks#1373]
**Describe the project you want to add with tech stack**
A landing page for a fitness website created with css and html

**Comment by manoranjanonline** [comment]
I like to add some responsive card components made by using html and css

**Comment by khushiminda** [comment]
Unleash Your Inner Athlete
I CAN ADD a very RESPONSIVE page for your fitness website with css and html
i have designed one before
i will use a responsive framework

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
