### ISSUE TITLE
Attractive Fashion Shopping Website

### ISSUE THREAD

**Issue by Naitik-554** [pranjay-poddar/Dev-Geeks#1384]
**Describe the project you want to add with tech stack**

A complete fashion shopping website with cart functionality.
Website will be having different pages such as home, shop, blog, about, contact and cart section.
Technology which will be used are HTML , CSS and JS.

**Expected behavior**

A customer will be able to buy products from the website as it is having cart functionality for which browser's local storage is also used so that previously added cart items remains there only.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by nehabulakhe** [comment]
I want to work on this issue

**Comment by Saurabh-kumar09** [comment]
@Naitik-554 go ahead.

**Comment by Naitik-554** [comment]
@Saurabh-kumar09 Please Review my PR and merge it.
Thank You :)

**Comment by Naitik-554** [comment]
@MohitGupta121 Please Review my PR and merge it.
Thank You.
