### ISSUE TITLE
Front end :- Spotify Clone (GSSOC'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [pranjay-poddar/Dev-Geeks#1388]
**Describe the project you want to add with tech stack**
Static spotify clone where the songs get played from the list.

**Expected behavior**
Interactive clone with songs.

**Comment by shellyverma** [comment]
Hey @pranjay-poddar , I would like to add spotify clone where the songs get played from the list.  . I can resolve this issue. I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23 .

**Comment by Aryan2727-debug** [comment]
Hey @pranjay-poddar, I would want to contribute to this issue, I have built a Spotify Clone and I can resolve this issue. Do look at my Github and assign this issue to me, as I am a contributor in GSSOC'23.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by pranjay-poddar** [comment]
Project already present
