### ISSUE TITLE
Front end :- Temperature Converter (GSSOC'23)

### ISSUE THREAD

**Issue by Bharatpathak08** [pranjay-poddar/Dev-Geeks#1389]
**Describe the project you want to add with tech stack**
Temperature converter to convert temperature to Celsius, Kelvin or Fahrenheit.

**Expected behavior**
Animated background with converter.

**Comment by whiteknight16** [comment]
Oasis infobyte ?

**Comment by Gun2902** [comment]
can u assign me this isssue
