### ISSUE TITLE
Frontend: Durga Puja

### ISSUE THREAD

**Issue by Shr-reny** [pranjay-poddar/Dev-Geeks#1390]
**Describe the Feature you want to add**

I want to improve the css of the website by changing color gradient , font and images.

**Comment by khushiminda** [comment]
so for a responsive Homepage-
i will-
Plan my layout
Use a responsive framework
Design for mobile-first
Use media queries
Test across devices
Provide touch-friendly interactions
I can make this more responsive.
assign this to me under gssoc'23.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by khushiminda** [comment]
Thankyouuuu so much for assigning I'll complete and provide u it
