### ISSUE TITLE
[Add project] : A bird game!

### ISSUE THREAD

**Issue by Shr-reny** [pranjay-poddar/Dev-Geeks#1393]
**Describe the project you want to add with tech stack**

I want to add a bird's game made using html and css only.  Here one simply needs to aim at a bird to kill it and would earn a point.

**Comment by pawankrgithub** [comment]
hello shr-reny,
i'm intrestred to build this can you please assign to me. i'm from GSSoc'23.

**Comment by Saurabh-kumar09** [comment]
@Shr-reny You can start working on this issue.

**Comment by Shr-reny** [comment]
![Bird_game](https://github.com/pranjay-poddar/Dev-Geeks/assets/125943681/1c70903d-e63a-4705-be8e-236456df5e61)
I've added the game in PR #1555 plz check @Saurabh-kumar09
