### ISSUE TITLE
Main Page Not Working

### ISSUE THREAD

**Issue by harshraj005** [pranjay-poddar/Dev-Geeks#1394]
**Describe the bug**
When I clicked on the site link it is displaying "404 There isn't a GitHub Pages site here."

**Expected behavior**
The site should be opened when I click on the link .

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/132002718/732fbabc-d863-4696-841e-a887720c423f)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/132002718/b8f70d3a-1fe9-4a4b-96a6-b9160bd0a865)

**Additional context (optional )**
I would be thankful if you assigned me this issue.
Thank you .

**Comment by pranjay-poddar** [comment]
Issue resolved
