### ISSUE TITLE
Want to add a jumble word game

### ISSUE THREAD

**Issue by shineishukla** [pranjay-poddar/Dev-Geeks#1395]
**Describe the project you want to add with tech stack**
Want to add  jumble word game using HTML, CSS, and JavaScript, including a timer and word checking functionality.

**Expected behavior**
1. When the game starts, a jumbled word is displayed on the screen.
2. The player enters their guess for the unjumbled word into an input field.
3. The player submits their guess by clicking a "Submit" button.
4. The game checks whether the guess is correct or not:
[If the guess is correct, the player receives a success message and may proceed to the next word or level.
If the guess is incorrect, the player receives a failure message and can try again with a new guess.]
5. The game may include a time limit within which the player must submit their guess. If the time runs out, the player loses the round or the game.
6. The game may keep track of the player's score or progress, either by counting the number of correct guesses or by assigning points for each correct answer.
7. The game may have multiple levels or rounds, with increasing difficulty, where the jumbled words become more challenging as the player progresses.
8. The game may include additional features like hints, a leaderboardand the time limit.

**Screenshots (optional)**

**Additional context (optional )**

Assign this to me under GSSoC'23

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by sahithi-1729** [comment]
Please assign me this issue
