### ISSUE TITLE
add Virtual drum kit in js-games(gssoc'23)

### ISSUE THREAD

**Issue by DP-NOTHING** [pranjay-poddar/Dev-Geeks#1397]
**Describe the project you want to add with tech stack**

- "Virtual Drum Kit" is an interactive web-based game that allows users to play and create music using a virtual drum kit. The game provides a realistic drumming experience where players can unleash their creativity and rhythm skills.
- The game presents a visually appealing drum kit interface with different drum pads representing various drum sounds.
- "Virtual Drum Kit" provides an engaging and entertaining platform for users to unleash their inner drummer and create captivating music. Whether you're a beginner or an experienced musician, this game offers a fun and interactive way to explore the world of drumming.
- tech stack
  - html
  - css
  - javascript
  
  
  **Expected behavior**

-  Add event listeners to each drum pad element to detect when they are clicked or tapped.
- Create a JavaScript function that plays the corresponding drum sound when a drum pad is clicked or tapped. 
- When a drum pad is clicked or tapped, call the drum sound function with the appropriate drum sound based on the ID of the clicked/tapped element.

**Screenshots (optional)**

![Screenshot 2023-05-25 115706](https://github.com/pranjay-poddar/Dev-Geeks/assets/107257619/167bcc88-0fbc-49b1-bd5a-467791500f72)

**Additional context (optional )**

**Comment by DP-NOTHING** [comment]
Kindly, assign me this project.

**Comment by pranjay-poddar** [comment]
Project already present
