### ISSUE TITLE
Tribute Page project

### ISSUE THREAD

**Issue by harshraj005** [pranjay-poddar/Dev-Geeks#1399]
**Describe the project you want to add with tech stack**
I just want to add a tribute page project using HTML and CSS.

**Expected behavior**
These are some of the following elements which should be associated in the Tribute Page : -
1. Displaying information: The tribute page should provide relevant information about the person being honored, such as their name, date of birth, date of passing (if applicable), and a brief biography.
2. Sharing memories and stories: Visitors to the tribute page should have the opportunity to share their memories, stories, and personal experiences related to the individual. This can be done through text-based comments, guestbooks, or submission forms.
3. Showcasing photos and videos: Tribute pages often include a collection of photographs and videos that highlight important moments and memories of the person's life. These visual elements can help visitors connect with the individual being honored and evoke emotions associated with their presence.

**Additional context (optional )**
I would be thankful if you assign me this project for GSSOC'23.

**Comment by anamithrak15** [comment]
Kindly, assign me this project.
