### ISSUE TITLE
GSSOC'23 Webpage Navbar Clone

### ISSUE THREAD

**Issue by Ayush9951** [pranjay-poddar/Dev-Geeks#1400]
Hi @pranjay-poddar, I am contributor in GSSOC'23.
I want to add a new project in Navbars repository.

project details - I will create a Navbar clone of GSSOC'23 website including dark mode functionality.
please assign me this task under label gssoc'23

**Comment by anamithrak15** [comment]
Hi @pranjay-poddar, I am contributor in GSSOC'23.
I want to add a new project in Navbars repository.

project details - I will create a Navbar clone of using glassmorphism including dark mode functionality.
please assign me this task under label gssoc'23

**Comment by Gun2902** [comment]
can u assign me this isssue
