### ISSUE TITLE
add a coffee shop website 

### ISSUE THREAD

**Issue by Sreenija03** [pranjay-poddar/Dev-Geeks#1404]
**Describe the project you want to add with tech stack**
I want to add a website for a coffee shop made using html and css 

**Expected behaviour**
Enhanced UI/UX design

**Comment by rks-031** [comment]
I want to add a website for a coffee shop made using html, css and reactJs.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by Sreenija03** [comment]
Can you please assign this issue to me under GSSoC'23 @pranjay-poddar @Saurabh-kumar09
