### ISSUE TITLE
Front End: Netflix Clone (GsSOC '23)

### ISSUE THREAD

**Issue by sp9324** [pranjay-poddar/Dev-Geeks#1405]
**Describe the project you want to add with tech stack**
I would like to create a Netflix landing page clone using HTML, CSS and JavaScript.

**Expected behavior**
The login page will open and will be interactive just like the actual website.

Please assign this issue to me.

**Comment by shellyverma** [comment]
Hey @pranjay-poddar ,I would like to create Netflix clone using html, css, javascript .
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by pranjay-poddar** [comment]
Project already present

**Comment by sp9324** [comment]
Ok. Thank you.
