### ISSUE TITLE
[GSSOC'23] Adding Banking System project

### ISSUE THREAD

**Issue by shubhanshurav** [pranjay-poddar/Dev-Geeks#1407]
**Describe the project you want to add with tech stack**
- In this project, you can:
* Open Account
* Balance enquiry
* Deposit Money
* Withdraw Money
* Close an Account
* Shiw all Accounts
* Quit

### Hey! @pranjay-poddar, I want to add this project. so please assign it to me.

**Screenshots (optional)**
- Select anyone option
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/e731f0b4-359b-4b03-98fe-ed11a03c0be9)

- Open Account
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/fef15f72-1d40-4709-9a3b-e9b4de68e10a)

- Balance Enquiry 
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/b1674171-1ff9-425c-a55b-7c08a9fea50c)

- Deposit Money
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/5a0b77ec-6ff6-4c07-8a92-c5d80a7384c3)

- Withdraw Money
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/c01dc9bf-13f9-4ec6-80a8-9b6040b60f46)

- Close Account
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/da54952e-5557-4590-aeb4-fb9b7b9677e8)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
