### ISSUE TITLE
Pac-Man Game in Javascript 

### ISSUE THREAD

**Issue by vishnuprasad2004** [pranjay-poddar/Dev-Geeks#1414]
**Describe the project you want to add with tech stack**
I want to add Pac-Man Game using HTML, CSS, and Javascript as a JS-Game project 

I would really like to add that classic game to the collection.

**Comment by Akanksha038** [comment]
Hello sir,
I want to add Pac-Man Game. I have made this game using HTML, CSS, and JavaScript. Can you Please assign this issue to me?

**Comment by Sampath-Vatsavaya** [comment]
Please assign this issue to me.

**Comment by pranjay-poddar** [comment]
Project already present
