### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Prakhar-Shankar** [pranjay-poddar/Dev-Geeks#1416]
**Describe the project you want to add with tech stack**
 Project - Digital Clock which uses the system to fetch time and runs efficiently.
Tech stack - HTML, CSS and JS

**Expected behavior**
A digital clock which keeps on updating every second.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/aa455546-eb2a-48bf-b79e-b002fcea18c2)

**Comment by BikramNarayan** [comment]
I want to work on this issue , please assign it to me @Prakhar-Shankar

**Comment by gkm0001** [comment]
Hey @pranjay-poddar ,I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.

**Comment by subhanshimishra246** [comment]
I want to work on this issue , please assign it to me @Prakhar-Shankar
