### ISSUE TITLE
Catch Me If You Can

### ISSUE THREAD

**Issue by Khaleeq01** [pranjay-poddar/Dev-Geeks#1418]
We will be using mouse event for the Project. Create a box whose size changes dynamically according to viewport size. Now when you hover over the box, it should change its position randomly inside the viewport. You can put box initially at any position inside the viewport; just make sure that it does not move out of the viewport at any given time.
The box will look like this -https://ninjasfiles.s3.amazonaws.com/0000000000001861.png
Gif for this problem is -https://ninjasfiles.s3.amazonaws.com/0000000000001878.gif

**Comment by Saurabh-kumar09** [comment]
@Khaleeq01 go ahead.
