### ISSUE TITLE
Animated Main Page for Portfolios 

### ISSUE THREAD

**Issue by vishnuprasad2004** [pranjay-poddar/Dev-Geeks#1420]
**Describe the project you want to add with tech stack**
A Landing Page or Main Page with a Cool animated Background using HTML, CSS, and Javascript (canvas API).
People can add this their portfolios.

**Expected behavior**
The particles in the Background collide with each other and swaps color when hit.  the website is Scrollable.
I can also add a Nav Bar.

I would really like to contribute to this Repo. Please assign this project to me.
**Screenshot **
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/116942066/ffbe421e-22c8-432d-80dc-2b417a785355)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/116942066/dc9eb83f-632a-4ce0-aaaa-3c660dc3a4f4)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
