### ISSUE TITLE
To Do list Web Application

### ISSUE THREAD

**Issue by Biswajit-Behera** [pranjay-poddar/Dev-Geeks#1423]
By using HTML, CSS and Vanila Javascript developed a Web Application to make a To-Do list for a day. 
Future Scope:-
Create and modify the web application with more features and more CSS animation for more user interaction friendly.

**Screenshots (optional)**
<img width="591" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/86191708/e778019b-4c1c-40a4-9976-1def08f0cc2b">

**Comment by BikramNarayan** [comment]
I want to work on this issue , please assign it to me @Biswajit-Behera

**Comment by Biswajit-Behera** [comment]
> I want to work on this issue , please assign it to me @Biswajit-Behera 

I am currently working on this.
You may pick up the another issue or create another issue on which u r willing to work.
