### ISSUE TITLE
I want to update the birthday website to make it look more attractive.

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1425]
**Describe the Feature you want to end**
Transform the birthday website into a captivating and visually stunning experience that will amaze everyone.

**Additional context (optional )**
I want to work on it . Please assign this issue to me

**Comment by nehabulakhe** [comment]
I wanted to work on this could you please assign this issue to me @pranjay-poddar

**Comment by Shiwani2002** [comment]
I want to work on it please assign this issue to me @pranjay-poddar
