### ISSUE TITLE
Update the radio button in one line 

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1427]
**Describe the Feature you want to end**
 To make the options in one line 

**Expected behavior**
So it will look more attractive and user friendly.

**Screenshots (optional)**
![Screenshot (157)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/87f01083-5160-4aef-b984-7b6ca1db1a43)

**Additional context (optional )**
I want to work on it please assign this issue to me

**Comment by Shiwani2002** [comment]
I want to work on it Please assign this issue to me

**Comment by gkm0001** [comment]
Hey @pranjay-poddar ,I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.
