### ISSUE TITLE
Dinosaur game is not opening [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [pranjay-poddar/Dev-Geeks#1428]
**Describe the bug**
Dinosaur game is not opening after clicking on Start Game

**Expected behavior**
It should have taken me (user) to the page where the game starts.
Instead it is showing error.

**Screenshots**

![2023-05-25](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/8268e047-e4b9-47a6-a83e-19b069dd6a79)

Would like to fix this. Please assign me this issue under GSSoC'23

**Comment by Gun2902** [comment]
can u assign me this isssue
