### ISSUE TITLE
I want to add features in Hotel Website.

### ISSUE THREAD

**Issue by vishal28d** [pranjay-poddar/Dev-Geeks#1429]
Before: 
![Screenshot (115)](https://github.com/pranjay-poddar/Dev-Geeks/assets/62495463/9b972e50-298f-4f8e-9f34-b00ebbeb7982)

After: 
![Screenshot (116)](https://github.com/pranjay-poddar/Dev-Geeks/assets/62495463/f18407e1-49bd-4353-b9b4-90cf40827968)

I want to add background-image, hover effect etc. 
please assign me @pranjay-poddar

**Comment by Shiwani2002** [comment]
I want to add background-image, hover effect and some other changes.
please assign me @pranjay-poddar

**Comment by Sujal942** [comment]
Hello i want to work in this project. Can you please assign it to me I can add background image, hover effect and do some other changes please assign me this.

**Comment by Sujal942** [comment]
@pranjay-poddar i make the hotel website
![Screenshot 2023-06-05 at 9 27 41 PM](https://github.com/pranjay-poddar/Dev-Geeks/assets/63149580/4d0f9525-ddab-4b26-9cb8-e6347374830a)
