### ISSUE TITLE
[GSSoC'23] New Project : 3d Box Game

### ISSUE THREAD

**Issue by AnmolChauhan123** [pranjay-poddar/Dev-Geeks#1431]
There will be 2 types of 3d boxes of color red and green. Red is for danger and green will be our moving block. So we have to avoid all the red boxes and keep the green box on the platform and go as far as we can... It's an amazing game and will really be fun to make. It's gonna use HTML, CSS, JavaScript and Three.js Library.

Please assign this issue to me under the tag GSSoC'23 and I will try my best to close this issue and create a PR...

**Comment by AnmolChauhan123** [comment]
I am actually currently working on this project and will make a PR very soon... So can you please assign this project to me so that my efforts don't go to waste.... Please assign me...

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by AnmolChauhan123** [comment]
Here are some Screenshots of the game that I made---
![ss1](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/f7cf803b-4a55-4226-801f-13a55d7abcca)
![ss2](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/f12d10fa-cd32-40c7-9a42-d3e417e17415)
![ss3](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/cae7e619-8bdd-4cfa-96ca-7c3fa11ba573)

**Comment by AnmolChauhan123** [comment]
Here are some Screenshots of the project that I have made---

![ss1](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/05c97e0b-24ba-4de5-ac32-3e6f68ac7eae)

![ss2](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/3eb77d86-5c9f-476f-962f-0ffb2a8429a5)

![ss3](https://github.com/pranjay-poddar/Dev-Geeks/assets/77499508/077c33a5-e88a-46fd-b868-8f10207b6a5f)
