### ISSUE TITLE
A textUtils Project

### ISSUE THREAD

**Issue by rks-031** [pranjay-poddar/Dev-Geeks#1435]
**Describe the project you want to add with tech stack**
I want to add a textUtils app created using HTML,CSS, JS and ReactJS.

**Expected behavior**
Here are some of the associated utilities that the app will provide:

1. Word Counter: The app counts the number of words in the text written by the user.
2. Character Counter: The app counts the number of characters in the in the provided text.
3. Lowercase to Uppercase: The app can convert the selected text from Lowercase to Uppercase.
4. Uppercase to Lowercase: The app can also convert the selected text from Uppercase to Lowercase.
5. Text Slicing: The app can slice the desired length of text as and when required by the user.
6. Text Erase: The app can erase text and will show alert after that.
7. Text Replace: The app can replace a particular word with another word(for example: 'this'  to 'that' ).

**Additional context (optional )**
I'll be really thankful if you assign me to contribute in this project for GSSOC'23.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
