### ISSUE TITLE
Issues In Project: Animation-CSS -> Distortion

### ISSUE THREAD

**Issue by rks-031** [pranjay-poddar/Dev-Geeks#1439]
**Describe the bug**

The text on the webpage has spelling errors which should be eliminated as it leaves a bad impact on the user and some fucntionalities such as font properties and video used can also be enhanced.

**Expected behavior**

1. The spelling of distortion is wrong in h2. 
    It should be 'Distortion' instead of 'Distortiion'.
2. The spelling of Distortion is wrong also in the title tag. 
    It should be 'Distortion' instead of 'Distrotion'.
3. The complete text should be rewritten as: 'Particle Distortion Effect' instead of 'Particles Distortion Effects'.
4. A little sober font can be used which gives a very professional yet dynamic look to the text written. 
    For example: font-family :'Playfair' , serif can be used instead of 'Poppins'.
5. And to manage the spacing, font-size should be updated to 5em under the css of h2.
6. The letter 'ff' in the word effect can also be given #ff022c color. And the video can also be edited to as to distort the #ff022c 
    color when flow reaches to 'ff'.

**Screenshots (optional)**

Here are the links to the required screenshots for calrity on my raised issues:-
https://drive.google.com/file/d/1zGJv4mmwPC7PnrYqT1ITO_Qhfwmrtpx6/view?usp=share_link
https://drive.google.com/file/d/122u3GmvjlrzhOdLMUBGUI5cPgq_ENfV5/view?usp=share_link
https://drive.google.com/file/d/1rdyURl_h7ZUCeP7fsYD8hWXmYVIzI6Si/view?usp=share_link

**Additional context (optional )**

I would request the admin @pranjay-poddar to assign this project to me so that I can give my contribution in GSSOC'23. I will be really thankful for the same.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
