### ISSUE TITLE
Request to add my Tic Tac Toe project with better UI

### ISSUE THREAD

**Issue by NAVEEN1442** [pranjay-poddar/Dev-Geeks#1444]
Hi, I am a contributor of GSSoC'23
I want to add my new project of Tic Tac Toe with better UI in Js-Games

![Screenshot 2023-05-26 125240](https://github.com/pranjay-poddar/Dev-Geeks/assets/70251950/eb71629e-0e27-421a-9264-8c8bcb1a758e)

Please assign me this task under GSSoC'23

**Comment by gkm0001** [comment]
Hey  ,I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.

**Comment by Sakshiii1800** [comment]
please assign this project to me
