### ISSUE TITLE
New Project :  Snake - Game

### ISSUE THREAD

**Issue by Ramya-korupolu** [pranjay-poddar/Dev-Geeks#1445]
**Describe the project you want to add with tech stack**

Snake game is a classic game which includes HTML, CSS, JS and animation tools where players controls a growing snake on a grid-like game board.

**Expected behavior**

In this the snake increases its length by eat food that randomly appears on the game board. The game ends when the snake collides with any part of its own body or hits the boundaries of the game board.

**Screenshots (optional)**

**Additional context (optional )**

could you please assign me this issue under GSSOC'23.

regards,
Ramya Korupolu

**Comment by gkm0001** [comment]
Hey   ,I hope this message finds you well. I am writing to express my interest in contributing to an open source project under your guidance and request to be assigned me this project .

I am passionate about open source and believe in its power to foster collaboration, innovation, and social impact. I am confident in my ability to make meaningful contributions to your project. I am excited to work alongside a talented team, learn from experienced contributors, and contribute to the growth of your open source community.

**Comment by Akanksha038** [comment]
Hello sir,
I want to add Snake Game. I have made this game using HTML, CSS, and JavaScript and also adding animations. Can you Please assign this issue to me?

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?
