### ISSUE TITLE
new project : Climate API

### ISSUE THREAD

**Issue by RJ025** [pranjay-poddar/Dev-Geeks#1451]
Hello @pranjay-poddar 

**Describe the project you want to add with tech stack**
Climate will fetch data about climate and news about it from some well known news websites
TECH STACK: node js

**Expected behavior**
Fetch Data about climate 

Please assign this to me under GSSOC'23 tag

**Comment by Saurabh-kumar09** [comment]
@RJ025 You can start working on this issue.
