### ISSUE TITLE
Tic Tac Toe Game 

### ISSUE THREAD

**Issue by SAKETSINGH120** [pranjay-poddar/Dev-Geeks#1454]
1. tech stack
    Html, Css , Javascript

Screenshot.
![Screenshot (64)](https://github.com/pranjay-poddar/Dev-Geeks/assets/93044592/4b0b95fc-3155-402e-b70d-241b3341067c)

**Comment by SAKETSINGH120** [comment]
hey @pranjay-poddar  I want to add Tic Tac Toi Game

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by Aryan2727-debug** [comment]
Hi,
Aryan Dev Shourie here (GSSOC'23 Contributor)
I want to conrtibute on this issue, please assign it to me.

**Comment by IT-0824** [comment]
I would like to contribute to this issue, kindly assign me with it.
