### ISSUE TITLE
want to modify the birthday website.

### ISSUE THREAD

**Issue by PrachiChauhan23** [pranjay-poddar/Dev-Geeks#1455]
i want to modify birthday website . It looks so simple. i want to add some features into it. Please assign me this issue @pranjay-poddar

**Comment by nehabulakhe** [comment]
I wanted to contribute in this website could you please assign this issue to me

**Comment by amankumar100** [comment]
please assign me this issue I want to contribute in this website.

**Comment by Nikita110602** [comment]
pls assign it to me . I like to contribute in this website
