### ISSUE TITLE
Basketball Score Card Project

### ISSUE THREAD

**Issue by BikramNarayan** [pranjay-poddar/Dev-Geeks#1459]
I would like to contribute to the open-source projects of GirlScript by taking up the Basketball Score Card project.

This project aims to develop a web application that allows users to keep track of basketball scores, manage team information, and generate scorecards for basketball matches

Tech used
HTML
CSS
JAVA SCRIPT

![Screenshot 2023-05-26 190658](https://github.com/pranjay-poddar/Dev-Geeks/assets/119877120/526d0225-f3da-4576-b594-21f33bd8313d)

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
