### ISSUE TITLE
Spacex Clone

### ISSUE THREAD

**Issue by shreyaslax** [pranjay-poddar/Dev-Geeks#1460]
I want to add a SpaceX Clone Project  with features such as type of Rockets, the Astronauts Crew, the mission details, etc.
This project has been built using React hooks, react-router-dom and the SpaceX API
I have worked on similar projects in the past.
Looking forward to useful contributions 
Thank you.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
