### ISSUE TITLE
Airbnb Clone

### ISSUE THREAD

**Issue by shreyaslax** [pranjay-poddar/Dev-Geeks#1461]
I want to add a Airbnb Clone Project with features such as types of Hotels, types of Rooms, Availability of Rooms, Number of Guests , etc.
This project has been built using React hooks , react-router-dom , Material UI and Hosted using Firebase Hosting.
I have worked on similar projects before.
Looking forward to useful contributions
Thank you.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
