### ISSUE TITLE
WhatsApp Clone

### ISSUE THREAD

**Issue by uzmaansari23** [pranjay-poddar/Dev-Geeks#1466]
**Describe the project you want to add with tech stack**
A WhatsApp clone typically replicates the core features and functionalities of WhatsApp, allowing users to send text messages, make voice and video calls, share media files, create group chats, and more

**Expected behavior**
Users can view and interact with their contacts, send and receive text messages, emojis, stickers, and media files (photos, videos, documents) in one-on-one conversations.
Users can create or join group chats with multiple participants, where they can exchange messages, media files.
 Indicating when a message has been delivered to the recipient's device and when it has been read.

**Screenshots (optional)**

![Screenshot (40)](https://github.com/pranjay-poddar/Dev-Geeks/assets/113499701/85463a30-5091-48d8-b561-e8289e9bdaad)

**Additional context (optional )**

**Comment by Abh71234** [comment]
Hey! I'm GSSoC 2023 contributor,Please assign me this project.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by uzmaansari23** [comment]
@pranjay-poddar I've generated the pr please review it.
