### ISSUE TITLE
[GSSoC'23] :- Want to add a webshooter game 

### ISSUE THREAD

**Issue by Abhishek8287** [pranjay-poddar/Dev-Geeks#1467]
**Describe the project you want to add with tech stack**
My project is a web shooter game . It has various levels ease , medium , insane . In this game we have to kill the enemies using various weapons that i have given in the game .  It also count score . It has coll animations as well . 

**Expected behavior**

**Screenshots (optional)**

![Screenshot (70)](https://github.com/pranjay-poddar/Dev-Geeks/assets/100223167/e4e8f034-65e8-4c90-89bf-78fcaab3d89b)
![Screenshot (71)](https://github.com/pranjay-poddar/Dev-Geeks/assets/100223167/64671c0d-a801-45d6-96d5-dbeac6983c48)

**Additional context (optional )**
game link :-https://abhishek8287.github.io/shooter-game/

Assign me this issue under GSSoC @pranjay-poddar

**Comment by amankumar100** [comment]
Assign me this issue under GSSoC 2023
