### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by Anugyagupta43** [pranjay-poddar/Dev-Geeks#1469]
**Describe the Feature you want to add**
I would like to make the responsive navbar responsive and add some animations and information to it. So please assign me the task

**Expected behavior**
 It will help the links present in it send you the mentioned places.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by beherabikram** [comment]
Please assign this project to me

**Comment by beherabikram** [comment]
![Screenshot (4)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101280738/bdab6c43-2a0c-44ac-81ea-38f7c3bad72d)

**Comment by subhanshimishra246** [comment]
Please assign this project to me
