### ISSUE TITLE
Want to add new game "Drum_And_Kit"

### ISSUE THREAD

**Issue by Roshnijeewani3457** [pranjay-poddar/Dev-Geeks#1472]
**Describe the project you want to add with tech stack**

Drum and Kit Game is a rhythm-based game where players simulate playing a virtual drum kit using input devices such as a keyboard or controller.
Technology used: Html, Css, Javascript

**Expected behavior**

The game provides visual feedback in the form of on-screen prompts or notes that indicate when and which drum element to hit.
With increasing difficulty levels and varying music tracks, Drum and Kit Game offers an engaging and immersive experience for rhythm game enthusiasts.

**Screenshots (optional)**

![Screenshot_20230210_073816](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/0ad7a17d-8f1d-4b84-bb63-91efd90b9e17)

**Additional context (optional )**

**Comment by Roshnijeewani3457** [comment]
I would like to work on this issue please assign me this.

**Comment by Abh71234** [comment]
Hey! I'm GSSoC 2023 contributor,I would like to work on this issue please assign me this.

**Comment by Roshnijeewani3457** [comment]
I have already assigned inder issue 185

**Comment by Roshnijeewani3457** [comment]
Assign me this task under GSSOC

**Comment by pranjay-poddar** [comment]
Already present
