### ISSUE TITLE
[GSSoC'23] add snake game using python

### ISSUE THREAD

**Issue by rakesh-nj** [pranjay-poddar/Dev-Geeks#1476]
Hey! I'm GSSoC 2023 contributor I want to add snake game to python projects. Could you please assign this issue to me

**Comment by aditya-bagla** [comment]
Hi ,
Aditya Bagla ( GSSOC'23 contributor ) 
I would like to contribute on this issue . Can you please assign me ?

**Comment by Abh71234** [comment]
Hey! I'm GSSoC 2023 contributor,pls assign me this project.

**Comment by pranjay-poddar** [comment]
Project already present
