### ISSUE TITLE
Image is not Visible on the car company Website 

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1479]
**Describe the Feature you want to end**
Make the image visible so that it look more attractive

**Expected behavior**
I want to update the html file
**Screenshots (optional)**
![Screenshot (160)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/f1e0389d-12d5-458d-a3a8-a8ebd3444f42)
![Screenshot (161)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/0975f5a0-12e3-404a-a267-b2edcf3a2dc0)

**Additional context (optional )**
I want to work on this issue . Please assign this issue to me @pranjay-poddar

**Comment by Nikita110602** [comment]
I really want to work on this issue. Please assign it to me

**Comment by pranjay-poddar** [comment]
Images created copyright issues, it is not required
