### ISSUE TITLE
Image is not visible in design_me Project

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1483]
**Describe the Feature you want to end**
Make the image visible so it look more attractive

**Expected behavior**
Add the new Image and delete the old image and make change in html file

**Screenshots (optional)**
![Screenshot (163)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/006f791d-8b47-4411-b030-2134713394ee)

**Additional context (optional )**
I want to work on this issue Please assign this issue to me

**Comment by vibhuti0** [comment]
I want to work on this issue.

**Comment by Nikita110602** [comment]
pls assign me. I like to contribute in this issue.

**Comment by vibhuti0** [comment]
Hii
I would like to work on this issue .please assign it to me
Thankyou

**Comment by beherabikram** [comment]
I would like to work on this project, please assign to me.

**Comment by khadesamrudhi** [comment]
please assign to me this project under GSSOC'23

**Comment by AyusGup** [comment]
I would like to work on this issue. Can you please assign it to me.
