### ISSUE TITLE
Add a new age-calc-project 

### ISSUE THREAD

**Issue by MohdSaquib114** [pranjay-poddar/Dev-Geeks#1486]
**Describe the project you want to add with tech stack**
Wants to add a age calculator responsive component in front-end folder 
Please assign  me this task 
**Expected behavior**

**Screenshots (optional)**

![desktop-completed](https://github.com/pranjay-poddar/Dev-Geeks/assets/107548091/f48a05cc-f531-49b7-8c35-d372e05fc087)
![mobile-design](https://github.com/pranjay-poddar/Dev-Geeks/assets/107548091/43eefc25-e9a4-4e1a-95db-e8299be948af)

**Additional context (optional )**

**Comment by yashvardhansingh15** [comment]
Please assign this issue to me, I would like to work on this issue

**Comment by MohdSaquib114** [comment]
Hey @pranjay-poddar  please assing me this
