### ISSUE TITLE
Adding a banking app javascript project

### ISSUE THREAD

**Issue by SatvikAgrawal04** [pranjay-poddar/Dev-Geeks#1488]
**Describe the project you want to add with tech stack**
Want to add a simple banking app called bakist made using html css and javascript

**Expected behavior**
Allows user to login with a username and password given in readme file

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/108514424/ecb4c4c2-022b-4f8b-86a8-b8c180baaa98)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/108514424/80190d4e-3a83-40a7-9520-aea3adc0ed3b)

**Additional context (optional )**
please assign me this for GSSoC'23

**Comment by aditya-stoic-sharma** [comment]
Hey @SatvikAgrawal04 I can make this banking website using html css and javascript . please assign it to me under gssoc23.

**Comment by Saurabh-kumar09** [comment]
@SatvikAgrawal04  Are you using any backend for this project ?

**Comment by SatvikAgrawal04** [comment]
@Saurabh-kumar09  No
