### ISSUE TITLE
[GSSOC'23] YouTube clone

### ISSUE THREAD

**Issue by Enhancer18** [pranjay-poddar/Dev-Geeks#1490]
**Describe the project you want to add with tech stack**

to create a website using HTML, CSS, and javascript which consists of 2 pages, Fist page of this website will be home page with a left sidebar, one banner, and a list of videos with thumbnails, videos title, and channel info, then the 2nd page of this website that is video watch page. on this page, I will also add a video and video information, channel information, list of comments and we will make a sidebar with a list of suggested videos.
This page is also responsive for small-screen devices.  this website design is similar to YouTube.

**Screenshots (optional)**

![Alt text](https://www.freecodecamp.org/news/content/images/2022/01/youtube-clone-repeation.PNG) similar to this

**Comment by payalpm** [comment]
@Enhancer18 @pranjay-poddar assign me then i will solve

**Comment by shellyverma** [comment]
Hey @pranjay-poddar , I would like to add YouTube clone using HTML, CSS, and javascript. I can resolve this issue. I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23 .

**Comment by khadesamrudhi** [comment]
@Enhancer18 @pranjay-poddar  please assign to me this project under GSSOC'23

**Comment by yashiitiwarii** [comment]
Please assign me this issue, I would like to work on this @Enhancer18

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by ssm0212** [comment]
@pranjay-poddar I am a GSSOC'23 contributor. I want to work on this issue. Please assign this issue to me.

**Comment by Saurabh-kumar09** [comment]
@Enhancer18 Go ahead.
