### ISSUE TITLE
[GSSOC'23] Google Docs Clone

### ISSUE THREAD

**Issue by Vidip-Ghosh** [pranjay-poddar/Dev-Geeks#1491]
**Describe the project you want to add with tech stack**
An application working on the lines of Google Docs. Sockets IO used for connecting between client and server. ReactJS is used as a frontend, QuillJS for editor, NodeJS as backend, Socket IO and MongoDB database. 

**Expected behavior**
It can save files automatically and also if a file is shared with someone then anyone can make changes in it. 

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/91741581/3c97a165-6976-4394-8714-9cae8f5b72f1

**Additional context (optional)**
Please assign me this for GSSoC'23.

**Comment by Abh71234** [comment]
Please assign me this for GSSoC'23.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Gun2902** [comment]
can u assign me this isssue
