### ISSUE TITLE
Google keep clone

### ISSUE THREAD

**Issue by Nikita110602** [pranjay-poddar/Dev-Geeks#1493]
Google keep clone:-is a a clone of google keep which is used as to-do list .
basically it is Google Keep, which is a popular to-do list application developed by Google, would involve building a full-fledged web application clone

**Comment by Nikita110602** [comment]
pls assign me with this issue to add this project

**Comment by Shivamm20** [comment]
please assign me this issue. i want to fix it .

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by yash8917** [comment]
hi @pranjay-poddar , Please assign this issue to me , under GSSoC'23
