### ISSUE TITLE
Gssoc water solve puzzle

### ISSUE THREAD

**Issue by payalpm** [pranjay-poddar/Dev-Geeks#1494]
Project description 
I would like to add a feature to the water sort puzzle that allows users to save their progress. This would be done by storing the state of the puzzle in a file, so that users can return to it later. The state of the puzzle would include the colors of the water in each container, as well as the positions of the containers.

**Describe the project you want to add with tech stack**
he tech stack that I would use to implement this feature is:

HTML: To create the user interface
CSS: To style the user interface
JavaScript: To handle user input and update the state of the puzzle

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Saurabh-kumar09** [comment]
@payalpm You can start working on this issue.

**Comment by payalpm** [comment]
Ya sure thank you 😊

**Comment by payalpm** [comment]
@Saurabh-kumar09 check updated my code
