### ISSUE TITLE
[GSSOC'23] UPDATE BMI CALCULTOR PROJECT

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#1495]
**Describe the Feature you want to end**
Recently i cam across variou frontend project. I saw BMI calculator and i think it could be more functional and attractive. I am well versed with HTML5, CSS3, Javascript.

**Expected behavior**
It would be having gender and age options as well which will give the better results to the users. Improving CSS and HTML will have a major effect on this project

as a contributor pls assign this issue to me so that i can redesign the BMI calculator under the GSSOC'23. Thank you in advance

**Comment by Sakshiii1800** [comment]
please assign this task to me

**Comment by rohanmittal1163** [comment]
hey @Saurabh-kumar09 ,
I have completed my previous issue
now i think its right time to start with this
pls assign me with this issue under GSSOC'23
thank you

**Comment by pranjay-poddar** [comment]
Project already present
