### ISSUE TITLE
[GSSOC'23] CLAYMORPHISM PROFILE CARD

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#1496]
**Describe the Feature you want to end**
I saw the claymorphism project. I have new ideas to implement claymorphism on the project. it would be having the social media account with the follower on current account with a decent profile photo and soothing background.

This is on your project and can be change
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/eb6d91b7-eece-42b5-94f7-4e08cd90c4e8)

PLS assign me with this issue under the GSSOC'23 contributor

**Comment by rohanmittal1163** [comment]
@pranjay-poddar pls assign me with this issue under GSSOC'23 contributor

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by rohanmittal1163** [comment]
hey @Saurabh-kumar09 ,
I have completed my previous issue
now i think its right time to start with this
pls assign me with this issue GSSOC'23
thank you

**Comment by rohanmittal1163** [comment]
hi @pranjay-poddar Pls add the specific labels to this issue 
thank you for your time

**Comment by Saurabh-kumar09** [comment]
@rohanmittal1163 labels will be added once PR get merged successfully.

**Comment by rohanmittal1163** [comment]
@Saurabh-kumar09 @pranjay-poddar

I will submit respective pr (in count 3) in an hour
Thank you for responding

**Comment by rohanmittal1163** [comment]
@Saurabh-kumar09 @pranjay-poddar i have created the PR of this issue 
#2305 pls review it
thank you for your time
