### ISSUE TITLE
[GSSOC'23] UPDATE GOOGLE UI

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#1497]
**Describe the Feature you want to end**
hey @pranjay-poddar I recenlty came across with the google clone project in the frontend section. Actually the UI is not complete. I want to complete the UI of this project and make it similar to google.

**PREVIOUS**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/5a6ae793-2e51-4c1a-8358-4061275bdfa7)

**AFTER**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/a8723271-3e2f-461f-97a8-8cce060438d9)

as a GSSOC'23 contributor PLS assign me with this issue under GSSOC'23

**Comment by Gun2902** [comment]
i would like to work on this issue can u asssign me this isssue

**Comment by rohanmittal1163** [comment]
hey @pranjay-poddar pls assign me with this issue i want to contribute in this repo
thank you

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by rohanmittal1163** [comment]
hi @pranjay-poddar Pls add the specific labels to this issue 
thank you for your time

**Comment by rohanmittal1163** [comment]
hi @pranjay-poddar I have created the PR for this issue. Pls review the changes i have made.
#2303
