### ISSUE TITLE
imporving music player frontend project ui with additional functionality [GSSOC'23]

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#1498]
**Describe the Feature you want to end**
hey @pranjay-poddar i recently came accross with the music player frontend project. It can be make bettr functionable by adding shuffle button , playlist button, download button and more other things with the better UI than the present ones.

**PREVIOUS**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/5f94a96b-4463-4f19-aac5-19cd6a10560e)

**AFTER**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/79e13ec3-e540-4698-ae57-fcdbdd098299)

as a GSSOC'23 contributor pls assign me with this issue. I would love to contribute in this. thank you

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by Gun2902** [comment]
can u assign me this isssue
