### ISSUE TITLE
ADD AN IMAGE EDITOR 

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#1499]
**Describe the project you want to add with tech stack**
hey @pranjay-poddar I want to add a new project which is an image editor where there are many options to choose like grayscale blur, inversion, rotate left right, and many more

**Expected behavior**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/316e7199-bdcb-49cd-b051-01fa9e9b96c4)

as a GSSOC'23 contributor pls assign me with the issue. I would love to contribute in the project

**Comment by Saurabh-kumar09** [comment]
@rohanmittal1163 You can start working on this issue. Please mention tech stacks you are using for this project.

**Comment by rohanmittal1163** [comment]
Html css vanilla js
Thank you for this opportunity

**Comment by rohanmittal1163** [comment]
@Saurabh-kumar09 pls assign me with this issue

**Comment by Saurabh-kumar09** [comment]
@rohanmittal1163 Hey Rohan, You are already working on other issue. Firstly complete that.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by rohanmittal1163** [comment]
hey @Saurabh-kumar09 ,
I have completed my previous issue 
now i think its right time to start with this
pls assign me with this issue
thank you

**Comment by rohanmittal1163** [comment]
pls merge #1616 
otherwise there will be merge conflicts in this
@pranjay-poddar @Saurabh-kumar09

**Comment by rohanmittal1163** [comment]
hi @pranjay-poddar I have added a new project pls see to it.
thank you for your time
i think there should not be any issue if i have merged three issue in one PR

**Comment by rohanmittal1163** [comment]
hi @pranjay-poddar Pls add the specific labels to this issue 
thank you for your time

**Comment by Saurabh-kumar09** [comment]
@rohanmittal1163 
For each issue you need to make a new PR.

**Comment by rohanmittal1163** [comment]
@Saurabh-kumar09 @pranjay-poddar I have created the PR for this issue
PR -> #2306 
pls review it.
thank you for your time and choosing me as a contributor in this project.
