### ISSUE TITLE
Add Reactjs mini-Projects

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#15]
Add a Navbar with side open animation in navbar folder

**Comment by Camilacslopes** [comment]
@pranjay-poddar can you assign me to this issue, please?

**Comment by sumitbaroniya** [comment]
@pranjay-poddar please assign me this issue. I wanted to contribute in it

**Comment by akshat-gupta60** [comment]
@pranjay-poddar i want to contribute can you assign me this issue

**Comment by R4Rohit23** [comment]
Hello this issue is closed or it is still open
