### ISSUE TITLE
want to change the hover button color

### ISSUE THREAD

**Issue by saurabhsingh720** [pranjay-poddar/Dev-Geeks#1500]
want to change the color to light red of the button on hovering the button

**Comment by yashiitiwarii** [comment]
Please assign me this as my first issue @saurabhsingh720

**Comment by SinghSachin2000** [comment]
hey @pranjay-poddar  please assign it to me . I know how to handle it.

**Comment by anupdhoble** [comment]
I know how to fix this , So would like to work on this project. Please assign it to me under GSSOC'23 @pranjay-poddar @saurabhsingh720

**Comment by Vaibhavi972** [comment]
I want to work on this issue ,please assign it to me under GSSOC'23 @pranjay-poddar

**Comment by Sharma711** [comment]
Please assign me this as  issue

**Comment by Saurabh-kumar09** [comment]
Hey @saurabhsingh720 , Thanks for opening the issue. It would be great if you provide more description for the issue. Then only I can assign it to you.

**Comment by saurabhsingh720** [comment]
> Hey @saurabhsingh720 , Thanks for opening the issue. It would be great if you provide more description for the issue. Then only I can assign it to you.

I want to change the color as well as some transition on hovering the button

**Comment by mshujaat10** [comment]
I want to work on this issue, please assign it to me.
