### ISSUE TITLE
Css is not Attached to Education Website

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1501]
**Describe the Feature you want to end**
Add CSS

**Expected behavior**
The website will look more attractive.
**Screenshots (optional)**
![Screenshot (165)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/cac34636-f71c-4258-a207-eba3a0bd8f58)

**Additional context (optional )**
I want to work on it . Please assign this issue to me

**Comment by AyushRai177** [comment]
I want to work on it . Please assign this issue to me

**Comment by aarushiksk** [comment]
Hi, I want to work on this issue, could you please assign this issue to me?

**Comment by muskanmandloi** [comment]
I Have a good Knowledge of CSS ,'
Please assign it to me

**Comment by Cadit21** [comment]
I would like to work on this issue.
I'm proficient in CSS, please assign it to me.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
