### ISSUE TITLE
Spelling is Incorrect in Educational Course Website

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1504]
**Describe the Feature you want to end**
Correct the Spelling

**Expected behavior**
So it will be understandable to others

**Screenshots (optional)**
![Screenshot (167)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/82c06c4e-4369-4a18-bb07-cc82a6914778)

**Additional context (optional )**
I want to work on it. Please assign this issue to me

**Comment by khadesamrudhi** [comment]
please assign to me this project under GSSOC'23

**Comment by pranjay-poddar** [comment]
@Mansi8874 don't raise a PR without getting it assigned as it may lead to disqualification.
