### ISSUE TITLE
Dynamic Product Catalogue 

### ISSUE THREAD

**Issue by Vraj1103** [pranjay-poddar/Dev-Geeks#1508]
A dynamic and responsive product catalogue with admin panel,contact form, chat integration build with React.js, MongoDb, Node.js

Help small business to grow online easily and make their global presence

**Comment by khadesamrudhi** [comment]
please assign to me this project under GSSOC'23

**Comment by Saurabh-kumar09** [comment]
@Vraj1103 Go ahead !!
