### ISSUE TITLE
Portfolio site

### ISSUE THREAD

**Issue by Vraj1103** [pranjay-poddar/Dev-Geeks#1509]
**Describe the project you want to add with tech stack**
A modern looking responsive portfolio site, ready to use by anyone, that will build using html,css and javascript, and will be containing contact us form connected, through google sheets api. 
**Expected behavior**
Will help the user to land good clients, giving headstart 🚀 to  their freelancing journey, can also help them land professional jobs.

**Comment by Abh71234** [comment]
please assign to me this project under GSSOC 2023

**Comment by akhilmishra365** [comment]
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/88160249/dda7517d-1cb3-4356-a0fd-2a3c9292a0e4)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/88160249/6993d401-729e-4d6a-a41c-8473fdb52970)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/88160249/032adffc-5d15-42c8-bd71-da8651d188cf)


created all the parts please assign me this project under GSSOC23

**Comment by khadesamrudhi** [comment]
please assign to me this project under GSSOC'23
