### ISSUE TITLE
Pocket Tanks

### ISSUE THREAD

**Issue by M0hitSingh** [pranjay-poddar/Dev-Geeks#1511]
**Describe the project you want to add with tech stack**
I want to make a game in JavaScript , where 2 tanks can fight with each other ( multiplayer ) 
**Expected behavior**

2 player game where they can shoot cannon on there turn 
they have to change angle and power to make target hit

**Comment by Saurabh-kumar09** [comment]
@M0hitSingh go ahead.

**Comment by M0hitSingh** [comment]
Hey @Saurabh-kumar09
I have completed the assigned work, please review my PR #1666
