### ISSUE TITLE
[GSSOC'23] Add: Number Guessing Game

### ISSUE THREAD

**Issue by MisterMickey** [pranjay-poddar/Dev-Geeks#1513]
**Number Guessing Game in Java**

A Java program where the player guesses a random number within a given range. Feedback is provided after each guess, and the game continues until the correct number is guessed.

**Expected behaviour**

1. Generate a random number within a specific range.
2. Prompt the player to enter their guess.
3. Read the player's input and compare it to the generated number.
4. If the guess is correct, display a congratulatory message and end the game.
5. If the guess is incorrect, provide feedback to the player (e.g., too high or too low).
6. Allow the player to make additional guesses until they guess the correct number.
7. Repeat steps 2-6 until the correct number is guessed.
8. End the game and display the total number of guesses made.

**Screenshots (optional)**

**Additional context (optional )**

![Screenshot from 2023-05-27 23-55-08](https://github.com/pranjay-poddar/Dev-Geeks/assets/93720428/b663c9d8-0d7c-4079-8bb4-75c293218e89)

**Comment by akhilmishra365** [comment]
generated the game please assign me this issue under gssoc 23

**Comment by silky-modi22** [comment]
Please assign me this issue under GSSoC'23

**Comment by NaveenChandraAdhikari** [comment]
Looking forward to work on this issue please assign me 🙌

**Comment by IT-0824** [comment]
Kindly assign me with this issue.

**Comment by MisterMickey** [comment]
@pranjay-poddar Kindly assign me this issue asap.

**Comment by Saurabh-kumar09** [comment]
@MisterMickey go ahead.

**Comment by MisterMickey** [comment]
@Saurabh-kumar09 Kindly review and merge my PR.
