### ISSUE TITLE
Upgrading a project

### ISSUE THREAD

**Issue by Soumyajit2825** [pranjay-poddar/Dev-Geeks#1514]
I want to upgrade the responsive-product-component project to make the UI and the project design more attractive 
Please assign me under this issue under gssov'23 @pranjay-poddar

**Comment by khadesamrudhi** [comment]
Please assign me this issue under GSSoC'23, as I would like to work on its frontend.

**Comment by Soumyajit2825** [comment]
@pranjay-poddar please go through the PR which I have done
