### ISSUE TITLE
Adding dark and light theme in the BeautifulTweets Frontend Page

### ISSUE THREAD

**Issue by mrgulrez** [pranjay-poddar/Dev-Geeks#1516]
**Describe the Feature you want to end**

**Expected behavior**

_Adding dark and light themes to a web page offers benefits such as visual comfort, accessibility, energy efficiency, aesthetics, personalization, and improved user engagement. It allows users to choose their preferred visual style, reduces eye strain, saves device battery, and enhances the overall browsing experience._

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this project.

**Comment by NaveenChandraAdhikari** [comment]
Looking forward to work on this issue please assign me
