### ISSUE TITLE
want to remove the overlaping of navbar and form text in become a volunteer section.

### ISSUE THREAD

**Issue by saurabhsingh720** [pranjay-poddar/Dev-Geeks#1518]
want to remove the overlaping between the nav bar and  text form in become a volunteer section
![Screenshot 2023-05-28 092729](https://github.com/pranjay-poddar/Dev-Geeks/assets/106748434/0798213c-c5a2-4a10-8d26-3c8497d0dda7)

**Comment by anupdhoble** [comment]
I know how to fix this , So would like to work on this project. Please assign it to me

**Comment by SinghSachin2000** [comment]
hey @pranjay-poddar please assign it to me under GSSOC'23. I know how to fix this issue.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
