### ISSUE TITLE
Interface of Btech chai wala need to be improved. Add a Join us page for the joining form, Cool looking footer need to be added

### ISSUE THREAD

**Issue by anupdhoble** [pranjay-poddar/Dev-Geeks#1520]
**Describe the Feature you want to end**

Issues in current project:
- No Good styling to page
- No fonts is there 
- No Navbar
- No Good images
- No Hover effects
**Expected behavior**

- Current user interface looks very basic.Will completely make it good looking
- New Join us page for the Become community member
- Add good looking footer

**Screenshots (optional)**

this is page i want to work on : 

![Screenshot_20230528_104744](https://github.com/pranjay-poddar/Dev-Geeks/assets/83175840/7f22471e-4901-47f7-8fbc-42e7df0dbc3e)

This form i will show on Join us navbar:
![Screenshot_20230528_104946-1](https://github.com/pranjay-poddar/Dev-Geeks/assets/83175840/4f3073d4-fe98-403c-b51a-96b6a1d354ff)

**Additional context (optional )**

Please assign this project to me under GSSOC'23

**Comment by anupdhoble** [comment]
Please assign this project to me i know very well how to do this. under GSSOC'23

**Comment by swatisingh42** [comment]
Please assign this project to me i know very well how to do this.

**Comment by Saurabh-kumar09** [comment]
@anupdhoble you can start working on this issue.

**Comment by anupdhoble** [comment]
Thanks for letting me work on this issue. I will do my job and will report to you at earliest

**Comment by anupdhoble** [comment]
Thanks for letting me work on this issue. I will do my job and will report to you at earliest @Saurabh-kumar09 just want to know ,how much time i have?

**Comment by Saurabh-kumar09** [comment]
Take your time. You have 5 days.

**Comment by anupdhoble** [comment]
Sure👍

**Comment by anupdhoble** [comment]
@Saurabh-kumar09  can u please tell me where r=this project is gone , i am not able to find it , someone renamed it to Btech tea shop?
