### ISSUE TITLE
🚀 [ADD] - FANCY CALCULATOR PROJECT (GSSoC'23)

### ISSUE THREAD

**Issue by 0xabdulkhalid** [pranjay-poddar/Dev-Geeks#1521]
**Describe the project you want to add with tech stack**
- I want to add my fancy calculator project which ensures proper logical incorporated for calculations as well as looks fancy
- It can evaluate expressions for Multiplication, Division, Subraction, Addition & Modulo Division
- It's Responsive for both Desktop & Mobile

**Screenshots (optional)**
![calc](https://github.com/pranjay-poddar/Dev-Geeks/assets/92252895/c4150503-131f-4d27-9924-1c525805ffc0)

**Additional context (optional )**
- I'm a participant of `GSSoC'23`
- So kindly assign me to this issue with `GSSoC'23` label

**Comment by Gun2902** [comment]
can u assign me this isssue

**Comment by niharikaagarwal9771** [comment]
Can you assign me this issue

**Comment by 0xabdulkhalid** [comment]
Hey Guys @Gun2902, @niharikaagarwal9771 please don't ask as "assign me to this issue"!

You can create your own, and wait for the mentor to assign you.

NOTE: This is issue is assigned by me so it can't be assigned to you until i drop this.

Regards
