### ISSUE TITLE
Incorrect Spelling in food ordering website

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1524]
**Describe the Feature you want to end**
 Update the Spelling

**Expected behavior**
So it look more attractive.
**Screenshots (optional)**
![Screenshot (170)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/bd1b5b73-eb97-45cf-b4aa-ad674937a722)
![Screenshot (171)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/3cd20741-9baf-440f-a7fd-42d797a474fd)

**Additional context (optional )**
I want to work on this issue . Please assign me this issue

**Comment by Sharma711** [comment]
I want to work on this issue . Please assign me this issue

**Comment by AnkitGupta30** [comment]
I want to on this projects issue . Please assign me this issue please

**Comment by Ananya01Agrawal** [comment]
I want to on this projects issue . Please assign me this issue please

**Comment by NaveenChandraAdhikari** [comment]
Want to work on this issue please assign me this

**Comment by AyusGup** [comment]
I want to add things like typing animation to head line "Our Food Gallery" , The active branch can hover or be highlighted on navbar. Also, spelling mistakes I would resolve.
Excited to resolve issue, kindly assign this issue to me .

**Comment by impeccable16** [comment]
hi @Mansi8874 please assign this issue to me.

**Comment by pranjay-poddar** [comment]
@Mansi8874 all changes and modifications related to this project will be considered in one issue/PR
