### ISSUE TITLE
Improve the Content of Food Ordering Website

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1526]
**Describe the Feature you want to end**
Improve the Content

**Expected behavior**
So that it look more attractive.

**Additional context (optional )**
I want to work on this issue. Please assign this issue to me

**Comment by Saurabh-kumar09** [comment]
@Mansi8874 It would be great if you share more information related to issues (like relevant screenshot).

**Comment by manshasinghal** [comment]
it would be great if i will add some styling to food ordering website and make it look good please assign this issue to me
