### ISSUE TITLE
[GSSOC'23] Numeric Base Convertor with Python

### ISSUE THREAD

**Issue by Taneesha-02** [pranjay-poddar/Dev-Geeks#1528]
**Describe the project you want to add with tech stack**

The project is a numeric base converter coded in Python, utilizing the Tkinter library for its graphical user interface (GUI). The converter is designed to handle conversions between decimal, octal, binary, and hexadecimal number systems. It provides a convenient way to convert numbers from one base to another, allowing users to input a number in any supported base and obtain its equivalent representation in the desired base.
The application supports decimal (base-10), octal (base-8), binary (base-2), and hexadecimal (base-16) number systems.

**Expected behavior**

The GUI, built using Tkinter, offers a user-friendly interface with intuitive controls and input fields. Users can easily enter a number and select the base they wish to convert from and the base they want to convert to. Upon clicking the "Convert" button, the program performs the conversion using Python's built-in functions and algorithms for base conversions.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by ssm0212** [comment]
I am a GSSoC'23 contributor. I want to work on this issue. Please assign this issue to me with GSSoC'23 label.

**Comment by Taneesha-02** [comment]
Sir , please assign me thid issue under GSSOC'23 , I want to work on this issue .

**Comment by Saurabh-kumar09** [comment]
@Taneesha-02 go ahead.
