### ISSUE TITLE
LinkedIn Clone

### ISSUE THREAD

**Issue by Killer2OP** [pranjay-poddar/Dev-Geeks#1529]
**Describe the project you want to add with tech stack**
I want to add a LinkedIn clone which will be build using React and Firebase.

**Expected behavior**
It will take to the sign in page and then , it will redirect to the home page of your profile.

**Screenshots**
Landing Page.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/111378171/0010a120-e1e5-4e29-995d-e75622fbb3ba)

**Comment by khadesamrudhi** [comment]
please assign me this clone
