### ISSUE TITLE
To add a Readme file for Gif Creator Python Project 

### ISSUE THREAD

**Issue by ayan-joshi** [pranjay-poddar/Dev-Geeks#1530]
So , I look through out the project Gif Creator pretty nicely done so it should have a readme file as well .
@pranjay-poddar Please assign me to improve it by adding the read me file to it , I am a GSSOC'23 contributor.

Following is the glimpse of the readme file :- 

Gif Creator
This project is a Gif Creator application that allows you to create animated GIFs from a series of images or video files. It provides various features and effects like fade in/out, star wipe, and window blinds transitions.

Usage
Add your images or video files to the appropriate directories:

For images: Place your image files in the "Image-Slideshow" directory.
For videos: Place your video files in the "Gif-Creator" directory.
Modify the filenames in the Python code to match your image or video files:

For the slide show: Update the filenames list in the first code block of create_slideshow.py with the filenames of your images.
For the GIF conversion: Update the VideoFileClip argument in the second code block of create_gif.py with the filename of your video.
Run the Python scripts to create the GIF:

For the slide show: Execute create_slideshow.py.
For the GIF conversion: Execute create_gif.py.
Find the generated GIF in the project directory with the name "output.gif".

Acknowledgements
This project makes use of the following libraries:
[imageio](https://imageio.github.io/)
[moviepy](https://zulko.github.io/moviepy/)
Please refer to their respective documentation for more information.

**Comment by Jaan19867** [comment]
Hey , I want to work on this plz assighn me

**Comment by ayan-joshi** [comment]
Thanks for assigning I will surely complete this in minimal time
