### ISSUE TITLE
[GSSoC'23] Change the UI of repository web page

### ISSUE THREAD

**Issue by 0307Vish** [pranjay-poddar/Dev-Geeks#1533]
**Describe the bug**
In the repository web page link of the image or GIF of the header is not working.

**Expected behavior**
there should be a proper image or GIF.

**Screenshots (optional)**
![Screenshot 2023-05-28 185352](https://github.com/pranjay-poddar/Dev-Geeks/assets/102068244/7a8392fb-cdb4-4e4e-ba76-8de7731e448e)
in the screen upper most part there is the header

**Additional context (optional )**
i have already solve this problem and after solving it will look some thing like this
![Screenshot 2023-05-28 181607](https://github.com/pranjay-poddar/Dev-Geeks/assets/102068244/c516d390-cfa5-4566-96ba-b9acd6863b95)

**Comment by 0307Vish** [comment]
Please assign this issue to me under GSSoC'23

**Comment by 0307Vish** [comment]
@pranjay-poddar I have made the PR. Please review it.

**Comment by karananu** [comment]
Please assign this issue to me under GSSoC'23. This is my first open source contribution for  I want to make some changes in the UI

**Comment by Saurabh-kumar09** [comment]
@karananu This issue is closed.
