### ISSUE TITLE
[GSSOC'23] Add: Kaun banega Crorepati Game 

### ISSUE THREAD

**Issue by anjz20** [pranjay-poddar/Dev-Geeks#1535]
**Describe the project you want to add with tech stack**
The Interactive Quiz Application is a web-based project designed to provide users with an engaging and interactive quiz experience

**Expected behavior**
1. The game presents a series of questions to the players, covering various topics or categories
2. Each question is typically accompanied by multiple answer options, from which players must choose the correct one.
3. Each question might have a time limit, adding a sense of urgency and encouraging quick thinking.
4. Players earn points for answering questions correctly, and their scores are tallied throughout the game
5. After each question, the game provides immediate feedback, indicating whether the answer is right or wrong.
6. The game often increases the difficulty level as players progress, challenging them with more complex questions.

**Screenshots (optional)**

![screencapture-kaun-banega-dollarpati-netlify-app-2023-05-28-20_12_20](https://github.com/pranjay-poddar/Dev-Geeks/assets/94970107/cd8ec2c2-73ef-4734-a8ef-e3cd0b2b8bbc)

**Comment by anjz20** [comment]
I want to contribute to this project! @pranjay-poddar

**Comment by IT-0824** [comment]
I would like to contribute to the repository.

**Comment by AyusGup** [comment]
I would like to make Kaun Banega Crorepati Game using Html, Css, Javascript.

The game would be as of required behaviour additionally it would show an image describing step to user at different level like on 10,000 or 3,20,000 making it user interactive and will make him feel to be seated on hot seat.

Excited to resolve issue, Kindly provide me this issue
