### ISSUE TITLE
Adding rock paper scissors game

### ISSUE THREAD

**Issue by MohammadAsiya** [pranjay-poddar/Dev-Geeks#1537]
I would like to add Rock paper scissors game.Please assign this issue to me under Gssoc2023

**Comment by khadesamrudhi** [comment]
please assign me this issue

**Comment by Vaibhavi972** [comment]
please assign me this issue

**Comment by Vaibhavi972** [comment]
![Rock ,Paper and Scissor - Google Chrome 5_29_2023 11_17_13 PM](https://github.com/pranjay-poddar/Dev-Geeks/assets/124433525/ba0e7bf4-ae66-4f75-911e-d7da8576acf2)

**Comment by Vaibhavi972** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/assets/124433525/457df1c8-b64c-4e07-8fd7-781052c5a36c
