### ISSUE TITLE
Age Calculator

### ISSUE THREAD

**Issue by Teddy1404** [pranjay-poddar/Dev-Geeks#1540]
**Describe the project you want to add with tech stack**

The project is made using html , CSS and JavaScript .
**Expected behavior**

The project is use to calculate the age.
**Screenshots (optional)**

**Additional context (optional )**

**Comment by contriking** [comment]
I would like to contribute

**Comment by IT-0824** [comment]
looking forward to work on this issue

**Comment by NandineeSrivastava** [comment]
I want to work on this issue , please assign it to me under GSSOC'23.

**Comment by sam2003j** [comment]
I want to work on this issue , please assign it to me under GSSOC'23.

**Comment by Arman-ali1** [comment]
I want to work on this issue , please assign it to me under GSSOC'23.
 i also work as these type of project
