### ISSUE TITLE
adding hiscore feature

### ISSUE THREAD

**Issue by Nancy248** [pranjay-poddar/Dev-Geeks#1542]
want to add hiscore feature on screen in snake game

**Comment by KavyaS5757** [comment]
I want to work on this issue can you assign this to me...?

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by Nancy248** [comment]
> Thanks for opening your first issue here! Be sure to follow the issue template and also star the repository so that you don't miss out with it!

please assign me this issue as i have raised it

**Comment by Nancy248** [comment]
> I want to work on this issue can you assign this to me...?

no, I  want to work on this  issue so you should  create another issue and as i have raised it earlier
