### ISSUE TITLE
Background Color Change of Page Through Click

### ISSUE THREAD

**Issue by shloksuman** [pranjay-poddar/Dev-Geeks#1543]
**Describe the project you want to add with tech stack**

This is a simple project meant for beginners to learn the basic working of Javascript events.

**Expected behavior**

It has a 'button' in the homepage which allows you to change the color of the background of the webpage.

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/77777064/451799ff-d4fe-4424-af39-912e8f074ec0

**Comment by Sakshiii1800** [comment]
please assign this task to me

**Comment by shloksuman** [comment]
@pranjay-poddar please merge the pull request number #1544   as no further changes are to be made, and deployed demo link is https://shloksuman.github.io/bgcolorchange/

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by subhanshimishra246** [comment]
please assign me this issue under GSSoC'23.
