### ISSUE TITLE
[GSSOC] wants to add full fledge social media app

### ISSUE THREAD

**Issue by souravbhunia07** [pranjay-poddar/Dev-Geeks#1545]
I want to add a social media app called sociopedia. 
the tech stack is MERN.

screenshot:-

![sociopedia](https://github.com/pranjay-poddar/Dev-Geeks/assets/93206401/2dab5251-4dc2-4cd1-a52e-12095e914984)

**Comment by souravbhunia07** [comment]
Please assign this issue to me

**Comment by keenpaul29** [comment]
@souravbhunia07 may i also help you contribute? I am a beginner and I have just learnt HTML, CSS, JS

**Comment by souravbhunia07** [comment]
Yeah sure! @keenpaul29  let the admin assign me the issue.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
