### ISSUE TITLE
Frontend Project's "Learning_Webpage: About Our Services" Section Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#1548]
### **Describe the Feature you want to end**
I want to add hover effect in the **"About Our Services"** Section of this website. Changing color, margin, background, and other style properties on the **"more"** button to make it look even better

### **Expected behavior**
An attractive UI of this section which feels realistic and natural in terms of designing

**Comment by harshvardhan119** [comment]
I want to add on some animated and hover effect to make it more attractive .Change in the font selection and color combination of this will make drastic change in this and I want to do that

**Comment by harshvardhan119** [comment]
Please assign it to me.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
