### ISSUE TITLE
Add a new List App-React.js

### ISSUE THREAD

**Issue by Aishjahan** [pranjay-poddar/Dev-Geeks#1554]
**Describe the project you want to add with tech stack**
I want to add a React.js project named LIST APP . It uses React.js, HTML, and CSS.

**Expected behavior**
It lists downs items that we add and allows us to delete them by double tapping on them.

![LA-1](https://github.com/pranjay-poddar/Dev-Geeks/assets/105747510/80030433-e618-4b29-9e64-a83de7e22ea4)
![LA-2](https://github.com/pranjay-poddar/Dev-Geeks/assets/105747510/f577f327-90be-46f1-8191-abdb0cfaa264)
![LA-3](https://github.com/pranjay-poddar/Dev-Geeks/assets/105747510/5b0cf3a0-632c-4764-b130-5fa2c2b175d8)

Please assign me this issue under GSSoc.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
