### ISSUE TITLE
Update the Navbar of Travel-Site-Home

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1556]
**Describe the Feature you want to end**
Make the Contact Us capital.
**Expected behavior**
All the other content of Navbar is Capital. So it will look more attractive.
**Screenshots (optional)**
![Screenshot (174)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/f0c8b8be-e2a6-401e-9775-3ebcd8ff2f51)

**Additional context (optional )**
I want to work on it. Please assign this issue to me.

**Comment by ShubhaSwarup** [comment]
please assign this task to me

**Comment by KavyaS5757** [comment]
I'll correct it. Please assign this issue to me

**Comment by manshasinghal** [comment]
I want to update the navbar by adding some css styling please assign this issue to me

**Comment by Sujal942** [comment]
I would like to work in this project. Can you Please assign me in this project.
