### ISSUE TITLE
[GSSOC'23] Add: Tilting Maze Game

### ISSUE THREAD

**Issue by Sampath-Vatsavaya** [pranjay-poddar/Dev-Geeks#1558]
**Describe the project you want to add with tech stack**

This Stress Buster game involves tilting a maze using a joystick to make all the balls in the maze fall in the safe zone(Middle of the maze). This game is developed by html,css and js tech stacks and you can play it easily by using the joystick given in the game.

**Expected behavior**

1.  The game comes with a maze and a joystick to control the orientation of the maze
2. There are 4 balls in the maze
3. The game comes with hard and easy mode 
4. Player has to move the joystick and your aim is to take all the balls in the middle
5. press E to switch to easy mode
6. press H to switch to hard mode

**Comment by Saurabh-kumar09** [comment]
@Sampath-Vatsavaya go ahead.
