### ISSUE TITLE
Image is Not Uploaded to Travel Website Template

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1560]
**Describe the Feature you want to end**
I want to add Image 

**Expected behavior**
It will look more attractive.
**Screenshots (optional)**
![Screenshot (176)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/914d5a1b-1ff9-4f65-83c6-fd4f1376ace0)

**Additional context (optional )**
I want to work on this issue. Please assign this issue to me.

**Comment by NandineeSrivastava** [comment]
I want to work on this issue, please assign this issue to me under gssoc'23

**Comment by PartikMalasi** [comment]
I want to work on this issue, please assign this issue to me under gssoc'23

**Comment by Anshul439** [comment]
I can work on this. Please assign this issue to me under GSSoC'23.

**Comment by Shiwani2002** [comment]
hey, i want to work on this please assign it to me
