### ISSUE TITLE
Pathfinding and Sorting visualizer

### ISSUE THREAD

**Issue by VardaPanchal005** [pranjay-poddar/Dev-Geeks#1562]
Pathfinding Visualizer
Is a user friendly website that helps understand DSA algorithms like DIjkshitra ,Swarm,BFS,DFS etc with the help of HTML,CSS and Javascript.
![Pathfinding visualizer](https://github.com/pranjay-poddar/Dev-Geeks/assets/114830938/79fcebe4-643b-4903-b336-4a3b5bed9569)

and

Sorting Visualizer
Helps understand algorithms like merge sort, bubble sort, insertion sort etc

![Sorting Visualizer](https://github.com/pranjay-poddar/Dev-Geeks/assets/114830938/71ef7725-8406-4ec3-88ab-b11486ab736f)

I would like to work on this issue.
@pranjay-poddar

**Comment by VardaPanchal005** [comment]
Is it okay if I contribute this project to another repo as well?
@Saurabh-kumar09

**Comment by Saurabh-kumar09** [comment]
Yes

**Comment by VardaPanchal005** [comment]
@Saurabh-kumar09 I'm sorry but the other repository that I was going to contribute to(this project) didn't allow me to contribute same thing anywhere else. Can you unassign me?
