### ISSUE TITLE
[GSSoC'23] Want to add a new frontend-project called FunSite

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1564]
**Describe the project you want to add with tech stack**
I want to add a new project called FunSite which can generate memes, jokes, riddles and quotes. Tech stack: HTML, CSS and JavaScript.

**Expected behavior**
4 different buttons each for memes, quotes, jokes and riddles. after clicking button for riddle, a new button appears for revealing the answer to the riddle.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/2167dd73-7496-4a95-97b0-51b9160642b5)

**Comment by Saurabh-kumar09** [comment]
@SoarinSkySagar You can start working on this issue.

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar You can start working on this issue.

@Saurabh-kumar09 please merge the PR #1570
