### ISSUE TITLE
Adding a Wordle Game

### ISSUE THREAD

**Issue by ishita80** [pranjay-poddar/Dev-Geeks#1565]
**Describe the project you want to add with tech stack**
Wordle is a word guessing game

**Expected behavior**
A player is given 6 guesses to guess a 5 letter word. After each guess square tile change its color according to the following color coding scheme:
Correct letter with correct position - GREEN
Correct letter with wrong position - YELLOW
Wrong letter - Grey
The keyboard keys also change color based on above color coding scheme.

**Screenshots (optional)**
<img width="421" alt="img3" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/121221158/812525de-5368-4bdd-b106-7433c8f6c854">

**Comment by Saurabh-kumar09** [comment]
@ishita80 Go ahead !!

**Comment by impeccable16** [comment]
hey @Saurabh-kumar09 can you please assign this issue to me
