### ISSUE TITLE
Car racing Game

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1566]
**Describe the project you want to add with tech stack**
A car racing game, similar to road rash, using HTML CSS and JavaScript 

**Expected behavior**
User can control the car in the race, and there will be standings 
**Screenshots (optional)**
Currently working, would be done by the evening

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @0307Vish @Saurabh-kumar09 can this be assigned to me? I'll make the PR in a few hours if assigned. Haven't seen such a game in the project section

**Comment by pranjay-poddar** [comment]
> @pranjay-poddar @0307Vish @Saurabh-kumar09 can this be assigned to me? I'll make the PR in a few hours if assigned. Haven't seen such a game in the project section 

Take your time no need to hurry
