### ISSUE TITLE
Stick Hero game 

### ISSUE THREAD

**Issue by Yashika-Agrawal** [pranjay-poddar/Dev-Geeks#1569]
**Describe the project you want to add with tech stack**
Players will control a stick figure character who can extend and retract a stick to bridge gaps between platforms. The player's input, such as tapping or clicking, will determine the length of the stick.

**Expected behavior**
The player needs to accurately gauge the length of the stick and position it to reach the next platform without falling. The player must adjust the stick length to match the gap width and ensure the stick lands on the next platform securely. The game will end if the stick falls short of the platform or extends beyond it, resulting in the player's character falling.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97408966/f3e80844-f930-48ab-a309-8da40e490713)

**Comment by Saurabh-kumar09** [comment]
@Yashika-Agrawal go ahead.
