### ISSUE TITLE
add roll racing game

### ISSUE THREAD

**Issue by S-ishita** [pranjay-poddar/Dev-Geeks#1573]
**Describe the project you want to add with tech stack**
This is a webpage where you can play a race game based on rolling the dice.
It is a very simplified version of the snake and ladder game we played in our childhood.

**Expected behavior**

- The player who reaches end point first is the winner.
- player starts moves when 6 is achieved
- player name can be set

**Screenshots (optional)**
![Roll_Race](https://github.com/pranjay-poddar/Dev-Geeks/assets/104543751/93c5fb9d-6c01-45d8-ae45-453c1a35996a)

**Additional context (optional )**

**Comment by Saurabh-kumar09** [comment]
@S-ishita go ahead.
