### ISSUE TITLE
[GSSOC'23] Realtime Currency Converter-Frontend Project

### ISSUE THREAD

**Issue by amansgith** [pranjay-poddar/Dev-Geeks#1575]
**Describe the project you want to add with tech stack**
I would like to add a Frontend project of Realtime Currency Conversion using HTML, CSS, javascript and basics of API.

**How it will work**
It will be using API endpoint key to fetch the results in json format in relatime thorugh the currency rates provider website "Exchangerate-API" and then through javascript functions it will use the results to calculate and show the converted currency value on the webpage.

**Expected behavior**
It will be a webpage with two features:-
    1. Display the current unit value of one currency to another
    2. Convert and display the amount entered by the user

**Screenshots (optional)**

**Additional context (optional )**
I will be contributing this under the GSSOC'23 program.. Kindly assign this issue to me
Thank you

**Comment by Saurabh-kumar09** [comment]
@amansgith go ahead.
That's really a good project idea. Make sure to add a readme of your project.
