### ISSUE TITLE
Fitness Regime 

### ISSUE THREAD

**Issue by AnuragJha003** [pranjay-poddar/Dev-Geeks#1576]
**Describe the project you want to add with tech stack**
A site for all the gym freaks out there who would learn the best of exercises with the intended target muscle and regions with tutorials and all type of recommendations and filtering available , A Onestop place for al gym enthus.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by AnuragJha003** [comment]
Bro I have opened the issue first and I would be assigned by the mentor and this is my project which I am going to add so you can please check out other issues or add another project of your own

**Comment by AnuragJha003** [comment]
@pranjay-poddar  please assign me this issue

**Comment by PartikMalasi** [comment]
i would like to work on this project . kindly assign me this project.

**Comment by AnuragJha003** [comment]
I am already working bro please checkout some other issues to work on

**Comment by AnuragJha003** [comment]
Shall I create the PR once I am done with the site building ?

**Comment by AnuragJha003** [comment]
Can I create the PR today night or is there any such specific timings you will look at the PR? @pranjay-poddar
