### ISSUE TITLE
[JS] Adding a basic Personal Finance Tracker for use (Modifications to be made but basic site and functionalities implemented)

### ISSUE THREAD

**Issue by AnuragJha003** [pranjay-poddar/Dev-Geeks#1577]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by AnuragJha003** [comment]
I have created a basic website using plain html css and js styling and extra functionalities will be added later shall I create a PR now?

**Comment by AnuragJha003** [comment]
? Shall I create the PR now? @pranjay-poddar It is a very basic site as of now
