### ISSUE TITLE
[JAVA] Tic Tac Toe

### ISSUE THREAD

**Issue by jainamthakkar** [pranjay-poddar/Dev-Geeks#1578]
**Describe the project you want to add with tech stack**

I want to add a mini project of java (Tic Tac Toe) which can be game on console 

From GSSoC'23

**Comment by Saurabh-kumar09** [comment]
@jainamthakkar go ahead.

**Comment by jainamthakkar** [comment]
i have made the pr which closes this issue can you please review that pr 
@Saurabh-kumar09 #1593

**Comment by 0xabdulkhalid** [comment]
> @jainamthakkar go ahead.

Hey there, can you assign me to this issue: #1563 
I've been waiting for 2 days, please share your thoughts.

Regards
