### ISSUE TITLE
Gpay Homepage clone

### ISSUE THREAD

**Issue by Ayush9951** [pranjay-poddar/Dev-Geeks#1580]
Hi @pranjay-poddar, I am a contributor in GSSOC'23.
I want to add a new project in Frontend projects repository.
Project - I will create a simple homepage clone of Gpay and make It responsive.
please assign me this task under label gssoc'23

**Comment by KavyaS5757** [comment]
Hi sir, I want to work on this using HTML, and CSS. Kindly assign this to me so that I work on it

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by PartikMalasi** [comment]
i would like to work on this project. kindly assign me this project
