### ISSUE TITLE
car game 

### ISSUE THREAD

**Issue by Hardik-2311** [pranjay-poddar/Dev-Geeks#1582]
it will have beautiful ui/ux with special effects and high score enabled and score auto calculate

**Comment by Saurabh-kumar09** [comment]
Hey @Hardik-2311, Someone already build the car racing game. So, It would be great if you can choose new issue to work upon.

**Comment by Saurabh-kumar09** [comment]
I'm closing this issue. If you need any help in working on different issue. Kindly ping us on discord.
