### ISSUE TITLE
car-racing-game

### ISSUE THREAD

**Issue by Hardik-2311** [pranjay-poddar/Dev-Geeks#1583]
**Describe the project you want to add with tech stack**

**Expected behavior**

@pranjay-poddar I am interested in this project kindly assign me under gssoc 23

**Comment by Saurabh-kumar09** [comment]
Hey @Hardik-2311, Someone already build the car racing game. So, It would be great if you can choose new issue to work upon. 
Few suggestions:
Whenever you raise any issue, kindly add enough information related to your issues.

It would be great if you try a different issue.
