### ISSUE TITLE
[GSSoc'23] Adding Code blocks to README.md

### ISSUE THREAD

**Issue by Atharvashirsh** [pranjay-poddar/Dev-Geeks#1584]
**Describe the bug**
The [How to Contribute](https://github.com/pranjay-poddar/Dev-Geeks#how-to-contribute) contains the Git commands in code highlights. 
Eg: `git clone https://github.com/pranjay-poddar/Dev-Geeks`

**Expected behavior**
I want to add Code blocks to the Git commands.
Eg: 
```
git clone https://github.com/pranjay-poddar/Dev-Geeks
```

**Reason for this Addition**
With Code blocks, it is easier to copy the commands to the terminal.

**Comment by Atharvashirsh** [comment]
**Additional Context (optional)**
Can you please assign this issue to me under GSSoC23 label?

**Comment by Piyush-Gambhir** [comment]
I'm interested in working on this issue to improve the readability of the Git commands in the 'How to Contribute' section. I believe that by adding code blocks, it will make it easier for contributors to copy the commands. Please assign this issue to me under gssoc23. Thank you.

**Comment by Saurabh-kumar09** [comment]
@Atharvashirsh go ahead.
