### ISSUE TITLE
Error showing on clicking Home in Ecommerce Sneaker Website [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [pranjay-poddar/Dev-Geeks#1595]
**Describe the bug**
Error showing on clicking Home in Ecommerce Sneaker Website

**Expected behavior**
Home page should have been opened

**Screenshots (optional)**

![Screenshot 2023-05-30 121400](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/0ab7abd5-f752-445b-bfff-2ff84abb5095)

Please assign me this issue under GSSoC'23

**Comment by Saurabh-kumar09** [comment]
@Anshul439 go ahead.
