### ISSUE TITLE
Hyperlinks of Web and Mobile Development are wrong in Education Website [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [pranjay-poddar/Dev-Geeks#1599]
**Describe the bug**
In the Education Website, hyperlink of Web Development is provided in Mobile Development, and vice versa

**Expected behavior**
After clicking on Web Development, learning material related to Web Development should have been shown. And same with Mobile Development. But this isn't the case.

**Screenshots (optional)**
![Screenshot 2023-05-30 124323](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/10c9321f-6ce9-47c2-9065-3621db5e1109)
![Screenshot 2023-05-30 124341](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/3bbf4e9e-6732-47f7-97a3-d909d8c78f9d)

I can fix this by interchanging the hyperlinks. Please assign me this issue under GSSoC'23.

**Comment by ShubhaSwarup** [comment]
I can fix. Please assign this issue to me.

**Comment by Ritika8081** [comment]
Assign me this task
