### ISSUE TITLE
Add stopwatch project in js-project

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#16]
Add stopwatch project in js

**Comment by sumitbaroniya** [comment]
@pranjay-poddar please assign me this issue

**Comment by sumitbaroniya** [comment]
@pranjay-poddar create pull request is not available from mine side so I am not able to create PR

**Comment by pranjay-poddar** [comment]
@sumitbaroniya PR functionality is working properly, follow the instruction in readme carefully.
