### ISSUE TITLE
[GSSoC'23] Quiz App in Flutter

### ISSUE THREAD

**Issue by Atharvashirsh** [pranjay-poddar/Dev-Geeks#1600]
**Describe the project you want to add with tech stack**
I want to add a Quiz App that is built in Flutter and uses Dart language.
This project contains:
- Concepts of Object Oriented Programming.
- Stateless and Stateful widgets.

**Expected behavior**
The following are the expected behavior of the project:
- Generate a question and expect a True/False type answer.
- Keeps track of score and shows if user got the answer correct or not.
- Displays a pop-up window at the end of the Quiz.
- It has a unique App icon than other default Flutter apps.

**Screenshots (optional)**

<img src="https://github.com/pranjay-poddar/Dev-Geeks/assets/121449422/ed3bf810-ea5b-486d-a63d-b194741ea21b" height="500px">

<img src="https://github.com/pranjay-poddar/Dev-Geeks/assets/121449422/01a5bbff-a88d-4931-9864-17a3b5f35831" height="500px">

**Additional context (optional )**
Can you please assign this issue to me under GSSoC'23 label?

**Comment by Saurabh-kumar09** [comment]
@Atharvashirsh go ahead.
