### ISSUE TITLE
[GSSoC'23] Xylophone app in Flutter

### ISSUE THREAD

**Issue by codewithavantika** [pranjay-poddar/Dev-Geeks#1601]
**Describe the project you want to add with tech stack**
I want to add a simple xylophone app built in flutter and dart language.
This project contains:
-It contains the sound library which would help beginners understand how to add sounds to their flutter app
-Stateless and Stateful widgets.

**Expected behavior**
-On clicking on the colorful keys, different notes of the music get played
-It has an amazing app icon different from the default flutter app icon making it look even more interactive

**Screenshots (optional)**
<img src="https://github.com/pranjay-poddar/Dev-Geeks/assets/89691113/f453edf5-8ef6-4e0b-a3cd-45318f587c4b" height="500px">

**Additional context (optional )**
can you please assign me this issue under GSSoC'23 label?

**Comment by Saurabh-kumar09** [comment]
@codewithavantika go ahead.
