### ISSUE TITLE
Update the Shop Now button of the Fruit Website

### ISSUE THREAD

**Issue by JPV2207** [pranjay-poddar/Dev-Geeks#1605]
**Decribe the Feature you want to end**
The button which is there on the website is simple and I want to change its appearance and make it more cool.
**Expected behavior**
After the changes have been made, the user will be able to hover over the button and will definitely love it.
**Screenshots(optional)**
![2023-05-30 (5)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111731727/9df731e5-1ded-42ec-a1b3-f993b9811fcd)
![2023-05-30 (2)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111731727/0c28d490-3856-4c8a-b583-5134ba16bab3)

**Comment by Sujal942** [comment]
I would like to work in this project. Can you Please assign me in this project

**Comment by Saurabh-kumar09** [comment]
hey @JPV2207   , If you want to make any changes in existing features or, project. Then, it would be great if you share relevant screenshots.

**Comment by JPV2207** [comment]
I have added the screenshots sir.

**Comment by Saurabh-kumar09** [comment]
@JPV2207 Go ahead.

**Comment by PartikMalasi** [comment]
I would like to work on this project under GSSOC'23.Please Assign me this task

**Comment by rudrakushwaha** [comment]
I would love to work on this project under GSSOC'23.Please Assign  this task to me.
