### ISSUE TITLE
[GSSOC'23] SIGN LANGUAGE INTERPRETER USING PYTHON

### ISSUE THREAD

**Issue by sahaycodes** [pranjay-poddar/Dev-Geeks#1606]
**SIGN LANGUAGE INTERPRETER USING PYTHON**
A clear and concise python project which will use different python libraries and the concepts of Machine Learning and maybe Deep Learning to understand and interpret Sign Language ...this Model would be helpful for  

**Expected behavior**
Language- python
Libraries- OpenCV , Numpy and etc.
Datasets 

**Screenshots (optional)**

I would be really pleased , if this issue gets assigned to me . Looking forward to your reply .

**Comment by Saurabh-kumar09** [comment]
@sahaycodes go ahead.

**Comment by sahaycodes** [comment]
Is there a time period to complete this issue ?
