### ISSUE TITLE
Create a random color pallete generator

### ISSUE THREAD

**Issue by amelia2802** [pranjay-poddar/Dev-Geeks#1617]
**Describe the project you want to add with tech stack**

Create a random color pallete generator using javascript

**Expected behavior**

Each time the user clicks generate it will give random color pallete ideas for their web/app design

**Screenshots (optional)**

**Additional context (optional )**

I want to contribute to this project as a GSSOC'23 participant

**Comment by amelia2802** [comment]
Hi @Saurabh-kumar09 ! I have raised the #1617 issue under gssoc'23.
It'd be great if you review this and assign me.

**Comment by Saurabh-kumar09** [comment]
@amelia2802 You can start working on this issue.
