### ISSUE TITLE
Iris Flowers Classification 

### ISSUE THREAD

**Issue by Enhancer18** [pranjay-poddar/Dev-Geeks#1619]
**Describe the project you want to add with the tech stack**

Predict the different species of flowers on the length of there petals and sepals only Jupyter notebook code.

**Expected behavior**

The iris dataset contains three classes of flowers, Versicolor, Setosa, Virginica, and each class contains 4 features, ‘Sepal length’, ‘Sepal width’, ‘Petal length’, ‘Petal width’. The aim of the iris flower classification is to predict flowers based on their specific features.

**Comment by SALegend** [comment]
I would like to work on this issue, can you assign it to me :)

**Comment by yash8917** [comment]
Assign that issue to me i have worked so many algorithms in Machine Learning
