### ISSUE TITLE
[GSSOC'23] I want to add a weather app in Frontend-Projects repository. 

### ISSUE THREAD

**Issue by Prashu-01** [pranjay-poddar/Dev-Geeks#1621]
**Describe the project you want to add with tech stack**
I want to add a realtime weather app implemented using CSS, JS and weatherAPI. It will contain a simple UI in which user can search for the city to get the current weather conditions.

**Expected behavior**
It will be responsive, have clean UI and changes its theme background according to the weather status of a location.

**Comment by Prashu-01** [comment]
Hi @Saurabh-kumar09 , I have raised this issue under GSSOC'23.
I would like you to assign this issue to me.

**Comment by Yashagrahari07** [comment]
I would like to work on this project. Please assign it to me.

**Comment by pyjamaSamm** [comment]
I have relevant experience and would like to work on this.

**Comment by Saurabh-kumar09** [comment]
Hey @Prashu-01 , A weather app already exist in this repository. So, It's better if you choose a different project and raise a new issue.
