### ISSUE TITLE
Hand Reacting

### ISSUE THREAD

**Issue by Ayush2966** [pranjay-poddar/Dev-Geeks#1625]
HandReacting is an app which allows the user to generate handwritten text in the form of a downloadable image from the input given. It can be used by students to generate their assignments so that they don't have to go through the hassle of writing down everything physically. Other feature include Converting Text to 34 different handwritten font faces, extracting text from images before converting to various fonts, and Converting speech to text.
![extract](https://github.com/pranjay-poddar/Dev-Geeks/assets/96340111/987f236a-b193-44b0-9b5b-77ee74d2441d)
![main](https://github.com/pranjay-poddar/Dev-Geeks/assets/96340111/846795ed-c70b-48e3-83e7-d5ba524ded73)
![voice](https://github.com/pranjay-poddar/Dev-Geeks/assets/96340111/cc9a55ae-bbb4-4437-a4df-50ce7d4130e1)

**Comment by Saurabh-kumar09** [comment]
@Ayush2966 go ahead.
