### ISSUE TITLE
Create a Image generator with API

### ISSUE THREAD

**Issue by NikhilCode12** [pranjay-poddar/Dev-Geeks#1627]
Describe the project you want to add with tech stack

Create a random Image Splasher using Javascript (ES6)

Expected behavior

User can search for random images in the search box it will splash the images.

Screenshots (optional)
# Dark Mode : OFF
![image](https://github.com/NikhilCode12/ImgSplash/assets/94921824/16009ab2-6d9c-4270-9f46-c560f16f8786)
# Dark Mode : ON
![image](https://github.com/NikhilCode12/ImgSplash/assets/94921824/ce249427-942e-40e7-8e89-fcd473c1155d)

Additional context (optional )

I want to contribute to this project as a GSSOC'23 participant

**Comment by NikhilCode12** [comment]
Hi @Saurabh-kumar09, I have raised a issue #1627 under GSSOC'23.
It would be great, if you can assign this issue to me.

**Comment by utkarshgupta04092003** [comment]
Hello,
I am familiar with these tech stacks like HTML, CSS, JAVASCRIPT, and working with API, you can see my work by clicking this link[click this link](http://utprojects.epizy.com/themealdb/index.html).
It will be grateful if you assign this issue to me. I'll resolve it in a efficient way.

**Comment by Saurabh-kumar09** [comment]
@utkarshgupta04092003 go ahead.
