### ISSUE TITLE
Want to improve UI of password validator

### ISSUE THREAD

**Issue by Illuminati9** [pranjay-poddar/Dev-Geeks#1628]
Since, the UI design of password validator is not that attractive.

I want to improve the UI/UX design of password validator website to become more attractive.

Could you please assign me this issue under GSSOC'23 : )

**Comment by Saurabh-kumar09** [comment]
@Illuminati9 It would be great if you share relevant screenshot if you want to make any changes in existing features.

**Comment by Illuminati9** [comment]
@Saurabh-kumar09 , Here is the screenshot of the improved UI for password validator to look more attractive.

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123324487/f94fbaf1-da2c-4ebd-b7e7-ca4c4eba5dba)

Also it shows prompt when the password is correct without using alert.

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123324487/1f68b674-34bf-4607-a475-89b5f50ccfb1)
