### ISSUE TITLE
[GSSOC'23] [NEW GAME] Creating NINETY NINE game under js-games

### ISSUE THREAD

**Issue by Illuminati9** [pranjay-poddar/Dev-Geeks#1629]
"Ninety Nine" is a simple and strategic number game where you, as the player, compete against a bot opponent. The objective of the game is to be the first player to reach a sum of 99 by strategically selecting numbers.

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/123324487/07a160d3-7eb7-4cb6-b93c-c8e1abffa0c6)

Can you please assign this to me under gssoc'23 : )

**Comment by Saurabh-kumar09** [comment]
@Illuminati9 go ahead and Please mention tech stacks you are using for this project.

**Comment by Illuminati9** [comment]
Hi @Saurabh-kumar09 , I have raised pull request #1653 . Can you please review the changes and merge it to main repository : )
