### ISSUE TITLE
[GSSoC'23] Save Cinema Frontend Project with Payment Gateway Integration

### ISSUE THREAD

**Issue by SJ-Kumar** [pranjay-poddar/Dev-Geeks#1636]
**Describe the project you want to add with tech stack**
The project is focused on promoting and supporting the cinema industry. It aims to create a platform that engages cinema lovers and encourages them to contribute to the well-being of those involved in the film-making process. The webpage showcases information about the project and provides a donation form for users to contribute.

Tech Stack:

HTML: The project uses HTML as the markup language for structuring the webpage.
CSS: CSS stylesheets are employed to define the visual appearance and layout of the webpage. Bootstrap framework is utilized for responsive design.
JavaScript: The project utilizes JavaScript for dynamic functionality, such as implementing the navigation menu and integrating the payment form.
Razorpay: The payment form is powered by Razorpay, a popular online payment gateway.

Please assign this issue to me under GSSOC 23

**Comment by rudrakushwaha** [comment]
Hey I would like to add the payment gateway. Please assign it to me!
