### ISSUE TITLE
[GSSoC'23]: Add a new tic-tac-toe game to JS Games.

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1642]
**Describe the project you want to add with tech stack**
I want to add a tic tac toe game to the JS-games folder. Tech stack: HTML, CSS, JavaScript.

**Expected behavior**
On starting the game, two players will be able to mark on a 3x3 board alternatively, each having been assigned either X or O. from there on, the winner is decided just as it is expected in a normal Tic-Tac-Toe game. Throughout the game, there wil be a button for restarting and a button for new game after the winner has been decided.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/7626a1cc-a503-479c-929a-7e3bebb579ef)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/e9fb3930-360c-4476-b277-d3a3c59d5bbc)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/8155d46e-b095-40de-a32c-2d003e600270)

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @Saurabh-kumar09 @0307Vish please assign me this issue

**Comment by pranjay-poddar** [comment]
Tic tac toe game is already present
