### ISSUE TITLE
[GSSOC'23] [New Project] Fitness center website

### ISSUE THREAD

**Issue by Roshnijeewani3457** [pranjay-poddar/Dev-Geeks#1646]
**Describe the project you want to add with tech stack**

Fitness website is to provide information and resources to help individuals improve their physical health and wellbeing.
Tech used-
HTML,CSS,JAVASCRIPT

**Expected behavior**

**A website having section**
1.Membership
2.BMI
3.Contact us
4.Blogs
5.Centers
6.About us

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/02f65eaf-6a7c-4f0e-a8a7-36fb4bf7f3ad)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/54084cdb-19ab-4dfb-a532-0f0040ac1ce1)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/7250f163-5f08-4f39-88c3-2cddfd2577e5)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/eda2f04e-7e5a-4665-9a13-0ed344b6084b)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/32e04f78-eb72-443e-9b81-8dd1bf6ab13a)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/f7ec581a-2a27-4a19-8c6d-d00cb4319cce)

**Additional context (optional )**

**Comment by Roshnijeewani3457** [comment]
I would like to work on this project under GSSOC'23.Please Assign me this task

**Comment by PartikMalasi** [comment]
i would like to work on this project

**Comment by rudrakushwaha** [comment]
I would love to work on this project under GSSOC'23.Please Assign  this task to me.

**Comment by Roshnijeewani3457** [comment]
I have made a PR's .Please review my PR @pranjay-poddar
