### ISSUE TITLE
3 games-(Tertris,Pong,Brick breaker)Flutter App

### ISSUE THREAD

**Issue by Adithya212** [pranjay-poddar/Dev-Geeks#1655]
I would like to add a Flutter App which has 3 games.
Tetris
Pong
Brick breaker

**Comment by Adithya212** [comment]
![pong](https://gith
![2](https://github.com/pranjay-poddar/Dev-Geeks/assets/81566547/81d0747d-aca2-4af8-b957-66d0690b021f)
ub.com/pranjay-poddar/Dev-Geeks/assets/81566547/2e45a467-8cfb-45b7-9f0b-38de3fb1e774)
![1](https://github.com/pranjay-poddar/Dev-Geeks/assets/81566547/3591d932-b0e1-4361-afe0-4170bb28a5f6)

**Comment by pranjay-poddar** [comment]
Some games are already present please update your issue request

**Comment by Adithya212** [comment]
Noticed that flutter project has only fewer projects available.so is it okay to contribute  these as flutter projects or should I change the topics that already exists.

Can you assign me under GSSOC'23
