### ISSUE TITLE
To add add a memory game 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [pranjay-poddar/Dev-Geeks#1660]
**Describe the project you want to add with tech stack**
To add a memory game created with the help of HTML, CSS and JavaScript

**Expected behaviour**
To make it interactive and playable

**Comment by stuti187** [comment]
For memory game - firstly we will give choice to the player that like what kind of name they want to play with like car ,fruits ,vegetables name etc. Then player have to write/select the name in the correct sequence only which leads to the memory game. Any number of players can play this game.
So this is the idea behind the memory game.
I would like to work on it if it is assign me

**Comment by DhairyaMajmudar** [comment]
Thank you @pranjay-poddar for assigning this issue to me.
I will be pleased if you add GSSoC label to this issue 😃
