### ISSUE TITLE
Image is not accessible in responsive_header

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1670]
**Describe the Feature you want to end**
Add the image in navbar.

**Expected behavior**
So it look more attractive.
** Screenshot**
![Screenshot (182)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/b78b23a6-aec2-4059-8ce8-ac40433b71dc)

**Additional context (optional )**
I want to work on this issue. Please assign this issue to me

**Comment by parth656** [comment]
i want to work on the issue of image on navbar . Kindly assign it to me
