### ISSUE TITLE
Gym Site

### ISSUE THREAD

**Issue by Prakhar-Shankar** [pranjay-poddar/Dev-Geeks#1696]
**Describe the project you want to add with tech stack**
A front end of gym website which will be easily expandible as per the requirement of the user.
Tech stack - HTML, CSS, Js

**Expected behavior**
A frontend of gym website with nav bar.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/a0ff3ca5-37b4-402a-80b8-b18281349506)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/53ed4550-e352-4aa6-815a-8a58a44a623e)

**Comment by Shiwani2002** [comment]
I want to work on it please assign this issue to me @pranjay-poddar
