### ISSUE TITLE
Add Dark Mode Feature 

### ISSUE THREAD

**Issue by Saikatssd** [pranjay-poddar/Dev-Geeks#1712]
**Describe the Feature you want to end**

Is your feature request related to a problem? Please describe.
There is no Dark mode option for this website

Describe the solution you'd like
The dark Mode feature will attract more peeps.
I will add a toggle button which will act as a theme changer from dark mode to light mode

**Comment by Saikatssd** [comment]
@pranjay-poddar Please assign this issue to me so that I can contribute in GSSOC 23.

**Comment by shellyverma** [comment]
Hey @pranjay-poddar ,I would like to add Dark Mode feature.
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23
