### ISSUE TITLE
[GSSOC'23]GUI Calculator with dark and light theme support

### ISSUE THREAD

**Issue by LakshmanGamers** [pranjay-poddar/Dev-Geeks#1717]
**Project Description**
In this project , iam going to make gui calculator .
This Calculator has a theme change support (i.e) We can Change to dark mode or light mode .

**Solution:**
This can done using tkinter module in python .

I have  finished this project  . Please assign this issue under gssoc 2023 , iam very intrested to contribute this repo.

**Comment by Saurabh-kumar09** [comment]
@LakshmanGamers go ahead.

**Comment by LakshmanGamers** [comment]
Sure 😃

**Comment by LakshmanGamers** [comment]
I request you assign gssoc 23 label to this issue m
