### ISSUE TITLE
[GSSoC'23] Wishing model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [pranjay-poddar/Dev-Geeks#1731]
**Describe the project you want to add with tech stack**

Title - **Wishing Model**
Technology - **PYTHON**

**Expected behavior**

- This model will open directly in the terminal,
- This model ask the occasion of wishing,
- Play the song of that occasion in the background,
- Creating a different emojis to wish, etc.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Avdhesh-Varshney** [comment]
@Saurabh-kumar09 @pranjay-poddar Sirs, please /assign this project to me to work under GSSoC'23.
Please Sir !

**Comment by Saurabh-kumar09** [comment]
@Avdhesh-Varshney go ahead.
