### ISSUE TITLE
Adding a blog webiste

### ISSUE THREAD

**Issue by sharmavikas4** [pranjay-poddar/Dev-Geeks#1739]
Blog website that will allow user to write and share blog. It is built on express, nodejs ,ejs and mongodb

**Expected behavior**
The blog will enable the user to share theoir ideas,new things with the rest of the world.

**Screenshots (optional)**

![Screenshot (21)](https://github.com/pranjay-poddar/Dev-Geeks/assets/103022164/a6230fb0-d51a-40db-94e4-9d26a55bf1bf)

**Additional context (optional )**

**Comment by sp9324** [comment]
I would like to work on this issue. Please assign it to me. @pranjay-poddar

**Comment by sharmavikas4** [comment]
I have raised the issue for working on it. Please do not try to take the issues raised by others
