### ISSUE TITLE
POSTMAN Clone using JS

### ISSUE THREAD

**Issue by Harikaraja** [pranjay-poddar/Dev-Geeks#1744]
Describe the project you want to add with tech stack
Post Master clone is similar to postman API platform where we can enter the URL and get the information in the format specified by the user.

This project is done using HML,CSS,JS,Bootstrap.

Expected behavior

we need to choose the request type either GET OR POST.

Now we need to specify the content type either JSON or Custom parameters.

we can add same many custom parameters we want by clicking on + button.

The output will be displayed in the ouput box.

Screenshots (optional)

Additional context (optional )

**Comment by Saurabh-kumar09** [comment]
@Harikaraja go ahead.

**Comment by Harikaraja** [comment]
Ok sir

**Comment by Harikaraja** [comment]
There are few more issues #1773,#1774 can you assign them please sir
actually I have raise the issue 2 weeks ago
