### ISSUE TITLE
Front End: Myntra Clone (GsSOC '23)

### ISSUE THREAD

**Issue by sp9324** [pranjay-poddar/Dev-Geeks#1749]
Describe the project you want to add with tech stack
I would like to create a Myntra homepage using HTML, CSS and JavaScript.

Expected behavior
The homepage will be interactive and responsive just like the actual website.

Please assign this issue to me, @pranjay-poddar

**Comment by shellyverma** [comment]
Hey @pranjay-poddar ,I would like to create Myntra clone using html, css, javascript .
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23

**Comment by sp9324** [comment]
Thank you for assigning this issue to me.
