### ISSUE TITLE
Front End: Spotify Clone (GsSOC '23)

### ISSUE THREAD

**Issue by sp9324** [pranjay-poddar/Dev-Geeks#1750]
Describe the project you want to add with tech stack
I would like to create a Spotify clone using HTML, CSS and JavaScript.

Expected behavior
The page will be interactive and will play music on demand, just like the actual Spotify website. The songs will be the ones that are present in the project files.

Please assign this issue to me @pranjay-poddar

**Comment by striker0234** [comment]
please assign this issue to me.

**Comment by shellyverma** [comment]
Hey @pranjay-poddar ,I would like to create Spotify Clone using html, css, javascript .
I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23.

**Comment by Ankita3503** [comment]
Hi  , Please assign me this issue  I have worked on the project of music app . 
Benefits:
 1. Search music 
 2. Play music
 3. change the music according to mood
 4. Liked music
 5. Smart  and attractive UI

**Comment by pranjay-poddar** [comment]
Project already present
