### ISSUE TITLE
Full Stack Implementation - PrimeFlix

### ISSUE THREAD

**Issue by U-DAY-333** [pranjay-poddar/Dev-Geeks#1751]
Description: I am taking on the ambitious project of creating a full stack application called "PrimeFlix" that aims to clone both the frontend and backend of Amazon Prime Video. This comprehensive endeavor will allow me to enhance my web development skills across the entire stack.

PrimeFlix will replicate the visually appealing user interface, seamless user experience, and robust functionalities of Amazon Prime Video. It will include features such as user authentication and account management, video browsing and searching, video streaming with player controls, personalized recommendations, and a responsive layout for various devices.

For the frontend, I will utilize HTML, CSS, and JavaScript to design and implement the user interface, ensuring it closely resembles the original Amazon Prime Video. The frontend will focus on delivering an intuitive and immersive viewing experience for users.

On the backend, I will employ a suitable framework such as Node.js with Express.js to build the server-side logic and handle API requests. For data storage, I will integrate a database management system like MongoDB to store user information, video metadata, and other relevant data.

Screenshots: (Optional)
If applicable, I will include screenshots to showcase the progress and key aspects of the frontend during its development.

Additional Context: (Optional)
If there are any specific challenges, constraints, or requirements related to the frontend implementation, I will provide additional context to address them accordingly.

**Comment by Saurabh-kumar09** [comment]
@U-DAY-333 go ahead.
