### ISSUE TITLE
[GSSOC'23] Broken images on the frontend project - The car company website

### ISSUE THREAD

**Issue by shivam0277** [pranjay-poddar/Dev-Geeks#1758]
**Screenshots **
![Screenshot 2023-06-04 112143](https://github.com/pranjay-poddar/Dev-Geeks/assets/114799765/9206fdd1-6f97-41ae-939b-d0c03f93a4b5)

**Comment by Sahil21dev** [comment]
Hey @pranjay-poddar sir 
If there's no update on this project i would like to contribute in it.Would fix the images and styling of navbar.
