### ISSUE TITLE
improving contact us page of food website

### ISSUE THREAD

**Issue by kashisha3** [pranjay-poddar/Dev-Geeks#1763]
**Describe the Feature you want to end**
The alignment and display of the fields is to be improved

**Expected behavior**
Making the contact us section more attractive and appealing

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/113295725/12cb21fc-53a7-46c7-8d1d-e7f234334aa2)

**Additional context (optional )**
I am A GSSOC'23 contributor please assign this issue to me @pranjay-poddar @Saurabh-kumar09

**Comment by Saurabh-kumar09** [comment]
Hey @kashisha3 , It would be great if you add relevant screenshots if you want to make any changes in existing projects.

**Comment by kashisha3** [comment]
@Saurabh-kumar09 I have attached the screenshot now. Please see once.

**Comment by Saurabh-kumar09** [comment]
@kashisha3 go ahead.

**Comment by itzanway** [comment]
please assign this task to me
