### ISSUE TITLE
Skype videocall clone

### ISSUE THREAD

**Issue by Shreya111111** [pranjay-poddar/Dev-Geeks#1764]
**Describe the Feature you want to end**

A skype videocall clone is made with Django with multiuser functionality using libraries and modules like agora/websocket.io
some of the features includes :
*  Login page
*  Room
*  Microphone
*  Videophone
*  Endcall Feature
**Expected behavior**

**Screenshots (optional)**
![Screenshot 2023-06-04 151907](https://github.com/pranjay-poddar/Dev-Geeks/assets/95047638/df6a0fc4-bfb2-4431-a24f-489162091f98)

**Additional context (optional )**

I am GSSOC'23 contributer ...plz assign this issue to me. This project belongs to level 2/level 3

**Comment by Saurabh-kumar09** [comment]
@Shreya111111 go ahead.
