### ISSUE TITLE
Virtual Key-Board

### ISSUE THREAD

**Issue by nikhilkumar50** [pranjay-poddar/Dev-Geeks#1770]
About Project:
The virtual keyboard is a user interface component created using HTML, CSS, and JavaScript.

**Expected behavior**
It emulates the functionality of a physical keyboard, allowing users to input text by clicking on virtual keys. It provides a seamless and interactive typing experience for web applications and touch-enabled devices.

Gssoc'23

**Comment by Saurabh-kumar09** [comment]
@nikhilkumar50 go ahead.
