### ISSUE TITLE
A new game: Pacman

### ISSUE THREAD

**Issue by utkarshgupta04092003** [pranjay-poddar/Dev-Geeks#1780]
**Describe the project you want to add with tech stack**
I want to contribute **Pacman game** with two ghosts and one player.

**Expected behavior**
Pac-Man is one of the most iconic video games of all time, and most people (even non-gamers) have at least a passing familiarity with it. The purpose of the game is very simple — the player is placed in a maze filled with food (depicted as pellets or dots) and needs to eat all of it to advance to the next level. This task is made difficult by four ghosts that pursue Pac-Man through the maze. If Pac-Man makes contact with any of the ghosts, the player loses a life and the positions of Pac-Man and the ghosts are reset back to their starting locations.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/63789702/30ba8d10-54e0-4512-988d-3c2e93201623)

**Comment by Vishalydv07** [comment]
@utkarshgupta04092003 are you a GSSoC'23 contributor?

**Comment by utkarshgupta04092003** [comment]
> @utkarshgupta04092003 are you a GSSoC'23 contributor?

yes
