### ISSUE TITLE
[New game]: Planet Defense Game[Gssoc'23]

### ISSUE THREAD

**Issue by Tushar98644** [pranjay-poddar/Dev-Geeks#1781]
**Describe the Feature you want to end**
A game where a spaceship will defend the earth from incoming meteors

**Expected behavior**
The score will increase with each destroyed meteor and the game will be over if the meteor hits the earth

**Screenshots (optional)**
<img width="1356" alt="Screenshot 2023-06-05 at 10 13 54 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/107763774/2fdcf023-2fd0-435f-b137-892f7beb2aad">

**Comment by Tushar98644** [comment]
@pranjay-poddar I would like to take up the issue under gssoc'23

**Comment by Saurabh-kumar09** [comment]
@Tushar98644 go ahead.
