### ISSUE TITLE
Frontend-Project "SIGN UP FORM" Form Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#1798]
**Describe the Feature you want to end**
The design of the form is nice but it can be improved by making some design adjustments. Through some styling changes, I can make it look even better which will effect overall website.

**Expected behavior**
Attractive form design

**Additional context (optional )**
Styling on the form

**Comment by Sujal942** [comment]
Hello i want to work in this project. Can you please assign me recently i make the login form hope you like this.
![Screenshot 2023-06-05 at 10 27 31 PM](https://github.com/pranjay-poddar/Dev-Geeks/assets/63149580/5971e0eb-3beb-4c41-97ca-03aa5f8dd475)
