### ISSUE TITLE
Designing and Adding a proper footer with various links (Figma + JS) [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [pranjay-poddar/Dev-Geeks#1806]
**Describe the Feature you want to add**
The website does not have a proper footer section. I can design a footer section in Figma and code it to the website. Sample footer designed my me:
![FOOTER @](https://github.com/pranjay-poddar/Dev-Geeks/assets/116020663/e1b45c8a-9c21-4182-8c8e-774cd11e1b49)
![FOOTER 1](https://github.com/pranjay-poddar/Dev-Geeks/assets/116020663/51403b67-2753-4e38-b204-0bd5aa0babe4)

**Expected behavior**
To have a footer

**Screenshots (optional)**
Pasted above

**Additional context (optional )**
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by anupriyapoddar** [comment]
I want to work on this issue. Can you please assign me?
