### ISSUE TITLE
Add Editorjs Project

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Dev-Geeks#1816]
**Describe the project you want to add with tech stack**
Hey @pranjay-poddar I want to add the editorjs project to your repo. Please assign me this issue. Thank you!

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Saurabh-kumar09** [comment]
@sumitkr2000 Add more explanation regarding your project.

**Comment by sumitkr2000** [comment]
This project is made using the famous editorjs library where users can create documents and save them in the database. Also, it provides a lot of features for editing text on the go. I have attached a screenshot for a better look:-

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/ae87a1a6-bea0-405a-baa2-1e76d6036182)
