### ISSUE TITLE
Adding a react restaurant website

### ISSUE THREAD

**Issue by Illaf** [pranjay-poddar/Dev-Geeks#1818]

**Comment by Saurabh-kumar09** [comment]
@Illaf Please provide enough information related to your project.

**Comment by Illaf** [comment]
> @Illaf Please provide enough information related to your project.

It is a web site designed for a restaurant .It consists of a Banner page, a menu page, laurels achieved by the owner of the website, a short promotion video and a well designed footer section.
 The website has an excellent and mobile optimised UI design
Overall the website can be customized and used by any of the restaurants in the city
Here is the link:  https://illaf.github.io/restaurantUI.github.io/

**Comment by Saurabh-kumar09** [comment]
@Illaf go ahead.
