### ISSUE TITLE
Adding CSS effect in navbar  and changing clients page : food-website

### ISSUE THREAD

**Issue by kaurjaskirat** [pranjay-poddar/Dev-Geeks#1827]
**Expected behavior**
Adding CSS effect in navbar and changing clients page :food-website

**Screenshots (optional)**
![Screenshot (6)](https://github.com/pranjay-poddar/Dev-Geeks/assets/104628038/f6017d96-ac27-4f44-ac3a-bdff5c086cf2)

**Additional context (optional )**
Please assign me with this task

**Comment by Nandita099** [comment]
Hey I would like to work on this issue .
I am a GSSOC'23 contributor
