### ISSUE TITLE
Flash Game 

### ISSUE THREAD

**Issue by Shreya111111** [pranjay-poddar/Dev-Geeks#1832]
**Describe the project you want to add with tech stack**
Made using Frontend Languages like HTML , CSS and Javascript. It is a Flash game which consists of Pictures which appears like a flash and and a question is asked with a timer and 4 options. The image appeared before is the hint to the answer.

**Expected behavior**
It is a Flash game which consists of Pictures which appears like a flash and and a question is asked with a timer and 4 options. some features are 
Timers
Sound effect
Restarted with reloading.
Scorelist

**Screenshots (optional)**
![Screenshot 2023-06-04 194230](https://github.com/pranjay-poddar/Dev-Geeks/assets/95047638/85569820-7304-4c16-993a-2b0d7fd5d2c2)
![Screenshot 2023-06-04 194253](https://github.com/pranjay-poddar/Dev-Geeks/assets/95047638/3b699bc1-b9d6-4234-84c5-42c4d24fc39a)

**Additional context (optional )**

I am the GSSoc'23 contributor plz assign this to me.

**Comment by Shreya111111** [comment]
@Saurabh-kumar09 kindly assign this issue to me

**Comment by Saurabh-kumar09** [comment]
@Shreya111111 labels will be added after merging the PR.

**Comment by Shreya111111** [comment]
@Saurabh-kumar09  plz merge the #1853 create with branch newjsgame

**Comment by Shreya111111** [comment]
@Saurabh-kumar09  plz check the PR
