### ISSUE TITLE
Improving the UI of the Birthday Site 

### ISSUE THREAD

**Issue by Rahul-web-hub** [pranjay-poddar/Dev-Geeks#1845]
**To improve the UI of the website and make it more feasible**

**The Website would contain the envelope and an updated button for getting the gift.**

![Screenshot 2023-06-06 001027](https://github.com/pranjay-poddar/Dev-Geeks/assets/120596309/f2600582-c126-46d8-a045-aac36bd05022)

**Comment by rudrakushwaha** [comment]
Hey I want to work on this issue under GSS0C 2023. I'will improve the U.I of the site and add a message box.
Please @pranjay-poddar assign it to me.
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/113119934/639dd216-1c33-43cc-9e9a-56402ffe4e01)
