### ISSUE TITLE
Add Todo App

### ISSUE THREAD

**Issue by SattyamSamania** [pranjay-poddar/Dev-Geeks#1857]
**Describe the project you want to add with tech stack**

- I want to add a Todo App made with React Js

**Expected behavior**

- A Todo App with Add and Delete features

**Screenshots (optional)**

![Screenshot (13)](https://github.com/pranjay-poddar/Dev-Geeks/assets/67833888/ae8abd02-17de-45c4-bca9-c551185c532f)

**Additional context (optional )**

**Comment by poorvamaggu** [comment]
Assign this project to me. under GSSOC'23

**Comment by siddhiagarkar** [comment]
I would like to contribute to the To-Do application, which I have made using HTML, CSS and JavaScript. Since I am familiar with the mentioned languages, I would like this task to be assigned to me.

**Comment by poorvamaggu** [comment]
I will make a to-do app with a better ui...please assign this issue to me
under gssoc'23

**Comment by yash8917** [comment]
I will do this  task very quick  a to-do app with a better features. please assign this issue to me
under gssoc'23

**Comment by pranjay-poddar** [comment]
Project already present
