### ISSUE TITLE
I want to add QR Code Generator

### ISSUE THREAD

**Issue by Babunshil** [pranjay-poddar/Dev-Geeks#1858]
# QR Code Generator

A simple QR Code Generator web app built with HTML, CSS, and JavaScript.

![Screenshot 2023-05-19 014047](https://github.com/Babunshil/QRgenerator/assets/106283743/eb15cdf4-e6c5-423b-baf6-c9718cae1c97)

## Features

- Generate QR codes by entering text or URLs.
- Customizable QR code size and appearance.
- Download the generated QR code for easy sharing.

**Comment by swatisingh42** [comment]
I know html ,css, javascript well.
please assign this issue to me under GSSoC'23

**Comment by yash8917** [comment]
I would like to work on this issue under the GSSOC '23 Please assign me this task.
