### ISSUE TITLE
Adding Google Clone Project

### ISSUE THREAD

**Issue by akshaykamath45** [pranjay-poddar/Dev-Geeks#1881]
**Describe the project you want to add with tech stack**
This is a Google Clone application built with React JS. It replicates the functionality of the Google search engine, providing a home page, search component, and search results page.

**Expected behavior**
- Home Page: The application displays a home page similar to the Google search page, with a search bar and buttons.
Search Component: Users can enter search queries in the search bar and click the search button to initiate a search.
- Search Page: The application displays search results instantly without refreshing the page, providing a list of search results with page titles, snippets, and links.

**Screenshots (optional)**
<b>Home Page</b> <br/>
![image](https://user-images.githubusercontent.com/73344382/236706316-0d16fe1e-5337-4218-8687-da82b814c556.png) <br/>

<b>Search Page</b> <br/>
![image](https://user-images.githubusercontent.com/73344382/236706359-76ed25ea-cc5b-4c30-bb78-a193c8b76d5e.png) <br/>

**Additional context (optional )**
## Technologies Used

- **React JS:** The application is built using React JS library, enabling efficient and modular UI components.
- **Material UI:** The Material UI library is used for styling the UI components and providing a modern and responsive design.
- **React Router:** React Router is utilized for handling routing within the application, allowing navigation between different pages.
- **Context API:** The Context API is used for state management, allowing data sharing between components using a global state.
- **Google Custom Search API:** The application makes use of the Google Custom Search API to fetch search results based on user queries.
- **Firebase:** Firebase is used to set up the app and connect it to Google services, facilitating authentication and other backend functionalities.

**Comment by pranjay-poddar** [comment]
Project already present
