### ISSUE TITLE
Weather web app using java with frontend

### ISSUE THREAD

**Issue by jainamthakkar** [pranjay-poddar/Dev-Geeks#1895]
**Describe the project you want to add with tech stack**

To make this  project i have used html, css, js and java.

**Expected behavior**

user can input a city name and he/she will get some information of weather as shown in snapshot

**Screenshots (optional)**

![Screenshot (528)](https://github.com/pranjay-poddar/Dev-Geeks/assets/105544028/8a5ccbe5-b327-4a79-a58b-5b4bda866852)

Assign this issue to me so i can make a pr..... From GSSoC'23

**Comment by pranjay-poddar** [comment]
Project already present

**Comment by jainamthakkar** [comment]
hey @pranjay-poddar, in this project I have used java for processing weather API and I have used maven build tool.
I have checked that in java projects folder we don't have weather web app so I think we can add this in java projects.
