### ISSUE TITLE
To Improve the UI of the gym website and make it more feasible

### ISSUE THREAD

**Issue by Shubham6621** [pranjay-poddar/Dev-Geeks#1897]
I want to change the UI of this site and make it more user friendly 

The website would contain working features and a section to fill person details for getting contacted 

Before changes :-
 
![WhatsApp Image 2023-06-08 at 00 00 58](https://github.com/pranjay-poddar/Dev-Geeks/assets/121442858/26f5b94d-1ef5-4ccf-8ed3-2a8d78192bca)

 After changes :-

![Screenshot 2023-06-07 233519](https://github.com/pranjay-poddar/Dev-Geeks/assets/121442858/6d076030-3a1e-43a5-be40-57bf718906e3)

**Comment by poorvamaggu** [comment]
assign this issue to me ...under GSSOC'23
