### ISSUE TITLE
Add frontend projects in HTML, CSS, and JS

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#19]
Add frontend projects in HTML, CSS, and JS in frontend-project folder

**Comment by Ms-Error** [comment]
Assign me this issue sir.

**Comment by Akanksha-Sen** [comment]
i want to work on this, please assign me

**Comment by sumitbaroniya** [comment]
@pranjay-poddar I want to work on it so please assign me this issue

**Comment by Subha-5** [comment]
@pranjay-poddar  i want to work on this issue. Assign me this issue.

**Comment by roakoth** [comment]
I want to work on this, please assign it to me.

**Comment by YashGadia** [comment]
@pranjay-poddar Can you assign this issue to me?

**Comment by Kpallavi5** [comment]
I would like to work on this issue can you please assign me this issue @pranjay-poddar ?

**Comment by bleep123** [comment]
I would like to work on this issue. Can you please assign this issue to me. @pranjay-poddar

**Comment by aishwarya1735** [comment]
Can this issue be assigned to me? I would add a quiz application with typewriter effect.

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by utkarshgupta04092003** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project as i have many projects that you can see on [this link](http://utprojects.epizy.com)
Kindly provide me the opportunity to work on the issue. @pranjay-poddar

**Comment by 007AnupamSharma** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by pjyoti121** [comment]
I have some good responsive projects please assign me this issue i wouls like to add them
