### ISSUE TITLE
To add a Snake Game 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [pranjay-poddar/Dev-Geeks#1903]
**Describe the project you want to add with tech stack**
I want to add a snake game created with the help of HTMl,  CSS and JavaScript

**Expected behavior**
To make someone to play and enjoy with it

**Screenshots (optional)**
![Screenshot 2023-05-24 224002](https://github.com/pranjay-poddar/Dev-Geeks/assets/124715224/a496b741-4117-4a64-9a25-143b7ce56c86)

**Comment by DhairyaMajmudar** [comment]
@Saurabh-kumar09 Sir and @pranjay-poddar Sir Check this project and assign it to me.

**Comment by nandini601** [comment]
Can you please assign this issue to me under GSSoC'23 label ?
