### ISSUE TITLE
Diabetes Prediction and Analysis

### ISSUE THREAD

**Issue by abhisek-1221** [pranjay-poddar/Dev-Geeks#1911]
**Describe the project you want to add with tech stack**

```
 - The project uses multiple ML classifier models and implements the best model to predict diabetes 
 - Perform exploratory data analysis and feature engineering on the diabetes dataset. 
```
**Tech Stacks:**

> - Numpy
> - Pandas
> - Matplotlib
> - Seaborn
> - Scikit-Learn
> - Scipy

**Expected behavior**

> The model will be able to predict whether the person has diabetes or not based on various features that affects diabetes

Add it to the **`ML Projects`** section

Add _GSSOC label_ to this issue and assign me under it

**Comment by nandini601** [comment]
Can you please assign this issue to me under GSSoC'23 label ?
