### ISSUE TITLE
Add new Project:  Password Generator 

### ISSUE THREAD

**Issue by shubhanshurav** [pranjay-poddar/Dev-Geeks#1915]
**Describe the project you want to add with tech stack**

Hi @pranjay-poddar, I want to add Password generator web aap. so please assign me this issue.

**Expected behavior**

In this project, you can generate up to 20-digit random password.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/e23f452c-ebad-4d60-8feb-a68be7d791e7)

**Comment by pranjay-poddar** [comment]
Project already present
