### ISSUE TITLE
New project calculator

### ISSUE THREAD

**Issue by jainamthakkar** [pranjay-poddar/Dev-Geeks#1916]
**Describe the project you want to add with tech stack**
A calculator is made with html, css and js

**Expected behavior**

It's a basic calculator which evalutes mathematical expressions

**Screenshots (optional)**

![Screenshot (530)](https://github.com/pranjay-poddar/Dev-Geeks/assets/105544028/e248da8b-36f7-4d70-984d-25ce3e22db11)

**Additional context (optional )**

GSSoC'23 

Assign yhis issue to me so i can work on it

**Comment by Saksham0205** [comment]
I know flutter so I can make a Calculator app.
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by swatisingh42** [comment]
I know html, css, and javascript. I know how to create it.
Please assign this issue to me so that i can work on it.

**Comment by jainamthakkar** [comment]
@Saksham0205 if you want to upload your project of flutter than try to open new issue and get it assigned so you can make pr !!

**Comment by yash8917** [comment]
I want to work on this issue under the GSSOC '23. Please Assign this issue to me.

**Comment by pranjay-poddar** [comment]
Project already present
