### ISSUE TITLE
[Add]:New game Bow_Arrow

### ISSUE THREAD

**Issue by Roshnijeewani3457** [pranjay-poddar/Dev-Geeks#1919]
**Describe the project you want to add with tech stack**

Bow_Arrow is a game implemented using HTML, CSS, and JavaScript. The game is to shoot monsters and save birds.
Objective is to Shoot monsters and save birds.

**Expected behavior**

HOW TO PLAY

- Start the game
- Move the man with Arrow Keys
- Shoot arrow with Space Bar
- +1 for hitting monsters
- -5 if monsters reaches birds
- Game Over if score<0
- Monsters speed increases each level.

**Screenshots (optional)**

![Screenshot1](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/7219a118-8620-4ef9-8a03-956a4242fefa)
![Screenshot2](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/7593ab10-f1a6-4623-9736-14fa62617f5d)

**Additional context (optional )**

**Comment by Roshnijeewani3457** [comment]
I would like to work on this issue under GSSOC'23.Please Assign me this task

**Comment by pranjay-poddar** [comment]
Project already present
