### ISSUE TITLE
Redirect links in footer and contact us page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1921]
**Describe the Feature you want to end**
In the "Adventure awaits" project, the footer links do not navigate to their respecrtive sections, and there is no contact us page
**Expected behavior**
On clicking the links in footer, it should redirect to those respective sections, and for this sort of a project, there should be a contact us page

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/433433db-0bfd-4fda-850b-7889b2ec83cd)

**Additional context (optional )**
The ss provided is the footer whose links I want to redirect and add  a contact us too

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @Saurabh-kumar09 Please assign this

**Comment by MohitGupta121** [comment]
@PoulavBhowmick03 Assigned, please go ahead.
