### ISSUE TITLE
Logo is not showing in responsive navbar [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [pranjay-poddar/Dev-Geeks#1925]
**Describe the bug**
Logo is not showing in responsive navbar

**Screenshots (optional)**

![Screenshot 2023-06-09 144000](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/ed6ad979-f2f7-4e17-96c2-69c61b2a826d)

Please assign this issue to me under GSSoC'23

**Comment by pranjay-poddar** [comment]
Logo is not required
