### ISSUE TITLE
[GSSoC'23] Chrome Dinosaur Game

### ISSUE THREAD

**Issue by Atharvashirsh** [pranjay-poddar/Dev-Geeks#1927]
**Describe the project you want to add with tech stack**
* This Project creates a Dinosaur game ( similar to the [Chrome Dinosaur game](https://chromedino.com/) )
* This project will be made using HTML5 , CSS3 and JavaScript ES6.

**Expected behavior**

This Project will have the following functionalities :
* Continuous gameplay.
* Scoreboard.
* Character hitboxes.
* Background music and sound effects. 

**Screenshots (optional)**

![](https://play-lh.googleusercontent.com/x_fh7woTmHB4F4y7Z0nm70y_gbC1wFCAyQBduEepFXm-1KQvRmCsQgSYCOvwNFs6yGs=w526-h296-rw)

**Additional context (optional )**

Can you please assign this issue to me @Atharvashirsh under GSSoC'23 label ?

**Comment by nandini601** [comment]
Can you please assign this issue to me under GSSoC'23 label ?

**Comment by pranjay-poddar** [comment]
Project already present
