### ISSUE TITLE
Want to add Animated Card

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1929]
**Describe the project you want to add with tech stack**
Creating an interactive and visually appealing card design using HTML and CSS.

**Expected behavior**
It is design of Card on hovering it will open the card and it will look amazing.

**Screenshots (optional)**
![Screenshot (207)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/0257835d-85c6-40be-a65b-709d93285a34)

![Screenshot (206)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/7435fb0b-0141-49b4-b02a-a5d81cbe532e)

**Additional context (optional )**
I want to work on this issue please assign this issue to me @pranjay-poddar

**Comment by silky-modi22** [comment]
I want to add hover image effect in circular shape.   
My design looks like this
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/99467488/dffda77d-b16a-48a4-9f8a-4f378bc18442) 
and after hovering on the image it looks like 
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/99467488/fe1948c4-6ba1-4f94-ab89-e303e29034f4) 
I want to work on this issue under GSSoC 2023. Please assign me this.
