### ISSUE TITLE
Want to add Day Planner

### ISSUE THREAD

**Issue by Mansi8874** [pranjay-poddar/Dev-Geeks#1930]
**Describe the project you want to add with tech stack**
It will be a website that allows users to plan and organize their activities for a given day. The website will have a form where users can input their tasks or activities along with their corresponding time slots.

**Expected behavior**
Will make a plan for you day along with time. 

**Screenshots (optional)**

![Screenshot (210)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/863ea9ec-9cd3-4ce3-b5bb-3d3fe9d16198)
![Screenshot (211)](https://github.com/pranjay-poddar/Dev-Geeks/assets/101468475/66bf7295-705d-4053-89aa-6b695915ce19)

**Additional context (optional )**
I want to work on this issue. Please assign this issue to me @pranjay-poddar

**Comment by nandini601** [comment]
I want to work on this issue. Please assign this issue to me @pranjay-poddar
