### ISSUE TITLE
Adding a front-end project: The coffee house [gssoc'23]

### ISSUE THREAD

**Issue by thevirengarg** [pranjay-poddar/Dev-Geeks#1958]
**Describe the project you want to add with tech stack**
This is a website for a coffee shop so that they can expand there business online, and their costumers can order coffee without waiting in big lines.  
Tech Stack: HTML, CSS, JAVASCRIPT.

Adding a new front-end project.

**Screenshots (optional)**

![Screenshot (212)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/60c0e357-6a22-4d13-bf6a-1e3a4f9d5721)

![Screenshot (213)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/4455c39d-bb5e-450c-b753-4ae1fd4e1634)

![Screenshot (216)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/69b2fe03-49af-4ac7-be85-4320ba91e303)

![Screenshot (218)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/d9b59c46-0ce5-473e-bbee-cddbca290e3c)

![Screenshot (219)](https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/58726b90-0155-44d4-ad7f-ad240b9edc06)

**Additional context (optional )**

I am a GSSoC'23 contributor, please add the tag of gssoc'23 after assigning the task to me.

**Comment by thevirengarg** [comment]
@pranjay-poddar @MohitGupta121 Please review this issue and assign it to me.

**Comment by MohitGupta121** [comment]
@thevirengarg please go ahead
