### ISSUE TITLE
[GSSoC'23]: Create a weather app 

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1967]
**Describe the project you want to add with tech stack**
A weather app using API. Enter your own location in the given space, and get the details of the weather in your city.

**Expected behavior**
On clicking Enter button,  the temperature and weather of the place will be shown on the screen
 
**Screenshots (optional)**
<img width="960" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/fea7db2c-f683-4b1c-b613-2c9bdd3defcb">

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @Saurabh-kumar09 @MohitGupta121 please assign me this issue...

**Comment by MohitGupta121** [comment]
@SoarinSkySagar please go ahead

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 @Saurabh-kumar09 please review the linked PR and close this issue after merging
