### ISSUE TITLE
Redesign the Best tweets project

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1969]
**Describe the Feature you want to end**
I want to add hover effect on the tweets and also some UI changes

**Screenshots (optional)**
Right now it looks blunt
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/3a5d5de0-92c6-4ade-bc14-f36d511fa5eb)

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121

**Comment by BhartiNagpure** [comment]
can I work on this issue please assign me under GSSoC Contributor tag.

**Comment by MohitGupta121** [comment]
@BhartiNagpure please pick another issue @PoulavBhowmick03 comment first on this issue
