### ISSUE TITLE
QR code generator

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#1971]
**Describe the project you want to add with tech stack**
Using HTML, CSS and Javascript, generates QR code with any text provided

**Expected behavior**
Provide some text to the website and accordingly, QR is generated
**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/31e8883e-4c44-437e-9e12-fb1e1c06a132)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/7a50c2d3-e4ac-4224-98fc-6c0398717d2b)

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121

**Comment by swatisingh42** [comment]
i know html ,css ,javascript well.
please assign this issue to me under GSSoC'23

**Comment by MohitGupta121** [comment]
@swatisingh42 please go ahead

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121  I made this issue! 
Should it not be assigned to me??

**Comment by PoulavBhowmick03** [comment]
Thanks!

**Comment by swatisingh42** [comment]
> Sorry @swatisingh42 first @PoulavBhowmick03 commented on this please pick another
It's okay
no problem
