### ISSUE TITLE
Adding how to contribute for Github Desktop users

### ISSUE THREAD

**Issue by GitWiz01** [pranjay-poddar/Dev-Geeks#1976]
**Describe the project you want to add with tech stack**

*Want to Add how to contribute for GitHub desktop users*

**Expected behavior**

*I faced this problem when I started contributing. Being a GitHub desktop user how to contribute using GitHub desktop was not given in the majority of the projects. So I feel that the upcoming new folks should not face this problem*

**Screenshots (optional)**

![Screenshot 2023-06-11 112621](https://github.com/pranjay-poddar/Dev-Geeks/assets/123467623/623c123d-8610-484d-a998-433692258fe6)

![Screenshot 2023-06-11 112447](https://github.com/pranjay-poddar/Dev-Geeks/assets/123467623/f2085f1a-fa7a-41f6-b3d3-2edeb60d9876)

Please assign me this under Gssoc'23

**Comment by pranjay-poddar** [comment]
Not required

**Comment by GitWiz01** [comment]
Ok @pranjay-poddar no problem, could you help me find more issues to contribute
