### ISSUE TITLE
Crypto Tracker Using React JS and Material UI

### ISSUE THREAD

**Issue by Harikaraja** [pranjay-poddar/Dev-Geeks#1980]
**Describe the project you want to add with tech stack**
   
   Crypto Tracker is a website where we can track the the daily Values of various crypto currencies , Initially we need to login to the website then We will be displayed a carousel with various Crypto coins.  We an search for the various coins in the search box and find out the value of them .. By default we will be getting the values of all the crypto currencies in Indian Rupees   but we can even view them in USD .

Tech stack used : HTML,CSS,JS ,REACT ,MATERIAL UI. 

**Expected behavior**

You can find out the dialy prices of various crypto currencies .

**Screenshots (optional)**

**Additional context (optional )**

**Comment by BhartiNagpure** [comment]
I would like to work on this project, please assign me this task.
