### ISSUE TITLE
Improve About section of Apna Gym

### ISSUE THREAD

**Issue by jyotsanashyama** [pranjay-poddar/Dev-Geeks#1982]
The about section can look more attractive by adding some features like:
ORIGINAL:
![about-original](https://github.com/pranjay-poddar/Dev-Geeks/assets/63206848/a190359b-d2a3-43f0-b739-8f2aca2aa238)
My design:
![about-myDesign](https://github.com/pranjay-poddar/Dev-Geeks/assets/63206848/5510a41f-3c3c-4943-a665-97e45c7f95e9)
Could you please raise an issue and assign it to me under GSSoC'23

**Comment by BhartiNagpure** [comment]
I would like to work on this issue, I make sure make it more perfect please assign me this issue.

**Comment by BhartiNagpure** [comment]
I would like to redesign whole website by adding more feature .
