### ISSUE TITLE
[GSSoC'23]: Temperature scale changer (C lang.)

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1997]
**Describe the project you want to add with tech stack**
A project in C which will take convert the inputted temperature to another unit, i.e., if input temperature is in Celsius, it will be converted to Fahrenheit scale and vice-versa

**Expected behavior**
Program takes input from user, along with the unit it is in from a second prompt, then display an output showing the emperature converted to a different scale.

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 please assign this issue to me.

**Comment by MohitGupta121** [comment]
Please go ahead, and keep use PR template and guidance. Thanks!

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 @pranjay-poddar @Saurabh-kumar09 please review and merge!

Issue: #1997 
PR: #2011
