### ISSUE TITLE
[GSSoC'23]: A C lang. project on creating a menu driven calculator

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#1998]
**Describe the project you want to add with tech stack**
A C project where on execution, a menu will be printed from where user can select an option to input, then take the input of number to perform calculation on, and accordingly print the result.

**Expected behavior**
Take 3 inputs, 2 for the values to perform mathematical operations on, and one for selecting the operation after displaying the menu. Then, calculating and displaying the result.

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 @pranjay-poddar @Saurabh-kumar09 please assign me this issue

**Comment by MohitGupta121** [comment]
Please go ahead, and keep use PR template and guidance. Thanks!

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 please merge this after review
Issue: #1998 
PR: #2012
