### ISSUE TITLE
[GSSoC'23]: Add a loan calculator

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#2007]
**Describe the project you want to add with tech stack**
A loan calculator to calculate the total amount you have to pay after the given amount of time, principal, time and interest rate both inputted by the user. tech stack: HTML, CSS, JavaScript.

**Expected behavior**
There are two text input fields to input principle and interest rate, and a drop down menu to select duration. After pressing enter, the monthly amount to be paid for the given duration will be calculated.

**Screenshots (optional)**
<img width="960" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/043c5cb4-834e-43f4-a0d5-d371a305dc5a">

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar please assign me this issue

**Comment by MohitGupta121** [comment]
@SoarinSkySagar Please go ahead, and keep use PR template and guidance. Thanks!

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 please review and merge the PR
Issue: #2007 
PR: #2087
