### ISSUE TITLE
Facebook Login Page Clone

### ISSUE THREAD

**Issue by SattyamSamania** [pranjay-poddar/Dev-Geeks#2028]
**Describe the project you want to add with tech stack**

- Facebook Login page clone made with HTML and Tailwind CSS

**Expected behavior**

- A Static Login page with the Tailwind CSS styling

**Screenshots (optional)**

![Screenshot (15)](https://github.com/pranjay-poddar/Dev-Geeks/assets/67833888/e82ee216-a4b6-498c-b5a7-11ef814e9dcf)

**Additional context (optional )**

**Comment by shellyverma** [comment]
Hey @pranjay-poddar, I'm a contributor to GSSOC'23 please assign this issue to me as a part of GSSOC'23 .
