### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2051]
**Describe the project you want to add with tech stack**
A website that generates random passwords on clicking it
**Expected behavior**

On clicking on "Generate", a random password is generated.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/8283e31d-acdf-4b43-af33-4e5773c956da)

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121 @pranjay-poddar

**Comment by MohitGupta121** [comment]
@PoulavBhowmick03 we already have this project.
