### ISSUE TITLE
Adding a new game 

### ISSUE THREAD

**Issue by Ankita3503** [pranjay-poddar/Dev-Geeks#2055]
Hi ,
I want to add a new game in the js game section.

**Comment by Ankita3503** [comment]
I want to add snake and ladder game .

**Comment by Ankita3503** [comment]
Hi can you give me some more time as i have exams in between 19-26. I have
completed half of the task .

**Comment by Ankita3503** [comment]
I have been working on it. Kindly do some other issues.

**Comment by yash8917** [comment]
I'm asking to @pranjay-poddar  sir.

**Comment by pranjay-poddar** [comment]
> I'm asking to @pranjay-poddar  sir.

This one is assigned to @Ankita3503 , you can create a new issue
