### ISSUE TITLE
[GSSoC'23] Add a Chess Game

### ISSUE THREAD

**Issue by AnkitaBarbora** [pranjay-poddar/Dev-Geeks#2075]
**Describe the project you want to add with tech stack**
Description: Add chess game to the js-games folder
Tech - HTML, CSS and JavaScript

**Expected behavior**
To develop a program which allows A game of Chess between 2 players.

**Additional context **
Chess is widely recognized as a game that enhances critical thinking, concentration, problem-solving, and decision-making skills. 
**I want to contribute this project under GSSoC'23.**

**Comment by AnkitaBarbora** [comment]
@MohitGupta121 @pranjay-poddar @Saurabh-kumar09 Please assign this task to me, sirs.

**Comment by MohitGupta121** [comment]
@AnkitaBarbora assigned, please go ahead.
