### ISSUE TITLE
Add animations in CSS and JS

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#21]
Add animations in CSS and JS in respective animation-css or animation-js folders.

**Comment by ghimanshi** [comment]
@pranjay-poddar can you please elaborate on what kinda animations you want to be added?

**Comment by Nymphalys** [comment]
I have fixed this issue. @pranjay-poddar Kindly review my Pull Request 😄

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by Humaira-Sadia** [comment]
hello @pranjay-poddar I believe I can work on this issue , can you please assign this issue to me :)
