### ISSUE TITLE
New Project - Basic Calculator [GSSoC'23]

### ISSUE THREAD

**Issue by Anshul439** [pranjay-poddar/Dev-Geeks#2117]
**Describe the project you want to add with tech stack**
I want to add a project Basic Calculator. The tech stack is - HTML, CSS and JavaScript.

**Screenshots (optional)**

![Screenshot 2023-06-14 001314](https://github.com/pranjay-poddar/Dev-Geeks/assets/123325132/d7cbf48d-2abf-460e-89c1-82b634c33030)

**Comment by imrish4** [comment]
Hi there! I'm excited to contribute to this project for GSSOC'23, Please assign it to me.

**Comment by Vaishwanavi** [comment]
Hi mentors ,I have made the basic calculator using html ,css , js. I want  to contribute to this projects.Please assign it to me.

**Comment by Vaishwanavi** [comment]
![calculator ](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/e444ac22-861a-4c98-a884-da446e1549db)
I AM VERY EXCITED TO CONTRIBUTE ON THIS ISSUE,PLEASE MENTORS ASSIGN THIS ISSUE TO ME.
