### ISSUE TITLE
[Gssoc23] (Frontend projects) Pizza Corner

### ISSUE THREAD

**Issue by invigorzz313** [pranjay-poddar/Dev-Geeks#2123]
**Describe the Feature you want to add**
I want to a add a footer to this website Pizza Corner

**Expected behavior**
A footer with aboutUs and contact links

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Vaishwanavi** [comment]
Hi mentors please assign this issue to me under GSSOC'23. I  want to make footer of this website ,fully responsive with hovering effect.

**Comment by Vaishwanavi** [comment]
plz assign this issue to  me I will make the footer fully responsive and attractive with hovering [effect``](![footer](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/08168115-ccab-474a-b4b1-c5794c01bc9f))
I  have made this,it is fully responsive

**Comment by Vaishwanavi** [comment]
![footer](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/a523097b-bdfd-473d-ac17-85e6d44846a1)
I have made this footer it is fully responsive with hovering effect.Respected mentors plz assign this issue to me
![footer](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/52440c2d-1053-4b44-9d55-75e179e5bba1)
