### ISSUE TITLE
Make a new UI for the Website in Figma [GSSOC'23]

### ISSUE THREAD

**Issue by Ujwal19k** [pranjay-poddar/Dev-Geeks#2128]
**Describe the Feature you want to end**

I saw your "<a src="https://devgeeks-os.netlify.app/repository_web_page">website and observed that the UI is old School. I can create a UI which looks modern and also add prototyping. [GSSOC'23]

**Expected behavior**

I will initially select a color pallet and typography. After conforming it with you (admin) I will create Wirefarme in Figma and at last the final design. You can mention if anything else is to be added in the design
Note-  I will create a new and modern design in figma and not develop website

**Screenshots (optional)**

<img width="960" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/106575224/4049ed88-ee62-4028-8c14-c4d05e30af59">

**Additional context (optional )**

**Comment by Ujwal19k** [comment]
GSSCO'23
Hello I have started the Design in figma. Here is the update.
1. Made a new logo
2. Started with the brand style and layout
3. Added few content

Drive link: https://drive.google.com/drive/folders/1KNG9CkMT6AvcxqwZj8aYnmuwuq0S0rQh?usp=sharing
[DevGeeks.pdf](https://github.com/pranjay-poddar/Dev-Geeks/files/11769292/DevGeeks.pdf)

**Comment by Ujwal19k** [comment]
GSSOC'23
Hey, I have completed the design in figma. Here I am ataching the figma file and PDF (inside drive link).
Figma file: https://www.figma.com/file/19PbwB00E4s1xHzzCD0NFV/DevGeeks?type=design&node-id=0%3A1&t=HmluyLUDnLU7bGuZ-1
Drive Link: https://drive.google.com/drive/folders/1KNG9CkMT6AvcxqwZj8aYnmuwuq0S0rQh?usp=sharing

**Comment by Ujwal19k** [comment]
Where should I add the assets (images and icons) in the repo ?

**Comment by pranjay-poddar** [comment]
You need to code in the website or make changes in the website only figma design are not accepted

**Comment by Ujwal19k** [comment]
I had mentioned it sir.
<img width="425" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/106575224/1d806ac7-4dc7-4b75-ab9f-ed93ceb26072">

**Comment by Ujwal19k** [comment]
Is there any possibility to add my design in your repo? I have invested time on this.

**Comment by Ujwal19k** [comment]
Hello Sir, any update.
