### ISSUE TITLE
Landing page for a community website

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2135]
**Describe the project you want to add with tech stack**
Landing Page for a community website
**Expected behavior**
Responsive, attractive looking website
**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/249dcf44-9c54-418a-83be-2b7a2a68719d)

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121

**Comment by MohitGupta121** [comment]
@PoulavBhowmick03 Okay no problem, Thanks
