### ISSUE TITLE
Add Navbar and a Footer to The Devgeeks Website

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2138]
**Describe the Feature you want to end**
Add a navbar and footer to the devgeeks website
**Expected behavior**
It would contain links to projects,Github repo, help sections and others
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/68ab84e1-69a5-4c2d-b9c4-fd4acdceeced)

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121

**Comment by pranjay-poddar** [comment]
@PoulavBhowmick03 it is a single page website, nav and fotter 8s not required
