### ISSUE TITLE
Change the UI of the website and create separate sections for Rules and How to Contribute

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2140]
**Describe the Feature you want to end**
1. Change the design of the DevGeeks website
2. Create separate pages for rules, how to contribute and others

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121

**Comment by pranjay-poddar** [comment]
Changes not required
