### ISSUE TITLE
Online food order project

### ISSUE THREAD

**Issue by mrenigmatic19** [pranjay-poddar/Dev-Geeks#2141]
**Describe the project you want to add with tech stack**
i want to develop fully working online food order web project using html css js nodejs expressjs and mongodb.

**Expected behavior**
this will fully work from adding your own restaurant to user searching surfing through variety of foods.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by mrenigmatic19** [comment]
this will include home page - login sign up each for user and administrative - backend code for booking

**Comment by pranjay-poddar** [comment]
Project already present
