### ISSUE TITLE
[GSSoC'23] : Typing Speed Test

### ISSUE THREAD

**Issue by vaibhavi-d18** [pranjay-poddar/Dev-Geeks#2143]
**Describe the project you want to add with tech stack**
A typing speed test game is a  website that measures and evaluates a player's typing speed and accuracy. It typically presents the player with a random set of words, phrases, or sentences that they need to type accurately within a certain time limit.

**Expected behavior**

- The player clicks the start button to initiate the game. 
- A random text snippet or set of words is displayed for the player to type.
- As the player types, their input is compared to the expected text for accuracy.
- Real-time feedback may be provided, such as highlighting correct and incorrect characters or words.
- It will display time taken , typing speed(words per minute) and accuracy of the user

**Screenshots (optional)**

**Additional context (optional )**

**Comment by vaibhavi-d18** [comment]
could you please assign this issue to me under GSSoC'23

**Comment by amankumar100** [comment]
Hey I assign it to me. I have already made it. Only I am not able to make pull requests.
