### ISSUE TITLE
[GSSoC'23]: Add a digital clock

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#2152]
**Describe the project you want to add with tech stack**
An aesthetically pleasing digital clock, created using HTML, CSS and JS

**Expected behavior**
Shows current time digitally and has a good background image

**Screenshots (optional)**
<img width="958" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/ddf66012-6788-48a1-887d-fe22314418fb">

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 please assign me this issue!

**Comment by subhanshimishra246** [comment]
@pranjay-poddar please assign me this issue.

**Comment by MohitGupta121** [comment]
@subhanshimishra246 it's already assigned to @SoarinSkySagar

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 please review and merge the PR
PR: https://github.com/pranjay-poddar/Dev-Geeks/pull/2502
Issue: https://github.com/pranjay-poddar/Dev-Geeks/issues/2152
