### ISSUE TITLE
[GSSoC'23]: Add a C lang. program to read and write from another file

### ISSUE THREAD

**Issue by SoarinSkySagar** [pranjay-poddar/Dev-Geeks#2154]
**Describe the project you want to add with tech stack**
A program in C where the program will fetch the list of employees from a given input file and print the employee detailes of the person with highest salary onto another output file.

**Expected behavior**
Read and write onto file

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 please assign me this issue.

**Comment by pranjay-poddar** [comment]
Only complete c projects are accepted
