### ISSUE TITLE
QR Code Reader

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2159]
**Describe the project you want to add with tech stack**
QR Code Reader using HTML, CSS and Javascript

**Expected behavior**
Upload a qr code from your files and it will take you to that site/ link

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/e0a1966b-cf55-4554-bfac-2759f416891c)

**Comment by Pavishnaam** [comment]
Kindly assign the issue to me under GSSOC'23 . I have included the pull request. @pranjay-poddar

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121 It is not his issue. I created the issue and this user has made the PR for some reason. Please mark it as spam
