### ISSUE TITLE
Real time character counter (GSSOC'23)

### ISSUE THREAD

**Issue by vidhimakani74** [pranjay-poddar/Dev-Geeks#2172]
**Describe the project you want to add with tech stack**

when you write something in text box this will gives you Real time character count as well as remaining characters.

**Expected behavior**

if yo write something in text box this will display home many characters are left and how many you have typed.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100896986/53c9e7da-bfe7-4ae5-afd1-3aa4f1202ab5)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100896986/8afd6fd1-c9c3-404b-9f4d-ee75479c1a90)

**Additional context (optional )**

**Comment by imrish4** [comment]
Hi there! I'm excited to contribute to this project for GSSOC'23. Please assign it to me.

**Comment by Parijatkumar** [comment]
Hi @vidhimakani74  Plz Assign this task to me.

**Comment by MohammadBinAftab** [comment]
I will use HTML,CSS,JS and react if you want. I can also add space counter and can also add dark theme if you want.I would like to take this issue. Please assign me this issue. I am trying very hard. Please assign me this.
