### ISSUE TITLE
Add Tower Of Hanoi game

### ISSUE THREAD

**Issue by Roshnijeewani3457** [pranjay-poddar/Dev-Geeks#2195]
**Describe the project you want to add with tech stack**

- The Tower of Hanoi is a classic mathematical puzzle that consists of three towers and a set of disks of various sizes. 

- The objective of the game is to move all the disks from one tower to another, while following certain rules, using one of the towers as an intermediate.

**Expected behavior**

- **Moving the disks**: The player can interact with the game by selecting a disk from one rod and moving it to another rod, following the rules of the game.

- **Counting moves**: The game keeps track of the number of moves the player has made and displays it to the player. This helps the player keep track of their progress and challenge themselves to solve the puzzle in fewer moves.

- **Checking if the puzzle has been solved**: The game checks if the player has successfully moved all the disks to another rod, indicating that they have solved the puzzle. This triggers a completion notification to the player.

- **Restarting the game**: The player can choose to restart the game at any point, which resets the game state and allows them to start again from the beginning.
<br>

## **How to play? 🕹️**
The puzzle starts with a number of disks stacked in one of the towers in the order of their size with the largest disk at the bottom and the smallest at the top. The other two rods are initially empty. The challenge is to transfer the entire stack of disks to another rod, adhering to the following rules:

- Only one disk can be moved at a time.
- Each move consists of taking the top disk from one of the rods and placing it on top of the stack on another rod.
- No disk may be placed on top of a smaller disk.
These rules create an interesting and often perplexing problem that requires careful planning and strategic thinking.  
<br>

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/89697445/1e021e04-944e-4319-b228-c6d7beb91612)

**Additional context (optional )**

**Comment by Roshnijeewani3457** [comment]
I would like to work on this under GSSOC'23.Please assign me this task.

**Comment by Souvik-223** [comment]
I would like to work on this issue and have decent experience with web development. Kindly assign this issue to me.

**Comment by pranjay-poddar** [comment]
@Roshnijeewani3457 please refrain from copying code it may lead to permanent id ban.

https://github.com/kunjgit/GameZone/tree/main/Games/Tower_Of_Hanoi
