### ISSUE TITLE
[GSSoC'23] Add a Clock Website(Analog Clock and Alarm Clock)

### ISSUE THREAD

**Issue by prernasngh** [pranjay-poddar/Dev-Geeks#2208]
**Describe the project you want to add with tech stack**
A fully responsive website which will contain both :
1) Analog clock                    
2) An Alarm clock
Tech Stack: HTML , CSS , JavaScript

**Expected behavior**
Users will see a homepage with options to watch the current time in analog clock as well as the option to set up the alarm. This project makes use of videos , audios, event listeners, media queries , etc to make it more interactive.

**Screenshots (optional)**
<img width="917" alt="alarmClock" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/121041518/9c3fea9c-928f-43e7-bdc8-3e1ef09ae367">

<img width="898" alt="analogClock" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/121041518/0714cf57-0833-4e47-9a10-1db0e5cd709c">

**Comment by MohammadBinAftab** [comment]
I would like to take this issue. Please assign me this issue. I am trying very hard. Please assign me this.
