### ISSUE TITLE
[Gssoc '23] Fruit_website (frontend projects)

### ISSUE THREAD

**Issue by invigorzz313** [pranjay-poddar/Dev-Geeks#2218]
**Describe the Feature you want to add**
I want to add a 'back-to-top' button in the fruit_website

**Expected behavior**
To scroll back to the start or header of the website

**Screenshots (optional)**

**Additional context (optional )**

**Comment by MohammadBinAftab** [comment]
I would like to take this issue. Please assign me this issue. I am trying very hard. Please assign me this.
