### ISSUE TITLE
[GSSoC'23] Image Gallery Website Project

### ISSUE THREAD

**Issue by shubhanshurav** [pranjay-poddar/Dev-Geeks#2222]
**Describe the project you want to add with tech stack**

Hey @pranjay-poddar, I want to add "Image Gallery" project please assign me this issue.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/eb0f3650-28b8-489a-b813-898f0ee9fd54)

**Comment by MohammadBinAftab** [comment]
I would like to take this issue. Please assign me this issue. I am trying very hard. Please assign me this.
