### ISSUE TITLE
Ping Pong Game

### ISSUE THREAD

**Issue by lakhan06** [pranjay-poddar/Dev-Geeks#2248]
**Describe the project you want to add with tech stack**
It is a multiplayers game in which two players play together and there is a ball which move between two walls and players have to hit the ball before it touches there respective wall.
**Expected behavior**

- It is a multiplayer game .
- There will be a ball which move between two walls .
- Players need to try that ball did not hit their wall using a moving vertical stick.
- If ball touches a player wall then its opponent point increase with one.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/119161467/dd643379-3b5b-47fe-9cfd-4a8d7c2edbdb)

**Additional context (optional )**
NO

**Comment by lakhan06** [comment]
@pranjay-poddar I also like to inform you that raise  a issue and request your attention and consideration in reviewing and assigning me this issue.
Thankyou

**Comment by pranjay-poddar** [comment]
Project already present
