### ISSUE TITLE
Frontend Notebook Page

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#2259]
**Describe the project you want to add with tech stack**
In this frontend project I have made a simple landing page of a online notebook where we save our daily work in the form of blogs.....

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by aakashmaity** [comment]
I AM VERY EXCITED TO CONTRIBUTE ON THIS ISSUE,PLEASE MENTORS ASSIGN THIS ISSUE TO ME.
