### ISSUE TITLE
Add Login Form

### ISSUE THREAD

**Issue by MisterMickey** [pranjay-poddar/Dev-Geeks#2284]
**Describe the project you want to add with tech stack**
I want to add a login form landing page. Tech Stack: HTML, CSS, Bootstrap 

**Expected behavior**
It's a reusable login form that one can embed to their project.

![Screenshot from 2023-06-17 15-52-21](https://github.com/pranjay-poddar/Dev-Geeks/assets/93720428/ffeeaa8b-5a3b-4531-bdf4-a39f89cb661c)

**Comment by pranjay-poddar** [comment]
Project is too basic
