### ISSUE TITLE
Calculator using html, css

### ISSUE THREAD

**Issue by MohammadAsiya** [pranjay-poddar/Dev-Geeks#2304]
**Describe the project you want to add with tech stack**

Calculator using html, Css

Please assign this issue to me under gssoc 23

**Comment by anoopgangwar4** [comment]
I have knowledge about this issue please assign me

**Comment by Vaishwanavi** [comment]
I HAVE MADE  THE CALCULATOR USING HTML CSS JAVASCRIPT
![calculator ](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/f2be718a-4f37-4204-95f2-b652d7b8ee18)
![calculator ](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/5c38e805-de15-4a7c-aee2-2da0311515d8)

**Comment by Vaishwanavi** [comment]
I HAVE MADE CALCULATOR USING HTML CSS JS .PLEASE ASSIGN THIS ISSUE TO ME.
![calculator ](https://github.com/pranjay-poddar/Dev-Geeks/assets/121885359/6b49b9e4-8640-467e-9dd2-755220211167)

**Comment by Kajal2468** [comment]
I would like to work on this project please assign it to me, I want to creat modern calculator by using HTML , CSS , JS

please assign to me 

Thank YOU!
