### ISSUE TITLE
Create an animated submit button

### ISSUE THREAD

**Issue by iamvittaln** [pranjay-poddar/Dev-Geeks#2318]
**Describe the project you want to add with tech stack**
Instead of using a normal submit button in forms, an animated submit button can be used to inform the user that the form has been submitted.

**Expected behavior**
Animate submit buttons, so that it can be used by everyone while using HTML forms.

**Screenshots (optional)**
![proxy-image](https://github.com/pranjay-poddar/Dev-Geeks/assets/62231556/cd8647df-4950-4ff4-8566-d34c06d4c308)

**Comment by iamvittaln** [comment]
Please assign me this issue.

**Comment by iamvittaln** [comment]
@pranjay-poddar sir can you please assign my friend @GiriprasadKrishnamurthy for this issue? He wants to do it

**Comment by GiriprasadKrishnamurthy** [comment]
Sir why have you closed the issue could you please reopen it I shall contribute to it Sir there are still 4 days of coding remaining

**Comment by GiriprasadKrishnamurthy** [comment]
Sir could you please assign it to me

**Comment by GiriprasadKrishnamurthy** [comment]
@MohitGupta121
