### ISSUE TITLE
TODO List Using React

### ISSUE THREAD

**Issue by Siripujitha01** [pranjay-poddar/Dev-Geeks#2320]
**### Description:**
    Here the TODO list was developed using ReactJS and coming to the Styling i would like to add Ant Design to this project.
In the TODO list the factors are title, description, due date, status of work all these are included.

### **Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/92497773/6cd46ff8-8421-47a3-a052-23f9f033dfaf)

**Comment by KHADIJA-09** [comment]
Please assign me this task.

**Comment by pranjay-poddar** [comment]
Project already present
