### ISSUE TITLE
Landing page for an Events website 

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2323]
**Describe the project you want to add with tech stack**
Landing page for "Thriving Cities"

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/783b91a8-d7a3-42e7-ae31-7caaec01ec1c)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/5d24cf73-8df1-4c98-a4d7-c9ee0fe44a0a)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/ff8a9c4a-d477-46ed-88fb-defc2db04d0e)

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121

**Comment by KHADIJA-09** [comment]
Please assign me this task.
