### ISSUE TITLE
Typing mistake in repo "Dev-Geeks/Frontend-Projects /Instragram Clone"

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#2329]
**Describe the bug**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by pranjay-poddar** [comment]
Can you please explain more and provide some screenshots

**Comment by soubhik-111** [comment]
Describe the bug : There is a spelling mistake in "Instragram Clone" it must be "Instagram CLone"

Expected behavior: Instagram Clone

Screenshots (optional):
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90599826/ec175fb8-9334-4e08-afef-26025f28156c)

Additional context (optional ) : Location is "Dev-Geeks/Frontend-Projects /Instragram Clone"
Please assign me the task under GSSOC 2023
