### ISSUE TITLE
A portfolio website

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#233]
**Describe the project you want to add with tech stack**
A portfolio website in HTML , CSS , JS.

**Expected behavior**

**Screenshots (optional)**
![Screenshot 2022-07-22 175518](https://user-images.githubusercontent.com/91176055/180438275-f6d5cc20-ce72-4616-8472-b5ad67ef9ac9.png)

**Additional context (optional )**

**Comment by ilhamansari** [comment]
please assign me this issue.

**Comment by srinjoy-26** [comment]
@pranjay-poddar bro c'mon this is a level 3 project

**Comment by pranjay-poddar** [comment]
@srinjoy-26 If you are working legitly on each line of code then only level 3 is given, simply pushing the project is not the aim of this repo.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 If you are working legitly on each line of code then only level 3 is given, simply pushing the project and gaining level 3 is not the aim of this repo.
Yes I have worked on this project legitly. Please assign me, I had opened this issue

**Comment by srinjoy-26** [comment]
> @srinjoy-26 If you are working legitly on each line of code then only level 3 is given, simply pushing the project and gaining level 3 is not the aim of this repo.

Ok fine , you want me to like properly explain my project while opening an issue?
