### ISSUE TITLE
TODO using MERN

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#2330]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by soubhik-111** [comment]
Please assign me this task under GSSOC

**Comment by pranjay-poddar** [comment]
Project already present

**Comment by soubhik-111** [comment]
Hello @pranjay-poddar,

## Query
Can you say me the name in which name does the project exist ?
# Screenshot
Project exist under mern stack are as follows:
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90599826/50df2b4f-bd90-4a38-91ac-65d01a8f902b)
