### ISSUE TITLE
Maze -Generation-Game

### ISSUE THREAD

**Issue by shambhavisingh011** [pranjay-poddar/Dev-Geeks#2342]
**Describe the project you want to add with tech stack**
A Maze-Generation-Game is built using basic HTML, CSS, AND JAVASCRIPT.

**Expected behavior**
It keeps the user engaged by creating an easy to medium-level maze and asking them to get through it.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/121101577/94d85814-bad9-42a9-8305-b95e40d85543)

**Additional context (optional )**
Kindly assign me this project.

**Comment by Lavesh12** [comment]
please assign me this issue.
