### ISSUE TITLE
this section requires some margins in the responsive part

### ISSUE THREAD

**Issue by devagya-rattan** [pranjay-poddar/Dev-Geeks#2344]
**Describe the bug**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by devagya-rattan** [comment]
![Screenshot (50)](https://github.com/pranjay-poddar/Dev-Geeks/assets/112056749/a75cf4a6-09e2-49f8-874c-417237f6a354)

**Comment by devagya-rattan** [comment]
please assign this work to me

**Comment by Lavesh12** [comment]
please assign me this issue.
