### ISSUE TITLE
Business Card Page

### ISSUE THREAD

**Issue by SattyamSamania** [pranjay-poddar/Dev-Geeks#2349]
**Describe the project you want to add with tech stack**

- Business Card Page made with HTML and CSS.

**Expected behavior**

- A Static Business Card Page with Information

**Screenshots (optional)**

![Screenshot (17)](https://github.com/pranjay-poddar/Dev-Geeks/assets/67833888/f59a4680-30d1-438a-974d-8311f43dc6d5)

**Additional context (optional )**

**Comment by Lavesh12** [comment]
please assign me this issue.
