### ISSUE TITLE
Add Virtual Guitar Instrument

### ISSUE THREAD

**Issue by Tisha6661** [pranjay-poddar/Dev-Geeks#2352]
**Describe the project you want to add with tech stack**
I want to add a virtual guitar using Javascript, which can be used to have guitar playing experience.

**Expected behavior**
It would be like a guitar on screen, which can be used to play tunes using keyboard keys.

As an active member of GSSOC'23, please assign me this task.

**Comment by Lavesh12** [comment]
please assign me this issue.
