### ISSUE TITLE
Improve UI 

### ISSUE THREAD

**Issue by Sarita-021** [pranjay-poddar/Dev-Geeks#2372]
Want to improve the UI of ' About Project Admin ' in Home page . 
Kindly assign it to me under GSSOC . 
![Screenshot (64)](https://github.com/pranjay-poddar/Dev-Geeks/assets/121181405/cc2569f0-7ef5-4539-98a0-b2521797c98b)

**Comment by Lavesh12** [comment]
please assign me this issue.
