### ISSUE TITLE
temperature convertor 

### ISSUE THREAD

**Issue by saurabhsingh720** [pranjay-poddar/Dev-Geeks#2387]
want to add a new project that is temperature convertor
under GSSOC'23

**Comment by adarsh-aur** [comment]
I have already completed this using HTML, CSS,
Could you kindly assign it to me? 
thanks

**Comment by Parmesh119** [comment]
Hi, @saurabhsingh720  I am Parmesh Bhatt.
I hope you are fine.
Can you please assign this issue to me if you are not working on this issue?
