### ISSUE TITLE
Unit Converter

### ISSUE THREAD

**Issue by Shr-reny** [pranjay-poddar/Dev-Geeks#2389]
**Describe the project you want to add with tech stack**

It's a simple unit converter which can convert one mathematical unit to another. It's built entirely on html ,css and js.

**Expected behavior**

It can convert one entered mathematical unit to another prefferred one.

**Screenshots (optional)**

![Screenshot (68)](https://github.com/pranjay-poddar/Dev-Geeks/assets/125943681/1f92172d-3787-4bfb-afa1-6151ef50a57d)

**Comment by imrish4** [comment]
I want to contribute to this issue, under Gssoc'23. Please assign it to me.
