### ISSUE TITLE
Want to add a Volume calculator

### ISSUE THREAD

**Issue by vedsom** [pranjay-poddar/Dev-Geeks#240]
**Describe the project you want to add with tech stack**
 
Want to a calculator using javascript to calculate the volume of different shapes such as circle, rectangle etc.
**Expected behavior**

it will calculate the respective shape volume.
  
Tech stack- HTML5, CSS3, JAVA SCRIPT

**Comment by vedsom** [comment]
@pranjay-poddar can you assign this project to me?

**Comment by akshat-gupta60** [comment]
@pranjay-poddar can you assign me this task ?
