### ISSUE TITLE
Character counter 

### ISSUE THREAD

**Issue by SimranLahrani842** [pranjay-poddar/Dev-Geeks#2401]
**Describe the project you want to add with tech stack**

We can add a sentence and click on button it will count the number of letters in a word or sentence.Very helpful for the kids who are learning.
**Expected behavior**

With the help of JS we will keep a counter that tracks number of letters.

**Comment by Parmesh119** [comment]
Hi, @SimranLahrani842 I am Parmesh Bhatt.
I hope you are fine.
Can you please assign this issue to me if you are not working on it?
