### ISSUE TITLE
Sample Frontend Project

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#2408]
**Describe the project you want to add with tech stack**
Frontend web page using HTML, CSS and JS

**Expected behavior**
Web Page

**Screenshots (optional)**

**Additional context (optional )**
Please assign me this task under GSSOC'23

**Comment by divyapaneru** [comment]
Please assign me this task under GSSOC'23

**Comment by soubhik-111** [comment]
@MohitGupta121 
Can you review it and give your feedback
