### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#2411]
**Describe the project you want to add with tech stack**
I want to add a responsive Navbar in React, CSS, styled Component.

**Expected behavior**
Responsive Navbar

**Screenshots (optional)**

**Additional context (optional )**
Please assign me this task under GSSOC'23

**Comment by anoopgangwar4** [comment]
sir i want to add responsive navbar ,please assign me this issue.
