### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by Avik-creator** [pranjay-poddar/Dev-Geeks#242]
It will be made using Python

**Comment by Avik-creator** [comment]
@pranjay-poddar please assign me this

**Comment by pranjay-poddar** [comment]
Please describe your project property.

**Comment by Avik-creator** [comment]
It will reduce size of a image like when we are required to upload a photo we are constrained by the size limit and we give our pics to other websites for reducing them but they are not genuine. So here I am planning to make a python project which would help in reducing the size of the image and also keep our data to our self. @pranjay-poddar
