### ISSUE TITLE
Add games in JavaScript games folder

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#247]
**Tech Stack** : HTLML, CSS, JavaScript 

**Expected behavior**
Light games to play on browsers

**Comment by Subha-5** [comment]
@pranjay-poddar  please assign me this issue

**Comment by mpasdan** [comment]
assigned me to this @pranjay-poddar

**Comment by mpasdan** [comment]
assign me to this @pranjay-poddar

**Comment by mpasdan** [comment]
i wiil create a light game stack tha plays on browsers @pranjay-poddar  please assign me
