### ISSUE TITLE
Random Joke Generator

### ISSUE THREAD

**Issue by Ayushkumargit7** [pranjay-poddar/Dev-Geeks#2486]
**Describe the project you want to add with tech stack**
I want to add Random Joke Generator Website made using HTML, CSS , Javascript and API.  

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114018461/88cca6ee-ae9b-4450-8e19-dd1df31b0545)

**Additional context (optional )**
Funny jokes releases the stress.

Please assign it to me.

**Comment by Chocolate-Cone** [comment]
Please assign it to me.
I am a contributor in GSSoC'23
