### ISSUE TITLE
JPEG / PNG to PDF

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#249]
**Describe the project you want to add with tech stack**
A program which converts JPEG / PNG images to PDF.
Tech stack - Python

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Subha-5** [comment]
@pranjay-poddar please assign me this issue

**Comment by srinjoy-26** [comment]
> @pranjay-poddar please assign me this issue

Bro please don't comment on my issues
