### ISSUE TITLE
Form Validation Website

### ISSUE THREAD

**Issue by Ayushkumargit7** [pranjay-poddar/Dev-Geeks#2491]
**Describe the project you want to add with tech stack**
A Form Validation Website , having input fields like name, email, password, etc. It is used to prevent errors by checking the data entered by the user for errors such as empty fields, invalid characters.Ensures the data is accurate. Prevent the mistakes of user inputing wrong data/format by giving errors.

**Expected behavior**
Provides accurate data to be filled.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114018461/42c39db2-5f0b-446f-ad80-ea19d3f7da8f)

**Comment by anoopgangwar4** [comment]
sir please assign me.
