### ISSUE TITLE
Random Testimonial Generator

### ISSUE THREAD

**Issue by PoulavBhowmick03** [pranjay-poddar/Dev-Geeks#2497]
**Describe the project you want to add with tech stack**
A random testimonial generator using HTML CSS and Javascript

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/6033ec2a-4c13-4f64-a68e-83187fce6775)

**Comment by parth656** [comment]
i will make it kindly assign it to me'

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121 please assign this
