### ISSUE TITLE
Add food truck project

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Dev-Geeks#2506]
**Describe the project you want to add with tech stack**
Hey @pranjay-poddar I want to add the Food truck project to the frontend project. Please assign me this issue. Thank you!

**Expected behavior**

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/8e7b117f-6cbb-4334-b192-cb75491dce74)

**Additional context (optional )**

**Comment by divyapaneru** [comment]
I would like to work on this under gssoc 23 . Please assign it to me.

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it @pranjay-poddar

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it @pranjay-poddar
