### ISSUE TITLE
Improve the UI of the deployed website

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Dev-Geeks#2507]
**Describe the Feature you want to end**
Hey, @pranjay-poddar The UI of the website that is deployed currently can be much good and attractive. Also, the information available there is outdated. I want to work on this issue. Please assign me this issue. Thank you!

**Expected behavior**

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/db87c66a-d834-4d3a-9750-177f7333c14d)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/de8dbd60-b54f-470e-8347-216937634ac2)

**Additional context (optional )**

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it @pranjay-poddar

**Comment by sumitkr2000** [comment]
@MohitGupta121 Why did u close this issue? The pr has not been merged yet

**Comment by sumitkr2000** [comment]
@MohitGupta121  please review that pr and merge it

**Comment by MohitGupta121** [comment]
Sorry we not accepting these changes

**Comment by sumitkr2000** [comment]
@MohitGupta121 Jab krna hi nhi rhta hai to time khrb kyu krte ho logo ka

**Comment by MohitGupta121** [comment]
This already done in this PR https://github.com/pranjay-poddar/Dev-Geeks/pull/4946

**Comment by gurjeetsinghvirdee** [comment]
> @MohitGupta121 Jab krna hi nhi rhta hai to time khrb kyu krte ho logo ka

This is not the way to talk maintainers first & last warn to you

**Comment by sumitkr2000** [comment]
> > @MohitGupta121 Jab krna hi nhi rhta hai to time khrb kyu krte ho logo ka
> 
> This is not the way to talk maintainers first & last warn to you

Bro I wasted 2 days designing the webpage and now he closed without any proper reason!!?

**Comment by gurjeetsinghvirdee** [comment]
He mentioned right here that someone did it 2 days ago on PR #4946

**Comment by sumitkr2000** [comment]
> He mentioned right here that someone did it 2 days ago

yes after I asked him why did he closed the pr

**Comment by sumitkr2000** [comment]
he didn't tell before i asked him
