### ISSUE TITLE
YouTube video downloader 

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#253]
**Describe the project you want to add with tech stack**
A python program which downloads the youtube videos on giving the URL as input.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Subha-5** [comment]
@pranjay-poddar  please assign me this issue

**Comment by srinjoy-26** [comment]
> @pranjay-poddar please assign me this issue
You can only comment on issues opened by the project admin
