### ISSUE TITLE
Iris Detection Model

### ISSUE THREAD

**Issue by Mochoye** [pranjay-poddar/Dev-Geeks#2555]
**Describe the project you want to add with tech stack**
The Project is mainly divided into 4 main points

- Loading Images and Labels
- Building a key point Neural network
- Evaluating Performance
- Detecting Iris in real time

**Expected behavior**
It will detect the Iris in real time.

**Comment by PrathamKumar125** [comment]
I would like to work on this project. Please assign it to me.
