### ISSUE TITLE
Freelancing website

### ISSUE THREAD

**Issue by ilhamansari** [pranjay-poddar/Dev-Geeks#257]
**Describe the project you want to add with tech stack**
My freelancing website using html and css.

**Expected behavior**
Will show my skills on the domain in which I do freelancing along with my rates.
**Screenshots (optional)**

**Additional context (optional )**

**Comment by pranjay-poddar** [comment]
Project should be anonymous and it should not contain any personal information.

**Comment by ilhamansari** [comment]
okay. please assign me this issue
