### ISSUE TITLE
Addition of Average Speed Calculation Feature in Internet Speed Checker

### ISSUE THREAD

**Issue by jyotsanashyama** [pranjay-poddar/Dev-Geeks#2584]
@pranjay-poddar I would like to enhance the internet speed checker by incorporating a functionality to conduct three sequential speed tests and deliver the average speed as the final result.
Please assign me this issue under GSSoC'23.

**Comment by Harshu467** [comment]
Assign it to me

**Comment by jyotsanashyama** [comment]
@TusharKesarwani I kindly request that you assign the issue raised by me to my responsibility.

**Comment by jyotsanashyama** [comment]
@TusharKesarwani Please kindly review this pull request and merge it.
