### ISSUE TITLE
Add a node.js project implementing queues using bull lib and redis

### ISSUE THREAD

**Issue by rheimon1** [pranjay-poddar/Dev-Geeks#26]
I would like to contribute adding a node.js project involving queues using bull (https://github.com/OptimalBits/bull) and redis

**Comment by pranjay-poddar** [comment]
@rheimon1 sure you can proceed.

**Comment by rheimon1** [comment]
Can I create a node.js folder and put the project inside it?

**Comment by pranjay-poddar** [comment]
@rheimon1 yes you can but keep the name as 'Node-JS Projects' .

**Comment by chakrinya009** [comment]
please assign this issue to me i will work on it

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!
