### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#262]
Update the list with all the missing projects with their name and link in a list format with proper numbering and subheadings in the readme.

**Comment by khushimarothi** [comment]
You want this to be updated on the main readme or a separate readme file.

**Comment by pranjay-poddar** [comment]
Update the current one, but keep it concise to make it less scrollable. (can be achieved by 3 or 4 projects columns in one row).

**Comment by khushimarothi** [comment]
So should I only mention the main folder name and not the sub folders ?

**Comment by pranjay-poddar** [comment]
Try to make something like this with all the project name and their links which will redirect to the project folder. Make it in alphabetical order.

![image](https://user-images.githubusercontent.com/52539501/181569209-9eec5b56-0959-4127-b244-05c9b02f25c4.png)

**Comment by khushimarothi** [comment]
Got an idea what you exactly want.

**Comment by khushimarothi** [comment]
![sample](https://user-images.githubusercontent.com/85816852/181577480-c1076e57-0585-4296-ab5f-2e849b552bb3.png)
Check if this will work or I should use the names of subfolder here. @pranjay-poddar

**Comment by pranjay-poddar** [comment]
use the name of the all the sub folders

**Comment by pranjay-poddar** [comment]
add one more column to make it four columns

**Comment by khushimarothi** [comment]
Then there will be more than 50 to 60 projects this will make the readme file so long.

**Comment by pranjay-poddar** [comment]
yes, no problem in the long readme. The purpose of this is to showcase all the available projects in this repo.

**Comment by khushimarothi** [comment]
Ok
