### ISSUE TITLE
Add Tic-Tac-Toe Project in C-Projects

### ISSUE THREAD

**Issue by 5h0ov** [pranjay-poddar/Dev-Geeks#2626]
**Describe the project you want to add with tech stack**
I would like to add a project about Tic Tac Toe coded in C.

**Expected behavior**
Would work like a normal tic tac toe game 

**Screenshots (optional)**

**Additional context (optional )**

**Comment by tanisha91** [comment]
Hello @pranjay-poddar  
I can solve this issue, as my skills are aligned with this issue,
Please assign me this issue, so that I can work on it.
