### ISSUE TITLE
Electricity bill calculator.

### ISSUE THREAD

**Issue by ilhamansari** [pranjay-poddar/Dev-Geeks#263]
**Describe the project you want to add with tech stack**
Electricity bill calculator using c programming language.

**Expected behavior**
Will calculate the electricity bill after we enter the number of units consumed.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by ilhamansari** [comment]
@pranjay-poddar please tell me under which folder will I put my c language file?

**Comment by pranjay-poddar** [comment]
make a new folder named:
c_projects/your_project_folder
followed by your project folder name.

**Comment by ilhamansari** [comment]
okay
