### ISSUE TITLE
Feature: Enhance Website Alignment and CSS Styling

### ISSUE THREAD

**Issue by nandini-0104** [pranjay-poddar/Dev-Geeks#2631]
Hello there,
In order to enhance the website, I would like to add more alignment and  CSS.
Please assign me the above task under GSSOC23.

![birthday](https://github.com/pranjay-poddar/Dev-Geeks/assets/121750832/54f7bc66-df73-47dd-bcaa-3e3871bc610d)

**Comment by Shubhranshu6370** [comment]
can  I  access  the issue of   code?
