### ISSUE TITLE
Spotify clone

### ISSUE THREAD

**Issue by ilhamansari** [pranjay-poddar/Dev-Geeks#264]
**Describe the project you want to add with tech stack**
Created a spotify clone using html, css and js.

**Expected behavior**
Will play the songs too.

**Screenshots (optional)**
![Screenshot (31)](https://user-images.githubusercontent.com/102286043/180646367-2779d5a3-ecb9-4257-bb74-21c61f2bea48.png)

**Additional context (optional )**

**Comment by srinjoy-26** [comment]
close this issue if PR is merged @ilhamansari

**Comment by ilhamansari** [comment]
done. @srinjoy-26
