### ISSUE TITLE
[Gssoc'23]-Metamask connect button

### ISSUE THREAD

**Issue by mswat5** [pranjay-poddar/Dev-Geeks#2664]
**Describe the project you want to add with tech stack**
This project is for creating Metamask Connect Button in react app

**Expected behavior**

**Screenshots (optional)**

<img width="713" alt="Screenshot 2023-06-25 at 3 36 09 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/111264418/e15bcfff-f18b-4d22-9f1e-6c86b6a80b3c">

**Additional context (optional )**

**Comment by mswat5** [comment]
@Ashutosh0120 hey can you please assign it to me?

**Comment by Ashutosh0120** [comment]
> 

Lol, I am not the project admin.

**Comment by mswat5** [comment]
@pranjay-poddar hey can you please assign it to me?
