### ISSUE TITLE
[GSSOC]A simple todo website

### ISSUE THREAD

**Issue by Palakkgoyal** [pranjay-poddar/Dev-Geeks#2668]
**Describe the project you want to add with tech stack**
I would use HTML, CSS, JS

**Expected behavior**
The website will let the user enter their todos and also let them to arrange the todos according to their priority. 

**Screenshots (optional)**
I am currently working on this

**Additional context (optional )**
Please assign this to me under GSSOC'23

**Comment by Palakkgoyal** [comment]
But Tushar assigned this to me and I thought I can add any project

**Comment by Palakkgoyal** [comment]
Can I change the tech-stacks?

**Comment by MohitGupta121** [comment]
@Killer2-O thanks
