### ISSUE TITLE
Restaraun bill Generator By cpp

### ISSUE THREAD

**Issue by Nayan808** [pranjay-poddar/Dev-Geeks#2669]
Hello Project Admin,

Restaraunt Name : VegMania 
I'm adding a `CPP` Program to Generate A Restaraunt bill  please assign me this so I can raise a PR.
It's a interesting Real-World Restaraunt Bill Generating.

Screenshot
![Screenshot from 2023-06-25 20-17-05](https://github.com/pranjay-poddar/Dev-Geeks/assets/107837638/ef6d7c57-6c68-4830-aac8-2801730b460b)

I'm working on this !

**Comment by geetanjalising** [comment]
Please assign me this.

**Comment by Nayan808** [comment]
@TusharKesarwani  I had Completed This Project And Raised A PR 
PR no. #2670
