### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by kaashikaagrawal** [pranjay-poddar/Dev-Geeks#2673]
**Describe the bug**
There is no favicon for this website

**Expected behavior**
There should be a relevant favicon on the tab

**Screenshots (optional)**
<img width="149" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/97745349/86ce2cfe-1b50-4670-af72-6cd6a21f69e1">

**Comment by Akshat162001** [comment]
can u telll me which repository it belongs sp that i can make contribution.. in it

**Comment by kaashikaagrawal** [comment]
> can u telll me which repository it belongs sp that i can make contribution.. in it

I want to be assigned to the issue myself. Thanks.
