### ISSUE TITLE
Random quote generator 

### ISSUE THREAD

**Issue by SimranLahrani842** [pranjay-poddar/Dev-Geeks#2676]
**Describe the project you want to add with tech stack**

The web page will generate random new quotes and can be copied form there.
The quote copied then it displays on the screen that it is copied.You can patse the quote.One can refresh to generate new quote.

**Expected behavior**

Made using html,css,js.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by harshitaaa8** [comment]
I can work on this issue.
