### ISSUE TITLE
Shopping Website Clone

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#269]
**Describe the project you want to add with tech stack**
HTML, CSS and JavaScript

**Expected behavior**
A shopping website to buy products like electronics, garments, etc

**Additional context (optional )**
very simple user interface and design

**Comment by Subha-5** [comment]
@pranjay-poddar  please assign me this issue

**Comment by sumitbaroniya** [comment]
please assign me this issue

**Comment by shraddha761** [comment]
Hye please assign me this issue..

**Comment by anjaliSilawat** [comment]
I would like to work on this issue @pranjay-poddar  please assign it to me

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly assign me this issue.@pranjay-poddar

**Comment by bleep123** [comment]
I would like to work on this issue. Please assign it to me. @pranjay-poddar

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
