### ISSUE TITLE
StopWatch 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#2717]
**Describe the project you want to add with tech stack**

I would like to create a StopWatch using Html , Css and Javascript. It will start timer when you click on it and stop when you want to stop the timer .Please assign it to me.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Kajal2468** [comment]
I want to creat a modern stop watch with adding some more functionality ,

Please assign it to me

Thank You!!
