### ISSUE TITLE
Improving Footer Section

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [pranjay-poddar/Dev-Geeks#2741]
**Describe the bug**
The text in the footer looks kinda akward and big

**Expected behavior**
I will be improvving its CSS and making it look lood

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/85278243/7a4bdc4a-557b-4e07-b86d-d5f6230918ab)

**Additional context (optional )**

Please assign me this issue under GSSOC'23

**Comment by Shikhar9425** [comment]
@Swapnil-Singh-99 please assign this issue
