### ISSUE TITLE
Scroll Navbar Project Under Navbar Section

### ISSUE THREAD

**Issue by rahulrana701** [pranjay-poddar/Dev-Geeks#2746]
**Describe the project you want to add with tech stack**
I would like to create a navbar which get's sticky and changes it's background color when we scroll down. I would like to add this 
project under Navbar section.

**Expected behavior**
This navbar will get sticky and will change it's background color as soon we scroll down to it's height

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/123585591/7511c967-40c6-4f61-8903-3b5e04a71346

**Additional context (optional )**
I would like to work on this issue , @MohitGupta121  can you please assign it to me.

**Comment by barsha511** [comment]
I would like to work on it .Please assign me this work@rahulrana701
