### ISSUE TITLE
Add Url Shortener MERN PROJECT

### ISSUE THREAD

**Issue by soumya-maheshwari** [pranjay-poddar/Dev-Geeks#2749]
## A Url Shortener MERN Stack project 
# TECH STACK-
  React
  Express
  Node
  MongoDB

**Expected behavior**
## Features
- Easily shorten long urls
  
- Track the number of clicks on your urls

**Screenshots**

![Screenshot (72)](https://github.com/pranjay-poddar/Dev-Geeks/assets/104725768/a812e54d-2d28-41f5-b839-6ada150dffba)
![Screenshot (73)](https://github.com/pranjay-poddar/Dev-Geeks/assets/104725768/3669689b-e427-4b52-b47e-cb5ae4485a50)

**Additional context (optional )**

**Comment by soumya-maheshwari** [comment]
@pranjay-poddar  please assign this issue to me.

**Comment by Adarsh9-dev** [comment]
Hello. Please assign me this issue. I have experience on URL Shortner project. Link:- https://urlconvertor.netlify.app
In this project I Use Node, MongoDb, Express, Redis, React, HTML, CSS.
