### ISSUE TITLE
Show password in Educational Course website

### ISSUE THREAD

**Issue by shraddha761** [pranjay-poddar/Dev-Geeks#2762]
**Describe the Feature you want to end**
In the educational website login/register do not have show password button 

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/106100728/5a8f762e-2ce6-4975-808b-223473586e61)

Assign this issue to me under GSSOC'23

**Comment by barsha511** [comment]
I would like to work on it .Please assign me this work@shraddha761

**Comment by shraddha761** [comment]
@MohitGupta121 please assign this issue to me
