### ISSUE TITLE
Google Search Engine Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [pranjay-poddar/Dev-Geeks#289]
**Describe the project you want to add to tech stack**
Google Search Engine Clone using React JS with the help of context API

**Expected behavior**
It will work like a real search engine & works on mobile-responsive

**Screenshots (optional)**
![Screenshot (1352)](https://user-images.githubusercontent.com/73753957/181172407-eac45dba-52c1-434b-aa79-7771869b0232.png)

**Additional context (optional )**

Deployed Link: https://google-clone-seven-ebon.vercel.app/

**Comment by gurjeetsinghvirdee** [comment]
@pranjay-poddar

**Comment by pranjay-poddar** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/google-clone

Already exists
