### ISSUE TITLE
OPEN LINKS IN A NEW TAB

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#2927]
**Describe the Feature you want to end**
The links are opening in the same tab

**Expected behavior**
Links should open in a new tab

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/9e8a1d8b-d009-44fe-8d5b-4a6968795655)

**Additional context (optional )**

**Comment by abansal15** [comment]
hello , i would like to work on the issue could you please assign it to me ?

**Comment by sunny06a** [comment]
i would like to work on the issue

**Comment by abansal15** [comment]
Hello @sunny06a i am also a contributor and raised this issue first so you can go can search for the another issue.
