### ISSUE TITLE
Screen recorder application 

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#293]
**Describe the project you want to add with tech stack**
An application which records screen and you can stop the recording and download the video too.

**Expected behavior**
Its sole purpose is to record the screen . 
Tech stack includes
- HTML
- CSS 
- JS
- screen capture API

**Screenshots (optional)**
![164353747-f298c34b-64f0-4b3f-ae1f-49a73d4ca936](https://user-images.githubusercontent.com/91176055/181228870-cb364a7e-5138-42e4-9453-395141a1cd3d.png)
![164353779-27cdbbd8-6df1-4c8d-bcce-39ff1480a800](https://user-images.githubusercontent.com/91176055/181228911-9065d664-9ff4-4bd4-a0ac-a3f4b087f61a.png)

**Comment by srinjoy-26** [comment]
Please assign me @pranjay-poddar

**Comment by srinjoy-26** [comment]
Please assign me @pranjay-poddar

**Comment by palakag29** [comment]
@MohitGupta121 @TusharKesarwani Can this issue be assigned to me? Its open for some time!
