### ISSUE TITLE
Bullseye Game

### ISSUE THREAD

**Issue by uzmaansari23** [pranjay-poddar/Dev-Geeks#2966]
**Describe the project you want to add with tech stack**
It is a simple game based on html, css and javascript where player have to draw back an arrow and launch it to hit the target.
**Expected behavior**
As the arrow hit the target the points will increase and if it doesn't the score will remain as it is.   

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/113499701/4dfeb66d-c604-49d9-8fcb-a53380936884)

**Additional context (optional )**

**Comment by uzmaansari23** [comment]
Please assign me this issue under Gssoc'23.

**Comment by uzmaansari23** [comment]
@MohitGupta121 please add the labels.

**Comment by MohitGupta121** [comment]
@uzmaansari23 make pr
