### ISSUE TITLE
Basketball Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [pranjay-poddar/Dev-Geeks#2976]
**Describe the project you want to add with tech stack**

It has a basket at a fixed position and a ball is given at various angles at various times. The player has to throw the ball into the basket and earn points. I will be using HTML ,CSS,JS

**Expected behavior**

Everytime the player accurately throws the ball into the basket, he earns 1 point.

**Screenshot**

![Screenshot 2023-07-04 103843](https://github.com/pranjay-poddar/Dev-Geeks/assets/111994644/f017f5b9-9c46-4a6c-983f-b65bcaeeb58d)

**Comment by Vyshnavi21504** [comment]
Please assign this issue to me @MohitGupta121, @pranjay-poddar, @Saurabh-kumar09 & @TusharKesarwani.

**Comment by Vyshnavi21504** [comment]
I have completed this issue.pls check it @MohitGupta121

**Comment by Vyshnavi21504** [comment]
pls merge it @MohitGupta121

**Comment by MohitGupta121** [comment]
What @Vyshnavi21504 ?

**Comment by Vyshnavi21504** [comment]
can u check it now @MohitGupta121

**Comment by MohitGupta121** [comment]
No PR is linked to this issue what I'll check? @Vyshnavi21504
