### ISSUE TITLE
Add flappy bird game to JS games folder

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#299]
**Describe the project you want to add with tech stack**
HTML, CSS, JS

**Expected behavior**
A simple game where a flying bird avoids obstacles

**Additional context (optional )**
simple but beautiful layout

**Comment by Subha-5** [comment]
@pranjay-poddar please assign me this issue

**Comment by Subha-5** [comment]
Hello @pranjay-poddar , I am also participating in hacktoberfest 2022, so can i contribute in this issue I created last time ?

**Comment by pranjay-poddar** [comment]
yes
