### ISSUE TITLE
Countdown-Timer

### ISSUE THREAD

**Issue by Shreyans2004** [pranjay-poddar/Dev-Geeks#2996]
**Describe the project you want to add with tech stack**

In this project user can give input of any date and automatically he/she would be able to see the Time left for the date.It is like a countdown-timer. Can you assign this task to me?
**Expected behavior**

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/c1037e6b-998b-4245-b837-3075ecda5591)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/4bc6c9b1-b816-439d-9b4b-f7155ad9811a)

**Additional context (optional )**

**Comment by Shreyans2004** [comment]
@MohitGupta121 Can you assign this take to me?

**Comment by Mohsinkkk** [comment]
assign me this project......
