### ISSUE TITLE
PHP web messenging app

### ISSUE THREAD

**Issue by rohanmittal1163** [pranjay-poddar/Dev-Geeks#3006]
**Describe the project you want to add with tech stack**
@pranjay-poddar 
I am eager to add a brand new php project in your github repo.
Tech stack : html, CSS, JS, PHP, Mysql

**Expected behavior**
This project helps you to communicate with your loved ones across the worl in a millisecond and express your emotions

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/670b58be-97f9-46c6-ba18-fedf143aad9f)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/ccc66225-f977-415a-b668-02ebf754158e)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/d9a716b8-6aeb-4728-9d09-b8e4979467a7)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/926e6769-bbe8-4864-9ea8-3ab8a6f529c8)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97821844/076365c3-be16-46aa-8432-5737c80d43ae)

**Additional context (optional )**
 @pranjay-poddar 
pls assign this issue to me  under GSSOC'23 as a contributor.
thank you

**Comment by Ashutosh0120** [comment]
Lol, I am not project admin, please remove my name.
@rohanmittal1163
