### ISSUE TITLE
Flutter tic tac toe game

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3023]
**Describe the project you want to add with tech stack**
This would be a flutter game where the user can play the tic-tac-toe with the computer. The screen would consist of a game interface, along with an info panel which would display the computer and the user's scores, the time left, and so on. 

Tech stack: Flutter

**Expected behavior**
- Splash screen to greet the user
- The user can start playing the game by pressing the relavant button. 
- As the game starts, the scores of player the computer would be displayed and would be updated as and when requird.
- It would also contain a timer, so that it would place a constraint to the player.

**Comment by jaivsh** [comment]
Please assign this issue to me @MohitGupta121, @pranjay-poddar, @Saurabh-kumar09 & @TusharKesarwani.

**Comment by Simran211103** [comment]
Please assign me this issue I would love to work on it. I am a GSSOC'23 contributor.
