### ISSUE TITLE
Customized quiz

### ISSUE THREAD

**Issue by Shreyans2004** [pranjay-poddar/Dev-Geeks#3035]
**Describe the project you want to add with tech stack**

The Project contains a customized quiz. You can First put questions and their answers and then the quiz will automatically  form. Can you assign this task to me?
User can enjoy the quiz and at last his/her score will be declared.
**Expected behavior**

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/973d2ee0-126f-4d50-aaaa-2453bd4c2919)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/768999c1-59e3-4339-bfa0-6c441b31ddec)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/97de772d-0fa7-4701-877c-34337fe73937)

**Additional context (optional )**

**Comment by Shreyans2004** [comment]
@MohitGupta121 Can you please assign this task to me?

**Comment by Simran211103** [comment]
Please assign me this issue I would love to work on it. I am a GSSOC'23 contributor.
