### ISSUE TITLE
[GSSoC'23] ChatBot App

### ISSUE THREAD

**Issue by shubhanshurav** [pranjay-poddar/Dev-Geeks#3037]
**Describe the project you want to add with tech stack**
Hey @pranjay-poddar, I want to add ChatBot App. so please assign me this issue.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/87806305/217a9891-0aff-4420-a21c-fe8efcfbf3af)

**Comment by shubhanshurav** [comment]
Hey @pranjay-poddar, please assign me this issue under GSSoC'23.

**Comment by Simran211103** [comment]
Please assign me this issue I would love to work on it. I am a GSSOC'23 contributor.
