### ISSUE TITLE
[GSSOC'23] Dictionary website 

### ISSUE THREAD

**Issue by vishnuprasad2004** [pranjay-poddar/Dev-Geeks#3038]
**Describe the project you want to add with tech stack**
A dictionary website uses HTML, CSS, and Javascript with a dictionary API.

**Expected Behavior**
It will provide the searched words: 
- meaning 
- parts of speech
- pronunciation.

**Comment by Simran211103** [comment]
Please assign me this issue I would love to work on it. I am a GSSOC'23 contributor.
