### ISSUE TITLE
Stickman Game

### ISSUE THREAD

**Issue by uzmaansari23** [pranjay-poddar/Dev-Geeks#3075]
**Describe the project you want to add with tech stack**
It is a simple game based on html, css and javascript. Goal of the game is to get to the other end of the canvas or kill the enemy.

**Expected behavior**
Hold spacebar to throw sword further!
While the sword is flying you can throw knives with spacebar!
Arrow keys to move!

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/113499701/51116324-6a14-455f-b95a-8a31bea798da)

**Additional context (optional )**

**Comment by uzmaansari23** [comment]
@MohitGupta121 please add the labels.

**Comment by MohitGupta121** [comment]
@uzmaansari23 make PR there will add lables
