### ISSUE TITLE
Customer Loan Repayment Prediction

### ISSUE THREAD

**Issue by Avik-creator** [pranjay-poddar/Dev-Geeks#316]
**Describe the project you want to add with tech stack**
* It will be a ML project which will predict customer loan repayment.
* Here we will use basic ML. 
* It will have Data Visualisation and Models Accuracy Score.

**Comment by Avik-creator** [comment]
@pranjay-poddar Please assign me this.

**Comment by Avik-creator** [comment]
@pranjay-poddar it must be level 3. Is it not?

**Comment by pranjay-poddar** [comment]
Can you please describe it more, from the description provided level will be assigned.

**Comment by Avik-creator** [comment]
So in this issue we will have eda of the dataset. It will be a ML problem which will predict how many people will pay the loan.

**Comment by Avik-creator** [comment]
@pranjay-poddar

**Comment by pranjay-poddar** [comment]
@Avik-creator okay go ahead
