### ISSUE TITLE
Andrew Tate themed card template

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3162]
**Describe the project you want to add with tech stack**
- This project is about a card template designed using html and css which is based on Andrew Tate, a social media influencer and an American kickboxer. 
- It would be a themed template card which can be used in profile displays. 
- It would be fully responsive for all devices. 

**Screenshots (optional)**

![maxresdefault](https://github.com/pranjay-poddar/Dev-Geeks/assets/93859359/dba7e4c4-060c-4d17-a934-a3194c4793d2)

**Comment by jaivsh** [comment]
Hi @MohitGupta121 @pranjay-poddar please review this issue and assign to me. Thanks!

**Comment by TusharKesarwani** [comment]
Card template is already present in the repo
