### ISSUE TITLE
College attendance tracker app using python

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3163]
**Describe the project you want to add with tech stack**
I'd design a college attendance tracker in python, which would send students personalized mails in case they miss their class. 
 

**Expected behavior**

- The input to this system is an excel sheet containing the students’ mail-id and their number of leaves in each class subject.
- It would send out an email message to student's gmail reminding that the student has taken one more leave.
- The same sheet can be input again and again, causing modifications to be noticed and tracked.

**Comment by jaivsh** [comment]
Hi @MohitGupta121 @pranjay-poddar please review this issue and assign to me. Thanks!

**Comment by N0529** [comment]
Can u send me the project
