### ISSUE TITLE
[GSSoC'23] : Add js projects website

### ISSUE THREAD

**Issue by palakag29** [pranjay-poddar/Dev-Geeks#3171]
**Describe the Feature you want to end**
Add a website which contains all the js projects available in the repo. Additionally I also want to delete the same projects (like there are 2 text editor projects). 

**Expected behavior**
It can be included in the dev-geeks website. And others can see what js projects are there in repo. 

**Additional context (optional )**
Done using html css js

**Comment by palakag29** [comment]
@MohitGupta121 @TusharKesarwani please assign me this issue

**Comment by Manish12-verma** [comment]
please ,assign this issue to me

**Comment by palakag29** [comment]
> please ,assign this issue to me

You can look for a new issue

**Comment by palakag29** [comment]
hey @MohitGupta121 
Can i delete the same projects?? Please tell so that i can proceed
