### ISSUE TITLE
Stopwatch[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#3178]
**Describe the project you want to add with tech stack**

### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Stopwatch⏰** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of **HTML,CSS & JS**. 
**Expected behavior**

### Description
It has  buttons with start, reset and pause . It also shows  hour, minute, second & millisecond⏱️.

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114172928/3de28b16-4e0c-4259-a01d-a9a744380446)

**Additional context (optional )**

Please **Assign** me the issue🙏

**Comment by apu52** [comment]
@Killer2-O I have checked that .But If possible please assign me this. So that I can contribute my exclusive work

**Comment by Neha626177** [comment]
Please assign me this project 
 Thank You!
