### ISSUE TITLE
Coffee Machine Web Animation[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#3179]
**Describe the project you want to add with tech stack**

### Hello  sir👋,
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Coffee Machine**☕ project under GSSoC'23.😁We all are coffee-lovers So, I have made a **web -animation of Coffee-machine** with the use of HTML & CSS.

**Expected behavior**
### Description

It is a simple Coffee-maker where you can see the one cup holding coffee, the coffee releasing point, button.☕

**Screenshots (optional)**

https://github.com/apu52/Webanimation/assets/114172928/973a4001-8e02-408c-939b-8fe9e1d2d522

**Additional context (optional )**

Please **Assign** me the issue🙏

**Comment by apu52** [comment]
@Killer2-O I have checked that .But If possible please assign me this. So that I can contribute my exclusive work

**Comment by apu52** [comment]
I am not copying from others & I have made it my own .Please assign me.

**Comment by apu52** [comment]
@pranjay-poddar @MohitGupta121 Please assign me this web animation Project under GSSoC'23.

**Comment by TusharKesarwani** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Cofee%20shop%20website

**Comment by apu52** [comment]
> https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Cofee%20shop%20website

I am not making any website, I want to make an snimation

**Comment by apu52** [comment]
**Screenshots (optional)**

https://github.com/apu52/Webanimation/assets/114172928/973a4001-8e02-408c-939b-8fe9e1d2d522

**Comment by apu52** [comment]
I will add this as my project, a web animation,please open the issue & assign me please 🙏@TusharKesarwani @MohitGupta121 @pranjay-poddar
