### ISSUE TITLE
Unit_Converter[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#3180]
**Describe the project you want to add with tech stack**

### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **Unit Converter** project under GSSoC'23.😁We all use this most used mobile application. I have made it with the use of HTML,CSS & JS.

**Expected behavior**

### Description
I have made a very basic Unit Converter where it just changes **foot to inch** & Vice-versa. Anyone can input integer or decimal. & there is also a up🔼 & down 🔽arrow. 

**Screenshots (optional)**

https://github.com/apu52/Unit-converter/assets/114172928/0b4d16dc-fbf8-4e7a-a63e-04bdb624aa18

**Additional context (optional )**

Please **Assign** me the issue🙏

**Comment by apu52** [comment]
@Killer2-O I have checked that .But If possible please assign me this. So that I can contribute my exclusive work

**Comment by TusharKesarwani** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Unit%20Converter

**Comment by apu52** [comment]
> https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Unit%20Converter

I want to make a different unot converter which changes inch to foot & viceversa & it also have up & down arrows.

**Comment by apu52** [comment]
**Screenshots (optional)**

https://github.com/apu52/Unit-converter/assets/114172928/0b4d16dc-fbf8-4e7a-a63e-04bdb624aa18

**Comment by apu52** [comment]
Like this @TusharKesarwani @MohitGupta121 @pranjay-poddar please reopen the issue so that I can contribute to this issue 🙏🙏🙏🙏🙏
