### ISSUE TITLE
Hotstar Clone[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#3181]
**Describe the project you want to add with tech stack**

### Hello Sir ,👋
I am Arpan Chowdhury, a aspiring Web developer.🤖 I want to add my **HOTSTAR Clone**📺 project under GSSoC'23.😁We all use this most used steaming Platform. I have made it with the use of HTML,CSS & JS.

**Expected behavior**

It is basically the landing Page of HOTSTAR application where you can see

- Subscribe, login , search bar🔎
- Some cards of the popular series
- Some small animations🦊
- Some cards of popular shows

**Screenshots (optional)**

# Screenshots
![hotstar](https://github.com/apu52/HotstarClone/assets/114172928/172d232d-a052-446d-bb7c-15396e918fa3)

# Video
https://github.com/apu52/HotstarClone/assets/114172928/0e0cf7e7-5509-4170-9a3a-adc53583929a

**Additional context (optional )**

Please **Assign** me the issue🙏

**Comment by apu52** [comment]
@Killer2-O I have checked that .But If possible please assign me this. So that I can contribute my exclusive work

**Comment by TusharKesarwani** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/Hotstar%20clone
