### ISSUE TITLE
Added animated footer

### ISSUE THREAD

**Issue by Shreya111111** [pranjay-poddar/Dev-Geeks#3229]
**Describe the project you want to add with tech stack**

Adding animated footer which consists of social icons and wave animation
**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

plz assign me under gssoc'23

**Comment by Shreya111111** [comment]
@MohitGupta121 kindly assign this issue to me under gssoc'23

**Comment by Kajal2468** [comment]
I want to work on the issue please assign it

Thank You!
