### ISSUE TITLE
Character counter 

### ISSUE THREAD

**Issue by SimranLahrani842** [pranjay-poddar/Dev-Geeks#3233]
**Describe the project you want to add with tech stack**

Project aims to create a real-time character counter using JavaScript. It features a text area container that displays both the total character count and remaining character count of 50. As users type, the total character count dynamically increases, and the remaining character count decreases. The text area locks once the limit of 50 characters is reached, and the remaining character count becomes zero. With this functionality, users can keep track of their remaining characters and be alerted when they hit the character limit.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SimranLahrani842** [comment]
> **Describe the project you want to add with tech stack**
> 
> Project aims to create a real-time character counter using JavaScript. It features a text area container that displays both the total character count and remaining character count of 50. As users type, the total character count dynamically increases, and the remaining character count decreases. The text area locks once the limit of 50 characters is reached, and the remaining character count becomes zero. With this functionality, users can keep track of their remaining characters and be alerted when they hit the character limit.
> 
> **Expected behavior**
> 
> **Screenshots (optional)**
> 
> **Additional context (optional )**

Assign me this @MohitGupta121 @pranjay-poddar

**Comment by MohitGupta121** [comment]
Already havee
