### ISSUE TITLE
Theme_changing_Calculator

### ISSUE THREAD

**Issue by ShreyashHatkar** [pranjay-poddar/Dev-Geeks#3241]
Hello, I am Shreyash and creating this issue under **:GSSOC:** and **:Level3:**

**Tech stack**
-Html -CSS -JS

**Expected behavior**
A simple calculator with toggle switch to change into three different type of themes.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90668713/c3dd2b47-4b8b-400d-aef2-ae3d841d9638)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90668713/a7ff7a05-4265-4656-8315-a56a20a4a3f8)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90668713/c3b8e94a-f212-49e9-9a0b-b9068322f3dd)

**Comment by TusharKesarwani** [comment]
Try to implement features in already existing calculators
