### ISSUE TITLE
raising issue to contribute the frontend web-page design of an e-commerce website. 

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3250]
**I want to add the webpage of an ecommerce website as my contirbution** 

**The website design can be used for making other projects and real-world applications. **

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Sidhupaji-2004** [comment]
Kindly assign this issue to me. I'm a contributor and participant of GSSOC 2023.

**Comment by TusharKesarwani** [comment]
Already in the repo
