### ISSUE TITLE
Todo application --- named TaskTrek

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3251]
**This is a todo application named tasktrek. 

 Techstack: HTML 5, CSS 3, Javascript
 Beginner friendly for contributors.  
**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Sidhupaji-2004** [comment]
Please assign me this issue. I'm a gssoc 2023 participant and contributor. It would be really helpful if you could assign me this issue.

**Comment by TusharKesarwani** [comment]
Already in the repo
