### ISSUE TITLE
Add Temperature Converter Project

### ISSUE THREAD

**Issue by blindaks** [pranjay-poddar/Dev-Geeks#3362]
**Describe the project you want to add with tech stack**
This temperature converter project uses front-end web technologies: HTML, CSS, and JavaScript.

**Expected behavior**
This website converts temperature to and from Celsius, Fahrenheit, and Kelvin.

**Screenshots (optional)**

![Screenshot (24)](https://github.com/pranjay-poddar/Dev-Geeks/assets/128223364/8f7c488b-714b-4575-9036-c5184e305c96)
![Screenshot (25)](https://github.com/pranjay-poddar/Dev-Geeks/assets/128223364/e3f92f1c-376b-4304-a7ed-832a58da57f4)

**Comment by blindaks** [comment]
@pranjay-poddar Please assign this issue to me.
#GSSOC'2023

**Comment by Akshat162001** [comment]
done by me

**Comment by blindaks** [comment]
@TusharKesarwani Please review this pull request.
