### ISSUE TITLE
Banker website --- frontend projects --- changing color of text in operations tab. 

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3369]
**Changing color of text to black from whitish-grey for better readablility in grey background**

**Comment by Sidhupaji-2004** [comment]
Sir can you please assign this issue to me. I'm a GSSOC 2023 Participant and contributor.

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
