### ISSUE TITLE
create a Diary Application

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#337]
**Describe the project you want to add with tech stack**
simple diary to add/delete entries made using HTML, CSS & JS

**Expected behavior**
Simply create, read, update and delete entries

**Additional context (optional )**
The aim of this project is to act as a substitute for physical diary in real world and since it is a web based application it is easily accessible by user

**Comment by Subha-5** [comment]
@pranjay-poddar please assign me this issue

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
Kindly provide me the opportunity to work on the issue.
