### ISSUE TITLE
Navbar in anime pics generator -- frontend projects

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3370]
**Navbar in anime pics generator website**

**Users will be able to navigate to sign up page and can create their own account . The website will be responsive since bootstrap will be used.**

**Comment by Sidhupaji-2004** [comment]
Sir can you please assign this issue to me. I'm a GSSOC 2023 Participant and contributor.

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
