### ISSUE TITLE
Bluetooth Chatting application Python

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3389]
**Describe the project you want to add with tech stack**
Through running this application, two bluetooth capable devices would be able to communicate and transfer messages through a socket channel. 
**Techstack :** Python, socket library

**Expected behavior**
- There would be a client and a server. 
- The client can connect to the server.
- After connection, they can exchange messages.

**Comment by GeekAvi007** [comment]
I would like to work on this project please assign it to me
