### ISSUE TITLE
Add a new frontend webpage

### ISSUE THREAD

**Issue by Subho0710** [pranjay-poddar/Dev-Geeks#34]
**Describe the project you want to add with tech stack**

A simple front end webpage using HTML and CSS

**Expected behavior**

Different webpage contents including home, form, games, etc.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by samyaksand** [comment]
Please assign me this issue.

Can I add my spotify clone project that I am making? 
It uses HTML, CSS, and Javascript, and I will also add a demo video and screenshots.

**Comment by PriyanshuGarg26** [comment]
Can you assign it to me. I want to add some projects.

**Comment by sumitbaroniya** [comment]
@pranjay-poddar please assign me this issue
