### ISSUE TITLE
Devgeeks Website - Navbar improvement and font size adjustment of Links

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3418]
**Adding icons to the navbar and a 'more' icon and changing the font-size of the links section since it's looking too large.**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/116648570/34a79535-5e45-4489-aa58-699c79d17011)

**Comment by Akshat162001** [comment]
Please asssign to me

**Comment by Akshat162001** [comment]
Just need to push ..I have already done

**Comment by Akshat162001** [comment]
i.e, and want to create the pull request for it

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
