### ISSUE TITLE
[GSSoC'23] [Docs] Adding a small Licenses section to the readme and a MIT Licenses badge

### ISSUE THREAD

**Issue by 1Shubham7** [pranjay-poddar/Dev-Geeks#3437]
**Describe the Feature you want to end**
The readme doesn't have any info about Licenses, I can add a small Licenses section
and a MIT badge

![afters](https://github.com/pranjay-poddar/Dev-Geeks/assets/116020663/654f875f-cd89-4c2d-9251-b276cd0c308b)

**Additional context (optional )**
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by TusharKesarwani** [comment]
Not required
