### ISSUE TITLE
Word Counter ---- React JS project.

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3439]
**Word counter using React.**

**The client-side application counts the number of words and characters and helps in converting the text to lower case and uppercase .It also clears text when required. It also estimates the amount of time required to read the text.**

**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/116648570/d6a46239-dfa9-41ba-a05f-8199317f03dc)
**

**Useful for teachers who need to check word limits while checking online pdfs. More additional functionalities will be added.**

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time

**Comment by sagargoyal-bit** [comment]
Hey.. i want to work on this issue kindly assign it to me
