### ISSUE TITLE
unnecessary blue background ---- in Apple Watch Section --- Apple Ecommerce

### ISSUE THREAD

**Issue by Sidhupaji-2004** [pranjay-poddar/Dev-Geeks#3440]
**Unnecessary blue background on one of the watches in the apple watch carousel** 

**White background will replace the blue background.**

**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/116648570/46b3c19a-0a1f-4692-8e8e-c41e71ec8ffe)
**

**Additional context (optional )**

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
