### ISSUE TITLE
College CGPA Calculator Python

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3456]
I'd create a CGPA Calculator in python where the user would be able to see their CGPA out of 10 based on the individual pointer grades they obtained for each individual course.

**Expected behavior**

- User can enter their courses and grades
- Entry can be done either manually or in CSV format
- The script would calculate their CGPA and display it to the users

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
