### ISSUE TITLE
Adding more filters in "Web-Image filter" python project

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3457]
**Describe the Feature you want to add**

The Web-Image python project currently has only 3 filters: grayscale, blur, and sepia. I'd add a dozen more such features into the project, enhancing its capabilities. 

**Expected behavior**

The python app would have much more filters, including the brightness, exposure, and clarity enhancers.

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
