### ISSUE TITLE
Random-Color-Generator

### ISSUE THREAD

**Issue by Shreyans2004** [pranjay-poddar/Dev-Geeks#3466]
**Describe the project you want to add with tech stack**

The project generates different colors on clicking the button.It also displays the hexadecimal code of the generated color.It becomes easier for the user to get its favorite color by just pressing buttons. Can you assign this task to me?
**Expected behavior**

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/54c3b5a7-22fc-4511-a891-36ed1165a9bd)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/b9bb52fc-0527-4519-9426-70d95095487c)

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/128773151/da9475cf-3b28-4659-ae8a-06e2ad1ec014)

**Additional context (optional )**

**Comment by Shreyans2004** [comment]
@MohitGupta121 Can you assign this task to me?

**Comment by MohitGupta121** [comment]
Already present
