### ISSUE TITLE
[B.Tech Tea Shop] Enhancing content and components to Contact Section

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#3497]
**Describe the Feature you want to end**
By adding components to make it attractive

**Expected behavior**
iT helps in increasing user experience better way.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,assign this to me.

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 please be sure that you add before and after screenshots in your PR to able to merge it.
