### ISSUE TITLE
[B.Tech Tea Shop] Enhancing Menu section

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#3498]
**Describe the Feature you want to end**
 By using css elements I can make it looking better

**Expected behavior**
This helps in user interface better structure

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,assign this to me.

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 please be sure that you add before and after screenshots in your PR to able to merge it.
