### ISSUE TITLE
[B.Tech Tea Shop] Adding related content to Review section

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#3499]
**Describe the Feature you want to end**
by using html and css it adds corresponidng content

**Expected behavior**
it helps the customers to know better

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,assign this to me

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 please be sure that you add before and after screenshots in your PR to able to merge it.
