### ISSUE TITLE
[B.Tech Tea Shop] Adding content to Blog Section

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#3500]
**Describe the Feature you want to end**
Using html and adding content relatable

**Expected behavior**
this helps to know more about the website and products quality

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly, assign this to me.

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 please be sure that you add before and after screenshots in your PR to able to merge it.
