### ISSUE TITLE
[Bus route booking system] "Home page" section styling

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#3503]
**Describe the Feature you want to end**
using css styling elements it can seem better to visualise

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,assign this to me.

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 Please add Before and After changes in your PR to able to merge it.
