### ISSUE TITLE
[GSSOC'23]: Algorithm learner using c++

### ISSUE THREAD

**Issue by Nikita06211** [pranjay-poddar/Dev-Geeks#3524]
**Describe the project you want to add with tech stack**
The project will help users understand various DSA algorithms 

**Expected behavior**
A brief explanation of the algorithms along with display of working will be added for better understanding.
Algorithms included-:
1. Sorting Algorithms-:
   i. Bubble Sort
   ii. Insertion Sort
   iii. Selection Sort
3. Searching Algorithms
   i. Linear Search
   ii. Binary Search

**Comment by Nikita06211** [comment]
@MohitGupta121 sir kindly assign me this issue

**Comment by Ash0069** [comment]
@MohitGupta121 please assign me this issue

**Comment by Ash0069** [comment]
please assign me this issue
