### ISSUE TITLE
[CHORE]: UPDATING CLOSE MULTIPLE ISSUES WORKFLOW 🔐

### ISSUE THREAD

**Issue by 0xabdulkhalid** [pranjay-poddar/Dev-Geeks#3559]
### Description
- There is a workflow for closing multiple issues opened by the contributor if he/she creates more than one issue at time.
- Currently this is not implemented as we intended due to lack of `PERSONAL_ACCESS_TOKEN` from Pranjay Podder
- So i'm willing to update the codebase of workflow to just close those issues as a Github Bot.
- The Github Bot will can manage those things, i'm changing the PA's ID into Github Bot ID.
- After this issue is closed **we can assure that this feature will must work without any `PERSONAL_ACCESS_TOKEN`**.

**Comment by 0xabdulkhalid** [comment]
Hey there @MohitGupta121, I want to update the code so that it doesn't need PA's Token.

It can do the Job as Github Bot.

Please assign this issue to me to make the work done!

**Comment by MohitGupta121** [comment]
@0xabdulkhalid okay thanks go ahead.
