### ISSUE TITLE
Notes app

### ISSUE THREAD

**Issue by Asttttha** [pranjay-poddar/Dev-Geeks#356]
Notes app using html, css, js. 

**Expected behavior**
You can write your notes and store in here with date and time. 

Please assign.

**Comment by jaypansuriya104** [comment]
Notes app using html ,css ,js 

special characterise : add notes to you local storage 

I am interested to do contribution please assign me !!

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar  I am Intersted to Contribute in it pls assign me if its available

**Comment by ruchagosavi** [comment]
@pranjay-poddar I have solution for this issue please assign me!!
