### ISSUE TITLE
Add Project "Countdown Animation"

### ISSUE THREAD

**Issue by Rakesh9100** [pranjay-poddar/Dev-Geeks#359]
**Describe the project you want to add with tech stack**

I want to add a Countdown which is animated.

**Expected behavior**

It is well-designed to be used in large timed and countdown projects.

**Comment by Rakesh9100** [comment]
Hey bro The project should be Level 2 I believe since Level 1 are Documentation Like Readme Editing, Fix typo and so on. @pranjay-poddar

**Comment by pranjay-poddar** [comment]
countdown animation will be considered in level one only it can be implemented very easily with js libs.

**Comment by Rakesh9100** [comment]
> countdown animation will be considered in level one only it can be implemented very easily with js libs.

Okay
