### ISSUE TITLE
Add responsive navbars

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#36]
Add responsive navbars with animations

**Comment by nawed2611** [comment]
Hey! Is this issue open?

**Comment by pranjay-poddar** [comment]
@nawed2611 yes

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar pls assign me this issue, I wanted to work on it

**Comment by sumitbaroniya** [comment]
@pranjay-poddar can you please me this issue, I wanted to work on it

**Comment by bleep123** [comment]
I would like to work on this issue. Can you please assign this issue to me. @pranjay-poddar

**Comment by purviporwal0** [comment]
can you pls assign this to me as I would love to create responsive nav bars

**Comment by Developer-Swati** [comment]
Hello @pranjay-poddar this is my first open source contribution . I have some basic knowledge of HTML, CSS, JS. So, please give me my first chance to start my journey in open source . It will be appreciatable.
Thanks

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me

**Comment by Tanishashrivas** [comment]
I am a contributor in gssoc'23. I would like to work on this issue. Please assign this to me.

**Comment by Shivam-Batham** [comment]
Please **assign me this issue to me uder Gssoc23**

**Comment by abhi03ruchi** [comment]
Hi @pranjay-poddar, I would like to work on this issue. I have a decent level of knowledge of HTML, CSS and javascript. And currently, I am learning react js. Plz, assign it to me.

**Comment by Vaibhav-Sharma010204** [comment]
Hello @pranjay-poddar 
kindly Please assign this issue to me

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me

**Comment by pjyoti121** [comment]
Please assign me this issue under gssoc23
