### ISSUE TITLE
Medical Encyclopedia Scraper in Python

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3615]
**Describe the project you want to add with tech stack**
I'd add a medical encyclopedia project in ```python projects``` which web-scrapes data from the mediline. The structure of the project is such that:
- There is a class having various end-user accissable functions. 
- The user can use these functions in order to get the relevant data from the medical encyclopedia.  

**Expected behavior**
>The user would use the accessable functions from the Encyclopedia class to get their desired data from the website. The data would include the medical terms, their definitions and related information, their formation genesis information, and so on.  

**Additional context (optional )**
This project can easily be used by other python projects who would want to have this feature by just importing the class.

**Comment by jaivsh** [comment]
Hi @MohitGupta121 plaese assign me this!

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
