### ISSUE TITLE
AI image generator in python

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3616]
**Describe the project you want to add with tech stack**
The user would describe about their required image taken as string input. Based on their description, a bunch of AI-generative images would be generated, which would be then returned to the user. The project would also have a "saving" option to save a particular image locally. 

Tech-stack: OpenAI, python

**Expected behavior**
- User provudes a descriptive input about the image.
- Based on the user's input, an AI image is created. 
- Bunch of such relevant images are created, and then returned to the user
- The user can save these images

**Comment by jaivsh** [comment]
@TusharKesarwani plaese assign me this! @MohitGupta121

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
