### ISSUE TITLE
Cubula Javascript Game

### ISSUE THREAD

**Issue by jaivsh** [pranjay-poddar/Dev-Geeks#3617]
**Describe the project you want to add with tech stack**
```In this game, the view of a cube is given which consists of 27 (3x3x3) smaller cubes. Each of them is either black or white (dark or light). The cubes are semi-transparent: If the player looks at a position where all cubes are white then it looks white, white and black cubes together look gray and a position where all cubes are black looks black. The view (from all 6 sides) of the large cube is displayed on the right side. The player's task is to find out the colors of the smaller cubes. First they would choose a color by interacting with the game UI and after that click on the fields which (the player thinks) has the same color. If the player makes a mistake, then the game is over. The game is solved when the colors of all fields are found out.```

**Tech stack:** HTML, CSS, Bootstrap, Javascript

**Screenshots (optional)**

![](https://user-images.githubusercontent.com/93859359/253682888-9e50624c-7ffd-458b-a96f-079571e396a8.png)

**Additional context (optional )**

**Comment by jaivsh** [comment]
hi @MohitGupta121 @TusharKesarwani please assign me this!

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time
