### ISSUE TITLE
[GSSOC'23]: Password Generator using C++

### ISSUE THREAD

**Issue by Nikita06211** [pranjay-poddar/Dev-Geeks#3622]
**Describe the project you want to add with tech stack**
A random password generator using c++

**Expected behavior**
The project will have following features-:
1. Password Length Control
2. Password Complexity Options (high, medium, low)
3. Password customization : user can give certain characters out of which password will be generated
4. customized password strength indicator

**Comment by Nikita06211** [comment]
@MohitGupta121 sir kindly assign me this issue

**Comment by sd-indic** [comment]
@MohitGupta121 I would like to work on this mini project as a part of GSSOC'23, you may count me in as well 🙂
