### ISSUE TITLE
Face Recognition 

### ISSUE THREAD

**Issue by Avik-creator** [pranjay-poddar/Dev-Geeks#365]
It will be made using OpenCV. It will create a blue rectangle around the face.

**Comment by Avik-creator** [comment]
@pranjay-poddar please assign me this

**Comment by Avik-creator** [comment]
@pranjay-poddar it will be level 3 sir. It will made using open cv. It will detect face sir.

**Comment by srinjoy-26** [comment]
@Avik-creator I have already done this , I had also integrated some cool filters along with face recognition
