### ISSUE TITLE
Frontend Project "Project_Tracking_Intro_Component" Homepage Buttons Styling

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#3667]
**Describe the Feature you want to end**
Working on the styling of the homepage buttons to improve their design.

**Expected behavior**
Improved design of the buttons.

**Screenshots (optional)**

Current Design
![ip (11)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/471ee855-14f0-47b4-b3ed-357f99d519f8)

Expected Updated Design
![ip (9)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/ea003aaf-9cff-4bae-a9a4-836f6031a9c7)

**Additional context (optional )**
N/A

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly assign me this issue.

**Comment by TusharKesarwani** [comment]
Do not make more than 5 issues at a time

**Comment by iamRabia-N** [comment]
> Do not make more than 5 issues at a time

@TusharKesarwani Kindly make this official in the group as well so that everyone will know this.
