### ISSUE TITLE
[GSSoC'23] : Add file reader

### ISSUE THREAD

**Issue by palakag29** [pranjay-poddar/Dev-Geeks#3680]
**Describe the project you want to add with tech stack**
File reader using js so that files can be read from web

**Expected behavior**
done using html css js

**Comment by palakag29** [comment]
@TusharKesarwani @MohitGupta121 Please assign me this issue

**Comment by ShrutiGossain** [comment]
I would like to work on this. Please assign this issue to me.

**Comment by palakag29** [comment]
I am already working on it. You can look for different issue
