### ISSUE TITLE
Add Responsive Footers

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#37]
Add responsive footers with different animations and stylings

**Comment by prachigarg19** [comment]
Please assign me this issue

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar 
please assign me this issue

**Comment by sumitbaroniya** [comment]
@pranjay-poddar please assign me this issue

**Comment by anjaliSilawat** [comment]
I would like to work on this issue @pranjay-poddar  please assign it to me

**Comment by bleep123** [comment]
I would like to work on this issue. Can you please assign this issue to me. @pranjay-poddar

**Comment by shineishukla** [comment]
Want to made the footer responsive. Can you please assign this issue to me. @pranjay-poddar
