### ISSUE TITLE
BLOOD DONATION CAMP

### ISSUE THREAD

**Issue by Nirvik07** [pranjay-poddar/Dev-Geeks#370]
# **Describe the project you want to add with tech stack**
## The objective of this project is as follows :
1. To make use of python and SQL in making a bloodbank
management system where individuals can give blood and
hospitals can request for blood from the blood bank.
2. To keep a record of how much blood is available for donation to
a hospital.
3. To make the blood donation and blood collection much more
simpler through use of python and SQL.

# **Expected behavior**
This project is useful for the blood bank employees, blood donors as well as hospital authorities to keep a track of the blood donation and withdrawal details. This project emphasises on creation of new blood donor and well as new hospital and nursing home accounts, managing the accounts of the existing account holders (donors/hospitals) in the blood bank, by making digital system one can check the details of the blood donated/withdrawn, hospitals can check availability of blood of required blood group and thus the system as a whole can cater a huge number of people or hospitals in times of urgent need.

# **Screenshots (optional)**
![Capture](https://user-images.githubusercontent.com/97960335/182210415-5e2d7bf7-2f1c-4bcb-b7a7-eeead0b6aa23.PNG)

**Additional context (optional )**

**Comment by Nirvik07** [comment]
@pranjay-poddar assign me this.

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Also I would like to do the same project using Java servlet (java and sql) and present it in the form of website.

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Also I would like to do the same project using Java servlet (java and sql) and present it in the form of website.

**Comment by Pavishnaam** [comment]
Kindly assign me this for GSSoC'23 @pranjay-poddar

**Comment by Pragati-3003** [comment]
Heyy @pranjay-poddar ,
I would like to contribute in this under GSSOC'23. 
Please assign this to me.

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me
