### ISSUE TITLE
Frontend Project "NFTCardComponent" Content Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#3713]
**Describe the Feature you want to end**
Changing few styling properties of the website to improve its alignment.

**Expected behavior**
Improved alignment of the content of website.

**Screenshots (optional)**

Current Design
![ip (15)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/24405516-0063-4de6-855f-39399c88474a)

Expected Updated Design
![ip (14)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/3b7edd5f-e1bc-414e-91ac-77294733ea3a)

**Additional context (optional )**
N/A

**Comment by ayushrathore111** [comment]
hii @iamRabia-N please assign this to me want to work with it...

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly assign me this issue.
