### ISSUE TITLE
Day & night mode Animation[GSSOC'23]

### ISSUE THREAD

**Issue by apu52** [pranjay-poddar/Dev-Geeks#3724]
**Describe the project you want to add with tech stack**

### Day & night mode animation
**Expected behavior**

Hello sir, 
I want to add day & night mode animation of a fox. I have made it using CSS.  
**Screenshots (optional)**

![Day   night fox img](https://github.com/pranjay-poddar/Dev-Geeks/assets/114172928/6a2bfeca-7820-41df-a741-782d82eee57a)

**Additional context (optional )**

I want to add this project under GSSOC'23. Please assign this

**Comment by apu52** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar Please assign me this issue under GSSOC'23.

**Comment by 0xabdulkhalid** [comment]
Hey there @apu52 please don't copy sources from online.

@gurjeetsinghvirdee for your verification, Here's the original source code: https://codepen.io/xinyashan1/pen/zYqgREr

Thank you.
