### ISSUE TITLE
Adding dark theme option in the main website of Dev-Geeks. [gssoc23]

### ISSUE THREAD

**Issue by thevirengarg** [pranjay-poddar/Dev-Geeks#3768]
**Describe the Feature you want to end**

I will add an option in the header of the main page of Dev-geeks website which when clicked will change the theme of the website.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Vermasushant144** [comment]
please asign this issue sir i want do work under Gssoc 23

**Comment by thevirengarg** [comment]
@MohitGupta121 @pranjay-poddar  please assign this issue to me

**Comment by thevirengarg** [comment]
> please asign this issue sir i want do work under Gssoc 23
@Vermasushant144 you need to raise your own issue
