### ISSUE TITLE
Add a website with space theme

### ISSUE THREAD

**Issue by PVBharadwaj** [pranjay-poddar/Dev-Geeks#3777]
**Describe the project you want to add with tech stack**
A website with all the space-related stuff. It uses HTML and CSS.

**Screenshots (optional)**

<img width="955" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/117581755/d768c899-15d4-4124-809d-9b49585149af">

**Comment by PVBharadwaj** [comment]
@MohitGupta121  please assign me this issue under gssoc'23

**Comment by MohitGupta121** [comment]
You make PR before assign it will be invalid sorry.
