### ISSUE TITLE
Add a Notes App Project

### ISSUE THREAD

**Issue by Rakesh9100** [pranjay-poddar/Dev-Geeks#378]
**Describe the project you want to add with tech stack**

I have created a project which helps to add many important Notes at one place.

**Expected behavior**

* We can add Different Notes Space Boxes in same website app and as many boxes we want.
* We can delete the particular Notes Space boxes by clicking on given delete button.

**Screenshots (optional)**

![1](https://user-images.githubusercontent.com/73993775/182461850-9bde8001-9016-4e0d-b3ee-d1fb0d0c3083.jpg)
![2](https://user-images.githubusercontent.com/73993775/182461856-28f5f77c-8cf5-4610-94f8-f36620c7f8c7.jpg)

**Comment by Avik-creator** [comment]
@pranjay-poddar @Rakesh9100 I have already made a similar project. It also does the same things that you have mentioned.

**Comment by Rakesh9100** [comment]
> @pranjay-poddar @Rakesh9100 I have already made a similar project. It also does the same things that you have mentioned.

I think there can be similar projects with different UI. Everyone is making their own with different styles and config.

**Comment by Avik-creator** [comment]
@Rakesh9100 I don't think that is the issue here. Mine and your project is providing the same functionality.
So according to the standards no one can give the same project again right? Even it is having a different "UI"
