### ISSUE TITLE
Add responsive and functional Dashboard

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#38]
Add responsive and functional Dashboard for user and admin.

**Comment by niyoj** [comment]
Can you assign this issue to me?

**Comment by Pavishnaam** [comment]
. Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

Kindly provide me the opportunity to work on the issue.@pranjay-poddar

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!
