### ISSUE TITLE
Protect Wildlife Website. 

### ISSUE THREAD

**Issue by Asttttha** [pranjay-poddar/Dev-Geeks#396]
A front end project, The goal of this website is to ensure the survival of wilds, and to educate people on living sustainably with other species, also donate for them.

**Comment by Asttttha** [comment]
Assign

**Comment by Petsamuel** [comment]
Assign

**Comment by Petsamuel** [comment]
pls reassign i'm working on it

**Comment by anjaliSilawat** [comment]
i would like to work on this @pranjay-poddar ,please assign it to me .

**Comment by anjaliSilawat** [comment]
i would like to work on this @Asttttha  ,please assign it to me .

**Comment by gkm0001** [comment]
I want to work on this issue @pranjay-poddar ,please assign me this issue.
