### ISSUE TITLE
WordCloud from Wikipedia 

### ISSUE THREAD

**Issue by Avik-creator** [pranjay-poddar/Dev-Geeks#399]
It will be made using python.

**Comment by Avik-creator** [comment]
@pranjay-poddar please assign me this

**Comment by Avik-creator** [comment]
@pranjay-poddar please assign me this

**Comment by pranjay-poddar** [comment]
Describe your project properly

**Comment by sagarmishra1103** [comment]
@pranjay-poddar can you tell me what will be happening in this project?
is there we have to access some lines from Wikipedia and print them to cmd or programs output?
if you describe it then I can work on them
