### ISSUE TITLE
UPDATING README

### ISSUE THREAD

**Issue by Death84L** [pranjay-poddar/Dev-Geeks#4]
Can I update something in README file to make it attractive ?

**Comment by pooja-sanap-53** [comment]
Can you assign this issue to me? Will get done by tomorrow itself.

**Comment by PoulasthaMukherjee** [comment]
@pranjay-poddar Please assign me this.

**Comment by manan1979** [comment]
@pranjay-poddar can you assign this to me i will make it much more attractive.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue
