### ISSUE TITLE
Stopwatch using python

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#403]
**Describe the project you want to add with tech stack**
    a stopwatch in python

![Screenshot 2022-08-06 110027](https://user-images.githubusercontent.com/91176055/183584605-7604c821-83be-4c4e-87b6-e5d318d14dce.png)

**Comment by srinjoy-26** [comment]
@pranjay-poddar please assign

**Comment by PayalPadmalyaPrusty** [comment]
@srinjoy-26 I want to contribute.Please assign me

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly assign me the issue.@pranjay-poddar

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me

**Comment by ARGHYADIPROY** [comment]
Hi! I am a  contributor under the GSSoC'23.I would like to contribute to this issue under the GSSoC'23. It seems interesting and I have the required skills. I would be happy to take it up and work on this project. Kindly assign me the issue.@pranjay-poddar

**Comment by Gun2902** [comment]
cab you assign me this issue

**Comment by IT-0824** [comment]
hello!! I would like to work on this interesting issue. looking forward for your response.
