### ISSUE TITLE
digital clock in python

### ISSUE THREAD

**Issue by srinjoy-26** [pranjay-poddar/Dev-Geeks#413]
**Describe the project you want to add with tech stack**
a digital clock in python.

**Expected behavior**
views time.

**Screenshots (optional)**
![Screenshot 2022-08-12 121449](https://user-images.githubusercontent.com/91176055/184299467-fec47eef-1958-4fd5-a321-5454e71e1087.png)

**Additional context (optional )**

**Comment by srinjoy-26** [comment]
@pranjay-poddar please assign me

**Comment by PayalPadmalyaPrusty** [comment]
@srinjoy-26 I want to contribute.Please assign me

**Comment by SNeha123o** [comment]
I want to contribute in this for GSSOC'23 . Please assign me

**Comment by pranjay-poddar** [comment]
This is already added
