### ISSUE TITLE
convert text to handwriting

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#416]
**Describe the project you want to add with tech stack**
Simple python project

**Expected behavior**
converts an inputted text to correspoding human handwriting

**Comment by Subha-5** [comment]
@pranjay-poddar please assign me this issue

**Comment by pranjay-poddar** [comment]
It is already assigned

**Comment by Subha-5** [comment]
@pranjay-poddar please review this issue for Hacktoberfest 2022
