### ISSUE TITLE
React Calculator

### ISSUE THREAD

**Issue by LovishMalhotra** [pranjay-poddar/Dev-Geeks#4294]
**Describe the project you want to add with tech stack**
React Calculator App

**Expected behavior**
Has calculator features made from React. Hooks are used to change the behavior of input.

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90837700/3ed1aa0c-7f66-492f-b65c-d7c27d443112)

**Additional context (optional )**

**Comment by LovishMalhotra** [comment]
@MohitGupta121 assign me this project

**Comment by MohitGupta121** [comment]
Too many calculators
