### ISSUE TITLE
Simon Says Game in cpp

### ISSUE THREAD

**Issue by Vineetg2003** [pranjay-poddar/Dev-Geeks#4319]
**Describe the project you want to add with tech stack**
This is a C++ command-line implementation of the classic Simon Says memory game. Simon will show a sequence of colors, and you need to repeat the sequence correctly to advance to the next level.
 
**Expected behavior**
Its is very interesting game for kids.

@MohitGupta121 @TusharKesarwani Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar  Sir kindly assigned me these issue

**Comment by MohitGupta121** [comment]
Spamming
