### ISSUE TITLE
Cache Simulator in cpp

### ISSUE THREAD

**Issue by Vineetg2003** [pranjay-poddar/Dev-Geeks#4320]
**Describe the project you want to add with tech stack**
I want to make a C++ command-line implementation of a cache simulator that demonstrates how cache memory works with different cache configurations..

**Expected behavior**
Its is very helpful to know how cache memory distributed.

@MohitGupta121 @TusharKesarwani Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar  Sir kindly assigned me these issue

**Comment by MohitGupta121** [comment]
Spamming
