### ISSUE TITLE
Improve the front end part of Game website

### ISSUE THREAD

**Issue by deepshikha2708** [pranjay-poddar/Dev-Geeks#436]
**Describe the Feature you want to end**
change the font and colour and background image

**Expected behavior**

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/80972038/187185059-34174541-6103-4d90-bc67-72ab3a6aa74d.png)

**Additional context (optional )**

**Comment by deepshikha2708** [comment]
@pranjay-poddar can u please assign me this issue?

**Comment by Ravenn57** [comment]
assign this to me

**Comment by Ravenn57** [comment]
please assign this to me
