### ISSUE TITLE
Renewable Energy Data Analytic in cpp

### ISSUE THREAD

**Issue by Vineetg2003** [pranjay-poddar/Dev-Geeks#4360]
**Describe the project you want to add with tech stack**
I want to make a command-line data analytics tool for renewable energy production data. It allows users to analyze historical energy production from solar panels and wind turbines, calculate average energy production, and add new energy data for further analysis.

@MohitGupta121 @TusharKesarwani Sir kindly assigned me these issue

**Comment by Vineetg2003** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar  Sir kindly assigned me these issue

**Comment by pranjay-poddar** [comment]
@Vineetg2003 please do not spam msg
