### ISSUE TITLE
Missing Spaces After The Line Ends

### ISSUE THREAD

**Issue by Souravvmishra** [pranjay-poddar/Dev-Geeks#4434]
**Describe the bug**

After the line ends, the next line starts without any space 

**Expected behavior**

There should be one space 

**Screenshots (optional)**

![Screenshot_2023-07-30-21-02-27-097_com.android.chrome.jpg](https://github.com/pranjay-poddar/Dev-Geeks/assets/89072785/647993e1-a81b-4557-8ca9-99fb481aa07f)
**Additional context (optional )**

**Comment by den319** [comment]
can you tell me where I can its code

**Comment by Souravvmishra** [comment]
@pranjay-poddar
