### ISSUE TITLE
Update Website with new Hacktoberfest 2022 details 

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#444]
Project available in repository_web page folder in root.

**Comment by Mustafa-Azad025** [comment]
Hello Sir,

I have gone through the repository and As Beginner I Want To Contribute For Hacktoberfest 2022 . I humbly wait for you to assign the task to me.

**Comment by pranjay-poddar** [comment]
Hi @Mustafa-Azad025 ,
Thanks for your interest in this project, you can create any issue of your choice or select to contribute in any of the existing issue by commenting on the issue to get it assigned to you.

**Comment by Ep1c-paav** [comment]
hey. i am very new to git and interested in your project. I am just wondering were can I find the to tweek the website :)

**Comment by pranjay-poddar** [comment]
@Ep1c-paav https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Repository_web_page

**Comment by Petsamuel** [comment]
I have gone through the project and I'll like to contribute, assign to me
