### ISSUE TITLE
responsive e-commerce product view component

### ISSUE THREAD

**Issue by chaaals** [pranjay-poddar/Dev-Geeks#445]
**Describe the project you want to add with tech stack**
Hi, I want to create a mini project and contribute it here. It's basically a reusable and responsive e-commerce product view component that anyone can easily use and customize if they ever needed one. I plan on only using React with css.

**Expected behavior**
Like a common product view component, you can increment the number of items and you can also save it to your cart or buy now. I plan on giving it default onclick functions that a user can populate with their own business logic

**Screenshots**
It should ideally look like this but more customizable (screenshot from Lazada)
![image](https://user-images.githubusercontent.com/70326902/193187374-833e16af-7857-4aa2-a72a-c3217475cf5f.png)

**Comment by pranjay-poddar** [comment]
Yes, go ahead add your project in reactjs folder and also mention your project in readme.md
