### ISSUE TITLE
[astromania] Contact us styling

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#4495]
**Describe the Feature you want to end**
 I would like to enhance contact us  

**Expected behavior**
it helps us increasing user experience

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly, assign this to me.

**Comment by MohitGupta121** [comment]
I want you to do this small small changes in 1 single PR, not in multiple PR's

**Comment by SnigdhaP2022** [comment]
> I want you to do this small small changes in 1 single PR, not in multiple PR's

If they all are from same project file,I can do as you mentioned. But they are from different right? So, how can I work on 1 PR
