### ISSUE TITLE
[Beautiful tweets] section styling

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#4497]
**Describe the Feature you want to end**
I would like to perform section styling by adding components into picture

**Expected behavior**
It helps and makes the site attractive to viewers

**Screenshots (optional)**

**Additional context (optional )**

**Comment by MohitGupta121** [comment]
@SnigdhaP2022 we do not need this spammy issues which contains 1 word change.

**Comment by SnigdhaP2022** [comment]
> @SnigdhaP2022 we do not need this spammy issues which contains 1 word change.

Kindly, note that I have never requested PR for 1 line change. I promise that this issue also needs more changes which is not 1 line. I would request you to think before making comments
