### ISSUE TITLE
[chess game] section styling

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#4502]
**Describe the Feature you want to end**
I would like to enhance section design

**Expected behavior**
it helps in increasing the user interaction to the site

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  Kindly, assign this to me.

**Comment by MohitGupta121** [comment]
No need

**Comment by SnigdhaP2022** [comment]
> No need

I don't understand what do you mean by "no need". I would like to enhance the section using my skills
