### ISSUE TITLE
[Dental site] Blog section styling

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#4506]
**Describe the Feature you want to end**
 I would like to add content to the blog section

**Expected behavior**
It helps in increasing viewer experience

**Screenshots (optional)**

**Additional context (optional )**

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  Kindly, assign this to me.

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  I believe there is no content in that section. Could you let me know why this issue isn't considered

**Comment by MohitGupta121** [comment]
If it's one line change then do in 1 Pr with multiple small issues otherwise it will be spam

**Comment by SnigdhaP2022** [comment]
> If it's one line change then do in 1 Pr with multiple small issues otherwise it will be spam

I can understand you concern. But I raised issue on various projects and the changes will not be change 1 line.
