### ISSUE TITLE
Python Project Tells you day on which you born

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#4541]
**Describe the project you want to add with tech stack**

 Tells you the day on which you born Using Python

**Expected behavior**

Show you the day you born

**Screenshots (optional)**

**Additional context (optional )**

Please assign me under GSSOC'23

**Comment by soubhik-111** [comment]
@MohitGupta121 
Kindly assign me under gssoc'23

**Comment by Neelraj-Reddy** [comment]
what exactly we want to do here ? what do you mean by telling the day we were born ? 
what is the input format ?
what is the output format ?
