### ISSUE TITLE
QR code converter and generator

### ISSUE THREAD

**Issue by Janhvi52** [pranjay-poddar/Dev-Geeks#455]
**Describe the project you want to add with tech stack**
html,css,c++,javascript

**Expected behavior**
the project will be a website which will convert and generate qr codes

i would like to work on this issue uner the label hackotober fest 2022
please assign me the same @pranjay-poddar

**Comment by flow6979** [comment]
hey @Janhvi52, I want to contribute to this issue. can you please assign this to me?

**Comment by Janhvi52** [comment]
> hey @Janhvi52, I want to contribute to this issue. can you please assign this to me?

hey this issue have been assigned to me and I'm already working on this issu @flow6979 

Please go and check out some other bugs and tasks in the project or add a new issue and start working on it, Thanks!
