### ISSUE TITLE
Jewellery Website Navbar

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#4566]
**Describe the Feature you want to end**
Working on the styling of the navbar to improve its design.

**Expected behavior**
Improved design

**Screenshots (optional)**

Current Design
![ip (1)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/98c874c3-6758-4e60-89ed-314fe4a5356f)

Expected Updated Design
![ip (2)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/403500e7-eb78-434f-949e-6122bb5b69a8)

**Additional context (optional )**
No

**Comment by iamRabia-N** [comment]
@MohitGupta121

**Comment by MohitGupta121** [comment]
Do in last issue
