### ISSUE TITLE
To Do List (Js)

### ISSUE THREAD

**Issue by smty2018** [pranjay-poddar/Dev-Geeks#4578]
**Describe the project you want to add with tech stack**
A JavaScript-based to-do list is a dynamic web application that allows users to add, edit, and delete tasks.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by smty2018** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar

**Comment by Pragati-3003** [comment]
@MohitGupta121 and @TusharKesarwani .
If no one working on this issue then i would to work on this.
