### ISSUE TITLE
GIF Converter in Python

### ISSUE THREAD

**Issue by smty2018** [pranjay-poddar/Dev-Geeks#4579]
**Describe the project you want to add with tech stack**
an .mp4 to GIF converter in python.

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by smty2018** [comment]
@MohitGupta121 @TusharKesarwani

**Comment by Abdullah-Web-D** [comment]
from moviepy.editor import VideoFileClip
from PIL import Image

def mp4_to_gif(mp4_file, gif_file):
    video = VideoFileClip(mp4_file)
    video.write_gif(gif_file)
    print("Conversion successful. GIF saved at:", gif_file)

def gif_to_mp4(gif_file, mp4_file):
    gif = Image.open(gif_file)
    gif_frames = [frame.copy() for frame in ImageSequence.Iterator(gif)]

    gif_frames[0].save(mp4_file, save_all=True, append_images=gif_frames[1:], loop=0, duration=gif.info['duration'])
    print("Conversion successful. MP4 saved at:", mp4_file)

if __name__ == "__main__":
    print("Select conversion type:")
    print("1. MP4 to GIF")
    print("2. GIF to MP4")
    choice = int(input("Enter your choice (1 or 2): "))

    if choice == 1:
        mp4_file = input("Enter the path of the MP4 file to convert: ")
        gif_file = input("Enter the path to save the GIF file: ")
        mp4_to_gif(mp4_file, gif_file)
    elif choice == 2:
        gif_file = input("Enter the path of the GIF file to convert: ")
        mp4_file = input("Enter the path to save the MP4 file: ")
        gif_to_mp4(gif_file, mp4_file)
    else:
        print("Invalid choice. Please select either 1 or 2.")
