### ISSUE TITLE
Snake Game in JAVA

### ISSUE THREAD

**Issue by satyacasm** [pranjay-poddar/Dev-Geeks#459]
**Describe the project you want to add with tech stack**
Designing a typical Snake game with the help of java.awt and java.swing package.

**Expected behavior**
The game will keep incrementing the score as the snakes keeps on consuming the powerup and displays game over message when the snake strikes the boundaries or strikes itself.

**Screenshots (optional)**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98680993/193297913-95f99eee-97fb-4ded-af7e-015348ab5882.png">

@pranjay-poddar Request you to assign this issue to me under hactoberfest 2022

**Comment by flow6979** [comment]
hey @pranjay-poddar, I want to contribute to this issue. can you please assign this to me?

**Comment by megha-vishwakarma** [comment]
Hey @pranjay-poddar , I would like to  contribute to this issue.

**Comment by flow6979** [comment]
@pranjay-poddar wow bro..pathetic

**Comment by pranjay-poddar** [comment]
> @pranjay-poddar wow bro..pathetic 

@flow6979 there's nothing pathetic, this issue is not opened by you and it is already assigned so someone else.
