### ISSUE TITLE
Animated Login Signup Notfound Using MERN

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#4596]
**Describe the project you want to add with tech stack**

Login Form Using React 

**Expected behavior**

Frontend project login form

**Screenshots (optional)**

**Additional context (optional )**

@MohitGupta121 
Assign me under gssoc'23

**Comment by Pragati-3003** [comment]
@MohitGupta121  and @TusharKesarwani , i would to work on this issue ,
So, if the issue is open then please assign me this issue.
