### ISSUE TITLE
real estate website using React js

### ISSUE THREAD

**Issue by YasirObaibullah99** [pranjay-poddar/Dev-Geeks#462]
**Describe the project you want to add with tech stack**
A Fully Responsive real estate website 

**Tech stack**
React js
Redux
TailwindCSS
Framer motion
Node js

**Expected behavior**
I am expecting to make a fully responsive website that will look good for the mobile also

**Screenshots**
![Screenshot from 2022-10-01 01-35-37](https://user-images.githubusercontent.com/83706868/193349386-640069a7-6961-4b73-b7ac-6a31dbe42484.png)

**Comment by YasirObaibullah99** [comment]
@pranjay-poddar I want to work on this.
pls add the hacktoberfest '22 tag

**Comment by pranjay-poddar** [comment]
Add this in react folder

**Comment by YasirObaibullah99** [comment]
okay
