### ISSUE TITLE
[GSSoC'23] Encipher and Decipher pulling bug

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [pranjay-poddar/Dev-Geeks#4637]
**Describe the bug**
"Encipher | Decipher" project while pulling the dev geeks repository, they will automatically deleted. Again after cloning the project, it will also automatically deleted and does not restore back. On creating the new pull request of other projects shows hindrance.

**Expected behavior**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114330097/fc746897-b791-417d-9fac-30c2dcad4301)

<br>

Even on restoring these files shows this error

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114330097/9dc0c863-f0a7-4fe2-8109-4c283fac0978)

<br>

This is comes because of spaces in between the folder names of "Encipher | Decipher" project.
I will simply change the folder name to "Encipher-Decipher" and download the files and send to you back as it is by creating the pull request.

**Comment by Avdhesh-Varshney** [comment]
@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar sir, please assign this task to me.

**Comment by Avdhesh-Varshney** [comment]
@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar sir, please assign this task to me contribute under gssoc23.

**Comment by Avdhesh-Varshney** [comment]
@pranjay-poddar @TusharKesarwani @MohitGupta121 @Saurabh-kumar09 sir, please assign it to me to raise the pr and remove conflicts

**Comment by Avdhesh-Varshney** [comment]
@Saurabh-kumar09 @pranjay-poddar @TusharKesarwani @MohitGupta121 sir, please review on this issue once and assign it to me to remove the bug

**Comment by MohitGupta121** [comment]
@Avdhesh-Varshney please don't spam

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney please don't spam

@MohitGupta121 sorry sir, i will keep it mind
