### ISSUE TITLE
3d button

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#4656]
**Describe the Feature you want to end**

i want to add my 3d button

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please assign it to me

**Comment by abansal15** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/1ffa3666-d69c-475a-ba49-b7c6cb1c1050

**Comment by MohitGupta121** [comment]
@abansal15 PR without assign
