### ISSUE TITLE
animated submit button

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#4658]
**Describe the Feature you want to end**

want to add animated submit button

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/f1603456-1508-4f77-a4b5-326dd2f2de63

**Additional context (optional )**

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please assign it to me

**Comment by MohitGupta121** [comment]
PR without assign
