### ISSUE TITLE
Paytm Clone

### ISSUE THREAD

**Issue by kumarkshitij171** [pranjay-poddar/Dev-Geeks#4683]
**Using HTML & CSS creating a paytm clone website**

**Ui/Ux design of paytm**

![Paytm Clone](https://github.com/pranjay-poddar/Dev-Geeks/assets/113905269/df9d9e55-98ef-4fea-8d08-f2f84d5434c2)

**Comment by kumarkshitij171** [comment]
Assign me for this issue

**Comment by kumarkshitij171** [comment]
@TusharKesarwani @pranjay-poddar @MohitGupta121 @Saurabh-kumar09 kindly check the issue I created and please assign this issue to me under GSSOC'23
I hope that you will look forward towards my request.

**Comment by MohitGupta121** [comment]
PR before assign

**Comment by kumarkshitij171** [comment]
assign it to me
