### ISSUE TITLE
Frontend Project To-do List Generator and Manager Responsive Website 

### ISSUE THREAD

**Issue by iamRabia-N** [pranjay-poddar/Dev-Geeks#4726]
**Describe the project you want to add with tech stack**
To-do list generator and manager website.
It is made with tech stack of HTML, CSS, JavaScript and JQuery.

**Expected behavior**
Attractive designed website.

**Additional context (optional )**
No

**Comment by iamRabia-N** [comment]
Hi @TusharKesarwani @MohitGupta121 
Kindly assign me this issue to add a project.

**Comment by kumarkshitij171** [comment]
@TusharKesarwani @pranjay-poddar @MohitGupta121 @Saurabh-kumar09 kindly check the issue I created and please assign this issue to me under GSSOC'23
