### ISSUE TITLE
a chat bot made with JS

### ISSUE THREAD

**Issue by Sushilverma002** [pranjay-poddar/Dev-Geeks#4738]
**Describe the project you want to add with tech stack**
a chat bot made with JS
**Expected behavior**

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/d3997773-cd47-4e17-839b-9258dc02ea40)
**Additional context (optional )**

**Comment by R4Rohit23** [comment]
@Sushilverma002 Hello can you assign me this issue
