### ISSUE TITLE
stopwatch

### ISSUE THREAD

**Issue by Vyshnavi21504** [pranjay-poddar/Dev-Geeks#4745]
**Describe the project you want to add with tech stack**

This is a simple stopwatch web application implemented using HTML, CSS, and JavaScript
**Expected behavior**

The stopwatch allows you to start, stop, and reset the timer.
**Screenshots (optional)**

**Additional context (optional )**

@TusharKesarwani @MohitGupta121  Sir kindly assigned me these issue

**Comment by SwetaPatil55** [comment]
Hello sir,Plese assign this project issuse to me
