### ISSUE TITLE
[New Project] QwickStay

### ISSUE THREAD

**Issue by SnigdhaP2022** [pranjay-poddar/Dev-Geeks#4762]
**Describe the project you want to add with tech stack**
I would like to add a project which has features in hotel booking per hour not like regular hotel booking as per night

**Expected behavior**
 It helps in customers usage as per their needs and accommodation will be affordable

**Screenshots (optional)**
<img width="1440" alt="Screenshot 2023-08-05 at 11 01 30 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/cb0c0efe-a77e-4644-8853-b4d47408a78b">

**Additional context (optional )**
I would like to contribute this project as per GSSOC'23 Contributor

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 @TusharKesarwani Kindly,assign this to me

**Comment by R4Rohit23** [comment]
@SnigdhaP2022 Hey Can you assign this issue to me.
