### ISSUE TITLE
UI Fixes in the DevGeeks Website

### ISSUE THREAD

**Issue by AnushkaKohli** [pranjay-poddar/Dev-Geeks#4764]
**Describe the bug**
Currently, the UI of the DevGeeks website is quite ordinary and have some design issues like spacing, fonts and cluttering of all information in the same space.

**Expected behavior**
I would like to make changes in the UI of the website and improve the frontend design to make the website more attractive.

**Screenshots (optional)**
<img width="952" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102284552/65b8328f-b5bd-496f-ad5d-18568260f1c7">

<img width="953" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102284552/ae774b42-304d-4c7a-8198-9d87a83d1a47">

**Additional context (optional )**
Please assign me the issue to improve the UI of the said website.

**Comment by R4Rohit23** [comment]
@AnushkaKohli can you assign me this issue and what type of changes do you need in you site ?
