### ISSUE TITLE
cat seeing animation 

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#4810]
**Describe the Feature you want to end**

i want to add this amazing cat seeing animation

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/f2d030b7-151d-4669-ad65-a555adca9adb

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please assign this issue to me

**Comment by Muskan1009** [comment]
@MohitGupta121 @TusharKesarwani Please assign this issue to me

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please assign this issue to me as i raised this issue first pls

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please  review it i have raised the pr
