### ISSUE TITLE
simple loading animation

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#4811]
**Describe the Feature you want to end**

i want to add this simple loading animation please review it

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/b1b21eaa-1f44-454e-b205-259f7182e7a1

**Additional context (optional )**

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please assign this issue to me

**Comment by MohitGupta121** [comment]
Already have
