### ISSUE TITLE
simple color changing box animation

### ISSUE THREAD

**Issue by abansal15** [pranjay-poddar/Dev-Geeks#4812]
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/10d92f28-1acf-45ce-8e1e-f7ab79378c1d

**Additional context (optional )**

**Comment by Muskan1009** [comment]
@MohitGupta121  @TusharKesarwani please assign this issue to me
