### ISSUE TITLE
Animated Frontend Project

### ISSUE THREAD

**Issue by soubhik-111** [pranjay-poddar/Dev-Geeks#4840]
**Describe the project you want to add with tech stack**

Animated Frontend Project

**Expected behavior**

Web Page in HTML, CSS & JS

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90599826/24747bfb-c73d-4b12-8ac5-1e1c4f07631f)

**Additional context (optional )**

**Comment by soubhik-111** [comment]
@MohitGupta121 Kindly assign me under GSSOC'23

**Comment by parth656** [comment]
@pranjay-poddar kindly assign it to me
@soubhik-111 kindly assign it to me

**Comment by parth656** [comment]
@MohitGupta121 kindly assign it to me

**Comment by soubhik-111** [comment]
Hello @parth656 ,
I have already raised the PR 
So, you can create a new Issue and work on it
