### ISSUE TITLE
Flower shop website

### ISSUE THREAD

**Issue by Yashika-Agrawal** [pranjay-poddar/Dev-Geeks#4872]
**Describe the project you want to add with tech stack**
I want to create a flower shop website using only HTML and CSS. The website will serve as an online platform for customers to browse and purchase various flowers and floral arrangements. It will have a visually appealing and user-friendly interface. Customers will be able to explore the products and view their details.

**Expected behavior**
The flower shop website should provide an aesthetically pleasing design and easy navigation for users to explore the available flower options. It should showcase product details, images, and prices effectively. 

**Screenshots (optional)**
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97408966/1f786112-b2b9-42ea-939e-268ae01ddadc)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97408966/b8f8a666-291b-43e4-a43d-77d9e6a6c4f4)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/97408966/cca7bbe4-63a7-4dbe-802e-d1d2251cd41c)

**Comment by Yashika-Agrawal** [comment]
@pranjay-poddar , @MohitGupta121 Hey please assign me this issue under GSSOC'23 contribution.

**Comment by harsh3311** [comment]
I think this is a template

**Comment by Yashika-Agrawal** [comment]
No i made this of my own.
