### ISSUE TITLE
BMI Calculator using React

### ISSUE THREAD

**Issue by sumitkr2000** [pranjay-poddar/Dev-Geeks#494]
I want to add a BMI Calculator project which is created using react.js. It help an user to calculates his/her BMI.
Tech stack used:

- **HTML**
- **CSS**
- **React.js**
- **Node.js**

By entering an user's height and weight they can see their BMI.

![Screenshot (296)](https://user-images.githubusercontent.com/100675296/193411036-9c3465c1-bd29-4bd2-b665-391cb312a81b.png)

Can you please assign me this issue.

**Comment by yamitrvg12** [comment]
Hey [sumitkr2000](https://github.com/sumitkr2000), can you assign me this task so that I can work on it?

**Comment by sumitkr2000** [comment]
> Hey [sumitkr2000](https://github.com/sumitkr2000), can you assign me this task so that I can work on it?

**Comment by sumitkr2000** [comment]
Hey @pranjay-poddar I have completed this issue can u please my merge request and add the "hacktoberfest-accepted" tag to it. Thank you!
