### ISSUE TITLE
Add a new responsive footer

### ISSUE THREAD

**Issue by Subho0710** [pranjay-poddar/Dev-Geeks#50]
**Describe the project you want to add with tech stack**

Footer with content and links

**Expected behavior**

Responsive

**Screenshots (optional)**

**Additional context (optional )**

**Comment by ilhamansari** [comment]
Please assign me this project .

**Comment by srinjoy-26** [comment]
please assign me @pranjay-poddar

**Comment by anjaliSilawat** [comment]
I would like to work on this issue @Subho0710 , please assign it to me

**Comment by Pavishnaam** [comment]
Not all part of the website is responsive. Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.
I will convert the whole website into responsive @pranjay-poddar 
Also when I open the website in mobile, the alignment is not proper.
Kindly provide me the opportunity to work on the issue.

**Comment by UdaySutradhar** [comment]
I would like to contribute in this issue. Please assign me in this project.
