### ISSUE TITLE
Supermarket Sales Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [pranjay-poddar/Dev-Geeks#545]
Describe the project you want to add with tech stack
I would want to create a model to predict the supermarket sales.

Dataset : https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales
This dataset includes historical record of sales data in 3 different supermarkets

Expected behavior
I will be doing an Exploratory Data Analysis, create models for predicting using different algorithms and compare them using accuracy scores. This will help us in knowing the right fit model for this problem statement.

Can you kindly assign this issue to me? @pranjay-poddar

**Comment by prathimacode-hub** [comment]
Why is the issue closed? @pranjay-poddar

**Comment by pranjay-poddar** [comment]
> Why is the issue closed? @pranjay-poddar 

This repository is no longer accepting hacktoberfest'22 PR
