### ISSUE TITLE
Want to add navigation tab and contact part

### ISSUE THREAD

**Issue by vedsom** [pranjay-poddar/Dev-Geeks#550]
**Describe the Feature you want to end**
As we all know having a good navigation bar makes exploring the site easy. I want to add a responsive navigation part and connect it to your different part of site.
On the other hand want to add a contact part for you various social media network.

@pranjay-poddar kindly assign me this issue to work on under hacktoberfest.

**Comment by vedsom** [comment]
@pranjay-poddar will it count under hacktoberfest 22 ??

**Comment by pranjay-poddar** [comment]
@vedsom yes

**Comment by Ravenn57** [comment]
kindly assign this to me
