### ISSUE TITLE
A form Page

### ISSUE THREAD

**Issue by wizeewig** [pranjay-poddar/Dev-Geeks#558]
**Describe the project you want to add with tech stack**
I want to add a form page. Every now and then we see form pages in different website. So it would be helpful for others if they get one good form using HTML and CSS made for them.

**Expected behavior**

My project will include a registration form where basic details of user will be asked. We see this type of forms when a user subscribes to a newsletter of any website.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Hanuvesh** [comment]
i want to make contribution to this repo , i have a good knowledge about html

**Comment by pranjay-poddar** [comment]
> i want to make contribution to this repo , i have a good knowledge about html
> 

@Hanuvesh create an issue on which you like to work and get it assigned to you

**Comment by Hanuvesh** [comment]
i want to make footer responsive
