### ISSUE TITLE
Update the Project in Readme.md

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#560]
update the list of all the projects in the readme.md by following the closed PRs with the level labels after October 7th, 2022. (Avoid the duplicate entry of projects)

https://github.com/pranjay-poddar/Dev-Geeks/pulls?q=is%3Apr+is%3Aclosed

**Comment by Samarthasbhat** [comment]
Ok i will do this work

**Comment by Samarthasbhat** [comment]
but all the readme should be updated?

**Comment by pranjay-poddar** [comment]
Only the main readme.md present in the root folder

**Comment by Samarthasbhat** [comment]
Where is the root folder present can I get the link

**Comment by pranjay-poddar** [comment]
Root folder means the base folder where all the project files exists.

https://github.com/pranjay-poddar/Dev-Geeks/blob/main/README.md

**Comment by gauriimaheshwarii** [comment]
Can I work on this issue?

**Comment by pranjay-poddar** [comment]
@gauriimaheshwarii yeah sure

**Comment by deepshikha2708** [comment]
can I also work in this issue? @pranjay-poddar

**Comment by Nymphalys** [comment]
I am eager to work on this ,Can you assign this issue to me

**Comment by kalyanikakade123** [comment]
Can you assign this issue to me ?

**Comment by pranjay-poddar** [comment]
@all update the list of all the projects in the readme. md by following the closed PRs with the hacktoberfest-accepted label after October 1st 2022. (Avoid the duplicate entry of projects)

**Comment by gauriimaheshwarii** [comment]
Hi @pranjay-poddar, the list of projects has been updated till 07 October, 2022.
Kindly merge my PR #685.

**Comment by pranjay-poddar** [comment]
> Hi @pranjay-poddar, the list of projects has been updated till 07 October, 2022. Kindly merge my PR #685.

Great will do the review!
Awesome Work @gauriimaheshwarii!

**Comment by radhika2503** [comment]
I too want to work on this issue.

**Comment by jatin00000** [comment]
Sir, Can I  also work on this issue?

**Comment by jatin00000** [comment]
Sir, the list of projects has been updated till 11th October, 2022.
Kindly merge my PR https://github.com/pranjay-poddar/Dev-Geeks/pull/940
