### ISSUE TITLE
A GoogleCrome extension

### ISSUE THREAD

**Issue by Morbius00** [pranjay-poddar/Dev-Geeks#576]
![Open Source Love](https://badges.frapsoft.com/os/v1/open-source.svg?v=103)

<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

**Describe the project you want to add with tech stack**
## Sessions

Save chrome tabs as sessions

## Tech stacks:
<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/>   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a>   <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="30" height="30"/> </a>

**Expected behavior**
* User can create workspaces from open tabs in just one click.
* The sessions can be restored at any time. They will stored in local storage and will not be erased.
* Ability to name sessions, restore and delete them.
* Effective memory management.

**Screenshots (optional)**

cant add the screenshot as it is extension.

**Additional context (optional )**

**Comment by sumitbaroniya** [comment]
please assign me this issue
