### ISSUE TITLE
Add Quiz App

### ISSUE THREAD

**Issue by PRERNA-CHOUDHARY** [pranjay-poddar/Dev-Geeks#578]
**Describe the project you want to add with tech stack**
 It is a Quiz App , Tech stack used are
- HTML
- CSS
- JS

**Expected behavior**
If the wrong answer is selected then 10 sec will be deducted from total time, multiple user can save their score, Tells if selected answer is correct or not.

**Screenshots (optional)**
LAPTOP VIEW
![Capture](https://user-images.githubusercontent.com/74724592/193990751-81786c55-d13e-4d9a-977d-aa869f2c2c30.PNG)

MOBILE VIEW
![Capture1](https://user-images.githubusercontent.com/74724592/193990744-80259f4d-8eda-4aa2-92ab-42cd1c48af3a.PNG)

**Comment by PRERNA-CHOUDHARY** [comment]
@pranjay-poddar kindly assign me this under hacktoberfest

**Comment by himanishu-2512** [comment]
@pranjay-poddar Hey can you assign me this under hactoberfest.

**Comment by PRERNA-CHOUDHARY** [comment]
> @pranjay-poddar Kindly assign me this issue under hactoberfest.
@himanishu-2512 this is already assigned to me.
