### ISSUE TITLE
Curved Carousel using Html and CSS

### ISSUE THREAD

**Issue by Divya2163** [pranjay-poddar/Dev-Geeks#588]
**Describe the project you want to add with tech stack**
A simple curved carousel using HTML and CSS only

**Expected behavior**
A draggable curved carousel 

**Screenshots (optional)**

![S9mmM](https://user-images.githubusercontent.com/76438709/194000025-b4f0e244-b1be-429c-9f62-f25ee424576d.png)

**Comment by Divya2163** [comment]
Kindly assign me this with hacktoberfest lables.

**Comment by aaushitiwari** [comment]
can you assign this to me?

**Comment by pranjay-poddar** [comment]
> can you assign this to me?

This task is already assigned to @Divya2163, you can raise some other issue and get it assigned
