### ISSUE TITLE
Add Frontend Project

### ISSUE THREAD

**Issue by itsPrajapat** [pranjay-poddar/Dev-Geeks#6]

**Comment by PriyanshuGarg26** [comment]
I added a project in frontend projects. Please review it

**Comment by srinjoy-26** [comment]
> I added a project in frontend projects. Please review it

close this issue

**Comment by pranjay-poddar** [comment]
> > I added a project in frontend projects. Please review it
> 
> close this issue

@srinjoy-26 not required

**Comment by wizeewig** [comment]
thank you @pranjay-poddar
