### ISSUE TITLE
Rolex Website Clone

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#616]
**Describe the project you want to add with tech stack**
Rolex Website Clone using HTML CSS JS

**Expected behavior**
Cool UI of rolex

**Comment by geetika001** [comment]
Hey! Can I work on this issue if still available?
Describe the project you want to add with tech stack
Rolex Website Clone using HTML CSS JS

Expected behavior
Elegant UI of Rolex website
