### ISSUE TITLE
Offcial Spotify Website Clone

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#618]
**Describe the project you want to add with tech stack**
HTML  CSS JS

**Expected behavior**
Spotify Website Clone

**Screenshots (optional)**

![Screenshot (313)](https://user-images.githubusercontent.com/91609324/194116866-160645c0-44e1-4ef1-8d2b-f81093a2b177.png)

**Comment by pranjay-poddar** [comment]
Already added
