### ISSUE TITLE
weather app in Javascript

### ISSUE THREAD

**Issue by ManishMadan2882** [pranjay-poddar/Dev-Geeks#632]
**Describe the project you want to add with tech stack**
I want to add a Weather application using OpenWeatherMap API using Javascript and TailwindCSS

**Expected behavior**
It shows weather info for the current location or the location the user search for

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/96079232/194179261-2874bd32-154a-4e0a-b965-5ed8b8625980.png)

**Comment by sumitbaroniya** [comment]
please assign me this issue

**Comment by pranjay-poddar** [comment]
@sumitbaroniya It's already assigned to @ManishMadan2882
