### ISSUE TITLE
Netflix frontend clone

### ISSUE THREAD

**Issue by SujalMishra** [pranjay-poddar/Dev-Geeks#636]
**Describe the project you want to add with tech stack**
I want to make Netflix frontend clone using HTML,CSS and JS

**Expected Behaviour**
UI design for Netflix

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/98722988/194229748-82fad919-2e68-4605-8ad0-92e562df7943.png)

**Comment by Yugal308** [comment]
I would also like to do the same with react and redux. Please assign me for the same.
