### ISSUE TITLE
Added To-do-list

### ISSUE THREAD

**Issue by NishantSingh-2705** [pranjay-poddar/Dev-Geeks#65]
**Describe the project you want to add with tech stack**

added to-do-list
**Expected behavior**

You can add activities to be performed by an individual in a day.
**Screenshots (optional)**

**Additional context (optional )**

**Comment by pranjay-poddar** [comment]
@Subha-5 please avoid tagging unassigned participants, only tag the project admins.

**Comment by pavankumarraju13** [comment]
@pranjay-poddar i would like to do this task please assign me

**Comment by pranjay-poddar** [comment]
This task is already assigned to @Subha-5 pls wait for some time.

**Comment by Subha-5** [comment]
@pranjay-poddar  i have already contributed to this issue here
https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Frontend-Projects/simple%20to%20do%20list

you may close this issue or you can tell me if any improvements to be made so i can improve this project
