### ISSUE TITLE
Sorting Visualizer

### ISSUE THREAD

**Issue by D-Anir** [pranjay-poddar/Dev-Geeks#662]
- I have an exciting sorting visualizer app which I created during my college days
- It has functionality for 5 most important day-to-day sorting algorithms
- I want to share with the community for everyone to gain help
- I think it will be a great feature to have as a part of this project

**@pranjay-poddar Please assign me this issue. Thanks in Advance!**

**Comment by D-Anir** [comment]
@pranjay-poddar
I have submitted a PR with the title "added sorting visualizer in js-projects directory #664". Please review the changes.
Thanks in Advance.

**Comment by sumitbaroniya** [comment]
Please assign me this issue
