### ISSUE TITLE
Drum Kit project using JAVASCRIPT

### ISSUE THREAD

**Issue by VedantSharma11** [pranjay-poddar/Dev-Geeks#663]
i want to work on this project so please assign me this issue :) with #isuue-assigned tag

**Comment by ianujvarshney** [comment]
I can Created this with the help JavaScript also with react please assign me and share also with sitemap.

**Comment by pranjay-poddar** [comment]
its already present https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Js-Games/Drumkit%20Game

**Comment by ianujvarshney** [comment]
ok no problem
