### ISSUE TITLE
improving the frontend of btech chaiwala project

### ISSUE THREAD

**Issue by pratikashpanda** [pranjay-poddar/Dev-Geeks#667]
**Describe the Feature you want to end**
The website looks way too plain for attracting people. It has no functionality, no interactive attributes, and not many images.

**Expected behavior**
Building a proper landing page displaying the essence of the business, a more user-friendly color scheme, interaction, and good looking website to the eyes.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by amankumarsahani** [comment]
I can improve the frontend. 
please assign me this issue :)
