### ISSUE TITLE
Online food order website (frontend)

### ISSUE THREAD

**Issue by pratikashpanda** [pranjay-poddar/Dev-Geeks#669]
**Describe the project you want to add with tech stack**
A completely responsive food ordering website built with HTML, CSS, and JavaScript for restaurants hoping to have their personal websites.

**Screenshots (optional)**
![Screenshot 2022-10-07 102128](https://user-images.githubusercontent.com/71447483/194470864-0803788d-8d7c-4971-a8b3-b270c668b680.jpg)

**Additional context (optional )**
Please do consider this under Hacktoberfest

**Comment by Purvesh77** [comment]
Hey @pratikashpanda I want to work on this task can you assign this to me?

**Comment by heysaiyad** [comment]
Please assign this task, bcoz I want work on this project . And I am a front end developer so I will make it very attractive .

**Comment by radhika2503** [comment]
hey please assign me this task
