### ISSUE TITLE
Simple Notes App

### ISSUE THREAD

**Issue by Asttttha** [pranjay-poddar/Dev-Geeks#671]
Stores notes with time as well as date, which can be edited or deleted later.

![Screenshot (285)](https://user-images.githubusercontent.com/95849912/194481943-cc9c172a-2843-443e-b872-557ce5c17ee4.png)

**Comment by Asttttha** [comment]
@pranjay-poddar please assign this issue to me under HacktoberFest2022

**Comment by heysaiyad** [comment]
please assign this issue to me, bcoz I am already work on Notes app. so I will make it very attractive.
