### ISSUE TITLE
Tic Tac Toe JavaScript

### ISSUE THREAD

**Issue by siddakbagga13** [pranjay-poddar/Dev-Geeks#675]
**Describe the project you want to add with tech stack**
It a tic tac toe game made with the help of Html, CSS and JavaScript

**Expected behavior**
Its a two players' game O's Turn will be first and who so ever wins will pop up

**Screenshots (optional)**
![Screenshot (270)](https://user-images.githubusercontent.com/92291965/194548367-75bd9e91-b42c-47a7-9579-ffc8ec6b5b40.png)

**Additional context (optional )**
Please add hacktoberfest tag

**Comment by durgesh-4526** [comment]
@pranjay-poddar Kindly Assign me this issue

**Comment by Aanya9693** [comment]
Hey! @siddakbagga13 Can you please assign this issue to me? I'm already working on it, will be able to submit it within a day after you will assign it.
Things I'll add to this project:
- Player instruction for playing the game
- Game board (3x3 grid)
- Game result section
- Restart button

Two different people will be able to play.
