### ISSUE TITLE
Awesome Draggable Navbar 

### ISSUE THREAD

**Issue by dheerajrao20** [pranjay-poddar/Dev-Geeks#676]
Hey, I have an awesome **_Draggable Navbar_**.
> Yeah It's can be dragged on Screen.

I am exploring this repository and found some <a href="https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Navbars">**_Navbar_**</a> related projects.
So I want to add this Draggable Navbar as a projects.

This contribution is under <a href="https://hacktoberfest.com/"> **_Hacktoberfest 2022_**</a>

@pranjay-poddar Do consider this Issue under hacktoberfest

![Untitled design](https://user-images.githubusercontent.com/89007097/194560863-965b346c-7f36-4395-8837-1ba96ef149f4.gif)

**Comment by heysaiyad** [comment]
sir please assign this project, bcoz I am a front end developer so i will make it very attractive pages.
