### ISSUE TITLE
Tetris game using React

### ISSUE THREAD

**Issue by FaizanCod** [pranjay-poddar/Dev-Geeks#681]
**Describe the project you want to add with tech stack**
Tetris game using React

**Expected behavior**
Implementation of the classic Tetris game using React as the frontend

**Screenshots (optional)**

**Additional context (optional)**
Add hacktoberfest label

**Comment by pranjay-poddar** [comment]
Its already present https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Js-Games/Tetris%20Game%20JS
