### ISSUE TITLE
Add Netflix Clone (Old version)

### ISSUE THREAD

**Issue by AwaneeshSoni** [pranjay-poddar/Dev-Geeks#686]
Hi, 
I am Awaneesh Soni.
I would like to add Netflix Clone (old version) to frontend projects.
It will be a simple frontend project based on HTML, CSS, and Javascript.

PLease assign it me.

**Comment by heysaiyad** [comment]
I would like to add Netflix Clone Old version , bcoz I am a front end developer.` So please it me.`

**Comment by AwaneeshSoni** [comment]
Hey,
I created a pull request, but it not showing some error message.
Can you please help?

**Comment by AwaneeshSoni** [comment]
Hi,
Can you please look into it ?
