### ISSUE TITLE
CSS overlay animation over an image

### ISSUE THREAD

**Issue by shreyanshp25** [pranjay-poddar/Dev-Geeks#69]
**Describe the project you want to add with tech stack**

HTML, CSS project for CSS overlay animation
 
**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by GundaSudarrshan** [comment]
Hey  Pranay can You assign this to me , I have some ideas regarding Animation effects

**Comment by pranjay-poddar** [comment]
*Pranjay

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by Humaira-Sadia** [comment]
Hello @pranjay-poddar I have some beautiful interacting ideas regarding overlay CSS animation over an image.
Can you please assign this issue to me :)

**Comment by Humaira-Sadia** [comment]
@pranjay-poddar can you please review my pr !!
link : https://github.com/pranjay-poddar/Dev-Geeks/pull/1367
