### ISSUE TITLE
Portfolio website

### ISSUE THREAD

**Issue by sshiwangi** [pranjay-poddar/Dev-Geeks#692]
**Describe the project you want to add with tech stack**
I would like to add a simple portfolio website built using HTML, CSS and JavaScript.

**Expected behavior**
It will have basic information about the person such as projects, skills etc.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by sshiwangi** [comment]
@pranjay-poddar please assign me this issue under hacktoberfest.

**Comment by radhika2503** [comment]
hey please assign me this task
this is my first hactoberfest.

**Comment by pranjay-poddar** [comment]
@sshiwangi , @radhika2503 both of you can work on your own version of portfolio websites.

**Comment by YashGadia** [comment]
@pranjay-poddar Can I work on this issue?
This is my first hactoberfest.

**Comment by Kpallavi5** [comment]
Hyy @pranjay-poddar kindly assign me too this issue..this is my first open source contribution.. ❤️ 💫
