### ISSUE TITLE
Image Slider frontend project

### ISSUE THREAD

**Issue by SunilPatel43** [pranjay-poddar/Dev-Geeks#694]
**Describe the project you want to add with tech stack**
An Image  slider using HTML, CSS, JS

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/56433897/194690349-2c356a90-9936-4699-89d9-43d4fa08c708.png)

@pranjay-poddar I'd like to work on this issue

**Comment by kirtilulle** [comment]
hey i want to work on this project

**Comment by pranjay-poddar** [comment]
@kirtilulle it is already assigned to @SunilPatel43
