### ISSUE TITLE
Digital Clock using JS

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [pranjay-poddar/Dev-Geeks#698]
**Describe the project you want to add with tech stack**
A javascript based Digital clock

**Screenshots**
![image](https://user-images.githubusercontent.com/52749230/194697865-7e3449d8-726a-4016-a76a-6d1b7488e493.png)

@pranjay-poddar I'd like to work on this issue

**Comment by Ahsan-Ehtesham** [comment]
@pranjay-poddar kindly assign this to me with the hacktoberfest label. Thanks!

**Comment by radhika2503** [comment]
hey this is my first hacktober.
please help me too to find pr.

**Comment by pranjay-poddar** [comment]
> hey this is my first hacktober.
> please help me too to find pr.
> 

You can work on this beginners friendly issue: 
 https://github.com/pranjay-poddar/Dev-Geeks/issues/560

**Comment by radhika2503** [comment]
will my pr be counted coz already people are assigned to it
