### ISSUE TITLE
Lee Cooper Website Clone

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#711]
**Describe the project you want to add with tech stack**
official Lee Cooper Website Clone

**Expected behavior**
Website clone with all the functionality

**Screenshots (optional)**

**Additional context (optional )**

**Comment by geetika001** [comment]
Hey @pranjay-poddar can I please be assigned this issue?

**Comment by pranjay-poddar** [comment]
@RAHULBAWA777 is already working on this
