### ISSUE TITLE
Bulbasaur Button

### ISSUE THREAD

**Issue by HarshJa1n** [pranjay-poddar/Dev-Geeks#722]
**Describe the project you want to add with tech stack**
A button design, built using CSS. Made to practice CSS-Art.

**Expected behavior**
Can act as a button, gets push down when you hover.

**Screenshots (optional)**

![u](https://user-images.githubusercontent.com/96345745/194704058-225f3ccb-eb7c-4e75-8f75-5a1a7fece199.gif)

**Comment by pranjay-poddar** [comment]
Keep it in css animations folder
