### ISSUE TITLE
CSS heart beating animation

### ISSUE THREAD

**Issue by shreyanshp25** [pranjay-poddar/Dev-Geeks#75]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar  Pls assign me this issue I wanted to work on this

**Comment by pavankumarraju13** [comment]
@pranjay-poddar plz assign me this issue  i like to work

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar  thanks for assigning me this issue , I wanted to ask that if this issue is labelled to HSCO and level of the Issue is mentioned or not

**Comment by GundaSudarrshan** [comment]
@pranjay-poddar  thanks for the PR, I think we can **Close this Issue** for Better Workflow of the Repository as the **PR is merged**
What do you think!!!!!
