### ISSUE TITLE
Google clone

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [pranjay-poddar/Dev-Geeks#768]
**Describe the project you want to add with tech stack**
The project is a dynamic registration table where users can add new details about them in the table.
Tech stack:- html,css,js

![194582411-5c7d6497-e341-4111-b066-10c1d91c86b8](https://user-images.githubusercontent.com/87663868/194724135-1ead7591-3b18-4bd1-84b4-4ef2569f00de.png)

**Comment by ShrutiMishra-2002** [comment]
@pranjay-poddar please assign me this issue

**Comment by Kpallavi5** [comment]
Can you please assign me this issue
