### ISSUE TITLE
expense tracker react

### ISSUE THREAD

**Issue by ayushkedia05** [pranjay-poddar/Dev-Geeks#787]
track your expenses with react and firebase suport

**Comment by ZawadiSumba66** [comment]
Please assign this to me. Would like to work on it

**Comment by ZawadiSumba66** [comment]
Any design template for this. Any idea where I can start form?

**Comment by pranjay-poddar** [comment]
> Any design template for this. Any idea where I can start form?
> 

You can work on any easy accessible design, for ideas, you can find designs on behance and dribble.

**Comment by ZawadiSumba66** [comment]
Hi @pranjay-poddar a little bit stuck on where the code for the api of this  frontend issue is hosted in order to perform http requests
