### ISSUE TITLE
A Virtual Calculator using Python

### ISSUE THREAD

**Issue by srummanf** [pranjay-poddar/Dev-Geeks#788]
A virtual Calculator using computer vision and python
It will use our handmovement and would capture operations and operand to calculate an expression.

**Comment by srummanf** [comment]
@pranjay-poddar Pls assign this issue to me

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it under hacktoberfest.

**Comment by srummanf** [comment]
Sumit, Hello brother , It was my Issue so can you please remove the comment
as I have made an PR , considering it to be my issue

**Comment by srummanf** [comment]
I have done the assigned task sir

**Comment by srummanf** [comment]
PR #796 is my assigned task which is done by me
