### ISSUE TITLE
Add Food Website

### ISSUE THREAD

**Issue by PRERNA-CHOUDHARY** [pranjay-poddar/Dev-Geeks#789]
**Describe the project you want to add with tech stack**
The frontend of a food website. Using tech stack 
- HTML
- CSS

**Expected behavior**
It is a frontend design thus effects like hover can be seen.

**Screenshots (optional)**
![PRERNA CHOUDHARY TASK 7](https://user-images.githubusercontent.com/74724592/194739813-845ebc2f-adbe-4650-8403-e7e12306adfe.png)

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it. Please add the label of hacktoberfest.

**Comment by souravaniket** [comment]
please assign me this issue
