### ISSUE TITLE
Add responsive navbar

### ISSUE THREAD

**Issue by Subho0710** [pranjay-poddar/Dev-Geeks#8]

**Comment by prachigarg19** [comment]
Could you assign me this issue?

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by srinjoy-26** [comment]
@pranjay-poddar please assign me

**Comment by pranjay-poddar** [comment]
@srinjoy-26 https://getbootstrap.com/docs/4.0/components/navbar/ no need for this PR it is simply a bootstrapped navbar.

**Comment by srinjoy-26** [comment]
@pranjay-poddar please don't unassign me , I will make a PR containing a navbar made using pure html-css
