### ISSUE TITLE
Build random quote generator with Javascript.

### ISSUE THREAD

**Issue by DevTomilola-OS** [pranjay-poddar/Dev-Geeks#826]
**Describe the project you want to add with tech stack**
A random quote generator built with Html, Css and Javascript.

**Expected behavior**
Generates random quotes at the click of a button.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by DevTomilola-OS** [comment]
Admin, kindly assign this to me before approving my PR. 

Thank you.

**Comment by pranjay-poddar** [comment]
Please wait for the issue to get assigned, then raise a PR

**Comment by DevTomilola-OS** [comment]
Okay thanks.
