### ISSUE TITLE
Adding HealthFit Project

### ISSUE THREAD

**Issue by ShivamAgarwal-code** [pranjay-poddar/Dev-Geeks#848]
*Please assign me the issue..

**Comment by pranjay-poddar** [comment]
Please describe your project

**Comment by ShivamAgarwal-code** [comment]
ok sure, it's a frontend project using HTML, CSS, js.
Features: the web app allows you to search exercises of your interest with a lot of filter options. It allows you to search exercises with respect to body parts and gave you more detail about the exercises that resembles the specified exercise in terms of target muscle or in terms of equipments.

**Comment by ShivamAgarwal-code** [comment]
@pranjay-poddar please assign me this issue under hacktoberfest
