### ISSUE TITLE
Adding Dark mode to the site

### ISSUE THREAD

**Issue by ElvinPero** [pranjay-poddar/Dev-Geeks#859]
**Describe the Feature you want to end**
Toggle switch for websites to change to night mode
**Expected behavior**
switch should hold previous input so theme remains unchanged even after refresh

**Comment by ElvinPero** [comment]
@prateekj7777 Kindly assign me this feature . I can work on it

**Comment by ElvinPero** [comment]
I can add dark mode to the site [bit.ly/30tAf40](https://bit.ly/30tAf40)

**Comment by prateekj7777** [comment]
Hey ! 

I am not getting why you are asking this to me.

**Comment by ElvinPero** [comment]
@pranjay-poddar Can you assign this to me?

**Comment by ElvinPero** [comment]
> Hey !
> 
> I am not getting why you are asking this to me.

By mistake.
