### ISSUE TITLE
HTML, CSS, JS Vignere Cipher

### ISSUE THREAD

**Issue by Karun842002** [pranjay-poddar/Dev-Geeks#86]
**Describe the project you want to add with tech stack**
A cool vignere ciphere encryption/decryption app built on Vanilla JS

**Expected behavior**
Either the encrypted text or plain text ccan be given, and the opposite will be printed out

**Comment by Nirvik07** [comment]
I want to work on this issue.

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!
