### ISSUE TITLE
Add a Drum Kit Website using HTML, CSS, Bootstrap, Javascript.

### ISSUE THREAD

**Issue by Kritika30032002** [pranjay-poddar/Dev-Geeks#894]
Adding a beginner friendly website made using HTML, CSS, Bootstrap framework and a little bit JavaScript.

It has sound when we press the drum boxes or press the character specified on them using keyboard.

Assign this issue to me !!

This is how it looks!!

![Drum Kit](https://user-images.githubusercontent.com/83400697/194911337-5036f680-6929-4c75-ad1a-d447b6bf4cec.png)

**Comment by pranjay-poddar** [comment]
It is already present
