### ISSUE TITLE
Add a functional sign up form

### ISSUE THREAD

**Issue by shreyanshp25** [pranjay-poddar/Dev-Geeks#9]
Functional sign up form built using JS, HTML, CSS

**Comment by Nirvik07** [comment]
I want to do this issue.

**Comment by Subha-5** [comment]
@pranjay-poddar i want to work on this issue, please assign it to me

**Comment by Nirvik07** [comment]
@pranjay-poddar please review my PR.

**Comment by PriyankaTamhankar01** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue.

**Comment by UditSharma9999** [comment]
I would love to contribute to this open source project!

**Comment by samarthhapse** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23.  I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue.

**Comment by Harshvardhan-Dubey-Github** [comment]
please assign me this issue

**Comment by pjyoti121** [comment]
please assign me this issue
