### ISSUE TITLE
Create a random password generator

### ISSUE THREAD

**Issue by Subha-5** [pranjay-poddar/Dev-Geeks#903]
**Describe the project you want to add with tech stack**
Python and its modules

**Expected behavior**
It will act as a random password generator to suggest users to input a safe password

**Screenshots (optional)**

**Additional context (optional )**
Since cyber attacks on accounts with low secure passwords is most probable, it is necessary for users to create random and difficult passwords for their various accounts to avoid cyber attacks.

**Comment by Subha-5** [comment]
@pranjay-poddar please assign me this issue

**Comment by pranjay-poddar** [comment]
It is already present
