### ISSUE TITLE
Bank Management System using C

### ISSUE THREAD

**Issue by Kritika30032002** [pranjay-poddar/Dev-Geeks#914]
Can I contribute this?
It will include following functions :-

open_account,
deposit,
withdraw,
show_balance,
show_all,
modify_account,
close_account

Along with the password security

**Comment by Kpallavi5** [comment]
Hyy i would like to work on this issue can you please assign me? @pranjay-poddar

**Comment by 035pratheeksha** [comment]
Please assign this to me. @pranjay-poddar
