### ISSUE TITLE
Random Password generator using HTML, CSS and JavaScript

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [pranjay-poddar/Dev-Geeks#917]
**Describe the project you want to add with tech stack**

 I want to add the project named "Random Password generator".
 It is based on HTML, CSS and Javascript.
 Please assign this issue to me, I am willing to work on it!

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/95978839/194939312-991142a0-f115-4dac-a9f9-b3b2c0062e04.png)

**Additional context (optional )**
This project will create a strong password for the user by combining uppercase characters, lowercase characters, numbers and symbols. The user will give password length.

**Comment by pranjay-poddar** [comment]
Already present
