### ISSUE TITLE
Repo excluded in Hacktoberfest

### ISSUE THREAD

**Issue by Ahsan-Ehtesham** [pranjay-poddar/Dev-Geeks#921]
**Describe the bug**
This repo was excluded from hacktoberfest, why is that?

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/52749230/195017166-840caad9-c949-4e87-a9dc-58cc57ff8e46.png)

@pranjay-poddar kindly look into this!

**Comment by pranjay-poddar** [comment]
No it is not will check and let you know
