### ISSUE TITLE
Hello brother i merged 2 PR's to your repo but on my hactoberfest account it shows taht your repo has been excluded from Hacktoberfest?

### ISSUE THREAD

**Issue by VedantSharma11** [pranjay-poddar/Dev-Geeks#939]
**Describe the bug**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by deepshikha2708** [comment]
same happened with me

**Comment by wizeewig** [comment]
Yeah same

**Comment by VedantSharma11** [comment]
please respond @pranjay-poddar  ,
if your repo has been excluded as a maintainer repo from the Fest then update your repo's readme as "Excluded from hactoberfest" , so that other contibuters can see before contributing

**Comment by pranjay-poddar** [comment]
> please respond @pranjay-poddar  ,
> if your repo has been excluded as a maintainer repo from the Fest then update your repo's readme as "Excluded from hactoberfest" , so that other contibuters can see before contributing

@VedantSharma11 please keep calm we are looking into it and will also update the readme also please remember people might have other deadlines to meet.
