### ISSUE TITLE
Project No longer accepting Hacktoberfest'22 PRs

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Dev-Geeks#951]
Sorry guys, due to some spam PRs project is now no longer accepting PRs for Hacktoberfest'22.

We are working on it and hopefully try our best to bring it back for contributions, till then please keep calm and have a great hacktoberfest'22.
Wish you all happy coding✨

**Comment by Shivangbhatnagar237** [comment]
Excluded 😭😭😭
