### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by Rachael-debug** [pranjay-poddar/Dev-Geeks#956]
Creating a signup form and login page

**Comment by Rachael-debug** [comment]
Please assign me this issue

**Comment by Anjali2312-Thombare** [comment]
Hello @Rachael-debug  I have the solution for this issue. Please assign me

**Comment by anjaliSilawat** [comment]
I would like to work on this issue . @Rachael-debug  please assign me

**Comment by Pjha72** [comment]
I would like to create signup and login page. 
Can u pls assign me?

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. I have experience in creating signup pages for website.

**Comment by bleep123** [comment]
I would like to contribute to this issue and create signup and login page. Can you please assign me?

**Comment by mridulsaggi** [comment]
Hi @pranjay-poddar @Rachael-debug I have expertise in html css and javascript and am a MERN developer pls Assign me this issue

**Comment by purviporwal0** [comment]
I would like to contribute to this issue for GSSOC'23

**Comment by Developer-Swati** [comment]
Hello, I have some basic knowledge of HTML, CSS and Js and I really want to contribute to this project. So, please assign it to me.

**Comment by Pragati-3003** [comment]
Heyy @pranjay-poddar 
, I would like to contribute in this under GSSOC'23. 
Please assign this to me.

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by itzanway** [comment]
I would like to contribute in this under GSSOC'23.
Please assign this to me

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me

**Comment by Cadit21** [comment]
I would like to contribute to this issue, I have some creative ideas for designing and making it more interactive. I'm proficient in html ,css and js.

**Comment by vk20july** [comment]
@pranjay-poddar sir i want to work on this issue under gssoc'23
