### ISSUE TITLE
Clash of Clan website

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#958]
**Describe the project you want to add with tech stack**
Clash of Clan website - HTML CSS JS

**Expected behavior**
Clash of Clan website Clone

**Screenshots (optional)**

**Additional context (optional )**

**Comment by bleep123** [comment]
Hi @RAHULBAWA777 
I have good knowledge of Html and css and decent knowledge of JS.
I would like to work on this issue. Can you please assign this issue to me.

**Comment by vk20july** [comment]
@pranjay-poddar sir i want to work on this issue under gssoc'23
