### ISSUE TITLE
Random Probability Maker Web App

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#959]
**Describe the project you want to add with tech stack**
Random Probability Maker Web App - HTML CSS JS

**Expected behavior**
 Random Probability Maker
this app takes your tasks as input and randomly selects one task for you to do.

**Screenshots (optional)**

**Additional context (optional )**

**Comment by Akanksha-202** [comment]
Hey! I would really like to work on this webapp. Please assign it to me

**Comment by sr2005roy** [comment]
@RAHULBAWA777 I am interested in making this web app Random Probability Maker
