### ISSUE TITLE
Smash Em' All 

### ISSUE THREAD

**Issue by RAHULBAWA777** [pranjay-poddar/Dev-Geeks#960]
**Describe the project you want to add with tech stack**
Smash Em' All Game  - HTML CSS JS

**Expected behavior**
Smash Em' All Game 

**Screenshots (optional)**

**Additional context (optional )**

**Comment by PiyushaGhodake** [comment]
@RAHULBAWA777 Can u pls assign me this issue. I would like to work on this project.
