### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by Drishti-jain21** [pranjay-poddar/Dev-Geeks#961]
**Describe the project you want to add with tech stack**

I want to add a Loan Calculator, which will calculate the loan based on the amount, percentage and time.
It will be made using HTML,CSS,JavaScript.

**Comment by Anjali2312-Thombare** [comment]
i would like to solve this issue.  please assign me this issue

**Comment by Ijaiswalshivam** [comment]
Can you assign me this role? 👀

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by subhadiip333** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Arka2708** [comment]
I would like to work on this issue, assign me this issue , under GSSoC'23
