### ISSUE TITLE
FOLK DANCES

### ISSUE THREAD

**Issue by Swastik200** [pranjay-poddar/Dev-Geeks#962]
**Describe the project you want to add with tech stack**

a page of html with css providing a clear image of indian map on clicking each state will show its folk dances

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by PiyushaGhodake** [comment]
@Swastik200 I would like to work on this project .Can u pls assign me this issue?

**Comment by bleep123** [comment]
I would like to work on this issue. Can you please assign this issue to me. @Swastik200
