### ISSUE TITLE
ESHOP WEBSITE CLONE

### ISSUE THREAD

**Issue by Swastik200** [pranjay-poddar/Dev-Geeks#963]
**Describe the project you want to add with tech stack**

using html and css cloning website and adding certain new features like background video or audio ,forms and all

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

**Comment by anjaliSilawat** [comment]
I would like to work on this task,  @Swastik200 please assign it to me

**Comment by bleep123** [comment]
Hi! @Swastik200 
 I have good knowledge of html and css and I have already cloned the website of Swiggy using it.
Can you please consider me for this issue.

**Comment by Swastik200** [comment]
It's there in github make a fork and do...by the way I'm contributor...not
mentor
