### ISSUE TITLE
Frontend Education Website

### ISSUE THREAD

**Issue by adityaprakash01** [pranjay-poddar/Dev-Geeks#972]
**This is a Simple online Education website where we can get online courses**

**We can Explore courses,learn more about website ,about section and working contact section**

**Screenshots (optional)**

![Screenshot 2022-10-17 111802](https://user-images.githubusercontent.com/83463518/196098784-108424e5-4e3a-4e7c-a940-638300093519.jpg)

**Additional context (optional )**

**Comment by Anjali2312-Thombare** [comment]
Hello @adityaprakash01 , i would like to solve this issue . Can you please assign me this issue

**Comment by Geeta259** [comment]
I would like to contribute on this project. I have decent knowledge of Programming languages like HTML, CSS , REACTJS , JS.
I think this is suitable project for me in which I can contribute.
Hope you will consider me @adityaprakash01 !

**Comment by anjaliSilawat** [comment]
I would like to work on this task, @adityaprakash01  please assign it to me

**Comment by Thrillseekr** [comment]
Hey @pranjay-poddar,
I'm Darshan Jain, and I'm thrilled to be a part of this GSSOC'23. I bring along my expertise in HTML5, CSS, PHP, Bootstrap, and creativity too. I'm passionate about open source projects and eager to contribute and collaborate with fellow enthusiasts.

Can you please assign this to me.

**Comment by Pragati-3003** [comment]
Hey @pranjay-poddar 
I would like to work on this issue. Please assign it to me.

**Comment by bleep123** [comment]
Hey @adityaprakash01 @pranjay-poddar 
I would like to work on this issue. I have good knowledge of Html and CSS and decent knowledge of Javascript. I think this is a suitable project for me.
Please consider me for it.

**Comment by mridulsaggi** [comment]
Hi I would like to contribute to this project. I have expertise in html css and javascript and am a MERN developer. Pls assign me this issue

**Comment by mridulsaggi** [comment]
Hey @pranjay-poddar @adityaprakash01 
I would like to contribute to this project. I have expertise in html css and javascript and am a MERN developer. Pls assign me this issue

**Comment by bleep123** [comment]
Hi @pranjay-poddar
I would like to work on this issue. Please assign it to me.

**Comment by Cadit21** [comment]
I would like to contribute to this issue.
I'm proficient in html, css and Js. Please assign this issue to me.

**Comment by abhi03ruchi** [comment]
Hi @pranjay-poddar, I'm excited to express my interest in working on this issue! I possess strong skills in HTML, CSS, and JavaScript, and I am currently learning and improving my skills in React.js.  Please consider assigning this task to me.

**Comment by pjyoti121** [comment]
please assign me this issue
