### ISSUE TITLE
I would like to add my Login Form (Validation with Js)

### ISSUE THREAD

**Issue by darshil-here** [pranjay-poddar/Dev-Geeks#974]
**Login Form (that uses validation with js)**

![image](https://user-images.githubusercontent.com/104206815/197269885-7b742234-87bc-4992-a82e-8ea84b4d1b17.png)

![image](https://user-images.githubusercontent.com/104206815/197269900-87d9647e-d0d9-4d49-8389-73c3db073d5b.png)

![image](https://user-images.githubusercontent.com/104206815/197269911-f03f00ff-2c8b-4bed-9ea2-80dd57921385.png)

**Comment by Tushar255** [comment]
If this issue is still open I want to work on it. I've experiennce in building Signup/Login forms. I'll use nodejs, expressjs, mongoose, bcrypt, and jsonwebtoken to implement this. Also if you want Social Signups then I'll use OAuth.

Waiting for your reponse. :)

**Comment by pranjay-poddar** [comment]
@Tushar255 sure you can go ahead.

**Comment by pranjay-poddar** [comment]
> Thank you so much @pranjay-poddar
> But before I start working, I just want to ask one thing :-
> 
> In the Frontend, Should I use React Js or HTML & CSS ?

Both are accepted

**Comment by Tushar255** [comment]
Ok I've finished my work, ready to make pull request :)

**Comment by Tushar255** [comment]
@pranjay-poddar please review my changes.

**Comment by Tushar255** [comment]
This is how it's looking :-

![Screenshot (79)](https://user-images.githubusercontent.com/98146176/235050736-066355a8-8513-4751-ab22-a6c309f28e5e.png)
![Screenshot (80)](https://user-images.githubusercontent.com/98146176/235050744-ad69d84f-fb97-480b-a615-8bc8ebf9beec.png)

**Comment by Tushar255** [comment]
@pranjay-poddar ??

**Comment by Tushar255** [comment]
Let me give you a very great advise @ruchagosavi, don't work on this project, @pranjay-poddar will not going to merge your changes. I'll tell you my story, he didn't even look on my code and work....

It's you choice, this is just a time waste, you can search for some another good first issues.

**Comment by Tushar255** [comment]
> I would like to work on this issue @pranjay-poddar !

Let me give you a very great advise @ruchagosavi, don't work on this project, @pranjay-poddar will not going to merge your changes. I'll tell you my story, he didn't even look on my code and work....

It's you choice, this is just a time waste, you can search for some another good first issues.

**Comment by Geeta259** [comment]
I would like to contribute on this issue . I have decent knowledge of HTML, CSS , JS and I think this is suitable project for me in which I can contribute.

Waiting for your reply @pranjay-poddar !

**Comment by Tushar255** [comment]
As your wish, but mark my words, he is not going to merge your changes. 
I've already worked and opened a PR but he's just ignoring me now, didn't even replied to my messages.
This is time waste, instead of this you can make your personal projects.
All the best!

**Comment by Sayak-Bhunia** [comment]
Hey I'm interested in working on this issue please assign me this issue @pranjay-poddar
