### ISSUE TITLE
Add weather emojis in weather app

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#983]
**Describe the bug**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

When we display the weather ,I would like to also add respective weather emoji it make more stylish.
After that ,whenever the weather is shown ,the respective weather emoji is also visible above it.

**Comment by Yashika-Agrawal** [comment]
Hi there! I would like to contribute to this issue. It seems interesting and aligned with my skills.

**Comment by AmanMittal-3305** [comment]
Hii,
I would like to work on this issue

**Comment by purviporwal0** [comment]
I would like to contribute to this issue for GSSOC'23

**Comment by AsmitKumar321** [comment]
Hello! I would like to work on this issue, Plz assign the issue me.

**Comment by Gun2902** [comment]
can u assign me this issue
