### ISSUE TITLE
Recipe Book App

### ISSUE THREAD

**Issue by Tusharjoshi1703** [pranjay-poddar/Dev-Geeks#984]
**Describe the project you want to add with tech stack**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

Recipe Book app consists of recipes of various food items which is made with the help of Html,Css , Javascript and also RecipeAPI.
It will show the recipes of various food items including the ingredients required and the procedure.
Please assign it to me.

**Comment by Pavishnaam** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.@pranjay-poddar

**Comment by AbhaBarge** [comment]
Hi ! As a GSSOC '23 contributor, I would like to work on this issue. I have experience with HTML5, CSS and JavaScript. I would be glad to be considered for this interesting project !

**Comment by Tusharjoshi1703** [comment]
Sorry by mistake I clicked on unassign me ..plz assign it to me

**Comment by Tusharjoshi1703** [comment]
Thanks for assigning it to me . I'll make sure you won't get disappointed.
Regards
Tushar Joshi

**Comment by ADITI-2003** [comment]
Hi mentor,
I want to contribute to this project under this issue for gssoc 2023, please assign it to me.
Thank you

**Comment by purviporwal0** [comment]
I kindly request to be assigned to this project for GSSOC'23 , as I express my interest in actively participating and contributing to its development.

**Comment by Developer-Swati** [comment]
Hello @pranjay-poddar  it seems like it aligns with my skills . I would like to contribute to it .  I have already designed the responsive home page of a restaurant website. Please assign it to me.

**Comment by tusharv01** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills.

**Comment by Arka2708** [comment]
hey @pranjay-poddar I would like to work on this issue under GSSoC'23

**Comment by Tusharjoshi1703** [comment]
Hey @pranjay-poddar I want like to create the recipe book by using Html css and Javascript with also using recipeAPI .Please assign it to me.
