### ISSUE TITLE
Python project 

### ISSUE THREAD

**Issue by SimranLahrani842** [pranjay-poddar/Dev-Geeks#985]
A text editor in python. A text editor where you can create your own file ,save it ,edit it whenever u want.

**Comment by ani0722** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. This is too easy for me to make .I have worked on python  files for way too long. Please assign this issue to me, and I will start working on it. @SimranLahrani842

**Comment by SimranLahrani842** [comment]
> Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. This is too easy for me to make .I have worked on python files for way too long. Please assign this issue to me, and I will start working on it. @SimranLahrani842

Hello I m also a contributor hence asking for issue.

**Comment by anjali7235** [comment]
please assign me this project..

**Comment by Srideepthi2384** [comment]
I would like to work on this python project.. Building a calculator.. I am very interstef to work on this.. Plz assign me under gssoc 23

**Comment by PayalPadmalyaPrusty** [comment]
@pranjay-poddar I want to contribute.Please assign me

**Comment by Gun2902** [comment]
can u assign me this isssue
