### ISSUE TITLE
ReactJS based Restaurant website [GSSOC '23]

### ISSUE THREAD

**Issue by anuraganand92** [pranjay-poddar/Dev-Geeks#986]
#### **Features:**
- **Responsive** and **dynamic navbar**
- Chef **profiles with social media links**
- Menu with food images and costs
- A **dynamic Week's Special section** (Breakfast, Lunch, Dinner)

#### **Expected Behavior:**
The Restaurant Website project will provide a **responsive UI**, **accurate chef profiles**, a **well-organized menu**, and a **dynamic Week's Special section**. Users can **click on each section** to **reveal the corresponding list of items (breakfast, lunch, dinner)** for an **interactive experience**.

**Comment by vaishnavi-3969** [comment]
I would like to work on this issues - GSSOC '23

**Comment by Cadit21** [comment]
I would like to contribute to this website.
I'm proficient in html,css, js and react js.

**Comment by pjyoti121** [comment]
please assign me this issue under gssoc23
