### ISSUE TITLE
Multiple Disease Prediction - Web App

### ISSUE THREAD

**Issue by neekamhrzn** [pranjay-poddar/Dev-Geeks#989]
**Takes various test result as parameters and predicts what type of disease is present.**

**Machine Learning model is used**

****

****

**Comment by TANIYASHARMA30** [comment]
I want to work on this issue pls assign this to me .(GSSOC 23)
Taniya sharma
github.com/TANIYASHARMA30

**Comment by Shreyg-27** [comment]
Hi @pranjay-poddar ! I am a GSSoC'23 contributor, and I would love to work on this issue. 
I have huge interest in Machine Learning and Artificial Intelligence. 
Please assign this to me. 
Thank you.
