### ISSUE TITLE
Real estate landing page

### ISSUE THREAD

**Issue by karthiknadar1204** [pranjay-poddar/Dev-Geeks#990]
**Describe the project you want to add with tech stack**

Reacts js

**Expected behavior**

A real estate landing page for anyone to get started with building a mern stack project

**Screenshots (optional)**

**Additional context (optional )**

**Comment by karthiknadar1204** [comment]
I would like to work on this under gssoc'23

**Comment by ShivendraTrivedi** [comment]
Hey there! I noticed the open issue in the repository. I would like to work on this frontend project and describe the tech stack and expectations for a real estate landing page. I will be using React.js for the frontend development. Please assign this issue to me under Gssoc'23. 
Thanks!

**Comment by karthiknadar1204** [comment]
@pranjay-poddar I HAVE MY PROJECT READY, DO I NEED TO HOST IT AS WELL?

**Comment by pranjay-poddar** [comment]
No hosting not required

**Comment by karthiknadar1204** [comment]
Submitting project today @pranjay-poddar
