### ISSUE TITLE
CryptoVerse Website

### ISSUE THREAD

**Issue by Aryan123-rgb** [pranjay-poddar/Dev-Geeks#993]
**Describe the project you want to add with tech stack**
 This website will show all the bitcoins dynamically fetched from the coingecko api. Clicking on the respective bitcoin card ,a detail page will open showing all the informations related to the bitcoin . Along with bitcoins it will also show latest cryptoexchange news

**Expected behavior**
On the front-end projects and Reactjs projects section this website should be added

**Screenshots (optional)**

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/118872531/4c168283-c4a2-4220-86fe-f2dcc8708347)
 

**Additional context (optional )**
 The above is just a sample ,one create an even better design adding carousel and firebase authentication 

If it's noteworthy assign it to me, I can work on it

**Comment by jessicacb12** [comment]
Greetings! I would like to work on this under GSSOC'23. I have been working as Frontend Engineer for 2.5 years using React TypeScript. Looking forward to be assigned in this project!

**Comment by Aryan123-rgb** [comment]
@pranjay-poddar Thank you for assigning it to me, it will take some time but I will create a pr for sure :)
