### ISSUE TITLE
Add EMI Calculator Project

### ISSUE THREAD

**Issue by Gurnav224** [pranjay-poddar/Dev-Geeks#996]
**Describe the project you want to add with tech stack**

I want to add an EMI Calculator project 
it will take the loan amount, interest rate, and loan tenure in a month

**Expected behavior**

It will calculate your EMI
![EMI-calulator](https://github.com/pranjay-poddar/Dev-Geeks/assets/72142482/c34c8d86-4b4d-4c9b-baff-7348dc789b05)
 per month
**Screenshots (optional)**

**Additional context (optional )**

TECH STACK: html css javascript

**Comment by Aditi323** [comment]
I would like to work in this project.Please assign this to me

**Comment by purviporwal0** [comment]
I kindly request to be assigned to this project, as I express my interest in actively participating and contributing to its development.

**Comment by pearlrathour** [comment]
I would like to work in this project under GSSoC 2023. Please assign this to me.

**Comment by Developer-Swati** [comment]
Hello, I would like to work on this project . Please assign it to me. 
Tech stack  : - HTML, CSS, JS.

**Comment by silwite** [comment]
Hello , I would like to work on this issue .Please assign it to me.
Tech Stack - MERN

**Comment by SatvikAgrawal04** [comment]
I would like to work on this issue as part of GSSoC  2023. Kindly assign this to me
