### ISSUE TITLE
Add Notes-Taking-WebApp

### ISSUE THREAD

**Issue by vikram-8290** [pranjay-poddar/Dev-Geeks#999]
**Describe the project you want to add with tech stack**

I want to Add A Note Taking Project

**Expected behavior**

It will Help to Make New Note,Edit and Delete Previous Notes.
It will also provie Date and Time Of Creation of the Note

**Screenshots (optional)**

<img width="1366" alt="Screenshot 2023-05-20 at 10 54 19 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/113750425/db6a0945-ca43-4bdc-ba84-515ece41f6a5">

**Additional context (optional )**

TECH STACK: html,css,Javascript,React

**Comment by vikram-8290** [comment]
I want To Work on this Issue Under Gssoc .Please Assign me this

**Comment by SHIVA769** [comment]
I want to Work on this Issue Under Gssoc .Please Assign me this

**Comment by vikram-8290** [comment]
hiii @pranjay-poddar ,
i am ready with this issue, but not able to understand how raise the PR. will you please help me with this
